//! Bloodfell Caves — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {B} or {R}.
//! Set: TDM #250 — Tarkir: Dragonstorm | Scryfall ID: 1dde3c68-6f29-4c00-b668-c25ac9e3e13b | Oracle ID: 64e29bfc-9313-4e8c-808c-bc27f6b018a6
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 289,
    oracle_id: "64e29bfc-9313-4e8c-808c-bc27f6b018a6",
    scryfall_id: "1dde3c68-6f29-4c00-b668-c25ac9e3e13b",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bloodfell Caves",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
