//! Jungle Hollow — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {B} or {G}.
//! Set: TDM #258 — Tarkir: Dragonstorm | Scryfall ID: ea13440b-3f7b-4182-9541-27c1fa3121e5 | Oracle ID: 6de714e1-446d-4fb9-9e3d-bcd3ec6af9ca
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 671,
    oracle_id: "6de714e1-446d-4fb9-9e3d-bcd3ec6af9ca",
    scryfall_id: "ea13440b-3f7b-4182-9541-27c1fa3121e5",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Jungle Hollow",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
