//! Stark Industries — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {R}.
//! Set: MSH #272 — Marvel Super Heroes | Scryfall ID: fe3609d8-71a2-49d9-a3fa-25e0906a1a0e | Oracle ID: 52401cb4-1bce-4191-9220-0d93ea4108b8
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1083,
    oracle_id: "52401cb4-1bce-4191-9220-0d93ea4108b8",
    scryfall_id: "fe3609d8-71a2-49d9-a3fa-25e0906a1a0e",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Stark Industries",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
    ],
}
