//! Subterranean Cavern — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {B} or {G}.
//! Set: MSH #273 — Marvel Super Heroes | Scryfall ID: 038bf500-e23a-4d38-9312-db1909e20353 | Oracle ID: d49a7525-eca5-48e1-b94b-d618a706fd02
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1100,
    oracle_id: "d49a7525-eca5-48e1-b94b-d618a706fd02",
    scryfall_id: "038bf500-e23a-4d38-9312-db1909e20353",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Subterranean Cavern",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
