//! Swiftwater Cliffs — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {R}.
//! Set: TDM #268 — Tarkir: Dragonstorm | Scryfall ID: ca53fb19-b8ca-485b-af1a-5117ae54bfe3 | Oracle ID: 2f4ad084-2062-44c0-9975-15f100204531
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1129,
    oracle_id: "2f4ad084-2062-44c0-9975-15f100204531",
    scryfall_id: "ca53fb19-b8ca-485b-af1a-5117ae54bfe3",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Swiftwater Cliffs",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
    ],
}
