//! The ledger as Rust: one constant per card, one file per set.
//!
//! `baylee_cards_index::ROWS` is the assignment; this is the same assignment
//! written in the language the rest of the workspace is written in. A card
//! file used to say `index = 11391`, which is a number nobody can read; it
//! says `index = index::MOX_OPAL` instead, and a wrong index is a name that
//! does not exist rather than a card that quietly resolves as another one.
//! `card!` takes the field as a `path`, so the old spelling is refused by the
//! matcher and cannot come back.
//!
//! # Why one file per set
//!
//! 33 694 constants in one file is a file nothing opens. The split is by
//! **first-appearance set**, which is the ledger's own second axis and
//! therefore needs no new decision: a card is assigned at the set it first
//! appeared in, so it is filed there too. A reprint is never listed twice
//! because the ledger holds one row per `oracle_id` — the deduplication
//! happens upstream, at assignment, and not here.
//!
//! `mod.rs` globs every set module back into one namespace, so
//! `index::LIGHTNING_BOLT` resolves without anybody having to know which set
//! that was. Which is the whole arrangement: the files are how it is stored,
//! the module is how it is read.
//!
//! Every module is prefixed `set_` — one rule, no exceptions. Three set codes
//! (`2x2`, `40k`, `5dn`) begin with a digit and are not identifiers on their
//! own, and a prefix applied to only those three is a rule somebody has to
//! remember. Applied to all of them it is a rule nobody has to think about.
//!
//! # The collision guard
//!
//! Glob re-exports do not conflict in Rust until the ambiguous name is *used*,
//! so two sets exporting one constant would compile and hide a card until
//! somebody named it. `IndexLedger::assign` already prevents that when an
//! index is handed out, and this checks it again on the way out, because the
//! ledger is generated too, and the failure mode of not checking is silence.

use crate::error::CodegenError;
use crate::ledger::{IndexLedger, LedgerEntry};
use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;

/// What every generated file in the tree opens with.
const HEADER: &str = "// GENERATED by `cargo xtask codegen` — do not edit by hand.\n\
                      // Source: the CardIndex ledger, baylee_cards_index::ROWS.\n";

/// One generated file: its name inside the tree, and its whole content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexFile {
    /// File name inside `crates/baylee-core/src/generated/index/`.
    pub name: String,
    /// The file, whole.
    pub content: String,
}

/// The module a set's constants live in.
///
/// Public because the orphan check in `xtask` has to ask the same question:
/// a `set_*.rs` the ledger no longer names is a file that compiles, is
/// declared by nothing and is read by nobody.
#[must_use]
pub fn module_name(set: &str) -> String {
    format!("set_{set}")
}

/// Renders the whole tree — one file per set, plus `mod.rs`.
///
/// # Errors
///
/// [`CodegenError::ConstantCollision`] if two cards claim one constant. See
/// the module docs: a glob re-export would hide one of them rather than
/// refuse.
pub fn render(ledger: &IndexLedger) -> Result<Vec<IndexFile>, CodegenError> {
    let mut by_set: BTreeMap<&str, Vec<&LedgerEntry>> = BTreeMap::new();
    let mut claimed: HashMap<&str, &str> = HashMap::new();
    for entry in ledger.entries() {
        if let Some(held) = claimed.insert(&entry.constant, &entry.name) {
            return Err(CodegenError::ConstantCollision {
                constant: entry.constant.clone(),
                held: held.to_string(),
                wanted: entry.name.clone(),
            });
        }
        by_set.entry(&entry.set).or_default().push(entry);
    }

    let mut files: Vec<IndexFile> = by_set
        .iter()
        .map(|(set, entries)| IndexFile {
            name: format!("{}.rs", module_name(set)),
            content: render_set(set, entries),
        })
        .collect();
    files.push(IndexFile {
        name: "mod.rs".to_string(),
        content: render_mod(&by_set),
    });
    Ok(files)
}

/// One set's constants, in index order — which is the order they were
/// assigned in, and inside one set that is the order the ledger lists them.
fn render_set(set: &str, entries: &[&LedgerEntry]) -> String {
    let mut out = String::with_capacity(entries.len() * 160);
    out.push_str(HEADER);
    let plural = if entries.len() == 1 { "" } else { "s" };
    let _ = writeln!(
        out,
        "// {} card{plural} first printed in `{set}`.",
        entries.len()
    );
    out.push_str("\nuse crate::ids::CardIndex;\n\n");
    for entry in entries {
        let _ = writeln!(
            out,
            "/// `{}` — oracle id `{}`.",
            entry.name, entry.oracle_id
        );
        let _ = writeln!(
            out,
            "pub const {}: CardIndex = CardIndex::new({});",
            entry.constant, entry.index
        );
    }
    out
}

/// The door: every set module declared privately and globbed back out, so the
/// tree looks from outside like one flat list of constants.
fn render_mod(by_set: &BTreeMap<&str, Vec<&LedgerEntry>>) -> String {
    let total: usize = by_set.values().map(Vec::len).sum();
    let mut out = String::with_capacity(by_set.len() * 48 + 2048);
    out.push_str(HEADER);
    out.push_str("\n//! Every card's `CardIndex`, under the constant the ledger froze for it.\n");
    out.push_str("//!\n");
    let _ = writeln!(
        out,
        "//! {total} cards across {} sets, each filed under the set it first",
        by_set.len()
    );
    out.push_str("//! appeared in. The modules are private and globbed back out here, so a\n");
    out.push_str("//! caller writes `index::LIGHTNING_BOLT` and never learns which set that\n");
    out.push_str("//! was — which is the point, because the set is a fact about the ledger\n");
    out.push_str("//! and the constant is a fact about the card.\n");
    out.push_str("//!\n");
    out.push_str("//! An index is an identity and not a position: it is assigned over the\n");
    out.push_str("//! whole card corpus rather than over the cards this repo implements, so\n");
    out.push_str("//! most of these name a card no `CardDef` exists for yet. That is what\n");
    out.push_str("//! makes implementing an old card insert nothing.\n");
    out.push_str("\n#![allow(missing_docs, clippy::all, clippy::pedantic)]\n\n");
    for set in by_set.keys() {
        let _ = writeln!(out, "mod {};", module_name(set));
    }
    out.push('\n');
    for set in by_set.keys() {
        let _ = writeln!(out, "pub use {}::*;", module_name(set));
    }
    out.push_str(&render_door_test(by_set));
    out
}

/// One constant per set module, named through the door.
///
/// Both ways this tree can fail are invisible until somebody names a
/// constant: a module missing from the list above is simply unreachable, and
/// two sets exporting one name are a glob ambiguity rustc reports at the *use
/// site* and nowhere else. Neither is a compile error in a tree nobody reads
/// from, which is exactly the state this tree is in until card files start
/// using it. So the generated test reads from every module — 382 names, one
/// apiece — and turns both into build failures today.
fn render_door_test(by_set: &BTreeMap<&str, Vec<&LedgerEntry>>) -> String {
    let mut out = String::with_capacity(by_set.len() * 64 + 512);
    out.push_str("\n#[cfg(test)]\nmod door {\n");
    out.push_str("    /// Every set module is declared above, and no two of them export one\n");
    out.push_str("    /// name — neither of which rustc reports until a constant is named.\n");
    out.push_str("    #[test]\n");
    out.push_str("    fn every_set_module_answers_through_the_door() {\n");
    for (set, entries) in by_set {
        let first = entries[0];
        let _ = writeln!(
            out,
            "        assert_eq!(super::{}.get(), {}, \"{set}\");",
            first.constant, first.index
        );
    }
    out.push_str("    }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::{module_name, render};
    use crate::ledger::{IndexLedger, LedgerEntry, row};

    fn ledger(rows: &[baylee_cards_index::Row]) -> IndexLedger {
        IndexLedger::from_rows(rows).expect("the test ledger reads")
    }

    fn entry(index: u32, oracle_id: &str, constant: &str, set: &str, name: &str) -> LedgerEntry {
        LedgerEntry {
            index,
            oracle_id: oracle_id.to_string(),
            constant: constant.to_string(),
            set: set.to_string(),
            name: name.to_string(),
        }
    }

    /// The prefix rule with no exceptions is the whole reason it is a rule:
    /// three real set codes begin with a digit, and `2x2` is not an
    /// identifier.
    #[test]
    fn a_set_code_that_starts_with_a_digit_is_still_a_module() {
        assert_eq!(module_name("2x2"), "set_2x2");
        assert_eq!(module_name("lea"), "set_lea");
        for name in [module_name("2x2"), module_name("40k"), module_name("5dn")] {
            assert!(name.starts_with("set_"));
            assert!(!name[4..].is_empty());
            assert!(name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'));
        }
    }

    /// A reprint is not a second constant. The ledger holds one row per
    /// `oracle_id`, so the card is filed at its first appearance and nowhere
    /// else — if this ever stopped holding, the glob below would hide one of
    /// the two.
    #[test]
    fn a_card_is_listed_once_at_the_set_it_first_appeared_in() {
        let files = render(&ledger(&[
            row(0, "aaa", "LIGHTNING_BOLT", "lea", "Lightning Bolt"),
            row(1, "bbb", "DARK_RITUAL", "lea", "Dark Ritual"),
            row(2, "ccc", "SOL_RING", "leb", "Sol Ring"),
        ]))
        .expect("no collision");
        let names: Vec<&str> = files.iter().map(|f| f.name.as_str()).collect();
        assert_eq!(names, ["set_lea.rs", "set_leb.rs", "mod.rs"]);
        let lea = &files[0].content;
        assert!(lea.contains("pub const LIGHTNING_BOLT: CardIndex = CardIndex::new(0);"));
        assert!(lea.contains("pub const DARK_RITUAL: CardIndex = CardIndex::new(1);"));
        assert!(!files[1].content.contains("LIGHTNING_BOLT"));
        let door = &files[2].content;
        assert!(door.contains("mod set_lea;"));
        assert!(door.contains("pub use set_lea::*;"));
        assert!(door.contains("pub use set_leb::*;"));
    }

    /// The counter-test for the guard the module docs describe: two sets
    /// exporting one name compiles and hides a card, so the renderer refuses
    /// rather than emits. Building the pair needs the unchecked door, because
    /// `from_rows` and `assign` both refuse a duplicate constant first — which
    /// the point: this is the third lock, not the first.
    #[test]
    fn two_cards_claiming_one_constant_are_refused_and_not_globbed() {
        let clash = IndexLedger::from_entries_unchecked(vec![
            entry(0, "aaa", "LIGHTNING_BOLT", "lea", "Lightning Bolt"),
            entry(1, "bbb", "LIGHTNING_BOLT", "m10", "Lightning Bolt"),
        ]);
        let Err(err) = render(&clash) else {
            panic!("a constant claimed twice must not render");
        };
        assert!(err.to_string().contains("LIGHTNING_BOLT"), "{err}");
    }

    /// Byte reproducibility: the tree is committed, so a second run that
    /// reordered anything would show up as a diff nobody asked for.
    #[test]
    fn rendering_twice_produces_the_same_bytes() {
        let led = ledger(&[
            row(0, "aaa", "SOL_RING", "leb", "Sol Ring"),
            row(1, "bbb", "DARK_RITUAL", "lea", "Dark Ritual"),
        ]);
        assert_eq!(render(&led).expect("a"), render(&led).expect("b"));
    }
}
