//! Scryfall subtype catalogs → generated `subtypes.rs`.
//!
//! Deterministic: every catalog is sorted alphabetically; ids are assigned
//! sequentially in kind order (creature, artifact, enchantment, land,
//! planeswalker, spell).

// One-shot string rendering; the allocation lint adds noise, not value.
#![allow(clippy::format_push_string)]

use baylee_core::types::SubtypeKind;
use serde::{Deserialize, Serialize};

/// All subtype catalogs, sorted and deduplicated.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SubtypeCatalogs {
    /// Creature subtypes.
    pub creature: Vec<String>,
    /// Artifact subtypes.
    pub artifact: Vec<String>,
    /// Enchantment subtypes.
    pub enchantment: Vec<String>,
    /// Land subtypes.
    pub land: Vec<String>,
    /// Planeswalker subtypes.
    pub planeswalker: Vec<String>,
    /// Spell (instant/sorcery) subtypes.
    pub spell: Vec<String>,
}

impl SubtypeCatalogs {
    /// Sorts and deduplicates every catalog.
    pub fn normalize(&mut self) {
        for list in [
            &mut self.creature,
            &mut self.artifact,
            &mut self.enchantment,
            &mut self.land,
            &mut self.planeswalker,
            &mut self.spell,
        ] {
            list.sort();
            list.dedup();
        }
    }

    /// Iterates `(kind, names)` in id-assignment order.
    pub fn ordered(&self) -> [(SubtypeKind, &Vec<String>); 6] {
        [
            (SubtypeKind::Creature, &self.creature),
            (SubtypeKind::Artifact, &self.artifact),
            (SubtypeKind::Enchantment, &self.enchantment),
            (SubtypeKind::Land, &self.land),
            (SubtypeKind::Planeswalker, &self.planeswalker),
            (SubtypeKind::Spell, &self.spell),
        ]
    }

    /// The generated constant path for a subtype name, e.g.
    /// `subtypes::land::FOREST`.
    #[must_use]
    pub fn const_path(&self, name: &str) -> Option<String> {
        for (kind, names) in self.ordered() {
            if names.iter().any(|n| n.eq_ignore_ascii_case(name)) {
                return Some(format!(
                    "subtypes::{}::{}",
                    module_name(kind),
                    const_name(name)
                ));
            }
        }
        None
    }
}

/// Rust module name for a kind.
#[must_use]
pub const fn module_name(kind: SubtypeKind) -> &'static str {
    match kind {
        SubtypeKind::Creature => "creature",
        SubtypeKind::Artifact => "artifact",
        SubtypeKind::Enchantment => "enchantment",
        SubtypeKind::Land => "land",
        SubtypeKind::Planeswalker => "planeswalker",
        SubtypeKind::Spell => "spell",
    }
}

/// `SCREAMING_SNAKE` constant identifier for a subtype name.
#[must_use]
pub fn const_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    let trimmed = out.trim_matches('_');
    if trimmed.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        return format!("S_{trimmed}");
    }
    trimmed.to_string()
}

/// Renders the complete `crates/baylee-core/src/generated/subtypes.rs`.
#[must_use]
pub fn render_subtypes_rs(cats: &SubtypeCatalogs) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str(
        "// GENERATED by `cargo xtask codegen` — do not edit by hand.\n\
         // Source: Scryfall subtype catalogs (sorted, ids sequential per kind).\n\n\
         #![allow(missing_docs, unused_imports, dead_code, clippy::all, clippy::pedantic)]\n\n\
         use crate::ids::SubtypeId;\n\
         use crate::types::SubtypeKind;\n\n",
    );

    // Constants, grouped per kind module, ids sequential across modules.
    let mut next: u16 = 0;
    let mut ends: Vec<(&'static str, u16)> = Vec::new();
    let mut name_arms: Vec<String> = Vec::new();
    for (kind, names) in cats.ordered() {
        out.push_str(&format!(
            "pub mod {} {{\n    use super::SubtypeId;\n",
            module_name(kind)
        ));
        for name in names {
            let cname = const_name(name);
            out.push_str(&format!(
                "    pub const {cname}: SubtypeId = SubtypeId::new({next});\n"
            ));
            name_arms.push(format!(
                "        \"{}\" => {}::{},",
                name.to_ascii_lowercase().replace('"', "\\\""),
                module_name(kind),
                cname
            ));
            next += 1;
        }
        out.push_str("}\n");
        ends.push((module_name(kind), next));
    }

    out.push_str(&format!("\npub const COUNT: u16 = {next};\n"));
    for (module, end) in &ends {
        out.push_str(&format!(
            "const {}_END: u16 = {end};\n",
            module.to_ascii_uppercase()
        ));
    }

    // kind()
    out.push_str("\npub const fn kind(id: SubtypeId) -> SubtypeKind {\n    let v = id.get();\n");
    let kinds = [
        (SubtypeKind::Creature, "CREATURE_END"),
        (SubtypeKind::Artifact, "ARTIFACT_END"),
        (SubtypeKind::Enchantment, "ENCHANTMENT_END"),
        (SubtypeKind::Land, "LAND_END"),
        (SubtypeKind::Planeswalker, "PLANESWALKER_END"),
    ];
    for (kind, end) in kinds {
        out.push_str(&format!(
            "    if v < {end} {{ return SubtypeKind::{kind:?}; }}\n"
        ));
    }
    out.push_str("    SubtypeKind::Spell\n}\n");

    // by_name()
    out.push_str(
        "\npub fn by_name(name: &str) -> Option<SubtypeId> {\n    Some(match name.to_ascii_lowercase().as_str() {\n",
    );
    for arm in name_arms {
        out.push_str(&arm);
        out.push('\n');
    }
    out.push_str("        _ => return None,\n    })\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn const_names() {
        assert_eq!(const_name("Assembly-Worker"), "ASSEMBLY_WORKER");
        assert_eq!(const_name("Urza's"), "URZA_S");
        assert_eq!(const_name("Forest"), "FOREST");
    }

    #[test]
    fn renders_deterministically() {
        let mut cats = SubtypeCatalogs {
            creature: vec!["Wizard".into(), "Ally".into()],
            land: vec!["Forest".into()],
            ..SubtypeCatalogs::default()
        };
        cats.normalize();
        let a = render_subtypes_rs(&cats);
        let b = render_subtypes_rs(&cats);
        assert_eq!(a, b);
        assert!(a.contains("pub const ALLY: SubtypeId = SubtypeId::new(0);"));
        assert!(a.contains("pub const FOREST: SubtypeId = SubtypeId::new(2);"));
        assert_eq!(
            cats.const_path("forest").as_deref(),
            Some("subtypes::land::FOREST")
        );
    }
}
