//! Planar Portal — {6} — Artifact
//! Oracle: {6}, {T}: Search your library for a card, put that card into your hand, then shuffle.
//! Set: 8ED #311 — Eighth Edition | Scryfall ID: 8743b2ce-0e18-42c9-aee4-f13197a9c481 | Oracle ID: d4b10505-2b7a-4099-aacb-ff2359b24310
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PLANAR_PORTAL,
    oracle_id = "d4b10505-2b7a-4099-aacb-ff2359b24310",
    scryfall_id = "8743b2ce-0e18-42c9-aee4-f13197a9c481",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Planar Portal",
        mana_cost = mana!("{6}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{6}", TapSelf),
        &[Effect::SearchLibrary {
            filter: &Filter::Any,
            finds: &[Find::HAND],
            optional: false
        }]
    ),],
);
