//! Snow-Covered Forest — (no cost) — Basic Snow Land — Forest
//! Oracle: ({T}: Add {G}.)
//! Set: KHM #284 — Kaldheim | Scryfall ID: ca17acea-f079-4e53-8176-a2f5c5c408a1 | Oracle ID: 5f0d3be8-e63e-4ade-ae58-6b0c14f2ce6d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1054,
    oracle_id: "5f0d3be8-e63e-4ade-ae58-6b0c14f2ce6d",
    scryfall_id: "ca17acea-f079-4e53-8176-a2f5c5c408a1",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Snow-Covered Forest",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::BASIC.union(SupertypeSet::SNOW),
        subtypes: &[subtypes::land::FOREST],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
    ],
}
