//! Seal of Strength — {G} — Enchantment
//! Oracle: Sacrifice this enchantment: Target creature gets +3/+3 until end of turn.
//! Set: EMA #184 — Eternal Masters | Scryfall ID: 559c3909-51e3-4a3e-8570-107ffe69e30d | Oracle ID: e41a68b3-e1cb-4f51-bd54-68882d2cc015
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SEAL_OF_STRENGTH,
    oracle_id = "e41a68b3-e1cb-4f51-bd54-68882d2cc015",
    scryfall_id = "559c3909-51e3-4a3e-8570-107ffe69e30d",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Seal of Strength",
        mana_cost = mana!("{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!(SacrificeSelf),
        &[Effect::PumpTarget {
            power: Amount::Fixed(3),
            toughness: Amount::Fixed(3),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
