//! Dwarven Ruins — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R}.
//! Oracle: {T}, Sacrifice this land: Add {R}{R}.
//! Set: ME2 #227 — Masters Edition II | Scryfall ID: 0b6adef9-a1c5-452d-94c7-4110f4998180 | Oracle ID: cbef6ad5-717f-4b02-9c62-e5deba407ad1
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 453,
    oracle_id: "cbef6ad5-717f-4b02-9c62-e5deba407ad1",
    scryfall_id: "0b6adef9-a1c5-452d-94c7-4110f4998180",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Dwarven Ruins",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana(ManaColor::Red, 2)]),
    ],
}
