//! Geothermal Crevice — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R}.
//! Oracle: {T}, Sacrifice this land: Add {B}{G}.
//! Set: INV #323 — Invasion | Scryfall ID: e744b593-13fe-4967-b492-ac02f5815e57 | Oracle ID: 83f9d84a-a011-4fa9-a3a4-51eb39159c54
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 544,
    oracle_id: "83f9d84a-a011-4fa9-a3a4-51eb39159c54",
    scryfall_id: "e744b593-13fe-4967-b492-ac02f5815e57",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Geothermal Crevice",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana(ManaColor::Black, 1), Effect::mana(ManaColor::Green, 1)]),
    ],
}
