//! Peat Bog — (no cost) — Land
//! Oracle: This land enters tapped with two depletion counters on it.
//! Oracle: {T}, Remove a depletion counter from this land: Add {B}{B}. If there are no depletion counters on this land, sacrifice it.
//! Set: MMQ #322 — Mercadian Masques | Scryfall ID: bcc9d1e0-c8f4-4bac-90d4-8167f7a1515a | Oracle ID: a176924c-78fc-4151-b2b5-1547b1114a40
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PEAT_BOG,
    oracle_id = "a176924c-78fc-4151-b2b5-1547b1114a40",
    scryfall_id = "bcc9d1e0-c8f4-4bac-90d4-8167f7a1515a",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Peat Bog",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: counters::DEPLETION,
                amount: Amount::Fixed(2)
            }
        ],
    ),],
    abilities = &[mana_ability!(
        cost!(
            TapSelf,
            RemoveCounterSelf {
                kind: counters::DEPLETION,
                n: 1
            }
        ),
        &[
            Effect::mana(ManaColor::Black, 2),
            Effect::IfNoCountersOnSelf {
                kind: counters::DEPLETION,
                then: &[Effect::SacrificeSelf]
            }
        ]
    ),],
);
