//! Remote Farm — (no cost) — Land
//! Oracle: This land enters tapped with two depletion counters on it.
//! Oracle: {T}, Remove a depletion counter from this land: Add {W}{W}. If there are no depletion counters on this land, sacrifice it.
//! Set: MMQ #323 — Mercadian Masques | Scryfall ID: 115cab84-60d7-4bf2-9beb-b4ed7b5ceaf4 | Oracle ID: 2c38f4c7-1b3f-42b4-a175-edab7acd6cc6
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::REMOTE_FARM,
    oracle_id = "2c38f4c7-1b3f-42b4-a175-edab7acd6cc6",
    scryfall_id = "115cab84-60d7-4bf2-9beb-b4ed7b5ceaf4",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Remote Farm",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: counters::DEPLETION,
                n: 2
            }
        ],
    ),],
    abilities = &[mana_ability!(
        cost!(
            TapSelf,
            RemoveCounterSelf {
                kind: counters::DEPLETION,
                n: 1
            }
        ),
        &[
            Effect::mana(ManaColor::White, 2),
            Effect::IfNoCountersOnSelf {
                kind: counters::DEPLETION,
                then: &[Effect::SacrificeSelf]
            }
        ]
    ),],
);
