//! Sandstone Needle — (no cost) — Land
//! Oracle: This land enters tapped with two depletion counters on it.
//! Oracle: {T}, Remove a depletion counter from this land: Add {R}{R}. If there are no depletion counters on this land, sacrifice it.
//! Set: MMQ #326 — Mercadian Masques | Scryfall ID: 82bc7c6b-2e3d-42d1-b2bb-b37b6f34d33b | Oracle ID: c8e0a1a5-8188-4677-9d8a-a18eb593343a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SANDSTONE_NEEDLE,
    oracle_id = "c8e0a1a5-8188-4677-9d8a-a18eb593343a",
    scryfall_id = "82bc7c6b-2e3d-42d1-b2bb-b37b6f34d33b",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sandstone Needle",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: counters::DEPLETION,
                n: 2
            }
        ],
    ),],
    abilities = &[mana_ability!(
        cost!(
            TapSelf,
            RemoveCounterSelf {
                kind: counters::DEPLETION,
                n: 1
            }
        ),
        &[
            Effect::mana(ManaColor::Red, 2),
            Effect::IfNoCountersOnSelf {
                kind: counters::DEPLETION,
                then: &[Effect::SacrificeSelf]
            }
        ]
    ),],
);
