//! Saprazzan Skerry — (no cost) — Land
//! Oracle: This land enters tapped with two depletion counters on it.
//! Oracle: {T}, Remove a depletion counter from this land: Add {U}{U}. If there are no depletion counters on this land, sacrifice it.
//! Set: MMQ #328 — Mercadian Masques | Scryfall ID: 006871fd-2641-42cb-a2ac-a33d05fc5a35 | Oracle ID: e4e6e796-39ce-4a63-8c61-c7c956d75d78
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SAPRAZZAN_SKERRY,
    oracle_id = "e4e6e796-39ce-4a63-8c61-c7c956d75d78",
    scryfall_id = "006871fd-2641-42cb-a2ac-a33d05fc5a35",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Saprazzan Skerry",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: counters::DEPLETION,
                amount: Amount::Fixed(2)
            }
        ],
    ),],
    abilities = &[mana_ability!(
        cost!(
            TapSelf,
            RemoveCounterSelf {
                kind: counters::DEPLETION,
                n: 1
            }
        ),
        &[
            Effect::mana(ManaColor::Blue, 2),
            Effect::IfNoCountersOnSelf {
                kind: counters::DEPLETION,
                then: &[Effect::SacrificeSelf]
            }
        ]
    ),],
);
