//! Snowfield Sinkhole — (no cost) — Snow Land — Plains Swamp
//! Oracle: ({T}: Add {W} or {B}.)
//! Oracle: This land enters tapped.
//! Set: CLB #915 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 3c6e17f2-b1e4-4189-a02f-92fa4b13a1ed | Oracle ID: 749c2c8e-9588-4e83-b07f-3c37eb63338b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1060,
    oracle_id: "749c2c8e-9588-4e83-b07f-3c37eb63338b",
    scryfall_id: "3c6e17f2-b1e4-4189-a02f-92fa4b13a1ed",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Snowfield Sinkhole",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::SNOW,
        subtypes: &[subtypes::land::PLAINS, subtypes::land::SWAMP],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
    ],
}
