//! Thriving Bluff — (no cost) — Land
//! Oracle: This land enters tapped. As it enters, choose a color other than red.
//! Oracle: {T}: Add {R} or one mana of the chosen color.
//! Set: MSC #578 — Marvel Super Heroes Commander | Scryfall ID: 82c96473-d7b9-48dc-9569-cdb649c78463 | Oracle ID: 91fceb34-0f2d-4392-be27-00dcd765637f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THRIVING_BLUFF,
    oracle_id = "91fceb34-0f2d-4392-be27-00dcd765637f",
    scryfall_id = "82c96473-d7b9-48dc-9569-cdb649c78463",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thriving Bluff",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::ChooseColorExcept(ManaColor::Red),
            EnterModifier::Tapped
        ],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen_or(&[ManaColor::Red])]),],
);
