//! Thriving Isle — (no cost) — Land
//! Oracle: This land enters tapped. As it enters, choose a color other than blue.
//! Oracle: {T}: Add {U} or one mana of the chosen color.
//! Set: MSC #581 — Marvel Super Heroes Commander | Scryfall ID: 58a3b5a5-eba0-4b4e-869a-5387ec7dd2b8 | Oracle ID: 69fc70b8-b143-4662-ac95-e2743037239d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THRIVING_ISLE,
    oracle_id = "69fc70b8-b143-4662-ac95-e2743037239d",
    scryfall_id = "58a3b5a5-eba0-4b4e-869a-5387ec7dd2b8",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thriving Isle",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::ChooseColorExcept(ManaColor::Blue),
            EnterModifier::Tapped
        ],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen_or(&[ManaColor::Blue])]),],
);
