//! Thriving Moor — (no cost) — Land
//! Oracle: This land enters tapped. As it enters, choose a color other than black.
//! Oracle: {T}: Add {B} or one mana of the chosen color.
//! Set: MSC #582 — Marvel Super Heroes Commander | Scryfall ID: 5d5eea5f-b9e8-4a10-8e7f-c42493a728cd | Oracle ID: bff416bb-d193-4c45-b2c1-7c297dbfad08
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THRIVING_MOOR,
    oracle_id = "bff416bb-d193-4c45-b2c1-7c297dbfad08",
    scryfall_id = "5d5eea5f-b9e8-4a10-8e7f-c42493a728cd",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thriving Moor",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::ChooseColorExcept(ManaColor::Black),
            EnterModifier::Tapped
        ],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen_or(&[
        ManaColor::Black
    ])]),],
);
