//! Turbulent Fen — (no cost) — Land — Swamp Forest
//! Oracle: ({T}: Add {B} or {G}.)
//! Oracle: This land enters tapped unless your opponents control eight or more lands.
//! Set: SOC #55 — Secrets of Strixhaven Commander | Scryfall ID: 9737159b-256c-4004-ba5f-0417c35e1b30 | Oracle ID: 114dd40d-5ad8-4913-a08f-572b9521eb5b
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[Filter::LAND, Filter::ControlledByOpponent]);

card!(
    index = index::TURBULENT_FEN,
    oracle_id = "114dd40d-5ad8-4913-a08f-572b9521eb5b",
    scryfall_id = "9737159b-256c-4004-ba5f-0417c35e1b30",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Turbulent Fen",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::SWAMP, subtypes::land::FOREST],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK1,
            at_least: 8
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Green
    ])]),],
);
