//! Turbulent Wilderness — (no cost) — Land — Forest Island
//! Oracle: ({T}: Add {G} or {U}.)
//! Oracle: This land enters tapped unless your opponents control eight or more lands.
//! Set: SOC #59 — Secrets of Strixhaven Commander | Scryfall ID: b6ca755c-4b17-450b-b995-bfec8a55396f | Oracle ID: bd8adca6-4f16-45f8-994a-fe55bd573bd0
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[Filter::LAND, Filter::ControlledByOpponent]);

card!(
    index = index::TURBULENT_WILDERNESS,
    oracle_id = "bd8adca6-4f16-45f8-994a-fe55bd573bd0",
    scryfall_id = "b6ca755c-4b17-450b-b995-bfec8a55396f",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Turbulent Wilderness",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::FOREST, subtypes::land::ISLAND],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK1,
            at_least: 8
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Green,
        ManaColor::Blue
    ])]),],
);
