//! Uncharted Haven — (no cost) — Land
//! Oracle: This land enters tapped. As it enters, choose a color.
//! Oracle: {T}: Add one mana of the chosen color.
//! Set: BLB #261 — Bloomburrow | Scryfall ID: 68b90f54-d629-4126-82cc-13b51d6c1c3e | Oracle ID: d23c3613-bc5e-4fc5-939c-62a090c53a79
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::UNCHARTED_HAVEN,
    oracle_id = "d23c3613-bc5e-4fc5-939c-62a090c53a79",
    scryfall_id = "68b90f54-d629-4126-82cc-13b51d6c1c3e",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Uncharted Haven",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::ChooseColor, EnterModifier::Tapped],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen()]),],
);
