//! Vivid Marsh — (no cost) — Land
//! Oracle: This land enters tapped with two charge counters on it.
//! Oracle: {T}: Add {B}.
//! Oracle: {T}, Remove a charge counter from this land: Add one mana of any color.
//! Set: C17 #292 — Commander 2017 | Scryfall ID: b71b3df3-e188-45bb-8dc8-53fd4d527735 | Oracle ID: 20b32052-f66f-4eb8-b56e-00d531907f19
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VIVID_MARSH,
    oracle_id = "20b32052-f66f-4eb8-b56e-00d531907f19",
    scryfall_id = "b71b3df3-e188-45bb-8dc8-53fd4d527735",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vivid Marsh",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: CounterKind::Charge,
                amount: Amount::Fixed(2)
            }
        ],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelf {
                    kind: CounterKind::Charge,
                    n: 1
                }
            ),
            &[Effect::mana_of_any_color()]
        ),
    ],
);
