//! Vivid Creek — (no cost) — Land
//! Oracle: This land enters tapped with two charge counters on it.
//! Oracle: {T}: Add {U}.
//! Oracle: {T}, Remove a charge counter from this land: Add one mana of any color.
//! Set: NCC #444 — New Capenna Commander | Scryfall ID: c9082527-aa88-42f7-b2f2-de21878cb179 | Oracle ID: 2da7c49f-cc1e-45d9-9cbf-067e92b0daef
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VIVID_CREEK,
    oracle_id = "2da7c49f-cc1e-45d9-9cbf-067e92b0daef",
    scryfall_id = "c9082527-aa88-42f7-b2f2-de21878cb179",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vivid Creek",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: CounterKind::Charge,
                n: 2
            }
        ],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelf {
                    kind: CounterKind::Charge,
                    n: 1
                }
            ),
            &[Effect::mana_of_any_color()]
        ),
    ],
);
