//! Vivid Crag — (no cost) — Land
//! Oracle: This land enters tapped with two charge counters on it.
//! Oracle: {T}: Add {R}.
//! Oracle: {T}, Remove a charge counter from this land: Add one mana of any color.
//! Set: CM2 #276 — Commander Anthology Volume II | Scryfall ID: da397243-2193-4e5d-8dee-df37b70677e7 | Oracle ID: d8e2efe0-33a4-4303-9e83-ac42ea5df8cb
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VIVID_CRAG,
    oracle_id = "d8e2efe0-33a4-4303-9e83-ac42ea5df8cb",
    scryfall_id = "da397243-2193-4e5d-8dee-df37b70677e7",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vivid Crag",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: CounterKind::Charge,
                n: 2
            }
        ],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelf {
                    kind: CounterKind::Charge,
                    n: 1
                }
            ),
            &[Effect::mana_of_any_color()]
        ),
    ],
);
