//! Vivid Meadow — (no cost) — Land
//! Oracle: This land enters tapped with two charge counters on it.
//! Oracle: {T}: Add {W}.
//! Oracle: {T}, Remove a charge counter from this land: Add one mana of any color.
//! Set: NCC #446 — New Capenna Commander | Scryfall ID: 625a42b4-d88c-48e0-96b1-77388ca48810 | Oracle ID: dee99df5-628f-4a4e-a203-4dfddc927373
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VIVID_MEADOW,
    oracle_id = "dee99df5-628f-4a4e-a203-4dfddc927373",
    scryfall_id = "625a42b4-d88c-48e0-96b1-77388ca48810",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vivid Meadow",
        types = TypeSet::LAND,
        enter_modifiers = &[
            EnterModifier::Tapped,
            EnterModifier::WithCounters {
                kind: CounterKind::Charge,
                amount: Amount::Fixed(2)
            }
        ],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelf {
                    kind: CounterKind::Charge,
                    n: 1
                }
            ),
            &[Effect::mana_of_any_color()]
        ),
    ],
);
