//! Baldur's Gate — (no cost) — Legendary Land — Gate
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}: Add X mana of any one color, where X is the number of other Gates you control.
//! Set: CLB #345 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 2436aa14-9200-4295-8041-b682cf3c4216 | Oracle ID: da307ea2-4df7-4d6b-be0f-9dc6ac93db61
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COUNT1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::GATE),
    Filter::ControlledByYou,
    Filter::Another,
]);

card!(
    index = index::BALDUR_S_GATE,
    oracle_id = "da307ea2-4df7-4d6b-be0f-9dc6ac93db61",
    scryfall_id = "2436aa14-9200-4295-8041-b682cf3c4216",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Baldur's Gate",
        types = TypeSet::LAND,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::land::GATE],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{2}", TapSelf),
            &[Effect::mana_choice_dynamic(
                ALL_MANA_COLORS,
                Amount::CountOf {
                    filter: &COUNT1,
                    zone: ZoneSel::Battlefield
                }
            )]
        ),
    ],
);
