//! Black Dragon Gate — (no cost) — Land — Gate
//! Oracle: This land enters tapped.
//! Oracle: As this land enters, choose a color other than black.
//! Oracle: {T}: Add {B} or one mana of the chosen color.
//! Set: CLB #347 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: c4ceb589-c741-44ac-98c8-3d997953ee61 | Oracle ID: dde6bce5-8bbe-4866-b5aa-2c05c7d37241
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BLACK_DRAGON_GATE,
    oracle_id = "dde6bce5-8bbe-4866-b5aa-2c05c7d37241",
    scryfall_id = "c4ceb589-c741-44ac-98c8-3d997953ee61",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Black Dragon Gate",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::GATE],
        enter_modifiers = &[
            EnterModifier::ChooseColorExcept(ManaColor::Black),
            EnterModifier::Tapped
        ],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen_or(&[
        ManaColor::Black
    ])]),],
);
