//! Cliffgate — (no cost) — Land — Gate
//! Oracle: This land enters tapped.
//! Oracle: As this land enters, choose a color other than red.
//! Oracle: {T}: Add {R} or one mana of the chosen color.
//! Set: CLB #350 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 557470dc-c594-4b26-81b9-356bedb0c215 | Oracle ID: 1999b5ac-21fb-4d99-ad72-58bf507f9a59
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CLIFFGATE,
    oracle_id = "1999b5ac-21fb-4d99-ad72-58bf507f9a59",
    scryfall_id = "557470dc-c594-4b26-81b9-356bedb0c215",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Cliffgate",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::GATE],
        enter_modifiers = &[
            EnterModifier::ChooseColorExcept(ManaColor::Red),
            EnterModifier::Tapped
        ],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen_or(&[ManaColor::Red])]),],
);
