//! Heap Gate — (no cost) — Land — Gate
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add one mana of any color.
//! Oracle: {1}, {T}, Tap an untapped Gate you control: Create a Treasure token. (It's an artifact with "{T}, Sacrifice this token: Add one mana of any color.")
//! Set: CLB #354 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 68489d65-1978-48b1-a903-2ef38c583239 | Oracle ID: 35922a30-6b84-44dd-a2f0-306554a1ae90
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::GATE),
    Filter::ControlledByYou,
]);

card!(
    index = index::HEAP_GATE,
    oracle_id = "35922a30-6b84-44dd-a2f0-306554a1ae90",
    scryfall_id = "68489d65-1978-48b1-a903-2ef38c583239",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Heap Gate",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::GATE],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(cost!("{1}", TapSelf), &[Effect::mana_of_any_color()]),
        activated!(
            cost!("{1}", TapSelf, TapOther(&COST1)),
            &[Effect::CreateToken {
                token: &generated_tokens::TREASURE
            }]
        ),
    ],
);
