//! Fountainport — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}, Sacrifice a token: Draw a card.
//! Oracle: {3}, {T}, Pay 1 life: Create a 1/1 blue Fish creature token.
//! Oracle: {4}, {T}: Create a Treasure token.
//! Set: BLB #253 — Bloomburrow | Scryfall ID: 658cfcb7-81b7-48c6-9dd2-1663d06108cf | Oracle ID: 94e8b0a9-44a1-4dce-8d44-78681ae638a1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

static COST1: Filter = Filter::And(&[Filter::IsToken, Filter::ControlledByYou]);

card!(
    index = index::FOUNTAINPORT,
    oracle_id = "94e8b0a9-44a1-4dce-8d44-78681ae638a1",
    scryfall_id = "658cfcb7-81b7-48c6-9dd2-1663d06108cf",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Fountainport", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(cost!("{2}", TapSelf, Sacrifice(&COST1)), &[Effect::draw(1)]),
        activated!(
            cost!("{3}", TapSelf, PayLife(1)),
            &[Effect::CreateToken {
                token: &generated_tokens::FISH_1_1_BLUE
            }]
        ),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::TREASURE
            }]
        ),
    ],
);
