//! Horizon Canopy — (no cost) — Land
//! Oracle: {T}, Pay 1 life: Add {G} or {W}.
//! Oracle: {1}, {T}, Sacrifice this land: Draw a card.
//! Set: IMA #240 — Iconic Masters | Scryfall ID: 93f7c880-9bae-4d29-b7b6-b6be6b2ffa89 | Oracle ID: 262a5d83-506c-4781-9bc9-1a2b5d83955c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HORIZON_CANOPY,
    oracle_id = "262a5d83-506c-4781-9bc9-1a2b5d83955c",
    scryfall_id = "93f7c880-9bae-4d29-b7b6-b6be6b2ffa89",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Horizon Canopy", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(
            cost!(TapSelf, PayLife(1)),
            &[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]
        ),
        activated!(cost!("{1}", TapSelf, SacrificeSelf), &[Effect::draw(1)]),
    ],
);
