//! Dragon Roost — {4}{R}{R} — Enchantment
//! Oracle: {5}{R}{R}: Create a 5/5 red Dragon creature token with flying. (It can't be blocked except by creatures with flying or reach.)
//! Set: 10E #197 — Tenth Edition | Scryfall ID: 1da84a3e-a8b2-4cb4-b9c9-1b5c2dca8c67 | Oracle ID: 6dc98143-7c4c-4b75-9bbb-5226d800b1d6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::DRAGON_ROOST,
    oracle_id = "6dc98143-7c4c-4b75-9bbb-5226d800b1d6",
    scryfall_id = "1da84a3e-a8b2-4cb4-b9c9-1b5c2dca8c67",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dragon Roost",
        mana_cost = mana!("{4}{R}{R}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{5}{R}{R}"),
        &[Effect::CreateToken {
            token: &generated_tokens::DRAGON_5_5_RED_FLYING
        }]
    ),],
);
