#!/usr/bin/env python3
"""A card this session added, fixed or refactored is played once in a test.

A `Stop` hook. It reads the list `card-test-debt.py` kept, throws away every
card that is still a stub (a refusal owes nothing — the file is byte-identical
to the one codegen wrote), and asks of each of the rest one question: does any
engine test name its `oracle_id`?

**Why the oracle id and not the card's name.** A card test addresses a card as
`card_index("<oracle_id>")`, so the id is the handle a test actually holds; a
name would match a doc comment and count a card as played because somebody
mentioned it.

**And why the walk is recursive, with a floor under it.** It read
`engine/*_tests.rs` — one non-recursive glob — from the day it was written,
and `card_tests` and `combo_tests` are *directories*. It reached 88 of the
216 ids the engine's tests actually hold and reported six freshly tested
cards as untested, with every one of their tests sitting in
`card_tests/enchantments.rs` and its neighbours. That is the same failure
`card_files` exists to prevent (CLAUDE.md: "a non-recursive `read_dir` over a
tree finds nothing and reports an empty worklist as an answer"), and the
floor is the other half: a walk that comes back with almost nothing now
*refuses* instead of turning its own blindness into a debt list.

**Why not a test module in the card file.** CLAUDE.md is explicit that a card
file carries none: "a card file is data, and a test that reads the literal it
sits under proves nothing". The thing worth proving is that the rules engine
does what the printed sentence says, and that can only be shown by playing it
— `crates/baylee-engine/src/engine/card_tests/` is the home, split by card
type, on the shared `testkit`.

**A machine-owned card is skipped**, because a rule wrote it and a rule is
what a test should hold. Asking per card would put 394 entries on the list
after one `codegen` run and would still not have tested the thing that can
be wrong.

**And a fix owes a second test.** A card that was wrong was wrong because a
rule was wrong, and the rule is where hundreds of other cards live. The
regression test belongs beside the rule — `keyword_tests`, `layers_tests`,
`abilities`, wherever the defect was — and has to be the test that fails
against the old code. Writing only the card's own scenario fixes one card and
leaves the next fifty to be found by a player.

It asks at the moment a card is **committed**, not at the moment it is
written, and the difference is the whole usability of the thing. A card in
the working tree is work in progress: a batch writes a hundred of them, a
verifier reverts some, and a hook shouting after every edit would be
answering a question nobody has finished asking yet. Committing is where a
card is declared done, so that is where the test is owed. The card stays on
the list until then, and is re-asked after every commit that leaves it
untested.

It blocks rather than warns, because a reminder that costs nothing is one
that gets read and stepped over. `stop_hook_active` keeps it from looping: a
stop that a hook already blocked is allowed through, so the debt is stated
once per turn and never traps the session.
"""

import json
import os
import pathlib
import re
import subprocess
import sys

STUB = "// GENERATED STUB"
OWNED = "// IMPLEMENTED \u2014 generated by `xtask codegen`"
ORACLE = re.compile(r'^//! .*Oracle ID: ([0-9a-f-]{36})', re.M)
FALLBACK = re.compile(r'oracle_id\s*=\s*"([0-9a-f-]{36})"')
HANDLE = re.compile(r'card_index\("([0-9a-f-]{36})"\)')

# What the walk reaches today: 57 files holding 216 ids. The floors are well
# under both, because they are not a target — they are the difference between
# "no card owes a test" and "this hook read the wrong directory".
FILE_FLOOR = 30
ID_FLOOR = 120


def uncommitted(root: pathlib.Path, path: pathlib.Path) -> bool:
    """Whether the file still differs from what `HEAD` holds."""
    try:
        return subprocess.run(
            ["git", "diff", "--quiet", "HEAD", "--", str(path)],
            cwd=root,
            capture_output=True,
            check=False,
        ).returncode != 0
    except OSError:
        return False


def main() -> int:
    event = json.load(sys.stdin)
    if event.get("stop_hook_active"):
        return 0

    root = pathlib.Path(os.environ.get("CLAUDE_PROJECT_DIR") or ".")
    debt = root / ".claude" / "card-test-debt"
    if not debt.exists():
        return 0
    touched = [line for line in debt.read_text().split("\n") if line.strip()]
    if not touched:
        return 0

    engine = root / "crates/baylee-engine/src/engine"
    read = [
        p
        for p in engine.rglob("*.rs")
        if p.name.endswith("_tests.rs") or p.parent.name.endswith("_tests")
    ]
    tests = "".join(p.read_text() for p in read)
    held = set(HANDLE.findall(tests))
    if len(read) < FILE_FLOOR or len(held) < ID_FLOOR:
        print(
            f"require-card-tests read {len(read)} test files holding {len(held)} card "
            f"ids (floors {FILE_FLOOR} and {ID_FLOOR}). That is not the engine's test "
            "suite, so every card would look untested. Fix the walk, not the cards.",
            file=sys.stderr,
        )
        return 0

    owed = []
    for rel in touched:
        path = root / "crates/baylee-cards/src/cards" / rel
        if not path.exists():
            continue
        if uncommitted(root, path):
            continue  # still being written; nobody has declared it done
        text = path.read_text()
        if STUB in text:
            continue  # a refusal restored its stub and owes nothing
        if OWNED in text:
            # A reader wrote this one, and CLAUDE.md is explicit about what
            # follows: "a machine-owned card is a rule's output, and a rule is
            # testable". One `codegen` run rewrites 394 of these, so asking
            # per card would be both noise and the wrong question — the test
            # belongs to `landgen`/`scriptgen`, beside the rule that emitted
            # it, exactly as a fix's regression test belongs beside the rule
            # it broke.
            continue
        m = ORACLE.search(text) or FALLBACK.search(text)
        if not m:
            continue
        if m.group(1) not in tests:
            name = text.split("—")[0].removeprefix("//! ").strip()
            owed.append((name or rel, rel, m.group(1)))

    if not owed:
        debt.unlink(missing_ok=True)
        return 0

    lines = [
        f"{len(owed)} card(s) written this session are not played by any engine test.",
        "",
        "A card file carries no test module (CLAUDE.md: it is data, and a test that",
        "reads the literal it sits under proves nothing). What is owed is a scenario in",
        "crates/baylee-engine/src/engine/card_tests/ on the shared testkit, addressing",
        'the card as card_index("<oracle id>") — small, and carrying only the card\'s own',
        "printed text as the situation:",
        "",
    ]
    for name, rel, oid in owed[:25]:
        lines.append(f'  {name}\n      {rel}\n      card_index("{oid}")')
    if len(owed) > 25:
        lines.append(f"  … and {len(owed) - 25} more (full list: .claude/card-test-debt)")
    lines += [
        "",
        "If any of these was a FIX rather than a new card, it owes a second test, and",
        "that one does not go in card_tests/: the card was wrong because a rule was",
        "wrong, so the regression test belongs beside the rule it broke and must be a",
        "test that fails against the old code. Strike both halves.",
        "",
        "These are cards that have been COMMITTED without one; a card still in the",
        "working tree is work in progress and is not asked about.",
        "",
        "Clear the list with `rm .claude/card-test-debt` once the tests are written, or",
        "deliberately, if a card genuinely plays nothing an engine can observe — say so.",
    ]
    print("\n".join(lines), file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never wedge a session on a bookkeeping hook
        print(f"require-card-tests hook failed: {exc}", file=sys.stderr)
        sys.exit(0)
