#!/usr/bin/env python3
"""A card this session added, fixed or refactored is played once in a test.

A `Stop` hook. It reads the list `card-test-debt.py` kept, throws away every
card that is still a stub (a refusal owes nothing — the file is byte-identical
to the one codegen wrote), and asks of each of the rest one question: does any
engine test name its `oracle_id`?

**Why the oracle id and not the card's name.** A card test addresses a card as
`card_index("<oracle_id>")`, so the id is the handle a test actually holds; a
name would match a doc comment and count a card as played because somebody
mentioned it.

**And why the walk is recursive, with a floor under it.** It read
`engine/*_tests.rs` — one non-recursive glob — from the day it was written,
and `card_tests` and `combo_tests` are *directories*. It reached 88 of the
216 ids the engine's tests actually hold and reported six freshly tested
cards as untested, with every one of their tests sitting in
`card_tests/enchantments.rs` and its neighbours. That is the same failure
`card_files` exists to prevent (CLAUDE.md: "a non-recursive `read_dir` over a
tree finds nothing and reports an empty worklist as an answer"), and the
floor is the other half: a walk that comes back with almost nothing now
*refuses* instead of turning its own blindness into a debt list.

**Why not a test module in the card file.** CLAUDE.md is explicit that a card
file carries none: "a card file is data, and a test that reads the literal it
sits under proves nothing". The thing worth proving is that the rules engine
does what the printed sentence says, and that can only be shown by playing it
— `crates/baylee-engine/src/engine/card_tests/` is the home, split by card
type, on the shared `testkit`.

**A machine-owned card is skipped**, because a rule wrote it and a rule is
what a test should hold. Asking per card would put 394 entries on the list
after one `codegen` run and would still not have tested the thing that can
be wrong.

**And a fix owes a second test.** A card that was wrong was wrong because a
rule was wrong, and the rule is where hundreds of other cards live. The
regression test belongs beside the rule — `keyword_tests`, `layers_tests`,
`abilities`, wherever the defect was — and has to be the test that fails
against the old code. Writing only the card's own scenario fixes one card and
leaves the next fifty to be found by a player.

It asks at the moment a card is **committed**, not at the moment it is
written, and the difference is the whole usability of the thing. A card in
the working tree is work in progress: a batch writes a hundred of them, a
verifier reverts some, and a hook shouting after every edit would be
answering a question nobody has finished asking yet. Committing is where a
card is declared done, so that is where the test is owed. The card stays on
the list until then, and is re-asked after every commit that leaves it
untested.

It blocks rather than warns, because a reminder that costs nothing is one
that gets read and stepped over. `stop_hook_active` keeps it from looping: a
stop that a hook already blocked is allowed through, so the debt is stated
once per turn and never traps the session.

## The second question: a reader that changed

The list above cannot see a generated card at all, and that hole was open
from the day both hooks were written. `card-test-debt.py` records `Edit`,
`Write` and `MultiEdit`; `xtask codegen` writes card files from a `Bash`
call, so a card a rule produced is never recorded — and if it were, the walk
above skips it for carrying the machine-owned marker. Eleven lands were
generated, committed and pushed on 18.09.2026 with an empty debt list, and
five more were hand-pulled onto a fixed reader's output the same day with no
engine test at all. Both were caught by a person reading CLAUDE.md, which is
exactly the guarantee a hook is supposed to replace.

Asking per generated card is still the wrong question, for the reason the
skip gives: one `codegen` run rewrites hundreds of them. So this asks the
*rule's* question instead, once. When a reader in
`crates/baylee-cards-codegen/` changed on this branch and machine-owned card
files changed with it, **at least one of those cards has to be played by an
engine test.** A rule whose entire output is unplayed is an untested rule;
one played card is what turns it into a testable one, and the rest are its
siblings.

The range is `origin/main..HEAD` plus the working tree — what this branch has
that the remote does not. It goes quiet after a push, which is the same
bargain the list above strikes: the debt is asked at the moment of
committing, and a push is where it was either paid or knowingly accepted.
"""

import json
import os
import pathlib
import re
import subprocess
import sys

STUB = "// GENERATED STUB"
OWNED = "// IMPLEMENTED \u2014 generated by `xtask codegen`"
ORACLE = re.compile(r'^//! .*Oracle ID: ([0-9a-f-]{36})', re.M)
FALLBACK = re.compile(r'oracle_id\s*=\s*"([0-9a-f-]{36})"')
HANDLE = re.compile(r'card_index\("([0-9a-f-]{36})"\)')

# What the walk reaches today: 57 files holding 216 ids. The floors are well
# under both, because they are not a target — they are the difference between
# "no card owes a test" and "this hook read the wrong directory".
FILE_FLOOR = 30
ID_FLOOR = 120


def uncommitted(root: pathlib.Path, path: pathlib.Path) -> bool:
    """Whether the file still differs from what `HEAD` holds."""
    try:
        return subprocess.run(
            ["git", "diff", "--quiet", "HEAD", "--", str(path)],
            cwd=root,
            capture_output=True,
            check=False,
        ).returncode != 0
    except OSError:
        return False


READERS = "crates/baylee-cards-codegen/src/"
CARDS = "crates/baylee-cards/src/cards/"


def changed_on_this_branch(root: pathlib.Path) -> list[str] | None:
    """Paths this branch changed that `origin/main` does not have, plus the
    working tree.

    `None` rather than `[]` when git could not answer, because the two mean
    opposite things: an empty answer is "nothing changed" and a failure is
    "this check saw nothing at all". Turning the second into the first is how
    a guard goes quietly blind, which is the failure this hook already has a
    floor against one paragraph up.
    """
    out: set[str] = set()
    for args in (
        ["git", "diff", "--name-only", "origin/main...HEAD"],
        ["git", "diff", "--name-only", "HEAD"],
    ):
        try:
            done = subprocess.run(args, cwd=root, capture_output=True, text=True, check=False)
        except OSError:
            return None
        if done.returncode != 0:
            return None
        out.update(line for line in done.stdout.split("\n") if line.strip())
    return sorted(out)


def reader_debt(root: pathlib.Path, tests: str) -> tuple[list[str], list[tuple[str, str]]] | None:
    """The readers that changed, and the machine-owned cards that changed with
    them — but only while not one of those cards is played."""
    changed = changed_on_this_branch(root)
    if changed is None:
        return None
    readers = [p for p in changed if p.startswith(READERS) and p.endswith(".rs")]
    if not readers:
        return ([], [])
    cards: list[tuple[str, str]] = []
    for rel in changed:
        if not rel.startswith(CARDS) or not rel.endswith(".rs") or rel.endswith("mod.rs"):
            continue
        path = root / rel
        if not path.exists():
            continue
        text = path.read_text()
        if STUB in text or OWNED not in text:
            continue  # a stub owes nothing, and a hand-written card is the list above
        m = ORACLE.search(text) or FALLBACK.search(text)
        if m:
            cards.append((rel[len(CARDS):], m.group(1)))
    if not cards:
        return ([], [])
    if any(oid in tests for _, oid in cards):
        return ([], [])  # the rule has a played output, which is what is owed
    return (readers, cards)


def main() -> int:
    event = json.load(sys.stdin)
    if event.get("stop_hook_active"):
        return 0

    root = pathlib.Path(os.environ.get("CLAUDE_PROJECT_DIR") or ".")
    debt = root / ".claude" / "card-test-debt"
    touched = (
        [line for line in debt.read_text().split("\n") if line.strip()]
        if debt.exists()
        else []
    )

    engine = root / "crates/baylee-engine/src/engine"
    read = [
        p
        for p in engine.rglob("*.rs")
        if p.name.endswith("_tests.rs") or p.parent.name.endswith("_tests")
    ]
    tests = "".join(p.read_text() for p in read)
    held = set(HANDLE.findall(tests))
    if len(read) < FILE_FLOOR or len(held) < ID_FLOOR:
        print(
            f"require-card-tests read {len(read)} test files holding {len(held)} card "
            f"ids (floors {FILE_FLOOR} and {ID_FLOOR}). That is not the engine's test "
            "suite, so every card would look untested. Fix the walk, not the cards.",
            file=sys.stderr,
        )
        return 0

    owed = []
    for rel in touched:
        path = root / "crates/baylee-cards/src/cards" / rel
        if not path.exists():
            continue
        if uncommitted(root, path):
            continue  # still being written; nobody has declared it done
        text = path.read_text()
        if STUB in text:
            continue  # a refusal restored its stub and owes nothing
        if OWNED in text:
            # A reader wrote this one, and CLAUDE.md is explicit about what
            # follows: "a machine-owned card is a rule's output, and a rule is
            # testable". One `codegen` run rewrites 394 of these, so asking
            # per card would be both noise and the wrong question — the test
            # belongs to `landgen`/`scriptgen`, beside the rule that emitted
            # it, exactly as a fix's regression test belongs beside the rule
            # it broke.
            continue
        m = ORACLE.search(text) or FALLBACK.search(text)
        if not m:
            continue
        if m.group(1) not in tests:
            name = text.split("—")[0].removeprefix("//! ").strip()
            owed.append((name or rel, rel, m.group(1)))

    if not owed:
        debt.unlink(missing_ok=True)

    reader = reader_debt(root, tests)
    if reader is None:
        print(
            "require-card-tests could not ask git what this branch changed, so the "
            "reader half of this check saw nothing. That is not the same as a clean "
            "branch — fix the walk, not the cards.",
            file=sys.stderr,
        )
        reader = ([], [])
    readers, generated = reader

    if not owed and not readers:
        return 0

    lines: list[str] = []
    if owed:
        lines += [
            f"{len(owed)} card(s) written this session are not played by any engine "
            "test.",
            "",
            "A card file carries no test module (CLAUDE.md: it is data, and a test that",
            "reads the literal it sits under proves nothing). What is owed is a scenario",
            "in crates/baylee-engine/src/engine/card_tests/ on the shared testkit,",
            'addressing the card as card_index("<oracle id>") — small, and carrying only',
            "the card's own printed text as the situation:",
            "",
        ]
        for name, rel, oid in owed[:25]:
            lines.append(f'  {name}\n      {rel}\n      card_index("{oid}")')
        if len(owed) > 25:
            lines.append(
                f"  … and {len(owed) - 25} more (full list: .claude/card-test-debt)"
            )
        lines += [
            "",
            "If any of these was a FIX rather than a new card, it owes a second test,",
            "and that one does not go in card_tests/: the card was wrong because a rule",
            "was wrong, so the regression test belongs beside the rule it broke and must",
            "be a test that fails against the old code. Strike both halves.",
            "",
            "These are cards that have been COMMITTED without one; a card still in the",
            "working tree is work in progress and is not asked about.",
            "",
            "Clear the list with `rm .claude/card-test-debt` once the tests are written,",
            "or deliberately, if a card genuinely plays nothing an engine can observe —",
            "say so.",
        ]

    if readers:
        if lines:
            lines += ["", "-" * 72, ""]
        lines += [
            f"A card reader changed on this branch and {len(generated)} machine-owned "
            "card(s) changed with it, and not one of them is played by an engine test.",
            "",
            "Asking per generated card would be the wrong question — one codegen run",
            "rewrites hundreds. What is owed is the RULE's test: at least one of these",
            "cards played in crates/baylee-engine/src/engine/card_tests/, because a rule",
            "whose entire output is unplayed is an untested rule.",
            "",
            "The readers that changed:",
        ]
        lines += [f"  {r}" for r in readers[:10]]
        if len(readers) > 10:
            lines.append(f"  … and {len(readers) - 10} more")
        lines += ["", "The cards they wrote:"]
        for rel, oid in generated[:25]:
            lines.append(f'  {rel}\n      card_index("{oid}")')
        if len(generated) > 25:
            lines.append(f"  … and {len(generated) - 25} more")
        lines += [
            "",
            "If the reader change was a FIX, the second test still applies and does not",
            "go in card_tests/: it belongs beside the rule that was wrong, and has to",
            "fail against the old code.",
            "",
            "This question goes quiet once the branch is pushed, like the one above.",
        ]

    print("\n".join(lines), file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never wedge a session on a bookkeeping hook
        print(f"require-card-tests hook failed: {exc}", file=sys.stderr)
        sys.exit(0)
