//! Mistvault Bridge — (no cost) — Artifact Land
//! Oracle: This land enters tapped.
//! Oracle: Indestructible
//! Oracle: {T}: Add {U} or {B}.
//! Set: MH2 #249 — Modern Horizons 2 | Scryfall ID: 9f36a6e2-3e51-4a30-a225-10cfe6650b9d | Oracle ID: 33ee23bc-6327-4a54-a704-dfd83be36bb5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 771,
    oracle_id: "33ee23bc-6327-4a54-a704-dfd83be36bb5",
    scryfall_id: "9f36a6e2-3e51-4a30-a225-10cfe6650b9d",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    keywords: KeywordSet::INDESTRUCTIBLE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Mistvault Bridge",
        types: TypeSet::ARTIFACT.union(TypeSet::LAND),
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
