//! Tanglepool Bridge — (no cost) — Artifact Land
//! Oracle: This land enters tapped.
//! Oracle: Indestructible
//! Oracle: {T}: Add {G} or {U}.
//! Set: MH2 #257 — Modern Horizons 2 | Scryfall ID: 57d2b895-8921-4615-a674-fb85eed5ea3f | Oracle ID: 29cd8a7c-108a-43d1-af63-f603a27c24f2
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1139,
    oracle_id: "29cd8a7c-108a-43d1-af63-f603a27c24f2",
    scryfall_id: "57d2b895-8921-4615-a674-fb85eed5ea3f",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    keywords: KeywordSet::INDESTRUCTIBLE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Tanglepool Bridge",
        types: TypeSet::ARTIFACT.union(TypeSet::LAND),
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
