//! Angelic Voices — {2}{W}{W} — Enchantment
//! Oracle: Creatures you control get +1/+1 as long as you control no nonartifact, nonwhite creatures.
//! Set: ME4 #3 — Masters Edition IV | Scryfall ID: 03f49b52-05fb-4d5a-a317-9fd89afcaa25 | Oracle ID: 3485109b-251f-4bef-a069-308031f47912
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static CHECK1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::Not(&Filter::HasColor(ColorSet::from_slice(&[Color::White]))),
    Filter::LacksType(TypeSet::ARTIFACT),
    Filter::ControlledByYou,
]);

card!(
    index = index::ANGELIC_VOICES,
    oracle_id = "3485109b-251f-4bef-a069-308031f47912",
    scryfall_id = "03f49b52-05fb-4d5a-a317-9fd89afcaa25",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Angelic Voices",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[static_ability!(
        Filter::YOUR_CREATURE,
        Modifier::ModifyPT(1, 1),
        condition = Some(Condition::ControlCountAtMost(&CHECK1, 0))
    ),],
);
