//! Castle — {3}{W} — Enchantment
//! Oracle: Untapped creatures you control get +0/+2.
//! Set: 7ED #5 — Seventh Edition | Scryfall ID: ffe82e29-e781-48bf-8673-7954553f7cf0 | Oracle ID: f3179c3c-7e53-44d2-b579-b9e677efe9d9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CASTLE,
    oracle_id = "f3179c3c-7e53-44d2-b579-b9e677efe9d9",
    scryfall_id = "ffe82e29-e781-48bf-8673-7954553f7cf0",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Castle",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[static_ability!(
        Filter::And(&[Filter::CREATURE, Filter::Untapped, Filter::ControlledByYou]),
        Modifier::ModifyPT(0, 2)
    ),],
);
