//! Conversion — {2}{W}{W} — Enchantment
//! Oracle: At the beginning of your upkeep, sacrifice this enchantment unless you pay {W}{W}.
//! Oracle: All Mountains are Plains.
//! Set: ME4 #9 — Masters Edition IV | Scryfall ID: 70bad071-f01e-4309-b37a-a3ea45dc7d3a | Oracle ID: a24e05fb-dffb-4400-b4ca-22fdde45e7a7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CONVERSION,
    oracle_id = "a24e05fb-dffb-4400-b4ca-22fdde45e7a7",
    scryfall_id = "70bad071-f01e-4309-b37a-a3ea45dc7d3a",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Conversion",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::PlayerMayPayManaOr {
                player: PlayerRel::You,
                cost: mana!("{W}{W}"),
                effect: &Effect::SacrificeSelf
            }]
        ),
        static_ability!(
            Filter::HasSubtype(subtypes::land::MOUNTAIN),
            Modifier::SetLandType(subtypes::land::PLAINS)
        ),
    ],
);
