//! Embargo — {3}{U} — Enchantment
//! Oracle: Nonland permanents don't untap during their controllers' untap steps.
//! Oracle: At the beginning of your upkeep, you lose 2 life.
//! Set: MMQ #77 — Mercadian Masques | Scryfall ID: 3fca3c65-f20e-4978-bfbb-ee7f9e1d829f | Oracle ID: edadd0bf-15c8-4e9c-810e-2edfd77a9d01
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::EMBARGO,
    oracle_id = "edadd0bf-15c8-4e9c-810e-2edfd77a9d01",
    scryfall_id = "3fca3c65-f20e-4978-bfbb-ee7f9e1d829f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Embargo",
        mana_cost = mana!("{3}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(Filter::NONLAND, Modifier::DoesNotUntap),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::LoseLife {
                amount: Amount::Fixed(2),
                target: PlayerRel::You
            }]
        ),
    ],
);
