//! Pegasus Refuge — {3}{W} — Enchantment
//! Oracle: {2}, Discard a card: Create a 1/1 white Pegasus creature token with flying.
//! Set: TMP #35 — Tempest | Scryfall ID: a2bce334-0ae6-4a7d-85db-99ee205ce546 | Oracle ID: 07462467-e4a3-409e-bcef-9cc92ca4c299
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::PEGASUS_REFUGE,
    oracle_id = "07462467-e4a3-409e-bcef-9cc92ca4c299",
    scryfall_id = "a2bce334-0ae6-4a7d-85db-99ee205ce546",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Pegasus Refuge",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{2}", Discard(&Filter::Any)),
        &[Effect::CreateToken {
            token: &generated_tokens::PEGASUS_1_1_WHITE_FLYING
        }]
    ),],
);
