//! Spiritual Asylum — {2}{W}{W} — Enchantment
//! Oracle: Creatures and lands you control have shroud. (They can't be the targets of spells or abilities.)
//! Oracle: When a creature you control attacks, sacrifice this enchantment.
//! Set: NEM #23 — Nemesis | Scryfall ID: e5eea354-2d92-4b57-aec7-25260ab7a70f | Oracle ID: 91924536-7a2b-44ec-9835-2efa402c83f9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPIRITUAL_ASYLUM,
    oracle_id = "91924536-7a2b-44ec-9835-2efa402c83f9",
    scryfall_id = "e5eea354-2d92-4b57-aec7-25260ab7a70f",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spiritual Asylum",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(
            Filter::Or(&[
                Filter::And(&[Filter::CREATURE, Filter::ControlledByYou]),
                Filter::And(&[Filter::LAND, Filter::ControlledByYou])
            ]),
            Modifier::AddKeyword(KeywordSet::SHROUD)
        ),
        triggered!(
            Trigger::Attacks(&Filter::YOUR_CREATURE),
            &[Effect::SacrificeSelf]
        ),
    ],
);
