[package]
name = "baylee-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Binary websocket protocol (protobuf), wasm-safe"

[lints]
workspace = true

[dependencies]
prost.workspace = true
bytes.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
