//! Yotian Soldier — {3} — Artifact Creature — Soldier
//! Oracle: Vigilance
//! Set: BBD #249 — Battlebond | Scryfall ID: 9e71190b-c96c-4aea-9696-780c69eff395 | Oracle ID: 645571f1-a775-4834-8b79-8852d38c9587
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::YOTIAN_SOLDIER,
    oracle_id = "645571f1-a775-4834-8b79-8852d38c9587",
    scryfall_id = "9e71190b-c96c-4aea-9696-780c69eff395",
    keywords = KeywordSet::VIGILANCE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Yotian Soldier",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::SOLDIER],
        power = Some(1),
        toughness = Some(4),
    ),],
);
