//! Clutch of Undeath — {3}{B}{B} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +3/+3 as long as it's a Zombie. Otherwise, it gets -3/-3.
//! Set: SCG #61 — Scourge | Scryfall ID: 7301fdec-ca17-47ae-9a0a-84ea8665ece1 | Oracle ID: 5a68c925-db79-44f2-a5c1-5a607298f6cf
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CLUTCH_OF_UNDEATH,
    oracle_id = "5a68c925-db79-44f2-a5c1-5a607298f6cf",
    scryfall_id = "7301fdec-ca17-47ae-9a0a-84ea8665ece1",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Clutch of Undeath",
        mana_cost = mana!("{3}{B}{B}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::AttachedToBySource,
                Filter::HasSubtype(subtypes::creature::ZOMBIE)
            ]),
            Modifier::ModifyPT(3, 3)
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::AttachedToBySource,
                Filter::Not(&Filter::HasSubtype(subtypes::creature::ZOMBIE))
            ]),
            Modifier::ModifyPT(-3, -3)
        ),
    ],
);
