//! Alexi's Cloak — {1}{U} — Enchantment — Aura
//! Oracle: Flash
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has shroud. (It can't be the target of spells or abilities.)
//! Set: PCY #29 — Prophecy | Scryfall ID: 457a5613-d1d4-4112-8484-f40120079b7b | Oracle ID: e52eb1a6-fff1-4a47-b434-31a74d76231c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ALEXI_S_CLOAK,
    oracle_id = "e52eb1a6-fff1-4a47-b434-31a74d76231c",
    scryfall_id = "457a5613-d1d4-4112-8484-f40120079b7b",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLASH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Alexi's Cloak",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::SHROUD)
        ),
    ],
);
