//! Diplomatic Immunity — {1}{U} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Shroud (A permanent with shroud can't be the target of spells or abilities.)
//! Oracle: Enchanted creature has shroud.
//! Set: MMQ #75 — Mercadian Masques | Scryfall ID: fb1e610e-a4a2-460b-8e4c-13674badbce3 | Oracle ID: f1a3153c-0200-4ff2-b7d5-48d23920bb3c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DIPLOMATIC_IMMUNITY,
    oracle_id = "f1a3153c-0200-4ff2-b7d5-48d23920bb3c",
    scryfall_id = "fb1e610e-a4a2-460b-8e4c-13674badbce3",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::SHROUD,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Diplomatic Immunity",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::SHROUD)
        ),
    ],
);
