//! Enfeeblement — {B}{B} — Enchantment — Aura
//! Oracle: Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
//! Oracle: Enchanted creature gets -2/-2.
//! Set: 9ED #127 — Ninth Edition | Scryfall ID: 4adaf0bf-b26d-4166-8809-431283690de7 | Oracle ID: 42b2db4c-4a1d-436f-9eeb-53a04db46c58
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ENFEEBLEMENT,
    oracle_id = "42b2db4c-4a1d-436f-9eeb-53a04db46c58",
    scryfall_id = "4adaf0bf-b26d-4166-8809-431283690de7",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Enfeeblement",
        mana_cost = mana!("{B}{B}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(-2, -2)
        ),
    ],
);
