//! Fishliver Oil — {1}{U} — Enchantment — Aura
//! Oracle: Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
//! Oracle: Enchanted creature has islandwalk. (It can't be blocked as long as defending player controls an Island.)
//! Set: 9ED #77 — Ninth Edition | Scryfall ID: c3c4a1f4-0a8e-4e70-a2a8-ceebbca63b6c | Oracle ID: 75457fe5-4ab6-42c4-98e5-8ed6e8bf122c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FISHLIVER_OIL,
    oracle_id = "75457fe5-4ab6-42c4-98e5-8ed6e8bf122c",
    scryfall_id = "c3c4a1f4-0a8e-4e70-a2a8-ceebbca63b6c",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fishliver Oil",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::ISLANDWALK)
        ),
    ],
);
