//! Illuminated Wings — {1}{U} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has flying.
//! Oracle: {2}, Sacrifice this Aura: Draw a card.
//! Set: UDS #34 — Urza's Destiny | Scryfall ID: 7f98e703-a0d3-497f-840a-aa026b02d47f | Oracle ID: 7a22389a-34e7-4726-a551-f6fbc225cefe
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ILLUMINATED_WINGS,
    oracle_id = "7a22389a-34e7-4726-a551-f6fbc225cefe",
    scryfall_id = "7f98e703-a0d3-497f-840a-aa026b02d47f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Illuminated Wings",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::FLYING)
        ),
        activated!(cost!("{2}", SacrificeSelf), &[Effect::draw(1)]),
    ],
);
