//! Inertia Bubble — {1}{U} — Enchantment — Aura
//! Oracle: Enchant artifact
//! Oracle: Enchanted artifact doesn't untap during its controller's untap step.
//! Set: MRD #37 — Mirrodin | Scryfall ID: 72b2d227-68b3-40e8-bef7-45ea43e17318 | Oracle ID: 864c7575-4589-416c-b143-310d5ef238c5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::INERTIA_BUBBLE,
    oracle_id = "864c7575-4589-416c-b143-310d5ef238c5",
    scryfall_id = "72b2d227-68b3-40e8-bef7-45ea43e17318",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Inertia Bubble",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::ARTIFACT)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
        ),
        static_ability!(Filter::AttachedToBySource, Modifier::DoesNotUntap),
    ],
);
