//! Phantasmal Terrain — {U}{U} — Enchantment — Aura
//! Oracle: Enchant land
//! Oracle: As this Aura enters, choose a basic land type.
//! Oracle: Enchanted land is the chosen type.
//! Set: ME4 #56 — Masters Edition IV | Scryfall ID: e9640cd5-bef8-486f-b903-46ff92efe3d3 | Oracle ID: 7dcbce46-2973-4a9f-93df-95ac41ce668a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PHANTASMAL_TERRAIN,
    oracle_id = "7dcbce46-2973-4a9f-93df-95ac41ce668a",
    scryfall_id = "e9640cd5-bef8-486f-b903-46ff92efe3d3",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Phantasmal Terrain",
        mana_cost = mana!("{U}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
        enter_modifiers = &[EnterModifier::ChooseBasicLandType],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::LAND)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::LAND)))
        ),
        static_ability!(Filter::AttachedToBySource, Modifier::SetLandTypeToChosen),
    ],
);
