//! Spectral Cloak — {U}{U} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has shroud as long as it's untapped. (It can't be the target of spells or abilities.)
//! Set: LEG #78 — Legends | Scryfall ID: 7524fd0d-a675-41d6-bc99-bd3ba336893b | Oracle ID: fadfa9f9-d096-4083-8630-1c18928133ff
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SPECTRAL_CLOAK,
    oracle_id = "fadfa9f9-d096-4083-8630-1c18928133ff",
    scryfall_id = "7524fd0d-a675-41d6-bc99-bd3ba336893b",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spectral Cloak",
        mana_cost = mana!("{U}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::AttachedToBySource,
                Filter::Untapped
            ]),
            Modifier::AddKeyword(KeywordSet::SHROUD)
        ),
    ],
);
