//! The Brute — {1}{R} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +1/+0.
//! Oracle: {R}{R}{R}: Regenerate enchanted creature.
//! Set: 5ED #272 — Fifth Edition | Scryfall ID: d3ded8fa-facf-4196-8964-56ebc6424be1 | Oracle ID: 99587b7a-cbd0-4ade-b517-50aaf0635fb1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::THE_BRUTE,
    oracle_id = "99587b7a-cbd0-4ade-b517-50aaf0635fb1",
    scryfall_id = "d3ded8fa-facf-4196-8964-56ebc6424be1",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "The Brute",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 0)
        ),
        activated!(
            cost!("{R}{R}{R}"),
            &[Effect::RegenerateAll {
                filter: &Filter::AttachedToBySource
            }]
        ),
    ],
);
