//! Wings of Aesthir — {W}{U} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +1/+0 and has flying and first strike.
//! Set: ME2 #199 — Masters Edition II | Scryfall ID: 00341664-d848-44d2-ba06-21a6ae8e6788 | Oracle ID: 06413d87-d119-4c04-93d5-5ced7ad4a858
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WINGS_OF_AESTHIR,
    oracle_id = "06413d87-d119-4c04-93d5-5ced7ad4a858",
    scryfall_id = "00341664-d848-44d2-ba06-21a6ae8e6788",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wings of Aesthir",
        mana_cost = mana!("{W}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 0)
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::FLYING.union(KeywordSet::FIRST_STRIKE))
        ),
    ],
);
