//! Dehydration — {3}{U} — Enchantment — Aura
//! Oracle: Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
//! Oracle: Enchanted creature doesn't untap during its controller's untap step.
//! Set: 10E #78 — Tenth Edition | Scryfall ID: 4414ad73-146e-47a6-926a-ec148194bb50 | Oracle ID: db27c686-e202-4b60-9a10-0a0fef25576c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DEHYDRATION,
    oracle_id = "db27c686-e202-4b60-9a10-0a0fef25576c",
    scryfall_id = "4414ad73-146e-47a6-926a-ec148194bb50",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dehydration",
        mana_cost = mana!("{3}{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::DoesNotUntap
        ),
    ],
);
