//! Improvised Armor — {3}{W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +2/+5.
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: DMR #10 — Dominaria Remastered | Scryfall ID: d3c205ba-cafb-4afc-83fe-09fff38130d7 | Oracle ID: aca7c0a7-b365-421e-aeb0-49d3a9873e4f
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::IMPROVISED_ARMOR,
    oracle_id = "aca7c0a7-b365-421e-aeb0-49d3a9873e4f",
    scryfall_id = "d3c205ba-cafb-4afc-83fe-09fff38130d7",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Improvised Armor",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        activated!(
            cost!("{3}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(2, 5)
        ),
    ],
);
