//! Serra's Embrace — {2}{W}{W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +2/+2 and has flying and vigilance. (Attacking doesn't cause it to tap.)
//! Set: DVD #21 — Duel Decks Anthology: Divine vs. Demonic | Scryfall ID: 2c45c4b3-f652-4b55-a316-55a864ac2342 | Oracle ID: 6d6ba936-4a15-4c40-aaa6-71605fb732d1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SERRA_S_EMBRACE,
    oracle_id = "6d6ba936-4a15-4c40-aaa6-71605fb732d1",
    scryfall_id = "2c45c4b3-f652-4b55-a316-55a864ac2342",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Serra's Embrace",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(2, 2)
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::FLYING.union(KeywordSet::VIGILANCE))
        ),
    ],
);
