//! Valgavoth's Lair — (no cost) — Enchantment Land
//! Oracle: Hexproof
//! Oracle: This land enters tapped. As it enters, choose a color.
//! Oracle: {T}: Add one mana of the chosen color.
//! Set: DSK #271 — Duskmourn: House of Horror | Scryfall ID: 65ff914e-3f3e-4b7a-b69d-73575b68fb8e | Oracle ID: 660d44a2-391a-416c-b46c-ddcc3739f527
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VALGAVOTH_S_LAIR,
    oracle_id = "660d44a2-391a-416c-b46c-ddcc3739f527",
    scryfall_id = "65ff914e-3f3e-4b7a-b69d-73575b68fb8e",
    keywords = KeywordSet::HEXPROOF,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Valgavoth's Lair",
        types = TypeSet::ENCHANTMENT.union(TypeSet::LAND),
        enter_modifiers = &[EnterModifier::ChooseColor, EnterModifier::Tapped],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen()]),],
);
