//! Arenson's Aura — {2}{W} — Enchantment
//! Oracle: {W}, Sacrifice an enchantment: Destroy target enchantment.
//! Oracle: {3}{U}{U}: Counter target enchantment spell.
//! Set: 5ED #6 — Fifth Edition | Scryfall ID: ba2bf14c-f04d-4380-b0d5-25028ddd999b | Oracle ID: 465843dc-57d0-46fd-ac47-238723034563
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static COST1: Filter = Filter::And(&[Filter::ENCHANTMENT, Filter::ControlledByYou]);

card!(
    index = index::ARENSON_S_AURA,
    oracle_id = "465843dc-57d0-46fd-ac47-238723034563",
    scryfall_id = "ba2bf14c-f04d-4380-b0d5-25028ddd999b",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Arenson's Aura",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        activated!(
            cost!("{W}", Sacrifice(&COST1)),
            &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
            target = Some(TargetSpec::Object(&Filter::ENCHANTMENT))
        ),
        activated!(
            cost!("{3}{U}{U}"),
            &[Effect::CounterTargetSpell],
            target = Some(TargetSpec::Spell(&Filter::ENCHANTMENT))
        ),
    ],
);
