//! Back to Basics — {2}{U} — Enchantment
//! Oracle: Nonbasic lands don't untap during their controllers' untap steps.
//! Set: UMA #46 — Ultimate Masters | Scryfall ID: 0600d6c2-0f72-4e79-a55d-1f06dffa48c2 | Oracle ID: 05c2dec2-d2f7-4036-b91f-4fccba10a8bb
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::BACK_TO_BASICS,
    oracle_id = "05c2dec2-d2f7-4036-b91f-4fccba10a8bb",
    scryfall_id = "0600d6c2-0f72-4e79-a55d-1f06dffa48c2",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Back to Basics",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[static_ability!(
        Filter::NONBASIC_LAND,
        Modifier::DoesNotUntap
    ),],
);
