//! Fires of Yavimaya — {1}{R}{G} — Enchantment
//! Oracle: Creatures you control have haste.
//! Oracle: Sacrifice this enchantment: Target creature gets +2/+2 until end of turn.
//! Set: PCA #92 — Planechase Anthology | Scryfall ID: 7294e30f-0356-4bcc-a264-4cd46d8f13a6 | Oracle ID: e23d6f3b-0e18-423b-943b-15db7837255b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::FIRES_OF_YAVIMAYA,
    oracle_id = "e23d6f3b-0e18-423b-943b-15db7837255b",
    scryfall_id = "7294e30f-0356-4bcc-a264-4cd46d8f13a6",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fires of Yavimaya",
        mana_cost = mana!("{1}{R}{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(
            Filter::YOUR_CREATURE,
            Modifier::AddKeyword(KeywordSet::HASTE)
        ),
        activated!(
            cost!(SacrificeSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(2),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
