//! Fortified Area — {1}{W}{W} — Enchantment
//! Oracle: Wall creatures you control get +1/+0 and have banding. (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)
//! Set: 4ED #26 — Fourth Edition | Scryfall ID: 8f89968f-0182-4639-96fd-0dc94b6ad926 | Oracle ID: cef37acf-ee97-48bf-a605-b17efcce5ce8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FORTIFIED_AREA,
    oracle_id = "cef37acf-ee97-48bf-a605-b17efcce5ce8",
    scryfall_id = "8f89968f-0182-4639-96fd-0dc94b6ad926",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fortified Area",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::ControlledByYou,
                Filter::HasSubtype(subtypes::creature::WALL)
            ]),
            Modifier::ModifyPT(1, 0)
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::ControlledByYou,
                Filter::HasSubtype(subtypes::creature::WALL)
            ]),
            Modifier::AddKeyword(KeywordSet::BANDING)
        ),
    ],
);
