//! Narcissism — {2}{G} — Enchantment
//! Oracle: {G}, Discard a card: Target creature gets +2/+2 until end of turn.
//! Oracle: {G}, Sacrifice this enchantment: Target creature gets +2/+2 until end of turn.
//! Set: TOR #134 — Torment | Scryfall ID: eea658dd-7567-4b93-88a4-08b4ffb3dad7 | Oracle ID: 59cd56d2-42f3-44de-b1b8-a5f9105dcaa8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::NARCISSISM,
    oracle_id = "59cd56d2-42f3-44de-b1b8-a5f9105dcaa8",
    scryfall_id = "eea658dd-7567-4b93-88a4-08b4ffb3dad7",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Narcissism",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        activated!(
            cost!("{G}", Discard(&Filter::Any)),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(2),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{G}", SacrificeSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(2),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
