//! Sacred Mesa — {2}{W} — Enchantment
//! Oracle: At the beginning of your upkeep, sacrifice this enchantment unless you sacrifice a Pegasus.
//! Oracle: {1}{W}: Create a 1/1 white Pegasus creature token with flying.
//! Set: C14 #86 — Commander 2014 | Scryfall ID: 377b2bc1-c710-439d-96d2-beef72ae80a7 | Oracle ID: 8776d14f-a5a2-4ef3-98d0-e1148e579e4d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::PEGASUS),
    Filter::ControlledByYou,
]);

card!(
    index = index::SACRED_MESA,
    oracle_id = "8776d14f-a5a2-4ef3-98d0-e1148e579e4d",
    scryfall_id = "377b2bc1-c710-439d-96d2-beef72ae80a7",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sacred Mesa",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::Sacrifice(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
        activated!(
            cost!("{1}{W}"),
            &[Effect::CreateToken {
                token: &generated_tokens::PEGASUS_1_1_WHITE_FLYING
            }]
        ),
    ],
);
