//! Spidersilk Armor — {2}{G} — Enchantment
//! Oracle: Creatures you control get +0/+1 and have reach. (They can block creatures with flying.)
//! Set: DDG #32 — Duel Decks: Knights vs. Dragons | Scryfall ID: e55202a1-c246-4b5b-94d6-43c86a69d61a | Oracle ID: ad73e5eb-197c-45a3-9d20-a406ba126c79
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPIDERSILK_ARMOR,
    oracle_id = "ad73e5eb-197c-45a3-9d20-a406ba126c79",
    scryfall_id = "e55202a1-c246-4b5b-94d6-43c86a69d61a",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spidersilk Armor",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(Filter::YOUR_CREATURE, Modifier::ModifyPT(0, 1)),
        static_ability!(
            Filter::YOUR_CREATURE,
            Modifier::AddKeyword(KeywordSet::REACH)
        ),
    ],
);
