//! Still Life — {1}{G}{G} — Enchantment
//! Oracle: {G}{G}: This enchantment becomes a 4/3 Centaur creature in addition to its other types until end of turn.
//! Set: ODY #275 — Odyssey | Scryfall ID: 12be33d7-f25e-4dbf-9706-74403103b127 | Oracle ID: 55159adc-36f0-4088-8930-5d9b45f76365
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STILL_LIFE,
    oracle_id = "55159adc-36f0-4088-8930-5d9b45f76365",
    scryfall_id = "12be33d7-f25e-4dbf-9706-74403103b127",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Still Life",
        mana_cost = mana!("{1}{G}{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{G}{G}"),
        &[
            Effect::continuous(
                &Filter::This,
                Modifier::AddType(TypeSet::CREATURE),
                Duration::UntilEndOfTurn
            ),
            Effect::continuous(
                &Filter::This,
                Modifier::AddSubtype(subtypes::creature::CENTAUR),
                Duration::UntilEndOfTurn
            ),
            Effect::continuous(
                &Filter::This,
                Modifier::SetPT(4, 3),
                Duration::UntilEndOfTurn
            )
        ]
    ),],
);
