//! Teferi's Care — {2}{W} — Enchantment
//! Oracle: {W}, Sacrifice an enchantment: Destroy target enchantment.
//! Oracle: {3}{U}{U}: Counter target enchantment spell.
//! Set: INV #43 — Invasion | Scryfall ID: 031b1cc1-4468-4bc5-85c0-c22dce131225 | Oracle ID: 6c5c7b26-9cd6-4f29-bbb2-a0745153ee5d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static COST1: Filter = Filter::And(&[Filter::ENCHANTMENT, Filter::ControlledByYou]);

card!(
    index = index::TEFERI_S_CARE,
    oracle_id = "6c5c7b26-9cd6-4f29-bbb2-a0745153ee5d",
    scryfall_id = "031b1cc1-4468-4bc5-85c0-c22dce131225",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Teferi's Care",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        activated!(
            cost!("{W}", Sacrifice(&COST1)),
            &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
            target = Some(TargetSpec::Object(&Filter::ENCHANTMENT))
        ),
        activated!(
            cost!("{3}{U}{U}"),
            &[Effect::CounterTargetSpell],
            target = Some(TargetSpec::Spell(&Filter::ENCHANTMENT))
        ),
    ],
);
