//! Think Tank — {2}{U} — Enchantment
//! Oracle: At the beginning of your upkeep, surveil 1. (Look at the top card of your library. You may put that card into your graveyard.)
//! Set: ODY #104 — Odyssey | Scryfall ID: 8c1c9d34-ea4c-4e89-a7ed-06c4469c1aca | Oracle ID: c13b9ee5-cf4f-47bc-a6e8-1dbf98df3d9c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THINK_TANK,
    oracle_id = "c13b9ee5-cf4f-47bc-a6e8-1dbf98df3d9c",
    scryfall_id = "8c1c9d34-ea4c-4e89-a7ed-06c4469c1aca",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Think Tank",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::surveil(1)]
    ),],
);
