//! Crookshank Kobolds — {0} — Creature — Kobold
//! Set: ME1 #90 — Masters Edition | Scryfall ID: f51d9dde-536b-4314-8de1-2c05a9bf3dbc | Oracle ID: 61023b48-0433-4993-9534-308c08cef07e
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CROOKSHANK_KOBOLDS,
    oracle_id = "61023b48-0433-4993-9534-308c08cef07e",
    scryfall_id = "f51d9dde-536b-4314-8de1-2c05a9bf3dbc",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crookshank Kobolds",
        mana_cost = mana!("{0}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KOBOLD],
        power = Some(0),
        toughness = Some(1),
        color_indicator = ColorSet::from_slice(&[Color::Red]),
    ),],
);
