//! Fireshrieker — {3} — Artifact — Equipment
//! Oracle: Equipped creature has double strike. (It deals both first-strike and regular combat damage.)
//! Oracle: Equip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: FDN #674 — Foundations | Scryfall ID: 484fbce6-71bd-40eb-a71b-86958a094708 | Oracle ID: a02e1ca7-23c5-41e3-a744-72fc9e9dd8ba
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FIRESHRIEKER,
    oracle_id = "a02e1ca7-23c5-41e3-a744-72fc9e9dd8ba",
    scryfall_id = "484fbce6-71bd-40eb-a71b-86958a094708",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fireshrieker",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{2}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::DOUBLE_STRIKE)
        ),
    ],
);
