//! Vulshok Battlegear — {3} — Artifact — Equipment
//! Oracle: Equipped creature gets +3/+3.
//! Oracle: Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: CMM #418 — Commander Masters | Scryfall ID: 8363acf3-eff9-4f57-8b8a-683256d279e0 | Oracle ID: 708df587-3b13-42cb-8341-f476ab4cbe45
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VULSHOK_BATTLEGEAR,
    oracle_id = "708df587-3b13-42cb-8341-f476ab4cbe45",
    scryfall_id = "8363acf3-eff9-4f57-8b8a-683256d279e0",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vulshok Battlegear",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{3}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(3, 3)
        ),
    ],
);
