//! Copper Myr — {2} — Artifact Creature — Myr
//! Oracle: {T}: Add {G}.
//! Set: SOM #146 — Scars of Mirrodin | Scryfall ID: 323efe27-da58-4207-9c0c-dba5031bfa04 | Oracle ID: 8b52f30c-5e38-4333-88ab-901b37105b36
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::COPPER_MYR,
    oracle_id = "8b52f30c-5e38-4333-88ab-901b37105b36",
    scryfall_id = "323efe27-da58-4207-9c0c-dba5031bfa04",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Copper Myr",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::MYR],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),],
);
