//! Coretapper — {2} — Artifact Creature — Myr
//! Oracle: {T}: Put a charge counter on target artifact.
//! Oracle: Sacrifice this creature: Put two charge counters on target artifact.
//! Set: EOC #132 — Edge of Eternities Commander | Scryfall ID: 00d9dd37-aad3-46bd-ac9b-140974c8dcaa | Oracle ID: 66e37011-f3d2-41ed-8e09-7bba9464e8c3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CORETAPPER,
    oracle_id = "66e37011-f3d2-41ed-8e09-7bba9464e8c3",
    scryfall_id = "00d9dd37-aad3-46bd-ac9b-140974c8dcaa",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Coretapper",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::MYR],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: CounterKind::Charge,
                amount: Amount::Fixed(1)
            }],
            target = Some(TargetSpec::Object(&Filter::ARTIFACT))
        ),
        activated!(
            cost!(SacrificeSelf),
            &[Effect::AddCounter {
                kind: CounterKind::Charge,
                amount: Amount::Fixed(2)
            }],
            target = Some(TargetSpec::Object(&Filter::ARTIFACT))
        ),
    ],
);
