//! Leaden Myr — {2} — Artifact Creature — Myr
//! Oracle: {T}: Add {B}.
//! Set: SOM #170 — Scars of Mirrodin | Scryfall ID: 3a709559-fec3-44f4-a2bf-3396989b9189 | Oracle ID: f62cabf0-df0d-4c4f-a93a-9340967d1775
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LEADEN_MYR,
    oracle_id = "f62cabf0-df0d-4c4f-a93a-9340967d1775",
    scryfall_id = "3a709559-fec3-44f4-a2bf-3396989b9189",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Leaden Myr",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::MYR],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),],
);
