//! Silver Myr — {2} — Artifact Creature — Myr
//! Oracle: {T}: Add {U}.
//! Set: NEC #158 — Neon Dynasty Commander | Scryfall ID: 3ebcc053-21c6-4708-b9fc-532e3749962f | Oracle ID: 66e8f7f8-3a6d-46ba-837c-b9713ddf7f40
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SILVER_MYR,
    oracle_id = "66e8f7f8-3a6d-46ba-837c-b9713ddf7f40",
    scryfall_id = "3ebcc053-21c6-4708-b9fc-532e3749962f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Silver Myr",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::MYR],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),],
);
