//! A registered player.

use sea_orm::entity::prelude::*;

/// One account. The e-mail is the login; the display name is what other
/// players see.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "account")]
pub struct Model {
    /// `UUIDv7`, generated by the gateway. See the crate doc on why the key
    /// is time-ordered.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// Login e-mail, stored as the player typed it.
    ///
    /// Uniqueness is enforced on `lower(email)` by an expression index
    /// rather than by lowercasing the column, because the address a
    /// confirmation mail is sent to should be the one its owner recognises.
    pub email: String,
    /// Display name, unique case-insensitively for the same reason and by
    /// the same means.
    pub display_name: String,
    /// Argon2id PHC hash. Never a password.
    pub password_hash: String,
    /// When the account was created.
    pub created_at: TimeDateTimeWithTimeZone,
    /// When the address was confirmed, if it ever was.
    ///
    /// `None` means two different things and the mailer decides which: on a
    /// gateway that sends mail it means the account cannot sign in yet; on
    /// one with no SMTP configured it means nothing at all, because nobody
    /// was ever asked. That is why it is a nullable timestamp and not a
    /// boolean — "never asked" and "asked and unanswered" are the same
    /// state, and only the configuration tells them apart.
    pub confirmed_at: Option<TimeDateTimeWithTimeZone>,
    /// The language the account registered in, for the mail it is sent.
    pub lang: String,
}

/// Everything that belongs to an account and dies with it.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// The player's decks.
    #[sea_orm(has_many = "super::deck::Entity")]
    Deck,
    /// Live sessions.
    #[sea_orm(has_many = "super::session_token::Entity")]
    SessionToken,
    /// Unspent confirmation links.
    #[sea_orm(has_many = "super::confirmation::Entity")]
    Confirmation,
    /// Remembered answers to optional abilities.
    #[sea_orm(has_many = "super::standing_answer::Entity")]
    StandingAnswer,
    /// The one preferences document.
    #[sea_orm(has_one = "super::client_settings::Entity")]
    ClientSettings,
}

impl Related<super::deck::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deck.def()
    }
}

impl Related<super::session_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionToken.def()
    }
}

impl Related<super::confirmation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Confirmation.def()
    }
}

impl Related<super::standing_answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StandingAnswer.def()
    }
}

impl Related<super::client_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
