//! Adun Oakenshield — {B}{R}{G} — Legendary Creature — Human Knight
//! Oracle: {B}{R}{G}, {T}: Return target creature card from your graveyard to your hand.
//! Set: ME1 #141 — Masters Edition | Scryfall ID: 184da30e-0db4-450c-8856-5c23088c35be | Oracle ID: aefd49a4-ecec-42cb-b882-e5db7f81eff8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ADUN_OAKENSHIELD,
    oracle_id = "aefd49a4-ecec-42cb-b882-e5db7f81eff8",
    scryfall_id = "184da30e-0db4-450c-8856-5c23088c35be",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Adun Oakenshield",
        mana_cost = mana!("{B}{R}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::KNIGHT],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{B}{R}{G}", TapSelf),
        &[Effect::GraveyardToHand {
            target: TargetSpec::CardInGraveyard(&Filter::CREATURE, PlayerRel::You)
        }],
        target = Some(TargetSpec::CardInGraveyard(
            &Filter::CREATURE,
            PlayerRel::You
        ))
    ),],
);
