//! Ambassador Laquatus — {1}{U}{U} — Legendary Creature — Merfolk Wizard
//! Oracle: {3}: Target player mills three cards.
//! Set: 10E #65 — Tenth Edition | Scryfall ID: b261067f-b5de-41cc-ba9e-6ef4c061e170 | Oracle ID: 2df8f253-1d3c-4b1f-8549-93fb90623474
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AMBASSADOR_LAQUATUS,
    oracle_id = "2df8f253-1d3c-4b1f-8549-93fb90623474",
    scryfall_id = "b261067f-b5de-41cc-ba9e-6ef4c061e170",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ambassador Laquatus",
        mana_cost = mana!("{1}{U}{U}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::MERFOLK, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{3}"),
        &[Effect::Mill {
            amount: Amount::Fixed(3),
            target: PlayerRel::Chosen
        }],
        target = Some(TargetSpec::AnyPlayer)
    ),],
);
