//! Argivian Archaeologist — {1}{W}{W} — Creature — Human Artificer
//! Oracle: {W}{W}, {T}: Return target artifact card from your graveyard to your hand.
//! Set: ME1 #3 — Masters Edition | Scryfall ID: 0e765567-4f45-4571-aa20-0d127fc522e0 | Oracle ID: 4b889ec0-6130-4e31-bb02-03fdabd28bee
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ARGIVIAN_ARCHAEOLOGIST,
    oracle_id = "4b889ec0-6130-4e31-bb02-03fdabd28bee",
    scryfall_id = "0e765567-4f45-4571-aa20-0d127fc522e0",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Argivian Archaeologist",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ARTIFICER],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{W}{W}", TapSelf),
        &[Effect::GraveyardToHand {
            target: TargetSpec::CardInGraveyard(&Filter::ARTIFACT, PlayerRel::You)
        }],
        target = Some(TargetSpec::CardInGraveyard(
            &Filter::ARTIFACT,
            PlayerRel::You
        ))
    ),],
);
