//! Arms Dealer — {2}{R} — Creature — Goblin Rogue
//! Oracle: {1}{R}, Sacrifice a Goblin: This creature deals 4 damage to target creature.
//! Set: M13 #120 — Magic 2013 | Scryfall ID: 910d3c33-8cda-487b-8b44-87a9d06d6749 | Oracle ID: 8ebc4198-7317-4ffb-b8b8-14733c2077ff
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::GOBLIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::ARMS_DEALER,
    oracle_id = "8ebc4198-7317-4ffb-b8b8-14733c2077ff",
    scryfall_id = "910d3c33-8cda-487b-8b44-87a9d06d6749",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Arms Dealer",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::ROGUE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{1}{R}", Sacrifice(&COST1)),
        &[Effect::DealDamage {
            amount: Amount::Fixed(4),
            target: TargetSpec::Object(&Filter::CREATURE)
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
