//! Azimaet Drake — {2}{U} — Creature — Drake
//! Oracle: Flying
//! Oracle: {U}: This creature gets +1/+0 until end of turn. Activate only once each turn.
//! Set: MIR #53 — Mirage | Scryfall ID: 854ba4e0-f6f3-4b6c-b6cb-ab2b93d64601 | Oracle ID: a82d9c9b-ec17-4f51-a6bf-5984ca4433e5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AZIMAET_DRAKE,
    oracle_id = "a82d9c9b-ec17-4f51-a6bf-5984ca4433e5",
    scryfall_id = "854ba4e0-f6f3-4b6c-b6cb-ab2b93d64601",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Azimaet Drake",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRAKE],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{U}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
