//! Balloon Peddler — {2}{U} — Creature — Human Spellshaper
//! Oracle: {U}, {T}, Discard a card: Target creature gains flying until end of turn.
//! Set: MMQ #59 — Mercadian Masques | Scryfall ID: c34963e6-850e-4ce4-b04f-5e623ce5b73f | Oracle ID: 10f182a7-ffa3-4128-8b2e-e05b97f92e00
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BALLOON_PEDDLER,
    oracle_id = "10f182a7-ffa3-4128-8b2e-e05b97f92e00",
    scryfall_id = "c34963e6-850e-4ce4-b04f-5e623ce5b73f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Balloon Peddler",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SPELLSHAPER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{U}", TapSelf, Discard(&Filter::Any)),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
