//! Balthor the Stout — {1}{R}{R} — Legendary Creature — Dwarf Barbarian
//! Oracle: Other Barbarian creatures get +1/+1.
//! Oracle: {R}: Another target Barbarian creature gets +1/+0 until end of turn.
//! Set: TOR #91 — Torment | Scryfall ID: e81ecdc5-d2c7-4292-9b59-fd6bf3ba29d5 | Oracle ID: 23669721-fe9e-49d7-9504-ae6164de723a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSubtype(subtypes::creature::BARBARIAN),
    Filter::Another,
]);

card!(
    index = index::BALTHOR_THE_STOUT,
    oracle_id = "23669721-fe9e-49d7-9504-ae6164de723a",
    scryfall_id = "e81ecdc5-d2c7-4292-9b59-fd6bf3ba29d5",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Balthor the Stout",
        mana_cost = mana!("{1}{R}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::DWARF, subtypes::creature::BARBARIAN],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::BARBARIAN),
                Filter::Another
            ]),
            Modifier::ModifyPT(1, 1)
        ),
        activated!(
            cost!("{R}"),
            &[Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&TARGET1))
        ),
    ],
);
