//! Barrin, Master Wizard — {1}{U}{U} — Legendary Creature — Human Wizard
//! Oracle: {2}, Sacrifice a permanent: Return target creature to its owner's hand.
//! Set: USG #63 — Urza's Saga | Scryfall ID: ec79e35f-9e78-462d-8b71-4f044e2eff90 | Oracle ID: 8c6d6684-1943-4af3-98da-951604193911
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BARRIN_MASTER_WIZARD,
    oracle_id = "8c6d6684-1943-4af3-98da-951604193911",
    scryfall_id = "ec79e35f-9e78-462d-8b71-4f044e2eff90",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Barrin, Master Wizard",
        mana_cost = mana!("{1}{U}{U}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{2}", Sacrifice(&Filter::ControlledByYou)),
        &[Effect::bounce(TargetSpec::Object(&Filter::CREATURE))],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
