//! Cat Warriors — {1}{G}{G} — Creature — Cat Warrior
//! Oracle: Forestwalk (This creature can't be blocked as long as defending player controls a Forest.)
//! Set: 6ED #219 — Classic Sixth Edition | Scryfall ID: 90823485-83cd-4260-b860-7f05d8588905 | Oracle ID: cee3d8e5-f26f-4f47-8a7b-9ac07ebf9025
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CAT_WARRIORS,
    oracle_id = "cee3d8e5-f26f-4f47-8a7b-9ac07ebf9025",
    scryfall_id = "90823485-83cd-4260-b860-7f05d8588905",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FORESTWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Cat Warriors",
        mana_cost = mana!("{1}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::CAT, subtypes::creature::WARRIOR],
        power = Some(2),
        toughness = Some(2),
    ),],
);
