//! D'Avenant Archer — {2}{W} — Creature — Human Soldier Archer
//! Oracle: {T}: This creature deals 1 damage to target attacking or blocking creature.
//! Set: ME3 #6 — Masters Edition III | Scryfall ID: dfc44b22-c46c-4b7e-91ff-3eff416bb357 | Oracle ID: 81bc4a5e-812f-4809-b6df-271c3c22f4fc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::And(&[Filter::CREATURE, Filter::Attacking]),
    Filter::And(&[Filter::CREATURE, Filter::Blocking]),
]);

card!(
    index = index::D_AVENANT_ARCHER,
    oracle_id = "81bc4a5e-812f-4809-b6df-271c3c22f4fc",
    scryfall_id = "dfc44b22-c46c-4b7e-91ff-3eff416bb357",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "D'Avenant Archer",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::SOLDIER,
            subtypes::creature::ARCHER
        ],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Object(&TARGET1)
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
