//! Devouring Deep — {2}{U} — Creature — Fish
//! Oracle: Islandwalk (This creature can't be blocked as long as defending player controls an Island.)
//! Set: LEG #50 — Legends | Scryfall ID: 0855a5a8-8c40-4396-9ad1-8fa0fc6a0c59 | Oracle ID: e0f18302-5ccf-47d2-a8a1-bb7aeaca9a53
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DEVOURING_DEEP,
    oracle_id = "e0f18302-5ccf-47d2-a8a1-bb7aeaca9a53",
    scryfall_id = "0855a5a8-8c40-4396-9ad1-8fa0fc6a0c59",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::ISLANDWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Devouring Deep",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FISH],
        power = Some(1),
        toughness = Some(2),
    ),],
);
