//! Diving Griffin — {1}{W}{W} — Creature — Griffin
//! Oracle: Flying, vigilance
//! Set: 8ED #17 — Eighth Edition | Scryfall ID: bfeb0854-87e7-4236-9791-8fe601704200 | Oracle ID: 8785f9b4-eea2-4b45-9ae4-194b9a715702
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DIVING_GRIFFIN,
    oracle_id = "8785f9b4-eea2-4b45-9ae4-194b9a715702",
    scryfall_id = "bfeb0854-87e7-4236-9791-8fe601704200",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::VIGILANCE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Diving Griffin",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GRIFFIN],
        power = Some(2),
        toughness = Some(2),
    ),],
);
