//! Drake Hatchling — {2}{U} — Creature — Drake
//! Oracle: Flying
//! Oracle: {U}: This creature gets +1/+0 until end of turn. Activate only once each turn.
//! Set: MMQ #76 — Mercadian Masques | Scryfall ID: 64ee32f9-6120-4f15-a692-89a4cd8167c6 | Oracle ID: bd55bcc4-f0c5-4c09-8b3b-2e25e9fbd9ee
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DRAKE_HATCHLING,
    oracle_id = "bd55bcc4-f0c5-4c09-8b3b-2e25e9fbd9ee",
    scryfall_id = "64ee32f9-6120-4f15-a692-89a4cd8167c6",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Drake Hatchling",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRAKE],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{U}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
