//! Fault Riders — {2}{R} — Creature — Human Soldier
//! Oracle: Sacrifice a land: This creature gets +2/+0 and gains first strike until end of turn. Activate only once each turn.
//! Set: PCY #88 — Prophecy | Scryfall ID: 1c9d3579-3fc1-434e-8f26-d5dbd6344429 | Oracle ID: df516046-7f83-4d64-aa0d-d687631d919a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FAULT_RIDERS,
    oracle_id = "df516046-7f83-4d64-aa0d-d687631d919a",
    scryfall_id = "1c9d3579-3fc1-434e-8f26-d5dbd6344429",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fault Riders",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&Filter::YOUR_LAND)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FIRST_STRIKE,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
