//! Fire Drake — {1}{R}{R} — Creature — Drake
//! Oracle: Flying
//! Oracle: {R}: This creature gets +1/+0 until end of turn. Activate only once each turn.
//! Set: ME3 #98 — Masters Edition III | Scryfall ID: 2afdb5e8-31ba-4013-93c9-36e9f755f238 | Oracle ID: fd3bcc9b-7d84-478e-aef5-2e44610107c7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FIRE_DRAKE,
    oracle_id = "fd3bcc9b-7d84-478e-aef5-2e44610107c7",
    scryfall_id = "2afdb5e8-31ba-4013-93c9-36e9f755f238",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fire Drake",
        mana_cost = mana!("{1}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRAKE],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{R}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
