//! Flowstone Wall — {2}{R} — Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {R}: This creature gets +1/-1 until end of turn.
//! Set: NEM #86 — Nemesis | Scryfall ID: 89844c2f-f0a4-41c6-ad8c-d559fcaec85c | Oracle ID: 5fa86b45-1d5b-42df-8811-6a10903f3039
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FLOWSTONE_WALL,
    oracle_id = "5fa86b45-1d5b-42df-8811-6a10903f3039",
    scryfall_id = "89844c2f-f0a4-41c6-ad8c-d559fcaec85c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Flowstone Wall",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(6),
    ),],
    abilities = &[activated!(
        cost!("{R}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::NegXFixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
