//! Foratog — {2}{G} — Creature — Atog
//! Oracle: {G}, Sacrifice a Forest: This creature gets +2/+2 until end of turn.
//! Set: 8ED #249 — Eighth Edition | Scryfall ID: 5d621fad-3a50-4910-a302-23ae9e77ebde | Oracle ID: 77f257b9-2047-40a3-85c2-00ad17deeb08
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::FOREST),
    Filter::ControlledByYou,
]);

card!(
    index = index::FORATOG,
    oracle_id = "77f257b9-2047-40a3-85c2-00ad17deeb08",
    scryfall_id = "5d621fad-3a50-4910-a302-23ae9e77ebde",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Foratog",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ATOG],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{G}", Sacrifice(&COST1)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
