//! Goblin Medics — {2}{R} — Creature — Goblin Shaman
//! Oracle: Whenever this creature becomes tapped, it deals 1 damage to any target.
//! Set: MOC #283 — March of the Machine Commander | Scryfall ID: deda9adf-43db-481b-840d-518a12873782 | Oracle ID: 457bee4c-2332-440c-9336-36f6a69614f9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GOBLIN_MEDICS,
    oracle_id = "457bee4c-2332-440c-9336-36f6a69614f9",
    scryfall_id = "deda9adf-43db-481b-840d-518a12873782",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Goblin Medics",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::SHAMAN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::BecomesTapped(&Filter::This),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        targets = Some(TargetReq::one(TargetSpec::AnyTarget))
    ),],
);
