//! Goblin Sky Raider — {2}{R} — Creature — Goblin Warrior
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Set: 10E #210 — Tenth Edition | Scryfall ID: ebbd596b-56c2-475c-93e4-c72f9f29281b | Oracle ID: 9e0ebf3b-9295-43a9-9b5c-4ffac6a6b630
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GOBLIN_SKY_RAIDER,
    oracle_id = "9e0ebf3b-9295-43a9-9b5c-4ffac6a6b630",
    scryfall_id = "ebbd596b-56c2-475c-93e4-c72f9f29281b",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Goblin Sky Raider",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::WARRIOR],
        power = Some(1),
        toughness = Some(2),
    ),],
);
