//! Hornet Cobra — {1}{G}{G} — Creature — Snake
//! Oracle: First strike
//! Set: LEG #190 — Legends | Scryfall ID: 27180bad-9bbc-462b-8832-626dc403a3fd | Oracle ID: 4958baf3-2f5a-4087-bc14-ffee9887db1d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::HORNET_COBRA,
    oracle_id = "4958baf3-2f5a-4087-bc14-ffee9887db1d",
    scryfall_id = "27180bad-9bbc-462b-8832-626dc403a3fd",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Hornet Cobra",
        mana_cost = mana!("{1}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SNAKE],
        power = Some(2),
        toughness = Some(1),
    ),],
);
