//! Junún Efreet — {1}{B}{B} — Creature — Efreet
//! Oracle: Flying
//! Oracle: At the beginning of your upkeep, sacrifice this creature unless you pay {B}{B}.
//! Set: ME4 #88 — Masters Edition IV | Scryfall ID: 5f6529eb-79ff-4ddc-9fae-38326324f7e6 | Oracle ID: afda663e-c5f7-4182-86f7-d95d71793717
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::JUNUN_EFREET,
    oracle_id = "afda663e-c5f7-4182-86f7-d95d71793717",
    scryfall_id = "5f6529eb-79ff-4ddc-9fae-38326324f7e6",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Junún Efreet",
        mana_cost = mana!("{1}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::EFREET],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::PlayerMayPayManaOr {
            player: PlayerRel::You,
            cost: mana!("{B}{B}"),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
