//! Kami of the Hunt — {2}{G} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, this creature gets +1/+1 until end of turn.
//! Set: CHK #219 — Champions of Kamigawa | Scryfall ID: 5ace3c4e-3287-4975-b4d0-91f009c0cf5b | Oracle ID: 96e68c7a-f187-4aa6-998c-238e7c833809
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::KAMI_OF_THE_HUNT,
    oracle_id = "96e68c7a-f187-4aa6-998c-238e7c833809",
    scryfall_id = "5ace3c4e-3287-4975-b4d0-91f009c0cf5b",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kami of the Hunt",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
