//! Kavu Glider — {2}{R} — Creature — Kavu
//! Oracle: {W}: This creature gets +0/+1 until end of turn.
//! Oracle: {U}: This creature gains flying until end of turn.
//! Set: APC #64 — Apocalypse | Scryfall ID: 158aa5a8-2769-4a8a-b457-001abc862b35 | Oracle ID: 425050a7-41d2-4850-bb45-3a83275d3c50
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KAVU_GLIDER,
    oracle_id = "425050a7-41d2-4850-bb45-3a83275d3c50",
    scryfall_id = "158aa5a8-2769-4a8a-b457-001abc862b35",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kavu Glider",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KAVU],
        power = Some(2),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{W}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{U}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FLYING,
                duration: Duration::UntilEndOfTurn
            }]
        ),
    ],
);
