//! Keepers of the Faith — {1}{W}{W} — Creature — Human Cleric
//! Set: CHR #9 — Chronicles | Scryfall ID: a3d1ad50-c60c-46a9-b2dc-5cd2680d7263 | Oracle ID: 6ddc1256-a166-464f-8136-bd111cba6327
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KEEPERS_OF_THE_FAITH,
    oracle_id = "6ddc1256-a166-464f-8136-bd111cba6327",
    scryfall_id = "a3d1ad50-c60c-46a9-b2dc-5cd2680d7263",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Keepers of the Faith",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::CLERIC],
        power = Some(2),
        toughness = Some(3),
    ),],
);
