//! Khabál Ghoul — {2}{B} — Creature — Zombie
//! Oracle: At the beginning of each end step, put a +1/+1 counter on this creature for each creature that died this turn.
//! Set: ME1 #75 — Masters Edition | Scryfall ID: 98f443cb-55bb-4e83-826a-98261287bfd3 | Oracle ID: cb558dda-0c05-426d-aedc-bc07cc54db76
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KHABAL_GHOUL,
    oracle_id = "cb558dda-0c05-426d-aedc-bc07cc54db76",
    scryfall_id = "98f443cb-55bb-4e83-826a-98261287bfd3",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Khabál Ghoul",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ZOMBIE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::End,
            whose: PlayerRel::EachPlayer
        },
        &[Effect::AddCounter {
            kind: CounterKind::P1P1,
            amount: Amount::CreaturesDiedThisTurn
        }]
    ),],
);
