//! Krark-Clan Grunt — {2}{R} — Creature — Goblin Warrior
//! Oracle: Sacrifice an artifact: This creature gets +1/+0 and gains first strike until end of turn.
//! Set: MRD #97 — Mirrodin | Scryfall ID: ffd9e422-206e-4c25-9964-ed6592c16e12 | Oracle ID: e7be5ab3-a11f-4786-9b0b-1daa94f59440
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KRARK_CLAN_GRUNT,
    oracle_id = "e7be5ab3-a11f-4786-9b0b-1daa94f59440",
    scryfall_id = "ffd9e422-206e-4c25-9964-ed6592c16e12",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Krark-Clan Grunt",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::WARRIOR],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&Filter::YOUR_ARTIFACT)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FIRST_STRIKE,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
