//! Land Leeches — {1}{G}{G} — Creature — Leech
//! Oracle: First strike
//! Set: 4ED #255 — Fourth Edition | Scryfall ID: 71f1d97c-5bfa-4791-9004-5f2464908c30 | Oracle ID: 228f0afa-146b-4564-a380-71595cdf1ef4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LAND_LEECHES,
    oracle_id = "228f0afa-146b-4564-a380-71595cdf1ef4",
    scryfall_id = "71f1d97c-5bfa-4791-9004-5f2464908c30",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Land Leeches",
        mana_cost = mana!("{1}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::LEECH],
        power = Some(2),
        toughness = Some(2),
    ),],
);
