//! Lieutenant Kirtar — {1}{W}{W} — Legendary Creature — Bird Soldier
//! Oracle: Flying
//! Oracle: {1}{W}, Sacrifice Lieutenant Kirtar: Exile target attacking creature.
//! Set: DMR #12 — Dominaria Remastered | Scryfall ID: 475ba0c3-237e-4349-85e9-c31b016f609b | Oracle ID: ad39e859-e4a6-49cc-b738-4578a5250538
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LIEUTENANT_KIRTAR,
    oracle_id = "ad39e859-e4a6-49cc-b738-4578a5250538",
    scryfall_id = "475ba0c3-237e-4349-85e9-c31b016f609b",
    color_identity = ColorSet::from_slice(&[Color::White]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lieutenant Kirtar",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::BIRD, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{1}{W}", SacrificeSelf),
        &[Effect::exile(TargetSpec::Object(
            &Filter::ATTACKING_CREATURE
        ))],
        target = Some(TargetSpec::Object(&Filter::ATTACKING_CREATURE))
    ),],
);
