//! Lost Soul — {1}{B}{B} — Creature — Spirit Minion
//! Oracle: Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)
//! Set: 6ED #142 — Classic Sixth Edition | Scryfall ID: 401896ac-6234-468a-a9af-cf11c7a11cd0 | Oracle ID: 1c68e877-ee47-42bf-a867-3f7f479eae1c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LOST_SOUL,
    oracle_id = "1c68e877-ee47-42bf-a867-3f7f479eae1c",
    scryfall_id = "401896ac-6234-468a-a9af-cf11c7a11cd0",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::SWAMPWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lost Soul",
        mana_cost = mana!("{1}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT, subtypes::creature::MINION],
        power = Some(2),
        toughness = Some(1),
    ),],
);
