//! Marker Beetles — {1}{G}{G} — Creature — Insect
//! Oracle: When this creature dies, target creature gets +1/+1 until end of turn.
//! Oracle: {2}, Sacrifice this creature: Draw a card.
//! Set: UDS #112 — Urza's Destiny | Scryfall ID: 5cbd3c78-197a-40b9-94d1-bbb1ec1e64b1 | Oracle ID: 4b1614fd-2810-4d4d-a0d6-934f27adbe65
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MARKER_BEETLES,
    oracle_id = "4b1614fd-2810-4d4d-a0d6-934f27adbe65",
    scryfall_id = "5cbd3c78-197a-40b9-94d1-bbb1ec1e64b1",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Marker Beetles",
        mana_cost = mana!("{1}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::INSECT],
        power = Some(2),
        toughness = Some(3),
    ),],
    abilities = &[
        activated!(cost!("{2}", SacrificeSelf), &[Effect::draw(1)]),
        triggered!(
            Trigger::Dies(&Filter::This),
            &[Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
    ],
);
