//! Merchant of Secrets — {2}{U} — Creature — Human Wizard
//! Oracle: When this creature enters, draw a card.
//! Set: C17 #87 — Commander 2017 | Scryfall ID: 10227a24-d4f7-4dfa-a54d-eaf183fd7e79 | Oracle ID: f6aebd42-0150-4741-84c2-4c85893640e9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MERCHANT_OF_SECRETS,
    oracle_id = "f6aebd42-0150-4741-84c2-4c85893640e9",
    scryfall_id = "10227a24-d4f7-4dfa-a54d-eaf183fd7e79",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Merchant of Secrets",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(Trigger::ETB, &[Effect::draw(1)]),],
);
