//! Moonwing Moth — {1}{W}{W} — Creature — Insect
//! Oracle: Flying
//! Oracle: {W}: This creature gets +0/+1 until end of turn.
//! Set: SOK #20 — Saviors of Kamigawa | Scryfall ID: f646ed53-c323-4f84-b8c9-39e31da1aca8 | Oracle ID: 6501b3c7-fd21-4668-b647-db12f0cc23f7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MOONWING_MOTH,
    oracle_id = "6501b3c7-fd21-4668-b647-db12f0cc23f7",
    scryfall_id = "f646ed53-c323-4f84-b8c9-39e31da1aca8",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Moonwing Moth",
        mana_cost = mana!("{1}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::INSECT],
        power = Some(2),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{W}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
