//! Moriok Rigger — {2}{B} — Creature — Human Rogue Rigger
//! Oracle: Whenever an artifact is put into a graveyard from the battlefield, you may put a +1/+1 counter on this creature.
//! Set: 5DN #54 — Fifth Dawn | Scryfall ID: 47ffdeb8-52d2-4059-b9c6-0ad71b96516a | Oracle ID: 9364b5bc-3e78-4b9d-9993-0081bbe2eef6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MORIOK_RIGGER,
    oracle_id = "9364b5bc-3e78-4b9d-9993-0081bbe2eef6",
    scryfall_id = "47ffdeb8-52d2-4059-b9c6-0ad71b96516a",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Moriok Rigger",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::ROGUE,
            subtypes::creature::RIGGER
        ],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::ARTIFACT),
        &[Effect::MayDo {
            effects: &[Effect::AddCounter {
                kind: CounterKind::P1P1,
                amount: Amount::Fixed(1)
            }]
        }]
    ),],
);
