//! Overeager Apprentice — {2}{B} — Creature — Human Minion
//! Oracle: Discard a card, Sacrifice this creature: Add {B}{B}{B}.
//! Set: DVD #35 — Duel Decks Anthology: Divine vs. Demonic | Scryfall ID: 8227e2fc-259d-4470-8522-d550746dbc4a | Oracle ID: 3ea71eed-e1ae-4e28-a4f5-44ff115949f4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::OVEREAGER_APPRENTICE,
    oracle_id = "3ea71eed-e1ae-4e28-a4f5-44ff115949f4",
    scryfall_id = "8227e2fc-259d-4470-8522-d550746dbc4a",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Overeager Apprentice",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MINION],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[mana_ability!(
        cost!(Discard(&Filter::Any), SacrificeSelf),
        &[Effect::mana(ManaColor::Black, 3)]
    ),],
);
