//! Pegasus Charger — {2}{W} — Creature — Pegasus
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: First strike (This creature deals combat damage before creatures without first strike.)
//! Set: 9ED #34 — Ninth Edition | Scryfall ID: 0d0dee73-4df3-4b2f-9420-b23e6ced65c0 | Oracle ID: 81a5ac8d-b904-4755-a5bc-650e95f4138f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PEGASUS_CHARGER,
    oracle_id = "81a5ac8d-b904-4755-a5bc-650e95f4138f",
    scryfall_id = "0d0dee73-4df3-4b2f-9420-b23e6ced65c0",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::FIRST_STRIKE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Pegasus Charger",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PEGASUS],
        power = Some(2),
        toughness = Some(1),
    ),],
);
