//! Phyrexian Rager — {2}{B} — Creature — Phyrexian Horror
//! Oracle: When this creature enters, you draw a card and you lose 1 life.
//! Set: MOC #265 — March of the Machine Commander | Scryfall ID: a9861fb3-6722-43b8-bf0a-af6dd166e59d | Oracle ID: e409c9be-0c9a-43c3-adb4-8c47afc1d551
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PHYREXIAN_RAGER,
    oracle_id = "e409c9be-0c9a-43c3-adb4-8c47afc1d551",
    scryfall_id = "a9861fb3-6722-43b8-bf0a-af6dd166e59d",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Phyrexian Rager",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::HORROR],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[
            Effect::draw(1),
            Effect::LoseLife {
                amount: Amount::Fixed(1),
                target: PlayerRel::You
            }
        ]
    ),],
);
