//! Priest of Gix — {2}{B} — Creature — Phyrexian Human Cleric Minion
//! Oracle: When this creature enters, add {B}{B}{B}.
//! Set: DDE #7 — Duel Decks: Phyrexia vs. the Coalition | Scryfall ID: 8cbc4c4c-f1f5-4593-9894-1d8715a2f2c1 | Oracle ID: d93f82ce-0eed-45cc-a7b1-50fd4cbb6152
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PRIEST_OF_GIX,
    oracle_id = "d93f82ce-0eed-45cc-a7b1-50fd4cbb6152",
    scryfall_id = "8cbc4c4c-f1f5-4593-9894-1d8715a2f2c1",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Priest of Gix",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::PHYREXIAN,
            subtypes::creature::HUMAN,
            subtypes::creature::CLERIC,
            subtypes::creature::MINION
        ],
        power = Some(2),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::mana(ManaColor::Black, 3)]
    ),],
);
