//! Raging Bull — {2}{R} — Creature — Ox
//! Set: LEG #163 — Legends | Scryfall ID: ec10a51c-d2c3-4d14-9a71-9e59155bf980 | Oracle ID: 341680e2-12a8-484f-be09-24dae9dbfaea
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RAGING_BULL,
    oracle_id = "341680e2-12a8-484f-be09-24dae9dbfaea",
    scryfall_id = "ec10a51c-d2c3-4d14-9a71-9e59155bf980",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Raging Bull",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::OX],
        power = Some(2),
        toughness = Some(2),
    ),],
);
