//! Ravenous Skirge — {2}{B} — Creature — Phyrexian Imp
//! Oracle: Flying
//! Oracle: Whenever this creature attacks, it gets +2/+0 until end of turn.
//! Set: USG #152 — Urza's Saga | Scryfall ID: d0b6e655-e05e-44b5-9c7f-9dbbc66e6e28 | Oracle ID: b8ae71b3-8ee7-49a0-87ea-7e938166ccb3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RAVENOUS_SKIRGE,
    oracle_id = "b8ae71b3-8ee7-49a0-87ea-7e938166ccb3",
    scryfall_id = "d0b6e655-e05e-44b5-9c7f-9dbbc66e6e28",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ravenous Skirge",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::IMP],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
