//! Rib Cage Spider — {2}{G} — Creature — Spider
//! Oracle: Reach (This creature can block creatures with flying.)
//! Set: PCY #121 — Prophecy | Scryfall ID: d71bebea-1634-4d9a-b3ad-2e01ecacad7e | Oracle ID: 906cba93-3dac-4720-a482-987cf1b4e786
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RIB_CAGE_SPIDER,
    oracle_id = "906cba93-3dac-4720-a482-987cf1b4e786",
    scryfall_id = "d71bebea-1634-4d9a-b3ad-2e01ecacad7e",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::REACH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rib Cage Spider",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIDER],
        power = Some(1),
        toughness = Some(4),
    ),],
);
