//! Rootwalla — {2}{G} — Creature — Lizard
//! Oracle: {1}{G}: This creature gets +2/+2 until end of turn. Activate only once each turn.
//! Set: W17 #27 — Welcome Deck 2017 | Scryfall ID: f5177a97-cf3b-4a82-adc4-14835152880d | Oracle ID: 4dda5f21-11d6-40ce-be24-7c9529272c25
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ROOTWALLA,
    oracle_id = "4dda5f21-11d6-40ce-be24-7c9529272c25",
    scryfall_id = "f5177a97-cf3b-4a82-adc4-14835152880d",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rootwalla",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::LIZARD],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{1}{G}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
