//! Rotlung Reanimator — {2}{B} — Creature — Zombie Cleric
//! Oracle: Whenever this creature or another Cleric dies, create a 2/2 black Zombie creature token.
//! Set: ONS #164 — Onslaught | Scryfall ID: 87b29d1e-9c06-4ad1-8178-b3eaa212f6f1 | Oracle ID: de7f1725-833c-4784-94b1-7a33e36aec94
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::CLERIC),
        Filter::Another,
    ]),
    Filter::This,
]);

card!(
    index = index::ROTLUNG_REANIMATOR,
    oracle_id = "de7f1725-833c-4784-94b1-7a33e36aec94",
    scryfall_id = "87b29d1e-9c06-4ad1-8178-b3eaa212f6f1",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rotlung Reanimator",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ZOMBIE, subtypes::creature::CLERIC],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&TRIGGER1),
        &[Effect::CreateToken {
            token: &generated_tokens::ZOMBIE_2_2_BLACK
        }]
    ),],
);
