//! Sedge Troll — {2}{R} — Creature — Troll
//! Oracle: This creature gets +1/+1 as long as you control a Swamp.
//! Oracle: {B}: Regenerate this creature.
//! Set: ME4 #135 — Masters Edition IV | Scryfall ID: 78de6044-1ed8-4fd9-822c-69658e3f3fba | Oracle ID: a6a43190-cca2-4f07-afe9-8af681d777da
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::SEDGE_TROLL,
    oracle_id = "a6a43190-cca2-4f07-afe9-8af681d777da",
    scryfall_id = "78de6044-1ed8-4fd9-822c-69658e3f3fba",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sedge Troll",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::TROLL],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[
        static_ability!(
            Filter::This,
            Modifier::ModifyPT(1, 1),
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
        activated!(cost!("{B}"), &[Effect::regenerate(TargetSpec::ThisObject)]),
    ],
);
