//! Skyhunter Prowler — {2}{W} — Creature — Cat Knight
//! Oracle: Flying, vigilance (This creature can't be blocked except by creatures with flying or reach, and attacking doesn't cause this creature to tap.)
//! Set: 10E #42 — Tenth Edition | Scryfall ID: 52aa4af5-f0cb-4512-bef5-2e46a43aa27b | Oracle ID: 5e0d13b0-d5d0-4c5f-945e-5cda7d980670
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SKYHUNTER_PROWLER,
    oracle_id = "5e0d13b0-d5d0-4c5f-945e-5cda7d980670",
    scryfall_id = "52aa4af5-f0cb-4512-bef5-2e46a43aa27b",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::VIGILANCE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Skyhunter Prowler",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::CAT, subtypes::creature::KNIGHT],
        power = Some(1),
        toughness = Some(3),
    ),],
);
