//! Soratami Rainshaper — {2}{U} — Creature — Moonfolk Wizard
//! Oracle: Flying
//! Oracle: {3}, Return a land you control to its owner's hand: Target creature you control gains shroud until end of turn. (It can't be the target of spells or abilities.)
//! Set: CHK #89 — Champions of Kamigawa | Scryfall ID: b942ee46-c78b-414a-9de7-4376370532fa | Oracle ID: 63c5f42b-13d0-4391-b033-4ab2f4e3152b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SORATAMI_RAINSHAPER,
    oracle_id = "63c5f42b-13d0-4391-b033-4ab2f4e3152b",
    scryfall_id = "b942ee46-c78b-414a-9de7-4376370532fa",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Soratami Rainshaper",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MOONFOLK, subtypes::creature::WIZARD],
        power = Some(2),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{3}", ReturnToHand(&Filter::YOUR_LAND)),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::SHROUD,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::YOUR_CREATURE))
    ),],
);
