//! Stalking Assassin — {1}{U}{B} — Creature — Human Assassin
//! Oracle: {3}{U}, {T}: Tap target creature.
//! Oracle: {3}{B}, {T}: Destroy target tapped creature.
//! Set: INV #277 — Invasion | Scryfall ID: ff8cc71f-3070-497f-908f-35aa13a8a857 | Oracle ID: 12117089-67f7-4d0e-88db-82b27a4c7cdc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[Filter::CREATURE, Filter::Tapped]);

card!(
    index = index::STALKING_ASSASSIN,
    oracle_id = "12117089-67f7-4d0e-88db-82b27a4c7cdc",
    scryfall_id = "ff8cc71f-3070-497f-908f-35aa13a8a857",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stalking Assassin",
        mana_cost = mana!("{1}{U}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ASSASSIN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{3}{U}", TapSelf),
            &[Effect::TapTarget],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{3}{B}", TapSelf),
            &[Effect::destroy(TargetSpec::Object(&TARGET1))],
            target = Some(TargetSpec::Object(&TARGET1))
        ),
    ],
);
