//! Taoist Hermit — {2}{G} — Creature — Human Mystic
//! Oracle: Hexproof (This creature can't be the target of spells or abilities your opponents control.)
//! Set: PTK #150 — Portal Three Kingdoms | Scryfall ID: d818c231-8d66-4024-91de-fe29f8622902 | Oracle ID: 960b1251-12af-4766-8df1-bb98e7e967f5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TAOIST_HERMIT,
    oracle_id = "960b1251-12af-4766-8df1-bb98e7e967f5",
    scryfall_id = "d818c231-8d66-4024-91de-fe29f8622902",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::HEXPROOF,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Taoist Hermit",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MYSTIC],
        power = Some(2),
        toughness = Some(2),
    ),],
);
