//! Thundering Wurm — {2}{G} — Creature — Wurm
//! Oracle: When this creature enters, sacrifice it unless you discard a land card.
//! Set: POR #189 — Portal | Scryfall ID: 8b0ba623-d17f-4f0e-b914-da139a3971df | Oracle ID: cdab50a8-1e02-4ba5-8c09-e2837e7652f7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::THUNDERING_WURM,
    oracle_id = "cdab50a8-1e02-4ba5-8c09-e2837e7652f7",
    scryfall_id = "8b0ba623-d17f-4f0e-b914-da139a3971df",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thundering Wurm",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::PlayerMayPayCostOr {
            player: PlayerRel::You,
            cost: &CostPart::Discard(&Filter::LAND),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
