//! Timberwatch Elf — {2}{G} — Creature — Elf
//! Oracle: {T}: Target creature gets +X/+X until end of turn, where X is the number of Elves on the battlefield.
//! Set: KHC #76 — Kaldheim Commander | Scryfall ID: 38807f17-1cf2-4736-ad10-df6c8b1a9f55 | Oracle ID: 50cee3ac-cba0-4abb-babf-de1928b1590e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COUNT1: Filter = Filter::HasSubtype(subtypes::creature::ELF);

card!(
    index = index::TIMBERWATCH_ELF,
    oracle_id = "50cee3ac-cba0-4abb-babf-de1928b1590e",
    scryfall_id = "38807f17-1cf2-4736-ad10-df6c8b1a9f55",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Timberwatch Elf",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::PumpTarget {
            power: Amount::CountOf {
                filter: &COUNT1,
                zone: ZoneSel::Battlefield
            },
            toughness: Amount::CountOf {
                filter: &COUNT1,
                zone: ZoneSel::Battlefield
            },
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
