//! Uktabi Orangutan — {2}{G} — Creature — Ape
//! Oracle: When this creature enters, destroy target artifact.
//! Set: 6ED #260 — Classic Sixth Edition | Scryfall ID: b6a944ef-dbf2-47c9-a245-dfd2533a0680 | Oracle ID: 6cc07a7e-e70c-45c5-83c5-a2704e57dbc5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::UKTABI_ORANGUTAN,
    oracle_id = "6cc07a7e-e70c-45c5-83c5-a2704e57dbc5",
    scryfall_id = "b6a944ef-dbf2-47c9-a245-dfd2533a0680",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Uktabi Orangutan",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::APE],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
    ),],
);
