//! Viridian Shaman — {2}{G} — Creature — Elf Shaman
//! Oracle: When this creature enters, destroy target artifact.
//! Set: DDU #25 — Duel Decks: Elves vs. Inventors | Scryfall ID: bed8b8aa-2c1f-4a5b-af6e-16802b3b9453 | Oracle ID: 5aa6d553-a144-4c5b-83fa-65e931903899
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VIRIDIAN_SHAMAN,
    oracle_id = "5aa6d553-a144-4c5b-83fa-65e931903899",
    scryfall_id = "bed8b8aa-2c1f-4a5b-af6e-16802b3b9453",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Viridian Shaman",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::SHAMAN],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
    ),],
);
