//! Wall of Blood — {2}{B} — Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: Pay 1 life: This creature gets +1/+1 until end of turn.
//! Set: MRD #82 — Mirrodin | Scryfall ID: 17320043-f81c-4e14-b9ba-c1309972c22b | Oracle ID: b26c3563-d289-4ca3-8736-9d89e191a840
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WALL_OF_BLOOD,
    oracle_id = "b26c3563-d289-4ca3-8736-9d89e191a840",
    scryfall_id = "17320043-f81c-4e14-b9ba-c1309972c22b",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wall of Blood",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(PayLife(1)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
