//! Wild Aesthir — {2}{W} — Creature — Bird
//! Oracle: Flying, first strike
//! Oracle: {W}{W}: This creature gets +2/+0 until end of turn. Activate only once each turn.
//! Set: ME4 #34 — Masters Edition IV | Scryfall ID: feffa722-fe05-4e70-ba4c-1cf110b3662f | Oracle ID: dbdf076c-18ce-45e3-8f70-0a32391ea4b6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WILD_AESTHIR,
    oracle_id = "dbdf076c-18ce-45e3-8f70-0a32391ea4b6",
    scryfall_id = "feffa722-fe05-4e70-ba4c-1cf110b3662f",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::FIRST_STRIKE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wild Aesthir",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{W}{W}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
