//! Wood Elves — {2}{G} — Creature — Elf Scout
//! Oracle: When this creature enters, search your library for a Forest card, put that card onto the battlefield, then shuffle.
//! Set: HOB #142 — The Hobbit | Scryfall ID: 2476e42b-b209-4207-8ed9-cb668f89b218 | Oracle ID: 8973bd99-20f8-4867-90ef-50392147ee1b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::land::FOREST);

card!(
    index = index::WOOD_ELVES,
    oracle_id = "8973bd99-20f8-4867-90ef-50392147ee1b",
    scryfall_id = "2476e42b-b209-4207-8ed9-cb668f89b218",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wood Elves",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::SCOUT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD],
            optional: false
        }]
    ),],
);
