//! Darksteel Pendant — {2} — Artifact
//! Oracle: Indestructible (Effects that say "destroy" don't destroy this artifact.)
//! Oracle: {1}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Set: DST #113 — Darksteel | Scryfall ID: 9c1bac5f-c41a-49f0-94b0-79653b6fa67a | Oracle ID: 431838a8-f020-4e4e-a6f4-2d4ca27c56df
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DARKSTEEL_PENDANT,
    oracle_id = "431838a8-f020-4e4e-a6f4-2d4ca27c56df",
    scryfall_id = "9c1bac5f-c41a-49f0-94b0-79653b6fa67a",
    keywords = KeywordSet::INDESTRUCTIBLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Darksteel Pendant",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(cost!("{1}", TapSelf), &[Effect::scry(1)]),],
);
