//! Grim Monolith — {2} — Artifact
//! Oracle: This artifact doesn't untap during your untap step.
//! Oracle: {T}: Add {C}{C}{C}.
//! Oracle: {4}: Untap this artifact.
//! Set: ULG #126 — Urza's Legacy | Scryfall ID: 9ddc9fe1-17c8-4e1d-aeb8-c4214e881280 | Oracle ID: 229d6627-1292-4ae1-8849-b0f956fa6540
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::GRIM_MONOLITH,
    oracle_id = "229d6627-1292-4ae1-8849-b0f956fa6540",
    scryfall_id = "9ddc9fe1-17c8-4e1d-aeb8-c4214e881280",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Grim Monolith",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        static_ability!(Filter::This, Modifier::DoesNotUntap),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 3)]),
        activated!(cost!("{4}"), &[Effect::UntapSelf]),
    ],
);
