//! Journeyer's Kite — {2} — Artifact
//! Oracle: {3}, {T}: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.
//! Set: DDI #65 — Duel Decks: Venser vs. Koth | Scryfall ID: 5440121d-d3b5-4d26-a2d9-674af73d449a | Oracle ID: 10aab5bc-5758-443b-ba4c-49f6c6d91262
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::JOURNEYER_S_KITE,
    oracle_id = "10aab5bc-5758-443b-ba4c-49f6c6d91262",
    scryfall_id = "5440121d-d3b5-4d26-a2d9-674af73d449a",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Journeyer's Kite",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{3}", TapSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::HAND],
            optional: false
        }]
    ),],
);
