//! Talisman of Indulgence — {2} — Artifact
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {B} or {R}. This artifact deals 1 damage to you.
//! Set: FRC #63 — Reality Fracture Commander | Scryfall ID: 36bd614f-ab3b-4ad1-ab5c-a7ca0a641f32 | Oracle ID: 1d9aeaaa-66f6-41cb-9bac-162d6fd8662c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TALISMAN_OF_INDULGENCE,
    oracle_id = "1d9aeaaa-66f6-41cb-9bac-162d6fd8662c",
    scryfall_id = "36bd614f-ab3b-4ad1-ab5c-a7ca0a641f32",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Talisman of Indulgence",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[
            Effect::mana_choice(&[ManaColor::Black, ManaColor::Red]),
            Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }
        ]),
    ],
);
