//! Talisman of Dominance — {2} — Artifact
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {U} or {B}. This artifact deals 1 damage to you.
//! Set: FRC #62 — Reality Fracture Commander | Scryfall ID: 78d5366f-eb6d-4ec1-880b-111872863766 | Oracle ID: 4c0a0448-b9d6-43a0-8549-64066dac63f0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TALISMAN_OF_DOMINANCE,
    oracle_id = "4c0a0448-b9d6-43a0-8549-64066dac63f0",
    scryfall_id = "78d5366f-eb6d-4ec1-880b-111872863766",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Talisman of Dominance",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[
            Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black]),
            Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }
        ]),
    ],
);
