//! Talisman of Progress — {2} — Artifact
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {W} or {U}. This artifact deals 1 damage to you.
//! Set: MSC #221 — Marvel Super Heroes Commander | Scryfall ID: b356ee36-1c62-4097-87d7-fef6a6dad067 | Oracle ID: 00e35322-1a9a-41e3-9ce1-359c8eaa3bc7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TALISMAN_OF_PROGRESS,
    oracle_id = "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7",
    scryfall_id = "b356ee36-1c62-4097-87d7-fef6a6dad067",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Talisman of Progress",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[
            Effect::mana_choice(&[ManaColor::White, ManaColor::Blue]),
            Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }
        ]),
    ],
);
