//! Talisman of Impulse — {2} — Artifact
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {R} or {G}. This artifact deals 1 damage to you.
//! Set: TDC #332 — Tarkir: Dragonstorm Commander | Scryfall ID: 5135919f-7b10-4a2e-a98a-83ed1347ad36 | Oracle ID: f2ccc9e8-8e92-4f8c-8728-8c748630e0dd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TALISMAN_OF_IMPULSE,
    oracle_id = "f2ccc9e8-8e92-4f8c-8728-8c748630e0dd",
    scryfall_id = "5135919f-7b10-4a2e-a98a-83ed1347ad36",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Talisman of Impulse",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[
            Effect::mana_choice(&[ManaColor::Red, ManaColor::Green]),
            Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }
        ]),
    ],
);
