//! Karplusan Giant — {6}{R} — Creature — Giant
//! Oracle: Tap an untapped snow land you control: This creature gets +1/+1 until end of turn.
//! Set: ME2 #133 — Masters Edition II | Scryfall ID: 67c031e0-7f5c-4c12-884b-d30eed5e888b | Oracle ID: f0fac3bc-a566-448e-a9a2-10927a49f182
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::LAND,
    Filter::HasSupertype(SupertypeSet::SNOW),
    Filter::ControlledByYou,
]);

card!(
    index = index::KARPLUSAN_GIANT,
    oracle_id = "f0fac3bc-a566-448e-a9a2-10927a49f182",
    scryfall_id = "67c031e0-7f5c-4c12-884b-d30eed5e888b",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Karplusan Giant",
        mana_cost = mana!("{6}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GIANT],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!(TapOther(&COST1)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
