//! Lady Orca — {5}{B}{R} — Legendary Creature — Demon
//! Set: ME3 #159 — Masters Edition III | Scryfall ID: db766e38-5407-431c-bcf4-f33791a7e5f9 | Oracle ID: fcae9e87-50af-46b4-ab48-42ed92985e10
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LADY_ORCA,
    oracle_id = "fcae9e87-50af-46b4-ab48-42ed92985e10",
    scryfall_id = "db766e38-5407-431c-bcf4-f33791a7e5f9",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lady Orca",
        mana_cost = mana!("{5}{B}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::DEMON],
        power = Some(7),
        toughness = Some(4),
    ),],
);
