//! Lady Caleria — {3}{G}{G}{W}{W} — Legendary Creature — Elf Archer
//! Oracle: {T}: Lady Caleria deals 3 damage to target attacking or blocking creature.
//! Set: ME3 #157 — Masters Edition III | Scryfall ID: 84b9a2b7-6ff7-4a81-86ae-64cc77c23030 | Oracle ID: 74284bbc-b011-4e16-b8d5-7ddacc77f9d7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::And(&[Filter::CREATURE, Filter::Attacking]),
    Filter::And(&[Filter::CREATURE, Filter::Blocking]),
]);

card!(
    index = index::LADY_CALERIA,
    oracle_id = "74284bbc-b011-4e16-b8d5-7ddacc77f9d7",
    scryfall_id = "84b9a2b7-6ff7-4a81-86ae-64cc77c23030",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lady Caleria",
        mana_cost = mana!("{3}{G}{G}{W}{W}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::ARCHER],
        power = Some(3),
        toughness = Some(6),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DealDamage {
            amount: Amount::Fixed(3),
            target: TargetSpec::Object(&TARGET1)
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
