//! Macetail Hystrodon — {6}{R} — Creature — Beast
//! Oracle: First strike, haste
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: DMR #130 — Dominaria Remastered | Scryfall ID: c750f7d7-25b8-433f-b3a8-0d842b99276f | Oracle ID: 2f1e2742-d7df-4893-abc8-cb927c500569
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MACETAIL_HYSTRODON,
    oracle_id = "2f1e2742-d7df-4893-abc8-cb927c500569",
    scryfall_id = "c750f7d7-25b8-433f-b3a8-0d842b99276f",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FIRST_STRIKE.union(KeywordSet::HASTE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Macetail Hystrodon",
        mana_cost = mana!("{6}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BEAST],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{3}", DiscardSelf),
        &[Effect::draw(1)],
        zone = ActivationZone::Hand
    ),],
);
