//! Omnath, Locus of Rage — {3}{R}{R}{G}{G} — Legendary Creature — Elemental
//! Oracle: Landfall — Whenever a land you control enters, create a 5/5 red and green Elemental creature token.
//! Oracle: Whenever Omnath or another Elemental you control dies, Omnath deals 3 damage to any target.
//! Set: ECC #129 — Lorwyn Eclipsed Commander | Scryfall ID: 637c5910-f835-496e-b1b9-445bfb71da97 | Oracle ID: 1816eede-c5bd-49df-958f-a3af64cb2932
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::This,
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::ELEMENTAL),
        Filter::Another,
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::OMNATH_LOCUS_OF_RAGE,
    oracle_id = "1816eede-c5bd-49df-958f-a3af64cb2932",
    scryfall_id = "637c5910-f835-496e-b1b9-445bfb71da97",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Omnath, Locus of Rage",
        mana_cost = mana!("{3}{R}{R}{G}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ELEMENTAL],
        power = Some(5),
        toughness = Some(5),
    ),],
    abilities = &[
        triggered!(
            Trigger::EntersBattlefield(&Filter::YOUR_LAND),
            &[Effect::CreateToken {
                token: &generated_tokens::ELEMENTAL_5_5_RED_GREEN
            }]
        ),
        triggered!(
            Trigger::Dies(&TRIGGER1),
            &[Effect::DealDamage {
                amount: Amount::Fixed(3),
                target: TargetSpec::AnyTarget
            }],
            targets = Some(TargetReq::one(TargetSpec::AnyTarget))
        ),
    ],
);
