//! Plated Slagwurm — {4}{G}{G}{G} — Creature — Wurm
//! Oracle: Hexproof (This creature can't be the target of spells or abilities your opponents control.)
//! Set: GVL #12 — Duel Decks Anthology: Garruk vs. Liliana | Scryfall ID: 941fa83a-cb61-47b1-83a7-7ce7e894c338 | Oracle ID: 4aec7624-e406-45a4-b2b6-2e8d29f6268a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PLATED_SLAGWURM,
    oracle_id = "4aec7624-e406-45a4-b2b6-2e8d29f6268a",
    scryfall_id = "941fa83a-cb61-47b1-83a7-7ce7e894c338",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::HEXPROOF,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Plated Slagwurm",
        mana_cost = mana!("{4}{G}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(8),
        toughness = Some(8),
    ),],
);
