//! Rootbreaker Wurm — {5}{G}{G} — Creature — Wurm
//! Oracle: Trample (This creature can deal excess combat damage to the player or planeswalker it's attacking.)
//! Set: TPR #190 — Tempest Remastered | Scryfall ID: a6ef7a7b-7d6d-4ee2-a961-482c66276f09 | Oracle ID: d3edbb47-6892-4853-badc-cc01499d4e55
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ROOTBREAKER_WURM,
    oracle_id = "d3edbb47-6892-4853-badc-cc01499d4e55",
    scryfall_id = "a6ef7a7b-7d6d-4ee2-a961-482c66276f09",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rootbreaker Wurm",
        mana_cost = mana!("{5}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(6),
        toughness = Some(6),
    ),],
);
