//! Shivan Hellkite — {5}{R}{R} — Creature — Dragon
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: {1}{R}: This creature deals 1 damage to any target.
//! Set: AFC #139 — Forgotten Realms Commander | Scryfall ID: d33cfe2d-150d-4ab7-990a-c8b0b6ff4d37 | Oracle ID: 069be6a0-9545-4fdc-ad40-957fe307db7a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SHIVAN_HELLKITE,
    oracle_id = "069be6a0-9545-4fdc-ad40-957fe307db7a",
    scryfall_id = "d33cfe2d-150d-4ab7-990a-c8b0b6ff4d37",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shivan Hellkite",
        mana_cost = mana!("{5}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRAGON],
        power = Some(5),
        toughness = Some(5),
    ),],
    abilities = &[activated!(
        cost!("{1}{R}"),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
