//! Rejuvenating Springs — (no cost) — Land
//! Oracle: This land enters tapped unless you have two or more opponents.
//! Oracle: {T}: Add {G} or {U}.
//! Set: MSC #260 — Marvel Super Heroes Commander | Scryfall ID: c4565a7b-a0ed-4a7f-ad48-7745c56d141b | Oracle ID: d1620449-930a-4895-a143-fd2a0a3c8b17
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, crowd land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::REJUVENATING_SPRINGS,
    oracle_id = "d1620449-930a-4895-a143-fd2a0a3c8b17",
    scryfall_id = "c4565a7b-a0ed-4a7f-ad48-7745c56d141b",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rejuvenating Springs",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessOpponents { at_least: 2 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Green,
        ManaColor::Blue
    ])]),],
);
