//! Sea of Clouds — (no cost) — Land
//! Oracle: This land enters tapped unless you have two or more opponents.
//! Oracle: {T}: Add {W} or {U}.
//! Set: CLB #360 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: d4fb722f-40af-4bd1-b660-e8186b98f233 | Oracle ID: 672e190d-8ea0-4a2e-b74f-5d35304631e4
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, crowd land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SEA_OF_CLOUDS,
    oracle_id = "672e190d-8ea0-4a2e-b74f-5d35304631e4",
    scryfall_id = "d4fb722f-40af-4bd1-b660-e8186b98f233",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sea of Clouds",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessOpponents { at_least: 2 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
