//! Spectator Seating — (no cost) — Land
//! Oracle: This land enters tapped unless you have two or more opponents.
//! Oracle: {T}: Add {R} or {W}.
//! Set: MSC #268 — Marvel Super Heroes Commander | Scryfall ID: 4c62dcfc-4bc8-4551-b3c7-9eec26be3362 | Oracle ID: cf6d10ed-85c3-48f2-8ba0-2960e03b408b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, crowd land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPECTATOR_SEATING,
    oracle_id = "cf6d10ed-85c3-48f2-8ba0-2960e03b408b",
    scryfall_id = "4c62dcfc-4bc8-4551-b3c7-9eec26be3362",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spectator Seating",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessOpponents { at_least: 2 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::White
    ])]),],
);
