//! Undergrowth Stadium — (no cost) — Land
//! Oracle: This land enters tapped unless you have two or more opponents.
//! Oracle: {T}: Add {B} or {G}.
//! Set: TMC #80 — Teenage Mutant Ninja Turtles Eternal | Scryfall ID: f25aa8aa-e2f7-4634-8a96-2082e76c6503 | Oracle ID: 7c69f718-acc8-4851-8e5d-0cbaaa86192c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, crowd land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::UNDERGROWTH_STADIUM,
    oracle_id = "7c69f718-acc8-4851-8e5d-0cbaaa86192c",
    scryfall_id = "f25aa8aa-e2f7-4634-8a96-2082e76c6503",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Undergrowth Stadium",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessOpponents { at_least: 2 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Green
    ])]),],
);
