//! Vault of Champions — (no cost) — Land
//! Oracle: This land enters tapped unless you have two or more opponents.
//! Oracle: {T}: Add {W} or {B}.
//! Set: CMM #436 — Commander Masters | Scryfall ID: cafd7db6-b04e-4fa2-bccd-981211132a93 | Oracle ID: ebc5ac83-08d4-4d6b-b840-0c4ba71a38ab
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, crowd land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VAULT_OF_CHAMPIONS,
    oracle_id = "ebc5ac83-08d4-4d6b-b840-0c4ba71a38ab",
    scryfall_id = "cafd7db6-b04e-4fa2-bccd-981211132a93",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vault of Champions",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessOpponents { at_least: 2 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Black
    ])]),],
);
