//! No-Dachi — {2} — Artifact — Equipment
//! Oracle: Equipped creature gets +2/+0 and has first strike.
//! Oracle: Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: CHK #264 — Champions of Kamigawa | Scryfall ID: 6c6061a8-d27f-4258-9e95-cd12365c4248 | Oracle ID: 417312f8-16ca-47a7-b991-906788691700
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::NO_DACHI,
    oracle_id = "417312f8-16ca-47a7-b991-906788691700",
    scryfall_id = "6c6061a8-d27f-4258-9e95-cd12365c4248",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "No-Dachi",
        mana_cost = mana!("{2}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{3}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(2, 0)
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::FIRST_STRIKE)
        ),
    ],
);
