//! Forgotten Cave — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R}.
//! Oracle: Cycling {R} ({R}, Discard this card: Draw a card.)
//! Set: C21 #289 — Commander 2021 | Scryfall ID: 62b0b5f8-6b51-4fa5-85ae-290475525a9d | Oracle ID: 394c6de5-7957-4a0b-a6b9-ee0c707cd022
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;

card! {
    index: 512,
    oracle_id: "394c6de5-7957-4a0b-a6b9-ee0c707cd022",
    scryfall_id: "62b0b5f8-6b51-4fa5-85ae-290475525a9d",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Forgotten Cave",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{R}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
