//! Night Market — (no cost) — Land
//! Oracle: This land enters tapped. As it enters, choose a color.
//! Oracle: {T}: Add one mana of the chosen color.
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: DFT #258 — Aetherdrift | Scryfall ID: a8c1dce3-6136-4294-9d2b-5ef8527d733b | Oracle ID: 4cdb9f80-d08f-4986-99c8-573166d66082
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::NIGHT_MARKET,
    oracle_id = "4cdb9f80-d08f-4986-99c8-573166d66082",
    scryfall_id = "a8c1dce3-6136-4294-9d2b-5ef8527d733b",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Night Market",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::ChooseColor, EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            cost!("{3}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana_chosen()]),
    ],
);
