//! Aether Spellbomb — {1} — Artifact
//! Oracle: {U}, Sacrifice this artifact: Return target creature to its owner's hand.
//! Oracle: {1}, Sacrifice this artifact: Draw a card.
//! Set: JMP #456 — Jumpstart | Scryfall ID: a54e8ce9-edd7-4ae7-9521-6fb6727cf63b | Oracle ID: 4b033a0a-c1ae-44d7-9662-72cbbfda024b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::AETHER_SPELLBOMB,
    oracle_id = "4b033a0a-c1ae-44d7-9662-72cbbfda024b",
    scryfall_id = "a54e8ce9-edd7-4ae7-9521-6fb6727cf63b",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aether Spellbomb",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(
            cost!("{U}", SacrificeSelf),
            &[Effect::bounce(TargetSpec::Object(&Filter::CREATURE))],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(cost!("{1}", SacrificeSelf), &[Effect::draw(1)]),
    ],
);
