//! Darkwater Egg — {1} — Artifact
//! Oracle: {2}, {T}, Sacrifice this artifact: Add {U}{B}. Draw a card. (Activate only as an instant.)
//! Set: ODY #299 — Odyssey | Scryfall ID: fb988572-1e1d-4b1d-8dc7-78bda966554e | Oracle ID: c4893a24-3cbc-4011-bef4-50e0c4dce16e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DARKWATER_EGG,
    oracle_id = "c4893a24-3cbc-4011-bef4-50e0c4dce16e",
    scryfall_id = "fb988572-1e1d-4b1d-8dc7-78bda966554e",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Darkwater Egg",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(
        cost!("{2}", TapSelf, SacrificeSelf),
        &[
            Effect::mana(ManaColor::Blue, 1),
            Effect::mana(ManaColor::Black, 1),
            Effect::draw(1)
        ]
    ),],
);
