//! Mana Cylix — {1} — Artifact
//! Oracle: {1}, {T}: Add one mana of any color.
//! Set: CON #138 — Conflux | Scryfall ID: 68e25c75-5e20-4990-9b7e-9d04c94fee9f | Oracle ID: 47f20da0-cd31-4877-8eca-0c8389a66e89
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MANA_CYLIX,
    oracle_id = "47f20da0-cd31-4877-8eca-0c8389a66e89",
    scryfall_id = "68e25c75-5e20-4990-9b7e-9d04c94fee9f",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mana Cylix",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(
        cost!("{1}", TapSelf),
        &[Effect::mana_of_any_color()]
    ),],
);
