//! Pyrite Spellbomb — {1} — Artifact
//! Oracle: {R}, Sacrifice this artifact: It deals 2 damage to any target.
//! Oracle: {1}, Sacrifice this artifact: Draw a card.
//! Set: 2XM #283 — Double Masters | Scryfall ID: 088c801d-381f-403b-aeb7-fbbfafee99bf | Oracle ID: 2c10cae2-951a-4f4f-94e4-8713b58d07dd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PYRITE_SPELLBOMB,
    oracle_id = "2c10cae2-951a-4f4f-94e4-8713b58d07dd",
    scryfall_id = "088c801d-381f-403b-aeb7-fbbfafee99bf",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Pyrite Spellbomb",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(cost!("{1}", SacrificeSelf), &[Effect::draw(1)]),
        activated!(
            cost!("{R}", SacrificeSelf),
            &[Effect::DealDamage {
                amount: Amount::Fixed(2),
                target: TargetSpec::AnyTarget
            }],
            target = Some(TargetSpec::AnyTarget)
        ),
    ],
);
