//! Sunbeam Spellbomb — {1} — Artifact
//! Oracle: {W}, Sacrifice this artifact: You gain 5 life.
//! Oracle: {1}, Sacrifice this artifact: Draw a card.
//! Set: MRD #250 — Mirrodin | Scryfall ID: d23ffdb7-9f8e-4376-9431-cf1c1814f2c4 | Oracle ID: 014c94d8-2c39-4d33-902b-fa2398406fd5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SUNBEAM_SPELLBOMB,
    oracle_id = "014c94d8-2c39-4d33-902b-fa2398406fd5",
    scryfall_id = "d23ffdb7-9f8e-4376-9431-cf1c1814f2c4",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sunbeam Spellbomb",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(cost!("{1}", SacrificeSelf), &[Effect::draw(1)]),
        activated!(cost!("{W}", SacrificeSelf), &[Effect::gain_life(5)]),
    ],
);
