//! Tanglebloom — {1} — Artifact
//! Oracle: {1}, {T}: You gain 1 life.
//! Set: 9ED #311 — Ninth Edition | Scryfall ID: eb8ff237-dac6-4c79-9d8c-b047d60083e8 | Oracle ID: 87890f04-b831-4869-a7de-72789a466c71
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TANGLEBLOOM,
    oracle_id = "87890f04-b831-4869-a7de-72789a466c71",
    scryfall_id = "eb8ff237-dac6-4c79-9d8c-b047d60083e8",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tanglebloom",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(cost!("{1}", TapSelf), &[Effect::gain_life(1)]),],
);
