//! Wayfarer's Bauble — {1} — Artifact
//! Oracle: {2}, {T}, Sacrifice this artifact: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
//! Set: HOC #211 — The Hobbit Eternal | Scryfall ID: b279f268-c37e-4a2d-8195-74f4881226fc | Oracle ID: 31f15274-301b-47c5-ba19-0ced04520878
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::WAYFARER_S_BAUBLE,
    oracle_id = "31f15274-301b-47c5-ba19-0ced04520878",
    scryfall_id = "b279f268-c37e-4a2d-8195-74f4881226fc",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wayfarer's Bauble",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{2}", TapSelf, SacrificeSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD_TAPPED],
            optional: false
        }]
    ),],
);
