//! Myr Matrix — {5} — Artifact
//! Oracle: Indestructible (Effects that say "destroy" don't destroy this artifact.)
//! Oracle: Myr creatures get +1/+1.
//! Oracle: {5}: Create a 1/1 colorless Myr artifact creature token.
//! Set: DST #132 — Darksteel | Scryfall ID: 4a1af62e-d566-4f39-a467-244602c9240b | Oracle ID: 46a07fdd-0ca3-4654-9caa-a88fae80c414
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MYR_MATRIX,
    oracle_id = "46a07fdd-0ca3-4654-9caa-a88fae80c414",
    scryfall_id = "4a1af62e-d566-4f39-a467-244602c9240b",
    keywords = KeywordSet::INDESTRUCTIBLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Myr Matrix",
        mana_cost = mana!("{5}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::MYR)
            ]),
            Modifier::ModifyPT(1, 1)
        ),
        activated!(
            cost!("{5}"),
            &[Effect::CreateToken {
                token: &generated_tokens::MYR_ARTIFACT_1_1
            }]
        ),
    ],
);
