//! The Hive — {5} — Artifact
//! Oracle: {5}, {T}: Create a 1/1 colorless Insect artifact creature token with flying named Wasp. (It can't be blocked except by creatures with flying or reach.)
//! Set: 10E #324 — Tenth Edition | Scryfall ID: 4141e02a-d42c-4272-833d-98e2614ab371 | Oracle ID: 87a77482-f286-4fb1-b179-85b2095bb768
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::THE_HIVE,
    oracle_id = "87a77482-f286-4fb1-b179-85b2095bb768",
    scryfall_id = "4141e02a-d42c-4272-833d-98e2614ab371",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "The Hive",
        mana_cost = mana!("{5}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{5}", TapSelf),
        &[Effect::CreateToken {
            token: &generated_tokens::WASP_ARTIFACT_1_1_FLYING
        }]
    ),],
);
