//! Cascade Bluffs — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {U/R}, {T}: Add {U}{U}, {U}{R}, or {R}{R}.
//! Set: SOC #364 — Secrets of Strixhaven Commander | Scryfall ID: 22acccd2-4e9d-46de-a060-863b08152e50 | Oracle ID: f1603384-4361-49c9-98aa-7785fc3504c4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CASCADE_BLUFFS,
    oracle_id = "f1603384-4361-49c9-98aa-7785fc3504c4",
    scryfall_id = "22acccd2-4e9d-46de-a060-863b08152e50",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Cascade Bluffs", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{U/R}", TapSelf),
            &[Effect::mana_combination(
                &[ManaColor::Blue, ManaColor::Red],
                Amount::Fixed(2)
            )]
        ),
    ],
);
