//! Crypt of the Eternals — (no cost) — Land
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add {U}, {B}, or {R}.
//! Set: HOU #169 — Hour of Devastation | Scryfall ID: cab5b199-e79d-4ca9-970c-cfd9df8fd1e4 | Oracle ID: cc78776b-822b-4f11-8982-0805a25a9d36
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CRYPT_OF_THE_ETERNALS,
    oracle_id = "cc78776b-822b-4f11-8982-0805a25a9d36",
    scryfall_id = "cab5b199-e79d-4ca9-970c-cfd9df8fd1e4",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Crypt of the Eternals", types = TypeSet::LAND,),],
    abilities = &[
        triggered!(
            Trigger::EntersBattlefield(&Filter::This),
            &[Effect::gain_life(1)]
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{1}", TapSelf),
            &[Effect::mana_choice(&[
                ManaColor::Blue,
                ManaColor::Black,
                ManaColor::Red
            ])]
        ),
    ],
);
