//! Rugged Prairie — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {R/W}, {T}: Add {R}{R}, {R}{W}, or {W}{W}.
//! Set: SOC #401 — Secrets of Strixhaven Commander | Scryfall ID: 6bd21c9e-de16-4ee9-ae16-6e82b490109d | Oracle ID: 8e7641e1-e814-4d5a-9cb3-71ad2f4ceee8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RUGGED_PRAIRIE,
    oracle_id = "8e7641e1-e814-4d5a-9cb3-71ad2f4ceee8",
    scryfall_id = "6bd21c9e-de16-4ee9-ae16-6e82b490109d",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Rugged Prairie", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{R/W}", TapSelf),
            &[Effect::mana_combination(
                &[ManaColor::Red, ManaColor::White],
                Amount::Fixed(2)
            )]
        ),
    ],
);
