//! Sunken Ruins — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {U/B}, {T}: Add {U}{U}, {U}{B}, or {B}{B}.
//! Set: 2XM #326 — Double Masters | Scryfall ID: 9181d30d-4f8e-421f-89b8-149ed8000fb2 | Oracle ID: e6415ffb-8b7a-41c3-bedf-0d4112b7b795
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SUNKEN_RUINS,
    oracle_id = "e6415ffb-8b7a-41c3-bedf-0d4112b7b795",
    scryfall_id = "9181d30d-4f8e-421f-89b8-149ed8000fb2",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Sunken Ruins", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{U/B}", TapSelf),
            &[Effect::mana_combination(
                &[ManaColor::Blue, ManaColor::Black],
                Amount::Fixed(2)
            )]
        ),
    ],
);
