//! Sunken Ruins — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {U/B}, {T}: Add {U}{U}, {U}{B}, or {B}{B}.
//! Set: FRC #86 — Reality Fracture Commander | Scryfall ID: b8652a52-d9f6-42ad-9746-6827845b540e | Oracle ID: e6415ffb-8b7a-41c3-bedf-0d4112b7b795
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SUNKEN_RUINS,
    oracle_id = "e6415ffb-8b7a-41c3-bedf-0d4112b7b795",
    scryfall_id = "b8652a52-d9f6-42ad-9746-6827845b540e",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Sunken Ruins", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{U/B}", TapSelf),
            &[Effect::mana_combination(
                &[ManaColor::Blue, ManaColor::Black],
                Amount::Fixed(2)
            )]
        ),
    ],
);
