//! Crenellated Wall — {4} — Artifact Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {T}: Target creature gets +0/+4 until end of turn.
//! Set: MMQ #290 — Mercadian Masques | Scryfall ID: d85ad08d-1120-411a-8bbe-ac93a56476bd | Oracle ID: ca9e41e8-7830-4721-b131-07d0b60297ad
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CRENELLATED_WALL,
    oracle_id = "ca9e41e8-7830-4721-b131-07d0b60297ad",
    scryfall_id = "d85ad08d-1120-411a-8bbe-ac93a56476bd",
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crenellated Wall",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(4),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
