//! Dancing Scimitar — {4} — Artifact Creature — Spirit
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Set: 9ED #292 — Ninth Edition | Scryfall ID: ede26e9e-95b6-4dbc-9263-59f370c4f6a3 | Oracle ID: 82b13601-d460-45c5-94a1-07e146d463a9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DANCING_SCIMITAR,
    oracle_id = "82b13601-d460-45c5-94a1-07e146d463a9",
    scryfall_id = "ede26e9e-95b6-4dbc-9263-59f370c4f6a3",
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dancing Scimitar",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(1),
        toughness = Some(5),
    ),],
);
