//! Living Wall — {4} — Artifact Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {1}: Regenerate this creature.
//! Set: ME4 #212 — Masters Edition IV | Scryfall ID: 7ed9efc7-65ea-425d-bd03-6f6c668db1df | Oracle ID: 4844312c-3c9d-4ca1-986d-4ad35e68454e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LIVING_WALL,
    oracle_id = "4844312c-3c9d-4ca1-986d-4ad35e68454e",
    scryfall_id = "7ed9efc7-65ea-425d-bd03-6f6c668db1df",
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Living Wall",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(6),
    ),],
    abilities = &[activated!(
        cost!("{1}"),
        &[Effect::regenerate(TargetSpec::ThisObject)]
    ),],
);
