//! Su-Chi — {4} — Artifact Creature — Construct
//! Oracle: When this creature dies, add {C}{C}{C}{C}.
//! Set: VMA #285 — Vintage Masters | Scryfall ID: f27a3660-a50d-4402-97c2-8d70dcbc1782 | Oracle ID: 9a28d53e-c789-47de-8f3e-a251843ac596
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SU_CHI,
    oracle_id = "9a28d53e-c789-47de-8f3e-a251843ac596",
    scryfall_id = "f27a3660-a50d-4402-97c2-8d70dcbc1782",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Su-Chi",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::CONSTRUCT],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::This),
        &[Effect::mana(ManaColor::Colorless, 4)]
    ),],
);
