//! Telethopter — {4} — Artifact Creature — Thopter
//! Oracle: Tap an untapped creature you control: This creature gains flying until end of turn.
//! Set: TPR #232 — Tempest Remastered | Scryfall ID: f6dd54ce-8a80-4746-bd1b-bc49c50c987c | Oracle ID: 8202ff77-9afc-4e5b-895b-471bbfa67cce
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TELETHOPTER,
    oracle_id = "8202ff77-9afc-4e5b-895b-471bbfa67cce",
    scryfall_id = "f6dd54ce-8a80-4746-bd1b-bc49c50c987c",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Telethopter",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::THOPTER],
        power = Some(3),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(TapOther(&Filter::YOUR_CREATURE)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
