//! Irradiate — {3}{B} — Instant
//! Oracle: Target creature gets -1/-1 until end of turn for each artifact you control.
//! Set: MRD #67 — Mirrodin | Scryfall ID: 7e0460cf-ff87-4cf8-89b5-a8b9fb7322e0 | Oracle ID: 84d45389-a085-44bc-a3fb-1a5f7cc6cbe0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::IRRADIATE,
    oracle_id = "84d45389-a085-44bc-a3fb-1a5f7cc6cbe0",
    scryfall_id = "7e0460cf-ff87-4cf8-89b5-a8b9fb7322e0",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Irradiate",
        mana_cost = mana!("{3}{B}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::Negated(&Amount::CountOf {
                filter: &Filter::YOUR_ARTIFACT,
                zone: ZoneSel::Battlefield
            }),
            toughness: Amount::Negated(&Amount::CountOf {
                filter: &Filter::YOUR_ARTIFACT,
                zone: ZoneSel::Battlefield
            }),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
