//! Might of Oaks — {3}{G} — Instant
//! Oracle: Target creature gets +7/+7 until end of turn.
//! Set: M10 #192 — Magic 2010 | Scryfall ID: 438a324b-cf3e-4a0f-95c4-cd548586f7e5 | Oracle ID: 8331f281-819b-4a0b-bad7-bd86dbedb877
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MIGHT_OF_OAKS,
    oracle_id = "8331f281-819b-4a0b-bad7-bd86dbedb877",
    scryfall_id = "438a324b-cf3e-4a0f-95c4-cd548586f7e5",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Might of Oaks",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::Fixed(7),
            toughness: Amount::Fixed(7),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
