//! Blackcleave Cliffs — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {B} or {R}.
//! Set: DSC #263 — Duskmourn: House of Horror Commander | Scryfall ID: f75715ce-744f-409c-aeb1-e66eb9186a74 | Oracle ID: 5ad94412-6f79-4c5d-bbd4-4ef5779a7b6d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::BLACKCLEAVE_CLIFFS,
    oracle_id = "5ad94412-6f79-4c5d-bbd4-4ef5779a7b6d",
    scryfall_id = "f75715ce-744f-409c-aeb1-e66eb9186a74",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Blackcleave Cliffs",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Red
    ])]),],
);
