//! Blooming Marsh — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {B} or {G}.
//! Set: OTJ #266 — Outlaws of Thunder Junction | Scryfall ID: 861caabb-0573-4e94-8b03-342f90465064 | Oracle ID: 66fa2326-1b5d-41fb-b919-83bf9f383577
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::BLOOMING_MARSH,
    oracle_id = "66fa2326-1b5d-41fb-b919-83bf9f383577",
    scryfall_id = "861caabb-0573-4e94-8b03-342f90465064",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Blooming Marsh",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Green
    ])]),],
);
