//! Concealed Courtyard — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {W} or {B}.
//! Set: OTJ #268 — Outlaws of Thunder Junction | Scryfall ID: b75df1f0-0513-40e4-a449-454f75de6434 | Oracle ID: 2d899466-b1eb-4901-b626-1f2fb09b786d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CONCEALED_COURTYARD,
    oracle_id = "2d899466-b1eb-4901-b626-1f2fb09b786d",
    scryfall_id = "b75df1f0-0513-40e4-a449-454f75de6434",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Concealed Courtyard",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Black
    ])]),],
);
