//! Copperline Gorge — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {R} or {G}.
//! Set: ONE #249 — Phyrexia: All Will Be One | Scryfall ID: 78b0f36b-7d8c-4e77-adc2-a4dad93a81d5 | Oracle ID: a05f641c-15c9-43dc-ae0d-1ea372fd33d5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::COPPERLINE_GORGE,
    oracle_id = "a05f641c-15c9-43dc-ae0d-1ea372fd33d5",
    scryfall_id = "78b0f36b-7d8c-4e77-adc2-a4dad93a81d5",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Copperline Gorge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::Green
    ])]),],
);
