//! Darkslick Shores — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {U} or {B}.
//! Set: OTC #281 — Outlaws of Thunder Junction Commander | Scryfall ID: c49305d1-ac95-43ea-b02d-c3c7205bcda6 | Oracle ID: a2b48695-f7d7-42ce-a8a0-2a723428542a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DARKSLICK_SHORES,
    oracle_id = "a2b48695-f7d7-42ce-a8a0-2a723428542a",
    scryfall_id = "c49305d1-ac95-43ea-b02d-c3c7205bcda6",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Darkslick Shores",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Black
    ])]),],
);
