//! Seachrome Coast — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {W} or {U}.
//! Set: ONE #258 — Phyrexia: All Will Be One | Scryfall ID: 9ed7441f-f624-49c8-8611-d9bba0e441ac | Oracle ID: 9e7a240d-dc33-47ac-9f17-77fab4c1c340
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SEACHROME_COAST,
    oracle_id = "9e7a240d-dc33-47ac-9f17-77fab4c1c340",
    scryfall_id = "9ed7441f-f624-49c8-8611-d9bba0e441ac",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Seachrome Coast",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
