//! Spirebluff Canal — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or fewer other lands.
//! Oracle: {T}: Add {U} or {R}.
//! Set: OTJ #270 — Outlaws of Thunder Junction | Scryfall ID: 59a04e16-a767-4112-ab01-6ca1b09c286c | Oracle ID: eb0d8093-5f93-4b25-9384-08f9731bfb28
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, fast land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPIREBLUFF_CANAL,
    oracle_id = "eb0d8093-5f93-4b25-9384-08f9731bfb28",
    scryfall_id = "59a04e16-a767-4112-ab01-6ca1b09c286c",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spirebluff Canal",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Red
    ])]),],
);
