//! A.I.M. Labs — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {B}.
//! Set: MSH #257 — Marvel Super Heroes | Scryfall ID: ca24cd9f-fd9f-4ea0-8b9c-ecf98db219a6 | Oracle ID: 8417f2d5-93c9-474a-a143-5c4e17097a88
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 196,
    oracle_id: "8417f2d5-93c9-474a-a143-5c4e17097a88",
    scryfall_id: "ca24cd9f-fd9f-4ea0-8b9c-ecf98db219a6",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "A.I.M. Labs",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
