//! Avengers Hangar — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {W} or {U}.
//! Set: MSH #259 — Marvel Super Heroes | Scryfall ID: c5d03ebb-1ce9-4a6b-b13e-a72f0b075ae8 | Oracle ID: 10fc2009-4212-47c6-8a97-ab0f45c1f91b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 242,
    oracle_id: "10fc2009-4212-47c6-8a97-ab0f45c1f91b",
    scryfall_id: "c5d03ebb-1ce9-4a6b-b13e-a72f0b075ae8",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Avengers Hangar",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
    ],
}
