//! Battlefield Forge — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {R} or {W}. This land deals 1 damage to you.
//! Set: SOC #362 — Secrets of Strixhaven Commander | Scryfall ID: c47c1bf5-f11e-4f86-b20b-5d899a11dc56 | Oracle ID: 6b75b94e-83b7-457e-ac41-7ca90b5a59aa
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 265,
    oracle_id: "6b75b94e-83b7-457e-ac41-7ca90b5a59aa",
    scryfall_id: "c47c1bf5-f11e-4f86-b20b-5d899a11dc56",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Battlefield Forge",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White]), Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::You) }]),
    ],
}
