//! Bayou — (no cost) — Land — Swamp Forest
//! Oracle: ({T}: Add {B} or {G}.)
//! Set: VMA #293 — Vintage Masters | Scryfall ID: bd7567df-b4d8-41a8-8eac-c05afa784bfe | Oracle ID: b76d1ae6-ad1d-4bac-b4c3-2e03e0e84d9b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 267,
    oracle_id: "b76d1ae6-ad1d-4bac-b4c3-2e03e0e84d9b",
    scryfall_id: "bd7567df-b4d8-41a8-8eac-c05afa784bfe",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bayou",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::FOREST],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
