//! Birnin Zana Plaza — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {G} or {W}.
//! Set: MSH #262 — Marvel Super Heroes | Scryfall ID: 41463827-46de-40c4-ac2b-1fdf6aa36f65 | Oracle ID: c3172c5d-c745-4422-b651-cd414c8da11b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 272,
    oracle_id: "c3172c5d-c745-4422-b651-cd414c8da11b",
    scryfall_id: "41463827-46de-40c4-ac2b-1fdf6aa36f65",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Birnin Zana Plaza",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
    ],
}
