//! Blighted Gorge — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {4}{R}, {T}, Sacrifice this land: It deals 2 damage to any target.
//! Set: DDT #58 — Duel Decks: Merfolk vs. Goblins | Scryfall ID: f133ba0a-e141-4f57-9819-bc17bbacd7b3 | Oracle ID: c2cb0afd-781f-4cfa-b680-ed1edfa81868
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::Any;

card! {
    index: 282,
    oracle_id: "c2cb0afd-781f-4cfa-b680-ed1edfa81868",
    scryfall_id: "f133ba0a-e141-4f57-9819-bc17bbacd7b3",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Blighted Gorge",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{4}{R}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DealDamage { amount: Amount::Fixed(2), target: TargetSpec::Object(&TARGET1) }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
