//! Bog Wreckage — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B}.
//! Oracle: {T}, Sacrifice this land: Add one mana of any color.
//! Set: ODY #314 — Odyssey | Scryfall ID: 189b4925-b34b-43bd-869e-1b1db99450e6 | Oracle ID: bce32541-3bc4-4553-ace2-784a58f164aa
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 293,
    oracle_id: "bce32541-3bc4-4553-ace2-784a58f164aa",
    scryfall_id: "189b4925-b34b-43bd-869e-1b1db99450e6",
    color_identity: ColorSet::from_slice(&[Color::Black]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bog Wreckage",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana_of_any_color()]),
    ],
}
