//! Breeding Pool — (no cost) — Land — Forest Island
//! Oracle: ({T}: Add {G} or {U}.)
//! Oracle: As this land enters, you may pay 2 life. If you don't, it enters tapped.
//! Set: TRK #279 — Star Trek | Scryfall ID: 63e4dc07-c742-41bd-8301-861637908fd1 | Oracle ID: 20283c4a-f1f0-42f0-bc08-6da87474426b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, shockland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 310,
    oracle_id: "20283c4a-f1f0-42f0-bc08-6da87474426b",
    scryfall_id: "63e4dc07-c742-41bd-8301-861637908fd1",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Breeding Pool",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::FOREST, subtypes::land::ISLAND],
        enter_modifiers: &[EnterModifier::TappedOrPayLife(2)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
