//! Canyon Slough — (no cost) — Land — Swamp Mountain
//! Oracle: ({T}: Add {B} or {R}.)
//! Oracle: This land enters tapped.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: MSC #228 — Marvel Super Heroes Commander | Scryfall ID: 587cc3ba-75c2-46a0-bd44-6f953fe1eb01 | Oracle ID: 2031b17c-0536-446f-a9aa-b46fe79b7ea7
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 327,
    oracle_id: "2031b17c-0536-446f-a9aa-b46fe79b7ea7",
    scryfall_id: "587cc3ba-75c2-46a0-bd44-6f953fe1eb01",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Canyon Slough",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::MOUNTAIN],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
