//! Castle Vantress — (no cost) — Land
//! Oracle: This land enters tapped unless you control an Island.
//! Oracle: {T}: Add {U}.
//! Oracle: {2}{U}{U}, {T}: Scry 2.
//! Set: DSC #267 — Duskmourn: House of Horror Commander | Scryfall ID: dead85f7-865c-4f7d-ad6c-014d4e90f8be | Oracle ID: cdf41cf4-4e77-453d-be5b-0abbbd358934
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::HasSubtype(subtypes::land::ISLAND),
]);

card! {
    index: 338,
    oracle_id: "cdf41cf4-4e77-453d-be5b-0abbbd358934",
    scryfall_id: "dead85f7-865c-4f7d-ad6c-014d4e90f8be",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Castle Vantress",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}{U}{U}"), parts: &[CostPart::TapSelf] }, &[Effect::Scry { amount: Amount::Fixed(2) }]),
    ],
}
