//! Cinder Barrens — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {R}.
//! Set: C19 #235 — Commander 2019 | Scryfall ID: 08136a39-bf9f-493c-92d6-178567647fb2 | Oracle ID: f155a05f-9f5e-4875-a407-103b85ce30ee
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 350,
    oracle_id: "f155a05f-9f5e-4875-a407-103b85ce30ee",
    scryfall_id: "08136a39-bf9f-493c-92d6-178567647fb2",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Cinder Barrens",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
