//! Clifftop Retreat — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Mountain or a Plains.
//! Oracle: {T}: Add {R} or {W}.
//! Set: MSC #231 — Marvel Super Heroes Commander | Scryfall ID: 4a7f7767-1959-4812-8654-0a22634096b1 | Oracle ID: d7faa3c8-46cf-46b2-bfa4-89000307cf18
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSubtype(subtypes::land::PLAINS),
    ]),
]);

card! {
    index: 358,
    oracle_id: "d7faa3c8-46cf-46b2-bfa4-89000307cf18",
    scryfall_id: "4a7f7767-1959-4812-8654-0a22634096b1",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Clifftop Retreat",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
    ],
}
