//! Darkmoss Bridge — (no cost) — Artifact Land
//! Oracle: This land enters tapped.
//! Oracle: Indestructible
//! Oracle: {T}: Add {B} or {G}.
//! Set: DSC #269 — Duskmourn: House of Horror Commander | Scryfall ID: 3ca3ef68-ea62-4098-bd43-4597ff0647d4 | Oracle ID: 2065cada-4078-41c4-9e06-2460d2a2e8ee
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 404,
    oracle_id: "2065cada-4078-41c4-9e06-2460d2a2e8ee",
    scryfall_id: "3ca3ef68-ea62-4098-bd43-4597ff0647d4",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    keywords: KeywordSet::INDESTRUCTIBLE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Darkmoss Bridge",
        types: TypeSet::ARTIFACT.union(TypeSet::LAND),
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
