//! Dimension X — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {R} or {W}.
//! Set: TMT #183 — Teenage Mutant Ninja Turtles | Scryfall ID: 1c244fc2-70f0-4149-b0d2-d49fc6bac2b0 | Oracle ID: 8683341a-e836-41e5-9034-4da09eb0ab42
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 426,
    oracle_id: "8683341a-e836-41e5-9034-4da09eb0ab42",
    scryfall_id: "1c244fc2-70f0-4149-b0d2-d49fc6bac2b0",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Dimension X",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
    ],
}
