//! Dismal Backwater — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {B}.
//! Set: TDM #254 — Tarkir: Dragonstorm | Scryfall ID: 082b52c9-c46e-44d3-b723-546ba528e07b | Oracle ID: 865a2194-fca0-446e-aae3-ca475cd66e00
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 431,
    oracle_id: "865a2194-fca0-446e-aae3-ca475cd66e00",
    scryfall_id: "082b52c9-c46e-44d3-b723-546ba528e07b",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Dismal Backwater",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
