//! Drifting Meadow — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: DMR #245 — Dominaria Remastered | Scryfall ID: 8cb024fa-2df1-4414-b0d7-6f700d152c51 | Oracle ID: c6eb2814-0021-4308-ad44-6c8cc59b0d1c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;

card! {
    index: 441,
    oracle_id: "c6eb2814-0021-4308-ad44-6c8cc59b0d1c",
    scryfall_id: "8cb024fa-2df1-4414-b0d7-6f700d152c51",
    color_identity: ColorSet::from_slice(&[Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Drifting Meadow",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
