//! Flood Plain — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}, Sacrifice this land: Search your library for a Plains or Island card, put it onto the battlefield, then shuffle.
//! Set: CMM #994 — Commander Masters | Scryfall ID: 61fc0fba-c285-4fad-85a6-79fd7f3f9c35 | Oracle ID: 9043d8d5-b38a-406f-a44c-49f579c644f0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::HasSubtype(subtypes::land::ISLAND),
]);

card! {
    index: 500,
    oracle_id: "9043d8d5-b38a-406f-a44c-49f579c644f0",
    scryfall_id: "61fc0fba-c285-4fad-85a6-79fd7f3f9c35",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Flood Plain",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        activated!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
