//! Forlorn Flats — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, it deals 1 damage to target opponent.
//! Oracle: {T}: Add {W} or {B}.
//! Set: OTJ #258 — Outlaws of Thunder Junction | Scryfall ID: 963c100e-4e12-438f-b5ae-14391406dff6 | Oracle ID: ebb3e2ff-2214-4e11-88fb-e0fa84288cf1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 514,
    oracle_id: "ebb3e2ff-2214-4e11-88fb-e0fa84288cf1",
    scryfall_id: "963c100e-4e12-438f-b5ae-14391406dff6",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Forlorn Flats",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::Chosen) }], targets: Some(TargetReq::one(TargetSpec::AnyOpponent))),
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
    ],
}
