//! Graypelt Refuge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {G} or {W}.
//! Set: C19 #249 — Commander 2019 | Scryfall ID: 0849b6dd-0330-4b7e-b7da-98e767adb4a0 | Oracle ID: 60b36821-0fad-423c-98c4-f64d991719f3
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 574,
    oracle_id: "60b36821-0fad-423c-98c4-f64d991719f3",
    scryfall_id: "0849b6dd-0330-4b7e-b7da-98e767adb4a0",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Graypelt Refuge",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
    ],
}
