//! Guadosalam, Farplane Gateway — (no cost) — Land — Town
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {U}.
//! Set: FIN #281 — Final Fantasy | Scryfall ID: dfcbc131-fd50-4908-b539-c8e52bb70c58 | Oracle ID: 849c97e4-df15-4ecb-bdf8-283bb497d90c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 588,
    oracle_id: "849c97e4-df15-4ecb-bdf8-283bb497d90c",
    scryfall_id: "dfcbc131-fd50-4908-b539-c8e52bb70c58",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Guadosalam, Farplane Gateway",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::TOWN],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
