//! Haunted Mire — (no cost) — Land — Swamp Forest
//! Oracle: ({T}: Add {B} or {G}.)
//! Oracle: This land enters tapped.
//! Set: SOC #379 — Secrets of Strixhaven Commander | Scryfall ID: 3e041aef-5771-4a3f-af07-e85a66c48979 | Oracle ID: b0b58a03-462c-4964-97c7-42bc777ec23e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 606,
    oracle_id: "b0b58a03-462c-4964-97c7-42bc777ec23e",
    scryfall_id: "3e041aef-5771-4a3f-af07-e85a66c48979",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Haunted Mire",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::FOREST],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
