//! Hell's Kitchen — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {B} or {R}.
//! Set: MSH #268 — Marvel Super Heroes | Scryfall ID: 6137c34e-cc4c-4342-a8e4-cfa9c767c67b | Oracle ID: 1337d89e-a883-4568-a14f-9ca3305cc3df
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 614,
    oracle_id: "1337d89e-a883-4568-a14f-9ca3305cc3df",
    scryfall_id: "6137c34e-cc4c-4342-a8e4-cfa9c767c67b",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Hell's Kitchen",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
