//! Hinterland Harbor — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Forest or an Island.
//! Oracle: {T}: Add {G} or {U}.
//! Set: MSC #250 — Marvel Super Heroes Commander | Scryfall ID: 892451a1-5527-4857-84f8-62028d147489 | Oracle ID: fb5a3403-7f0b-406c-8c4f-d693be010ca6
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSubtype(subtypes::land::ISLAND),
    ]),
]);

card! {
    index: 630,
    oracle_id: "fb5a3403-7f0b-406c-8c4f-d693be010ca6",
    scryfall_id: "892451a1-5527-4857-84f8-62028d147489",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Hinterland Harbor",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
