//! Illegitimate Business — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {B} or {G}.
//! Set: TMT #186 — Teenage Mutant Ninja Turtles | Scryfall ID: 71597acf-1ce6-46a8-b6c0-88755c8a377c | Oracle ID: 01ee70d4-6527-45ae-9600-bd3d16b3037d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 649,
    oracle_id: "01ee70d4-6527-45ae-9600-bd3d16b3037d",
    scryfall_id: "71597acf-1ce6-46a8-b6c0-88755c8a377c",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Illegitimate Business",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
