//! Irrigation Ditch — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {T}, Sacrifice this land: Add {G}{U}.
//! Set: INV #324 — Invasion | Scryfall ID: 977f1b44-166c-4faf-8a7b-d431707e90ce | Oracle ID: e0c3c87b-83e3-4cff-b05f-78a192e2bba4
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 659,
    oracle_id: "e0c3c87b-83e3-4cff-b05f-78a192e2bba4",
    scryfall_id: "977f1b44-166c-4faf-8a7b-d431707e90ce",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Irrigation Ditch",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana(ManaColor::Green, 1), Effect::mana(ManaColor::Blue, 1)]),
    ],
}
