//! Looming Spires — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, target creature gets +1/+1 and gains first strike until end of turn.
//! Oracle: {T}: Add {R}.
//! Set: BFZ #238 — Battle for Zendikar | Scryfall ID: b88177a2-de41-417d-a8f1-07edf005b453 | Oracle ID: 7d09b136-525f-49dd-a3a2-dfaca4e8e9a8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::CREATURE;

card! {
    index: 720,
    oracle_id: "7d09b136-525f-49dd-a3a2-dfaca4e8e9a8",
    scryfall_id: "b88177a2-de41-417d-a8f1-07edf005b453",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Looming Spires",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::PumpTarget { power: Amount::Fixed(1), toughness: Amount::Fixed(1), keywords: KeywordSet::FIRST_STRIKE, duration: Duration::UntilEndOfTurn }], targets: Some(TargetReq::one(TargetSpec::Object(&TARGET1)))),
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Red, 1)]),
    ],
}
