//! Minamo, School at Water's Edge — (no cost) — Legendary Land
//! Oracle: {T}: Add {U}.
//! Oracle: {U}, {T}: Untap target legendary permanent.
//! Set: CHK #279 — Champions of Kamigawa | Scryfall ID: 7536292c-da25-41c8-ba28-1e35758a7f3d | Oracle ID: 17784f90-89a1-47a5-83ef-ae60dfc30bd1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::HasSupertype(SupertypeSet::LEGENDARY);

card! {
    index: 757,
    oracle_id: "17784f90-89a1-47a5-83ef-ae60dfc30bd1",
    scryfall_id: "7536292c-da25-41c8-ba28-1e35758a7f3d",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Minamo, School at Water's Edge",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::LEGENDARY,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Blue, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{U}"), parts: &[CostPart::TapSelf] }, &[Effect::UntapTarget], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
