//! Mishra's Workshop — (no cost) — Land
//! Oracle: {T}: Add {C}{C}{C}. Spend this mana only to cast artifact spells.
//! Set: VMA #305 — Vintage Masters | Scryfall ID: aac0c8df-f01d-4178-8d66-ee603f814d24 | Oracle ID: ba284fe6-bb29-455c-8321-9714a0cdc05e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SPEND1: Filter = Filter::ARTIFACT;

card! {
    index: 769,
    oracle_id: "ba284fe6-bb29-455c-8321-9714a0cdc05e",
    scryfall_id: "aac0c8df-f01d-4178-8d66-ee603f814d24",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Mishra's Workshop",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 3).restricted(&SPEND1, SpendRider::None)]),
    ],
}
