//! Mutant Town — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {G} or {U}.
//! Set: TMT #187 — Teenage Mutant Ninja Turtles | Scryfall ID: c6eac43d-08b6-45a4-803b-10a321a241d7 | Oracle ID: f6059731-2e10-4f72-a214-b257f1677e9e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 795,
    oracle_id: "f6059731-2e10-4f72-a214-b257f1677e9e",
    scryfall_id: "c6eac43d-08b6-45a4-803b-10a321a241d7",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Mutant Town",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
