//! Nature's Lore — {1}{G} — Sorcery
//! Oracle: Search your library for a Forest card, put that card onto the battlefield, then shuffle.
//! Set: MSC #177 — Marvel Super Heroes Commander | Scryfall ID: 7afc4a15-5ff8-457a-aa62-803b2d78d912 | Oracle ID: 78826359-fe63-44ad-adc4-a17ffcd710e4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::land::FOREST);

card! {
    index: 1354,
    oracle_id: "78826359-fe63-44ad-adc4-a17ffcd710e4",
    scryfall_id: "7afc4a15-5ff8-457a-aa62-803b2d78d912",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Nature's Lore",
        mana_cost: baylee_core::mana!("{1}{G}"),
        types: TypeSet::SORCERY,
    },
    ],
    abilities: &[
        spell!(&[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
