//! Needle Spires — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {W}.
//! Oracle: {2}{R}{W}: Until end of turn, this land becomes a 2/1 red and white Elemental creature with double strike. It's still a land.
//! Set: MKC #278 — Murders at Karlov Manor Commander | Scryfall ID: 4a58a287-e4ca-4c6b-8096-142660cee299 | Oracle ID: e7bb8160-0a4b-4e46-b196-7a19fb388d8e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 805,
    oracle_id: "e7bb8160-0a4b-4e46-b196-7a19fb388d8e",
    scryfall_id: "4a58a287-e4ca-4c6b-8096-142660cee299",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Needle Spires",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
        activated!(Cost { mana: baylee_core::mana!("{2}{R}{W}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::ELEMENTAL), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::Red, Color::White])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Ability, filter: &Filter::This, modifier: Modifier::AddKeyword(KeywordSet::DOUBLE_STRIKE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(2, 1), duration: Duration::UntilEndOfTurn }]),
    ],
}
