//! Omashu City — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {G}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #275 — Avatar: The Last Airbender | Scryfall ID: c21e413b-96ed-4ded-b567-f1647074ce5f | Oracle ID: 6f9a4bb2-5959-4a5c-83af-c2729e6673df
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 831,
    oracle_id: "6f9a4bb2-5959-4a5c-83af-c2729e6673df",
    scryfall_id: "c21e413b-96ed-4ded-b567-f1647074ce5f",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Omashu City",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
