//! Pine Barrens — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {B} or {G}. This land deals 1 damage to you.
//! Set: TPR #240 — Tempest Remastered | Scryfall ID: b0f794f0-3588-4fe2-8792-64a58482ff8b | Oracle ID: 603dc263-270c-4a16-9b75-41f36fd7dfde
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 860,
    oracle_id: "603dc263-270c-4a16-9b75-41f36fd7dfde",
    scryfall_id: "b0f794f0-3588-4fe2-8792-64a58482ff8b",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Pine Barrens",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green]), Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::You) }]),
    ],
}
