//! Racers' Ring — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {G}.
//! Oracle: {2}{R}{G}, {T}, Sacrifice this land: Draw a card.
//! Set: SNC #253 — Streets of New Capenna | Scryfall ID: 2a11bdb2-a269-4038-85f3-69fbd02982e9 | Oracle ID: 7e2eb4d5-22a3-43c1-8cf3-e85723da1b61
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 886,
    oracle_id: "7e2eb4d5-22a3-43c1-8cf3-e85723da1b61",
    scryfall_id: "2a11bdb2-a269-4038-85f3-69fbd02982e9",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Racers' Ring",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
        activated!(Cost { mana: baylee_core::mana!("{2}{R}{G}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
