//! Ravaged Highlands — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R}.
//! Oracle: {T}, Sacrifice this land: Add one mana of any color.
//! Set: ODY #324 — Odyssey | Scryfall ID: bb60ffc9-4919-40f2-bdd6-07eee6abf37c | Oracle ID: 68919931-b995-4aa0-9d2a-e80eae2f335f
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 899,
    oracle_id: "68919931-b995-4aa0-9d2a-e80eae2f335f",
    scryfall_id: "bb60ffc9-4919-40f2-bdd6-07eee6abf37c",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Ravaged Highlands",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana_of_any_color()]),
    ],
}
