//! Razortide Bridge — (no cost) — Artifact Land
//! Oracle: This land enters tapped.
//! Oracle: Indestructible
//! Oracle: {T}: Add {W} or {U}.
//! Set: EOC #171 — Edge of Eternities Commander | Scryfall ID: 0bbd24cd-48f7-40d7-9741-f30108f04b84 | Oracle ID: 6cb37ac1-dd11-4a8c-bca5-ef44d828059f
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 901,
    oracle_id: "6cb37ac1-dd11-4a8c-bca5-ef44d828059f",
    scryfall_id: "0bbd24cd-48f7-40d7-9741-f30108f04b84",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    keywords: KeywordSet::INDESTRUCTIBLE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Razortide Bridge",
        types: TypeSet::ARTIFACT.union(TypeSet::LAND),
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
    ],
}
