//! Remote Isle — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U}.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: DMR #254 — Dominaria Remastered | Scryfall ID: a340af37-c0a7-4f26-974b-95397b5c32f7 | Oracle ID: 24aebda0-315f-4d2f-8bd9-00bbaf5bd76a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;

card! {
    index: 908,
    oracle_id: "24aebda0-315f-4d2f-8bd9-00bbaf5bd76a",
    scryfall_id: "a340af37-c0a7-4f26-974b-95397b5c32f7",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Remote Isle",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
