//! Restless Reef — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {B}.
//! Oracle: {2}{U}{B}: Until end of turn, this land becomes a 4/4 blue and black Shark creature with deathtouch. It's still a land.
//! Oracle: Whenever this land attacks, target player mills four cards.
//! Set: LCI #282 — The Lost Caverns of Ixalan | Scryfall ID: 8a8121c9-2480-419c-aa9c-5b8b55f65014 | Oracle ID: df20f85b-5f81-4ee4-8487-55d90109ac36
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 914,
    oracle_id: "df20f85b-5f81-4ee4-8487-55d90109ac36",
    scryfall_id: "8a8121c9-2480-419c-aa9c-5b8b55f65014",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Restless Reef",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{2}{U}{B}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::SHARK), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::Blue, Color::Black])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Ability, filter: &Filter::This, modifier: Modifier::AddKeyword(KeywordSet::DEATHTOUCH), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(4, 4), duration: Duration::UntilEndOfTurn }]),
        triggered!(Trigger::Attacks(&Filter::This), &[Effect::Mill { amount: Amount::Fixed(4), target: PlayerRel::Chosen }], targets: Some(TargetReq::one(TargetSpec::AnyPlayer))),
    ],
}
