//! Sacred Foundry — (no cost) — Land — Mountain Plains
//! Oracle: ({T}: Add {R} or {W}.)
//! Oracle: As this land enters, you may pay 2 life. If you don't, it enters tapped.
//! Set: TRK #295 — Star Trek | Scryfall ID: a7758cc6-4e18-48a5-8720-5f42b5cd9d31 | Oracle ID: 45181cb8-2090-4471-ba90-e5a8f04d525f
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, shockland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 950,
    oracle_id: "45181cb8-2090-4471-ba90-e5a8f04d525f",
    scryfall_id: "a7758cc6-4e18-48a5-8720-5f42b5cd9d31",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sacred Foundry",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::MOUNTAIN, subtypes::land::PLAINS],
        enter_modifiers: &[EnterModifier::TappedOrPayLife(2)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
    ],
}
