//! Secluded Steppe — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: Cycling {W} ({W}, Discard this card: Draw a card.)
//! Set: EOC #177 — Edge of Eternities Commander | Scryfall ID: aaa5bee9-3f6a-45b0-a282-6b23222e948f | Oracle ID: 8dec6fcf-1254-4b1b-ba23-7a3e492a7241
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;

card! {
    index: 992,
    oracle_id: "8dec6fcf-1254-4b1b-ba23-7a3e492a7241",
    scryfall_id: "aaa5bee9-3f6a-45b0-a282-6b23222e948f",
    color_identity: ColorSet::from_slice(&[Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Secluded Steppe",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{W}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
