//! Serpent's Pass — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {B}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #279 — Avatar: The Last Airbender | Scryfall ID: ad87bff5-9b8c-44e4-a6d3-8cc71be9640a | Oracle ID: f715f701-a735-42ab-b31a-8e1bd04ac5ff
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1004,
    oracle_id: "f715f701-a735-42ab-b31a-8e1bd04ac5ff",
    scryfall_id: "ad87bff5-9b8c-44e4-a6d3-8cc71be9640a",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Serpent's Pass",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
