//! Shinka, the Bloodsoaked Keep — (no cost) — Legendary Land
//! Oracle: {T}: Add {R}.
//! Oracle: {R}, {T}: Target legendary creature gains first strike until end of turn.
//! Set: CHK #282 — Champions of Kamigawa | Scryfall ID: d2d5f30e-cc3a-46c1-82a9-2cd73705b2f5 | Oracle ID: 255b937f-c9c9-4ae9-815e-17418eba0602
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
]);

card! {
    index: 1022,
    oracle_id: "255b937f-c9c9-4ae9-815e-17418eba0602",
    scryfall_id: "d2d5f30e-cc3a-46c1-82a9-2cd73705b2f5",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Shinka, the Bloodsoaked Keep",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::LEGENDARY,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Red, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{R}"), parts: &[CostPart::TapSelf] }, &[Effect::PumpTarget { power: Amount::Fixed(0), toughness: Amount::Fixed(0), keywords: KeywordSet::FIRST_STRIKE, duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
