//! Skybridge Towers — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {U}.
//! Oracle: {2}{W}{U}, {T}, Sacrifice this land: Draw a card.
//! Set: SNC #256 — Streets of New Capenna | Scryfall ID: e28c871f-a96a-4e7d-a159-2e93aeb276d4 | Oracle ID: 46466819-3c8b-4f7e-82c2-93cb0118a6e6
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1041,
    oracle_id: "46466819-3c8b-4f7e-82c2-93cb0118a6e6",
    scryfall_id: "e28c871f-a96a-4e7d-a159-2e93aeb276d4",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Skybridge Towers",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
        activated!(Cost { mana: baylee_core::mana!("{2}{W}{U}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
