//! Slippery Karst — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G}.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: DMR #256 — Dominaria Remastered | Scryfall ID: c41073e8-01cc-4d19-acb5-caaf2861bc6a | Oracle ID: 58bfd9a1-67ce-41d0-be38-f05addd1dd9e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1049,
    oracle_id: "58bfd9a1-67ce-41d0-be38-f05addd1dd9e",
    scryfall_id: "c41073e8-01cc-4d19-acb5-caaf2861bc6a",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Slippery Karst",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
