//! Snow-Covered Swamp — (no cost) — Basic Snow Land — Swamp
//! Oracle: ({T}: Add {B}.)
//! Set: KHM #280 — Kaldheim | Scryfall ID: 6aa85af8-15f5-4620-8aea-0b45c28372ed | Oracle ID: d8239a86-7184-4005-ba1e-2dddcd756c47
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1058,
    oracle_id: "d8239a86-7184-4005-ba1e-2dddcd756c47",
    scryfall_id: "6aa85af8-15f5-4620-8aea-0b45c28372ed",
    color_identity: ColorSet::from_slice(&[Color::Black]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Snow-Covered Swamp",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::BASIC.union(SupertypeSet::SNOW),
        subtypes: &[subtypes::land::SWAMP],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
    ],
}
