//! Stirring Wildwood — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {W}.
//! Oracle: {1}{G}{W}: Until end of turn, this land becomes a 3/4 green and white Elemental creature with reach. It's still a land.
//! Set: UMA #251 — Ultimate Masters | Scryfall ID: 22f40dfc-a35d-4094-9805-0de8b7f61cb0 | Oracle ID: e900f211-dc8b-40f7-a217-1b1462b15c26
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1088,
    oracle_id: "e900f211-dc8b-40f7-a217-1b1462b15c26",
    scryfall_id: "22f40dfc-a35d-4094-9805-0de8b7f61cb0",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Stirring Wildwood",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
        activated!(Cost { mana: baylee_core::mana!("{1}{G}{W}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::ELEMENTAL), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::Green, Color::White])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Ability, filter: &Filter::This, modifier: Modifier::AddKeyword(KeywordSet::REACH), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(3, 4), duration: Duration::UntilEndOfTurn }]),
    ],
}
