//! Sulfur Falls — (no cost) — Land
//! Oracle: This land enters tapped unless you control an Island or a Mountain.
//! Oracle: {T}: Add {U} or {R}.
//! Set: MSC #269 — Marvel Super Heroes Commander | Scryfall ID: c762f475-7e58-4477-839b-b3c55434b88f | Oracle ID: 6a6c5e17-6465-4a1f-9d63-8a3ce2edc522
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
    ]),
]);

card! {
    index: 1103,
    oracle_id: "6a6c5e17-6465-4a1f-9d63-8a3ce2edc522",
    scryfall_id: "c762f475-7e58-4477-839b-b3c55434b88f",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sulfur Falls",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
    ],
}
