//! Sunlit Marsh — (no cost) — Land — Plains Swamp
//! Oracle: ({T}: Add {W} or {B}.)
//! Oracle: This land enters tapped.
//! Set: SOC #409 — Secrets of Strixhaven Commander | Scryfall ID: fa447616-db24-4729-bf66-7f72aba0272d | Oracle ID: a5e5a259-5fa7-4b01-93cb-a2b4aaf80927
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1117,
    oracle_id: "a5e5a259-5fa7-4b01-93cb-a2b4aaf80927",
    scryfall_id: "fa447616-db24-4729-bf66-7f72aba0272d",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sunlit Marsh",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::PLAINS, subtypes::land::SWAMP],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
    ],
}
