//! Sunscorched Divide — (no cost) — Land
//! Oracle: {1}, {T}: Add {R}{W}.
//! Set: SOC #410 — Secrets of Strixhaven Commander | Scryfall ID: eae999f9-9c58-4609-8ade-aca0acf07519 | Oracle ID: 8d2b2675-19df-4f40-9e8e-196ec097b91c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1120,
    oracle_id: "8d2b2675-19df-4f40-9e8e-196ec097b91c",
    scryfall_id: "eae999f9-9c58-4609-8ade-aca0acf07519",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sunscorched Divide",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost { mana: baylee_core::mana!("{1}"), parts: &[CostPart::TapSelf] }, &[Effect::mana(ManaColor::Red, 1), Effect::mana(ManaColor::White, 1)]),
    ],
}
