//! TCRI Building — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {R}.
//! Set: TMT #189 — Teenage Mutant Ninja Turtles | Scryfall ID: 8817a1d6-ef39-4e7c-8277-74aea012803b | Oracle ID: 4139f40a-873b-4842-96a2-b7875de1c20a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1130,
    oracle_id: "4139f40a-873b-4842-96a2-b7875de1c20a",
    scryfall_id: "8817a1d6-ef39-4e7c-8277-74aea012803b",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "TCRI Building",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
    ],
}
