//! Temple of Malice — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {B} or {R}.
//! Set: FDN #701 — Foundations | Scryfall ID: d78eccc4-1500-43f1-94f5-b39c160b6381 | Oracle ID: 7c439c18-31dc-41fe-b03d-3fca06e6fc0b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1151,
    oracle_id: "7c439c18-31dc-41fe-b03d-3fca06e6fc0b",
    scryfall_id: "d78eccc4-1500-43f1-94f5-b39c160b6381",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Malice",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
