//! Temple of Mystery — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {G} or {U}.
//! Set: SOC #414 — Secrets of Strixhaven Commander | Scryfall ID: 258077cf-edef-40fe-ab46-03c965ebe990 | Oracle ID: 7e26f0b7-20e6-46d5-8130-d98c14d6aa29
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1152,
    oracle_id: "7e26f0b7-20e6-46d5-8130-d98c14d6aa29",
    scryfall_id: "258077cf-edef-40fe-ab46-03c965ebe990",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Mystery",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
