//! Temple of Plenty — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {G} or {W}.
//! Set: TDC #405 — Tarkir: Dragonstorm Commander | Scryfall ID: de1f7e5e-a503-4f99-91a1-2fdabb7d5e89 | Oracle ID: e521322b-0e83-458c-8936-7021a80ee279
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1153,
    oracle_id: "e521322b-0e83-458c-8936-7021a80ee279",
    scryfall_id: "de1f7e5e-a503-4f99-91a1-2fdabb7d5e89",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Plenty",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
    ],
}
