//! Temple of Enlightenment — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {W} or {U}.
//! Set: EOC #186 — Edge of Eternities Commander | Scryfall ID: dd139d4d-3a40-4015-93de-c838c64156c6 | Oracle ID: 89f43e27-790b-4ca1-8ba7-0882b31e0783
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1148,
    oracle_id: "89f43e27-790b-4ca1-8ba7-0882b31e0783",
    scryfall_id: "dd139d4d-3a40-4015-93de-c838c64156c6",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Enlightenment",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
    ],
}
