//! Temple of Triumph — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {R} or {W}.
//! Set: SOC #417 — Secrets of Strixhaven Commander | Scryfall ID: d0e763f7-25b8-444f-8722-614297d0663f | Oracle ID: 6f0d94d9-64bb-4175-83bc-301e8f79f54f
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1155,
    oracle_id: "6f0d94d9-64bb-4175-83bc-301e8f79f54f",
    scryfall_id: "d0e763f7-25b8-444f-8722-614297d0663f",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Triumph",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
    ],
}
