//! The Surgical Bay — (no cost) — Land — Sphere
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U}.
//! Oracle: {1}{U}, {T}, Sacrifice this land: Draw a card.
//! Set: ONE #260 — Phyrexia: All Will Be One | Scryfall ID: 1b49ec35-2c4f-4144-85fe-226f7cb67266 | Oracle ID: db9c155f-b342-41bb-9e1a-50358fb9f40e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1181,
    oracle_id: "db9c155f-b342-41bb-9e1a-50358fb9f40e",
    scryfall_id: "1b49ec35-2c4f-4144-85fe-226f7cb67266",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "The Surgical Bay",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SPHERE],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{U}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
