//! Thornglint Bridge — (no cost) — Artifact Land
//! Oracle: This land enters tapped.
//! Oracle: Indestructible
//! Oracle: {T}: Add {G} or {W}.
//! Set: MH2 #258 — Modern Horizons 2 | Scryfall ID: 9d483643-6a11-47f7-a0aa-190e0179525f | Oracle ID: 99720c65-be96-4220-8ed4-720660bf6928
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1185,
    oracle_id: "99720c65-be96-4220-8ed4-720660bf6928",
    scryfall_id: "9d483643-6a11-47f7-a0aa-190e0179525f",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    keywords: KeywordSet::INDESTRUCTIBLE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Thornglint Bridge",
        types: TypeSet::ARTIFACT.union(TypeSet::LAND),
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
    ],
}
