//! Thornwood Falls — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {G} or {U}.
//! Set: TDM #269 — Tarkir: Dragonstorm | Scryfall ID: ebb502c2-5fd0-46a9-b77d-010f4a942056 | Oracle ID: ec96cde2-f1e6-495c-94e2-3e8ae79e556c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1187,
    oracle_id: "ec96cde2-f1e6-495c-94e2-3e8ae79e556c",
    scryfall_id: "ebb502c2-5fd0-46a9-b77d-010f4a942056",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Thornwood Falls",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
