//! Timber Gorge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {G}.
//! Set: M19 #258 — Core Set 2019 | Scryfall ID: 07076412-18fe-4e15-bdb5-17111b4a66db | Oracle ID: 00b34fab-5a80-4a4d-b6cf-72479197677a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1200,
    oracle_id: "00b34fab-5a80-4a4d-b6cf-72479197677a",
    scryfall_id: "07076412-18fe-4e15-bdb5-17111b4a66db",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Timber Gorge",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
    ],
}
