//! Tournament Grounds — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {R}, {W}, or {B}. Spend this mana only to cast a Knight or Equipment spell.
//! Set: ELD #248 — Throne of Eldraine | Scryfall ID: cd438d51-a778-4b38-8b4b-a6a9cd9b4b22 | Oracle ID: a3ed5d7f-c554-4d46-86e5-7bb8df2693f6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SPEND1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::creature::KNIGHT),
    Filter::HasSubtype(subtypes::artifact::EQUIPMENT),
]);

card! {
    index: 1212,
    oracle_id: "a3ed5d7f-c554-4d46-86e5-7bb8df2693f6",
    scryfall_id: "cd438d51-a778-4b38-8b4b-a6a9cd9b4b22",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Tournament Grounds",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Red, ManaColor::White, ManaColor::Black]).restricted(&SPEND1, SpendRider::None)]),
    ],
}
