//! Tramway Station — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {R}.
//! Oracle: {2}{B}{R}, {T}, Sacrifice this land: Draw a card.
//! Set: SNC #258 — Streets of New Capenna | Scryfall ID: e0532304-da6d-45cd-b1e6-4779d3f3b2bc | Oracle ID: e90e519d-023e-4d19-85ad-9972a76df3ba
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1215,
    oracle_id: "e90e519d-023e-4d19-85ad-9972a76df3ba",
    scryfall_id: "e0532304-da6d-45cd-b1e6-4779d3f3b2bc",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Tramway Station",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
        activated!(Cost { mana: baylee_core::mana!("{2}{B}{R}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
