//! Tranquil Cove — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {W} or {U}.
//! Set: TDM #270 — Tarkir: Dragonstorm | Scryfall ID: 1c4efa6c-4f29-41cd-a728-bf0e479ace05 | Oracle ID: 5d641bf6-0f93-4189-8dc1-ec7ea446dade
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1216,
    oracle_id: "5d641bf6-0f93-4189-8dc1-ec7ea446dade",
    scryfall_id: "1c4efa6c-4f29-41cd-a728-bf0e479ace05",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Tranquil Cove",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
    ],
}
