//! Underground River — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {U} or {B}. This land deals 1 damage to you.
//! Set: DSC #321 — Duskmourn: House of Horror Commander | Scryfall ID: 5e50c8d5-6b22-4fc6-87ea-3d7d77ced17f | Oracle ID: 857febd9-cdd7-4f8e-a852-d88084b0cfbc
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1253,
    oracle_id: "857febd9-cdd7-4f8e-a852-d88084b0cfbc",
    scryfall_id: "5e50c8d5-6b22-4fc6-87ea-3d7d77ced17f",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Underground River",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black]), Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::You) }]),
    ],
}
