//! Volcanic Island — (no cost) — Land — Island Mountain
//! Oracle: ({T}: Add {U} or {R}.)
//! Set: VMA #324 — Vintage Masters | Scryfall ID: 2f607e7e-30c0-45e9-8f61-bf6e9fe63f2b | Oracle ID: c718911c-c955-4eb9-9e16-be4bd49a4e4e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1300,
    oracle_id: "c718911c-c955-4eb9-9e16-be4bd49a4e4e",
    scryfall_id: "2f607e7e-30c0-45e9-8f61-bf6e9fe63f2b",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Volcanic Island",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::ISLAND, subtypes::land::MOUNTAIN],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
    ],
}
