//! The four house decks, as card names.
//!
//! Their own file because they are 396 rows of content and the migration
//! beside them is about the schema. Names rather than indices, for the reason
//! `entity::deck` gives: a deck outlives the pool it was built against.
//!
//! Each list is the 99 cards beside the commander, which the migration names
//! separately — a commander is not in the deck, it starts in the command zone
//! (CR 903.3).

/// The Kenrith, the Returned King decklist, 99 cards beside the commander.
pub(super) const KENRITH: &[&str] = &[
    "1 Birds of Paradise",
    "1 Delighted Halfling",
    "1 Deathrite Shaman",
    "1 Bloom Tender",
    "1 Faeburrow Elder",
    "1 Devoted Druid",
    "1 Vizier of Remedies",
    "1 Emiel the Blessed",
    "1 Derevi, Empyrial Tactician",
    "1 Ranger-Captain of Eos",
    "1 Esper Sentinel",
    "1 Orcish Bowmasters",
    "1 Drannith Magistrate",
    "1 Grand Abolisher",
    "1 Spellseeker",
    "1 Theorist's Proxy",
    "1 Eternal Witness",
    "1 Endurance",
    "1 Solitude",
    "1 Recruiter of the Guard",
    "1 Academy Rector",
    "1 Gemrazer",
    "1 White Plume Adventurer",
    "1 Palace Jailer",
    "1 Thorin Oakenshield",
    "1 Fatehold Chronologist // Peer Review",
    "1 Fable of the Mirror-Breaker",
    "1 Invasion of Ikoria",
    "1 Finale of Devastation",
    "1 Green Sun's Zenith",
    "1 Chord of Calling",
    "1 Eldritch Evolution",
    "1 Demonic Tutor",
    "1 Vampiric Tutor",
    "1 Enlightened Tutor",
    "1 Worldly Tutor",
    "1 Swords to Plowshares",
    "1 Abrupt Decay",
    "1 Cyclonic Rift",
    "1 Force of Will",
    "1 Fierce Guardianship",
    "1 Swan Song",
    "1 Silence",
    "1 Veil of Summer",
    "1 Teferi's Protection",
    "1 Deflecting Swat",
    "1 Rhystic Study",
    "1 Mystic Remora",
    "1 Sylvan Library",
    "1 Survival of the Fittest",
    "1 Training Grounds",
    "1 Smothering Tithe",
    "1 Carpet of Flowers",
    "1 Sol Ring",
    "1 Mana Vault",
    "1 Chrome Mox",
    "1 Mox Diamond",
    "1 Lotus Petal",
    "1 Arcane Signet",
    "1 The One Ring",
    "1 Sensei's Divining Top",
    "1 Agatha's Soul Cauldron",
    "1 Swift Reconfiguration",
    "1 Neoform",
    "1 Arid Mesa",
    "1 Bloodstained Mire",
    "1 Flooded Strand",
    "1 Marsh Flats",
    "1 Misty Rainforest",
    "1 Polluted Delta",
    "1 Scalding Tarn",
    "1 Verdant Catacombs",
    "1 Windswept Heath",
    "1 Wooded Foothills",
    "1 Command Tower",
    "1 City of Brass",
    "1 Mana Confluence",
    "1 Exotic Orchard",
    "1 Reflecting Pool",
    "1 Ancient Tomb",
    "1 Gaea's Cradle",
    "1 Boseiju, Who Endures",
    "1 Otawara, Soaring City",
    "1 Gemstone Caverns",
    "1 Savannah",
    "1 Tropical Island",
    "1 Bayou",
    "1 Tundra",
    "1 Underground Sea",
    "1 Taiga",
    "1 Plateau",
    "1 Scrubland",
    "1 Volcanic Island",
    "1 Badlands",
    "1 Breeding Pool",
    "1 Temple Garden",
    "1 Forest",
    "1 Island",
    "1 Plains",
];

/// The Breya, Etherium Shaper decklist, 99 cards beside the commander.
pub(super) const BREYA: &[&str] = &[
    "1 Esper Sentinel",
    "1 Goblin Welder",
    "1 Goblin Engineer",
    "1 Emry, Lurker of the Loch",
    "1 Urza, Lord High Artificer",
    "1 Nettlecyst",
    "1 Arcbound Ravager",
    "1 Phyrexian Fleshgorger",
    "1 Oswald Fiddlebender",
    "1 Scrap Trawler",
    "1 Myr Retriever",
    "1 Borg Queen, Perfection Manifest",
    "1 Disciple of the Vault",
    "1 Marionette Apprentice",
    "1 Walking Ballista",
    "1 Phyrexian Metamorph",
    "1 Simulacrum Synthesizer",
    "1 Rabbit Battery",
    "1 Seven of Nine",
    "1 Thought Monitor",
    "1 Dwalin, Weaponmaster",
    "1 Sol Ring",
    "1 Mana Vault",
    "1 Grim Monolith",
    "1 Basalt Monolith",
    "1 Chrome Mox",
    "1 Mox Diamond",
    "1 Mox Opal",
    "1 Lotus Petal",
    "1 Lion's Eye Diamond",
    "1 Arcane Signet",
    "1 Talisman of Dominance",
    "1 Talisman of Progress",
    "1 Skullclamp",
    "1 Sensei's Divining Top",
    "1 The One Ring",
    "1 Time Sieve",
    "1 Thopter Foundry",
    "1 Sword of the Meek",
    "1 Ashnod's Altar",
    "1 Krark-Clan Ironworks",
    "1 Nim Deathmantle",
    "1 Grinding Station",
    "1 Wishclaw Talisman",
    "1 Aether Spellbomb",
    "1 Braided Net",
    "1 Chromatic Sphere",
    "1 Smuggler's Copter",
    "1 U.S.S. Enterprise-D, Galaxy-Class",
    "1 Mystic Forge",
    "1 Demonic Tutor",
    "1 Vampiric Tutor",
    "1 Enlightened Tutor",
    "1 Fabricate",
    "1 Reshape",
    "1 Whir of Invention",
    "1 Sevinne's Reclamation",
    "1 Dispatch",
    "1 Swords to Plowshares",
    "1 Cyclonic Rift",
    "1 Force of Will",
    "1 Fierce Guardianship",
    "1 Flusterstorm",
    "1 Silence",
    "1 Underworld Breach",
    "1 Rhystic Study",
    "1 Mystic Remora",
    "1 Arid Mesa",
    "1 Bloodstained Mire",
    "1 Flooded Strand",
    "1 Marsh Flats",
    "1 Misty Rainforest",
    "1 Polluted Delta",
    "1 Scalding Tarn",
    "1 Verdant Catacombs",
    "1 Windswept Heath",
    "1 Wooded Foothills",
    "1 Command Tower",
    "1 City of Brass",
    "1 Mana Confluence",
    "1 Exotic Orchard",
    "1 Ancient Tomb",
    "1 Gemstone Caverns",
    "1 Urza's Saga",
    "1 Inventors' Fair",
    "1 Academy Ruins",
    "1 Buried Ruin",
    "1 Seat of the Synod",
    "1 Vault of Whispers",
    "1 Ancient Den",
    "1 Great Furnace",
    "1 Darksteel Citadel",
    "1 Tundra",
    "1 Underground Sea",
    "1 Volcanic Island",
    "1 Scrubland",
    "1 Badlands",
    "1 Plateau",
    "1 Island",
];

/// The Kess, Dissident Mage decklist, 99 cards beside the commander.
pub(super) const KESS: &[&str] = &[
    "1 Thassa's Oracle",
    "1 Spellseeker",
    "1 Stingcaster Mage",
    "1 Dualcaster Mage",
    "1 Opposition Agent",
    "1 Orcish Bowmasters",
    "1 Dauthi Voidwalker",
    "1 Ledger Shredder",
    "1 Birgi, God of Storytelling",
    "1 Storm-Kiln Artist",
    "1 Ragavan, Nimble Pilferer",
    "1 Dragon's Rage Channeler",
    "1 Malevolent Hermit",
    "1 Brazen Borrower",
    "1 Sol Ring",
    "1 Mana Vault",
    "1 Chrome Mox",
    "1 Mox Diamond",
    "1 Lotus Petal",
    "1 Lion's Eye Diamond",
    "1 Arcane Signet",
    "1 Wishclaw Talisman",
    "1 The One Ring",
    "1 Necropotence",
    "1 Rhystic Study",
    "1 Mystic Remora",
    "1 Underworld Breach",
    "1 Demonic Consultation",
    "1 Tainted Pact",
    "1 Brain Freeze",
    "1 Ad Nauseam",
    "1 Demonic Tutor",
    "1 Vampiric Tutor",
    "1 Mystical Tutor",
    "1 Gamble",
    "1 Intuition",
    "1 Dark Ritual",
    "1 Cabal Ritual",
    "1 Jeska's Will",
    "1 Rite of Flame",
    "1 Brainstorm",
    "1 Geist of Saint Thalia",
    "1 Open Communications",
    "1 Gitaxian Probe",
    "1 Faithless Looting",
    "1 Frantic Search",
    "1 Windfall",
    "1 Wheel of Fortune",
    "1 Expressive Iteration",
    "1 Treasure Cruise",
    "1 Dig Through Time",
    "1 Past in Flames",
    "1 Mizzix's Mastery",
    "1 Yawgmoth's Will",
    "1 Force of Will",
    "1 Force of Negation",
    "1 Fierce Guardianship",
    "1 Pact of Negation",
    "1 Flusterstorm",
    "1 Swan Song",
    "1 Mental Misstep",
    "1 Deflecting Swat",
    "1 Deadly Rollick",
    "1 Cyclonic Rift",
    "1 Fire // Ice",
    "1 Borne Upon a Wind",
    "1 Sudden Spoiling",
    "1 Twinflame",
    "1 Arid Mesa",
    "1 Bloodstained Mire",
    "1 Flooded Strand",
    "1 Marsh Flats",
    "1 Misty Rainforest",
    "1 Polluted Delta",
    "1 Scalding Tarn",
    "1 Verdant Catacombs",
    "1 Cephalid Coliseum",
    "1 Wooded Foothills",
    "1 Command Tower",
    "1 City of Brass",
    "1 Mana Confluence",
    "1 Exotic Orchard",
    "1 Ancient Tomb",
    "1 Gemstone Caverns",
    "1 Underground Sea",
    "1 Volcanic Island",
    "1 Badlands",
    "1 Watery Grave",
    "1 Steam Vents",
    "1 Blood Crypt",
    "1 Undercity Sewers",
    "1 Thundering Falls",
    "1 Raucous Theater",
    "1 Otawara, Soaring City",
    "1 Takenuma, Abandoned Mire",
    "1 Island",
    "1 Snow-Covered Island",
    "1 Swamp",
    "1 Mountain",
];

/// The Tayam, Luminous Enigma decklist, 99 cards beside the commander.
pub(super) const TAYAM: &[&str] = &[
    "1 Birds of Paradise",
    "1 Delighted Halfling",
    "1 Deathrite Shaman",
    "1 Llanowar Elves",
    "1 Elvish Mystic",
    "1 Brad Boimler, Eager Ensign",
    "1 Avacyn's Pilgrim",
    "1 Devoted Druid",
    "1 Wall of Roots",
    "1 Bloom Tender",
    "1 Rishkar, Peema Renegade",
    "1 Quirion Ranger",
    "1 Scryb Ranger",
    "1 Viscera Seer",
    "1 Carrion Feeder",
    "1 Yawgmoth, Thran Physician",
    "1 Zulaport Cutthroat",
    "1 Blood Artist",
    "1 Young Wolf",
    "1 Strangleroot Geist",
    "1 Safehold Elite",
    "1 Kitchen Finks",
    "1 Mikaeus, the Unhallowed",
    "1 Hapatra, Vizier of Poisons",
    "1 Scavenging Ooze",
    "1 Esper Sentinel",
    "1 Drannith Magistrate",
    "1 Archon of Emeria",
    "1 Spirit of the Labyrinth",
    "1 Collector Ouphe",
    "1 Aven Mindcensor",
    "1 Grand Abolisher",
    "1 Ranger-Captain of Eos",
    "1 Recruiter of the Guard",
    "1 Eternal Witness",
    "1 Renegade Rallier",
    "1 Saffi Eriksdotter",
    "1 Liliana the Repentant",
    "1 Stitcher's Supplier",
    "1 Golgari Thug",
    "1 Hermit Druid",
    "1 Gravecrawler",
    "1 Lotleth Troll",
    "1 Walking Ballista",
    "1 Lotus Cobra",
    "1 Endurance",
    "1 Lake-town Lookout",
    "1 Luminous Broodmoth",
    "1 Sol Ring",
    "1 Mox Diamond",
    "1 Chrome Mox",
    "1 Skullclamp",
    "1 Agatha's Soul Cauldron",
    "1 Earthcraft",
    "1 Survival of the Fittest",
    "1 Sylvan Library",
    "1 Grist, the Hunger Tide",
    "1 Eladamri's Call",
    "1 Enlightened Tutor",
    "1 Vampiric Tutor",
    "1 Demonic Tutor",
    "1 Chord of Calling",
    "1 Green Sun's Zenith",
    "1 Finale of Devastation",
    "1 Swords to Plowshares",
    "1 Abrupt Decay",
    "1 Arid Mesa",
    "1 Bloodstained Mire",
    "1 Flooded Strand",
    "1 Marsh Flats",
    "1 Misty Rainforest",
    "1 Polluted Delta",
    "1 Urza's Saga",
    "1 Verdant Catacombs",
    "1 Windswept Heath",
    "1 Wooded Foothills",
    "1 Command Tower",
    "1 City of Brass",
    "1 Mana Confluence",
    "1 Exotic Orchard",
    "1 Gaea's Cradle",
    "1 Boseiju, Who Endures",
    "1 Takenuma, Abandoned Mire",
    "1 Gemstone Caverns",
    "1 Ancient Tomb",
    "1 Bayou",
    "1 Savannah",
    "1 Scrubland",
    "1 Overgrown Tomb",
    "1 Temple Garden",
    "1 Godless Shrine",
    "1 Nurturing Peatland",
    "1 Horizon Canopy",
    "1 Silent Clearing",
    "1 Dryad Arbor",
    "1 Phyrexian Tower",
    "1 Forest",
    "1 Plains",
    "1 Swamp",
];
