//! The six account-side tables, and the indexes the gateway's own queries ask
//! for.
//!
//! # Indexes are cut to the questions, not to the columns
//!
//! Every index here exists because a route runs a query that would otherwise
//! be a sequential scan:
//!
//! - Signing in looks an account up by e-mail, case-insensitively, so the
//!   index is on `lower(email)` — an index on the plain column is not
//!   usable by that comparison and would be a scan that looked like it was
//!   covered. A display name is *not* unique and needs no index at all;
//!   what distinguishes two players called Alice is `account.tag`, whose
//!   own uniqueness comes with the identity column.
//! - A session token and a confirmation link are found by their hash, which
//!   is the primary key, so neither needs an index of its own. What both need
//!   is one on `expires_at`, because the sweep that removes lapsed rows is
//!   the only query that does not name a key.
//! - A deck list is "this account's decks, newest first", which is one index
//!   on `(account_id, updated_at DESC)` and no sort.
//!
//! The foreign keys are all `ON DELETE CASCADE`, which is the whole of
//! account deletion: one `DELETE` and the decks, sessions, links, answers and
//! settings go with it.

use sea_orm_migration::prelude::*;
use sea_orm_migration::schema::{
    array, big_integer, binary, boolean, integer, json_binary, pk_uuid, text, text_null,
    timestamp_with_time_zone, timestamp_with_time_zone_null, uuid,
};

/// The first migration.
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        accounts(manager).await?;
        credentials(manager).await?;
        decks(manager).await?;
        preferences(manager).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Children before the parent: the cascades would do it, but a
        // rollback that relied on them would drop `account` and take five
        // tables with it whether or not this migration made them.
        for table in [
            ClientSettings::Table.into_iden(),
            StandingAnswer::Table.into_iden(),
            Deck::Table.into_iden(),
            Confirmation::Table.into_iden(),
            SessionToken::Table.into_iden(),
            Account::Table.into_iden(),
        ] {
            manager
                .drop_table(Table::drop().table(table).if_exists().to_owned())
                .await?;
        }
        Ok(())
    }
}

/// The account table, the address that is unique and the name that is not.
async fn accounts(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Account::Table)
                .if_not_exists()
                // Minted by the database. See the crate doc: a `UUIDv7` is
                // ordered by the clock of whoever made it, and two gateways
                // have two clocks.
                .col(pk_uuid(Account::Id).default(Expr::cust("uuidv7()")))
                .col(text(Account::Email))
                .col(text(Account::DisplayName))
                // The discriminator: what tells two players called Alice
                // apart. `BY DEFAULT` rather than `ALWAYS` because
                // `ALWAYS` refuses an explicit value outright, and a
                // restore from `pg_dump` writes every column explicitly.
                // Nothing in the gateway supplies one — a tag handed out
                // by hand would not move the sequence and would collide
                // with a later registration.
                .col(
                    integer(Account::Tag)
                        .extra("GENERATED BY DEFAULT AS IDENTITY")
                        .unique_key(),
                )
                .col(text(Account::PasswordHash))
                .col(timestamp_with_time_zone(Account::CreatedAt))
                .col(timestamp_with_time_zone_null(Account::ConfirmedAt))
                .col(text(Account::Lang).default(""))
                .to_owned(),
        )
        .await?;

    // Uniqueness that means what a person means by it: two accounts whose
    // addresses differ only in case are one address.
    //
    // A display name has no such index, and that is the point of the tag.
    // A globally unique name is a race every popular name loses — the
    // twentieth Alice registers as `Alice_2004` and stays that way — and it
    // leaks: a registration refused for a taken name says that name exists,
    // which is exactly the enumeration everything else in this route works
    // to prevent. `Alice#3f0a` and `Alice#af03` are two people, and the
    // number is the account's own, not the name's.
    manager
        .create_index(
            Index::create()
                .name("account_email_lower")
                .table(Account::Table)
                .unique()
                .col(Func::lower(Expr::col(Account::Email)))
                .to_owned(),
        )
        .await?;
    Ok(())
}

/// Sessions and confirmation links: the two tables keyed by the hash of a
/// secret, and the expiry indexes their sweeps stand on.
async fn credentials(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(SessionToken::Table)
                .if_not_exists()
                // A digest, stored as the bytes it is. `text` was sixty-four
                // hex characters for thirty-two bytes of hash, in a column
                // that would have taken `hello`.
                .col(binary(SessionToken::TokenHash).primary_key())
                .col(uuid(SessionToken::AccountId))
                .col(timestamp_with_time_zone(SessionToken::ExpiresAt))
                .foreign_key(&mut cascade_to_account(
                    "session_token_account",
                    SessionToken::Table,
                    SessionToken::AccountId,
                ))
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(Confirmation::Table)
                .if_not_exists()
                .col(binary(Confirmation::TokenHash).primary_key())
                .col(uuid(Confirmation::AccountId))
                .col(timestamp_with_time_zone(Confirmation::ExpiresAt))
                .foreign_key(&mut cascade_to_account(
                    "confirmation_account",
                    Confirmation::Table,
                    Confirmation::AccountId,
                ))
                .to_owned(),
        )
        .await?;

    // The sweeps. Both tables are read by key on every other path, so
    // expiry is the one query with nothing to stand on.
    manager
        .create_index(
            Index::create()
                .name("session_token_expiry")
                .table(SessionToken::Table)
                .col(SessionToken::ExpiresAt)
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("confirmation_expiry")
                .table(Confirmation::Table)
                .col(Confirmation::ExpiresAt)
                .to_owned(),
        )
        .await?;
    // Resending a link invalidates the last one, which is a delete by
    // account rather than by hash.
    manager
        .create_index(
            Index::create()
                .name("confirmation_account_id")
                .table(Confirmation::Table)
                .col(Confirmation::AccountId)
                .to_owned(),
        )
        .await?;
    Ok(())
}

/// Decks, and the one index that answers "mine, newest first" in order.
async fn decks(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Deck::Table)
                .if_not_exists()
                .col(pk_uuid(Deck::Id).default(Expr::cust("uuidv7()")))
                .col(uuid(Deck::AccountId))
                .col(text(Deck::Name))
                .col(array(Deck::Cards, ColumnType::Text))
                .col(array(Deck::Sideboard, ColumnType::Text).default(Expr::cust("'{}'")))
                .col(text_null(Deck::Commander))
                .col(text_null(Deck::Sleeve))
                .col(text_null(Deck::Playmat))
                .col(timestamp_with_time_zone(Deck::UpdatedAt))
                .foreign_key(&mut cascade_to_account(
                    "deck_account",
                    Deck::Table,
                    Deck::AccountId,
                ))
                .to_owned(),
        )
        .await?;

    // "My decks, newest first" in index order, with no sort on top.
    manager
        .create_index(
            Index::create()
                .name("deck_account_recent")
                .table(Deck::Table)
                .col(Deck::AccountId)
                .col((Deck::UpdatedAt, IndexOrder::Desc))
                .to_owned(),
        )
        .await?;

    Ok(())
}

/// What an account remembers: standing answers, and the client's own
/// preferences document.
async fn preferences(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(StandingAnswer::Table)
                .if_not_exists()
                .col(uuid(StandingAnswer::AccountId))
                .col(big_integer(StandingAnswer::Card))
                .col(big_integer(StandingAnswer::Ability))
                .col(boolean(StandingAnswer::Yes))
                .primary_key(
                    Index::create()
                        .col(StandingAnswer::AccountId)
                        .col(StandingAnswer::Card)
                        .col(StandingAnswer::Ability),
                )
                .foreign_key(&mut cascade_to_account(
                    "standing_answer_account",
                    StandingAnswer::Table,
                    StandingAnswer::AccountId,
                ))
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(ClientSettings::Table)
                .if_not_exists()
                .col(uuid(ClientSettings::AccountId).primary_key())
                .col(json_binary(ClientSettings::Doc))
                .col(timestamp_with_time_zone(ClientSettings::UpdatedAt))
                .foreign_key(&mut cascade_to_account(
                    "client_settings_account",
                    ClientSettings::Table,
                    ClientSettings::AccountId,
                ))
                .to_owned(),
        )
        .await?;
    Ok(())
}

/// One child-to-account reference, cascading.
fn cascade_to_account<T, C>(name: &str, table: T, column: C) -> ForeignKeyCreateStatement
where
    T: IntoIden + 'static,
    C: IntoIden + 'static,
{
    ForeignKey::create()
        .name(name)
        .from(table, column)
        .to(Account::Table, Account::Id)
        .on_delete(ForeignKeyAction::Cascade)
        .to_owned()
}

#[derive(DeriveIden)]
enum Account {
    Table,
    Id,
    Email,
    DisplayName,
    Tag,
    PasswordHash,
    CreatedAt,
    ConfirmedAt,
    Lang,
}

#[derive(DeriveIden)]
enum SessionToken {
    Table,
    TokenHash,
    AccountId,
    ExpiresAt,
}

#[derive(DeriveIden)]
enum Confirmation {
    Table,
    TokenHash,
    AccountId,
    ExpiresAt,
}

#[derive(DeriveIden)]
enum Deck {
    Table,
    Id,
    AccountId,
    Name,
    Cards,
    Sideboard,
    Commander,
    Sleeve,
    Playmat,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum StandingAnswer {
    Table,
    AccountId,
    Card,
    Ability,
    Yes,
}

#[derive(DeriveIden)]
enum ClientSettings {
    Table,
    AccountId,
    Doc,
    UpdatedAt,
}
