//! Aven Brigadier — {3}{W}{W}{W} — Creature — Bird Soldier
//! Oracle: Flying
//! Oracle: Other Bird creatures get +1/+1.
//! Oracle: Other Soldier creatures get +1/+1.
//! Set: ONS #7 — Onslaught | Scryfall ID: da24ef56-8d54-4146-97e9-4abded807545 | Oracle ID: 910ae0ca-257d-4b45-b039-f26e7b2f3d5c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AVEN_BRIGADIER,
    oracle_id = "910ae0ca-257d-4b45-b039-f26e7b2f3d5c",
    scryfall_id = "da24ef56-8d54-4146-97e9-4abded807545",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aven Brigadier",
        mana_cost = mana!("{3}{W}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD, subtypes::creature::SOLDIER],
        power = Some(3),
        toughness = Some(5),
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::BIRD),
                Filter::Another
            ]),
            Modifier::ModifyPT(1, 1)
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::SOLDIER),
                Filter::Another
            ]),
            Modifier::ModifyPT(1, 1)
        ),
    ],
);
