//! Craw Wurm — {4}{G}{G} — Creature — Wurm
//! Set: M10 #173 — Magic 2010 | Scryfall ID: 3875f73d-6108-488b-bd34-4cf2c23ce6b3 | Oracle ID: 6a462a69-3e42-41de-a3aa-a488d9f38d69
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CRAW_WURM,
    oracle_id = "6a462a69-3e42-41de-a3aa-a488d9f38d69",
    scryfall_id = "3875f73d-6108-488b-bd34-4cf2c23ce6b3",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Craw Wurm",
        mana_cost = mana!("{4}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(6),
        toughness = Some(4),
    ),],
);
