//! Dakkon Blackblade — {2}{W}{U}{U}{B} — Legendary Creature — Human Warrior
//! Oracle: Dakkon Blackblade's power and toughness are each equal to the number of lands you control.
//! Set: ME1 #143 — Masters Edition | Scryfall ID: 235bbf86-02ad-497b-b698-e60930bbde9c | Oracle ID: 1aa78e3b-bf7e-4645-9521-4b3537c93f46
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DAKKON_BLACKBLADE,
    oracle_id = "1aa78e3b-bf7e-4645-9521-4b3537c93f46",
    scryfall_id = "235bbf86-02ad-497b-b698-e60930bbde9c",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue, Color::White]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dakkon Blackblade",
        mana_cost = mana!("{2}{W}{U}{U}{B}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WARRIOR],
        power = Some(0),
        toughness = Some(0),
    ),],
    abilities = &[static_ability!(
        Filter::This,
        Modifier::CharacteristicPT {
            count: PtCount::YouControl(&Filter::YOUR_LAND),
            toughness_plus: 0
        }
    ),],
);
