//! Grassland Crusader — {5}{W} — Creature — Human Cleric Soldier
//! Oracle: {T}: Target Elf or Soldier creature gets +2/+2 until end of turn.
//! Set: ONS #32 — Onslaught | Scryfall ID: c129f361-8769-4f9a-9745-eb5d0c085b88 | Oracle ID: b4cff81a-0c60-417d-acf9-2170ebdbea14
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::CREATURE,
        Filter::HasSubtype(subtypes::creature::ELF),
    ]),
    Filter::And(&[
        Filter::CREATURE,
        Filter::HasSubtype(subtypes::creature::SOLDIER),
    ]),
]);

card!(
    index = index::GRASSLAND_CRUSADER,
    oracle_id = "b4cff81a-0c60-417d-acf9-2170ebdbea14",
    scryfall_id = "c129f361-8769-4f9a-9745-eb5d0c085b88",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Grassland Crusader",
        mana_cost = mana!("{5}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::CLERIC,
            subtypes::creature::SOLDIER
        ],
        power = Some(2),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::PumpTarget {
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
