//! Gruul Nodorog — {4}{G}{G} — Creature — Beast
//! Oracle: {R}: This creature gains menace until end of turn. (It can't be blocked except by two or more creatures.)
//! Set: GPT #88 — Guildpact | Scryfall ID: 9855ce83-ae26-4b1d-ab7f-637cde09d679 | Oracle ID: 68fc3611-8d82-4f87-ab50-603790a27455
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GRUUL_NODOROG,
    oracle_id = "68fc3611-8d82-4f87-ab50-603790a27455",
    scryfall_id = "9855ce83-ae26-4b1d-ab7f-637cde09d679",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gruul Nodorog",
        mana_cost = mana!("{4}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BEAST],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{R}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::MENACE,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
