//! Jerrard of the Closed Fist — {3}{R}{G}{G} — Legendary Creature — Human Knight
//! Set: ME3 #154 — Masters Edition III | Scryfall ID: 621d4d0b-bcff-4855-bbaf-7aeeabeafe99 | Oracle ID: fd20576d-4abe-4af8-ac53-ab9356593fe7
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::JERRARD_OF_THE_CLOSED_FIST,
    oracle_id = "fd20576d-4abe-4af8-ac53-ab9356593fe7",
    scryfall_id = "621d4d0b-bcff-4855-bbaf-7aeeabeafe99",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Jerrard of the Closed Fist",
        mana_cost = mana!("{3}{R}{G}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::KNIGHT],
        power = Some(6),
        toughness = Some(5),
    ),],
);
