//! Kamahl, Pit Fighter — {4}{R}{R} — Legendary Creature — Human Barbarian
//! Oracle: Haste (This creature can attack and {T} as soon as it comes under your control.)
//! Oracle: {T}: Kamahl deals 3 damage to any target.
//! Set: DDS #39 — Duel Decks: Mind vs. Might | Scryfall ID: 7a65dd4d-f838-4964-bd5a-a517960cc644 | Oracle ID: 153bb46f-ee8a-4da3-aab4-ae884f6ff403
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KAMAHL_PIT_FIGHTER,
    oracle_id = "153bb46f-ee8a-4da3-aab4-ae884f6ff403",
    scryfall_id = "7a65dd4d-f838-4964-bd5a-a517960cc644",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::HASTE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kamahl, Pit Fighter",
        mana_cost = mana!("{4}{R}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::BARBARIAN],
        power = Some(6),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DealDamage {
            amount: Amount::Fixed(3),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
