//! Kavu Mauler — {4}{G}{G} — Creature — Kavu
//! Oracle: Trample
//! Oracle: Whenever this creature attacks, it gets +1/+1 until end of turn for each other attacking Kavu.
//! Set: APC #80 — Apocalypse | Scryfall ID: 79adc3af-5fa3-4cb6-9bbc-52ede0c69263 | Oracle ID: 6ffbcaba-5437-4fb6-a2d6-e94b1e6dc1d2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COUNT1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::KAVU),
    Filter::Attacking,
    Filter::Another,
]);

card!(
    index = index::KAVU_MAULER,
    oracle_id = "6ffbcaba-5437-4fb6-a2d6-e94b1e6dc1d2",
    scryfall_id = "79adc3af-5fa3-4cb6-9bbc-52ede0c69263",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kavu Mauler",
        mana_cost = mana!("{4}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KAVU],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::CountOf {
                filter: &COUNT1,
                zone: ZoneSel::Battlefield
            },
            toughness: Amount::CountOf {
                filter: &COUNT1,
                zone: ZoneSel::Battlefield
            },
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
