//! Phyrexian Gargantua — {4}{B}{B} — Creature — Phyrexian Horror
//! Oracle: When this creature enters, you draw two cards and you lose 2 life.
//! Set: CMM #178 — Commander Masters | Scryfall ID: 08648c0a-e075-45ac-ad8c-80c425d3487e | Oracle ID: a3925dfd-62b0-44ef-8545-7bee92cad5a2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PHYREXIAN_GARGANTUA,
    oracle_id = "a3925dfd-62b0-44ef-8545-7bee92cad5a2",
    scryfall_id = "08648c0a-e075-45ac-ad8c-80c425d3487e",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Phyrexian Gargantua",
        mana_cost = mana!("{4}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::HORROR],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[
            Effect::draw(2),
            Effect::LoseLife {
                amount: Amount::Fixed(2),
                target: PlayerRel::You
            }
        ]
    ),],
);
