//! Scaled Hulk — {5}{G} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, this creature gets +2/+2 until end of turn.
//! Set: BOK #143 — Betrayers of Kamigawa | Scryfall ID: 3b27457e-2c40-4983-9680-b7292db4c668 | Oracle ID: ce4570eb-f637-45d1-afbc-f11357c09bf9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::SCALED_HULK,
    oracle_id = "ce4570eb-f637-45d1-afbc-f11357c09bf9",
    scryfall_id = "3b27457e-2c40-4983-9680-b7292db4c668",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Scaled Hulk",
        mana_cost = mana!("{5}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
