//! Sire of the Storm — {4}{U}{U} — Creature — Spirit
//! Oracle: Flying
//! Oracle: Whenever you cast a Spirit or Arcane spell, you may draw a card.
//! Set: VOC #113 — Crimson Vow Commander | Scryfall ID: bea64c04-6cd0-49e9-b4ba-1b50aab0a490 | Oracle ID: 68f1db12-82fb-4bf1-908d-db38fd67efe5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::SIRE_OF_THE_STORM,
    oracle_id = "68f1db12-82fb-4bf1-908d-db38fd67efe5",
    scryfall_id = "bea64c04-6cd0-49e9-b4ba-1b50aab0a490",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sire of the Storm",
        mana_cost = mana!("{4}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::MayDo {
            effects: &[Effect::draw(1)]
        }]
    ),],
);
