//! Tangle Spider — {4}{G}{G} — Creature — Spider
//! Oracle: Flash (You may cast this spell any time you could cast an instant.)
//! Oracle: Reach (This creature can block creatures with flying.)
//! Set: 10E #303 — Tenth Edition | Scryfall ID: 8f1e75e1-a827-46c1-896f-cd8fbdf79fa8 | Oracle ID: 597bd341-c5a0-47a3-9864-1fccab8a2a00
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TANGLE_SPIDER,
    oracle_id = "597bd341-c5a0-47a3-9864-1fccab8a2a00",
    scryfall_id = "8f1e75e1-a827-46c1-896f-cd8fbdf79fa8",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FLASH.union(KeywordSet::REACH),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tangle Spider",
        mana_cost = mana!("{4}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIDER],
        power = Some(3),
        toughness = Some(4),
    ),],
);
