//! Yavimaya Wurm — {4}{G}{G} — Creature — Wurm
//! Oracle: Trample (This creature can deal excess combat damage to the player or planeswalker it's attacking.)
//! Set: M11 #200 — Magic 2011 | Scryfall ID: 4516b135-3691-4be5-ab73-91fbdc6b24b6 | Oracle ID: 93514874-41e8-49e7-8935-d06e852dd1e3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::YAVIMAYA_WURM,
    oracle_id = "93514874-41e8-49e7-8935-d06e852dd1e3",
    scryfall_id = "4516b135-3691-4be5-ab73-91fbdc6b24b6",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Yavimaya Wurm",
        mana_cost = mana!("{4}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(6),
        toughness = Some(4),
    ),],
);
