//! Alabaster Potion — {X}{W}{W} — Instant
//! Oracle: Choose one —
//! Oracle: • Target player gains X life.
//! Oracle: • Prevent the next X damage that would be dealt to any target this turn.
//! Set: ME3 #2 — Masters Edition III | Scryfall ID: 8ce1f383-258d-4fa1-a3c7-3424bb2e568c | Oracle ID: 2fcca686-03c8-4407-9f9f-2b7462470044
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ALABASTER_POTION,
    oracle_id = "2fcca686-03c8-4407-9f9f-2b7462470044",
    scryfall_id = "8ce1f383-258d-4fa1-a3c7-3424bb2e568c",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Alabaster Potion",
        mana_cost = mana!("{X}{W}{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[AbilityDef::ModalSpell {
        choose: ModeCount::ONE,
        modes: &[
            mode!(
                &[Effect::GainLifeFor {
                    amount: Amount::X,
                    who: PlayerRel::Chosen
                }],
                targets = Some(TargetReq::one(TargetSpec::AnyPlayer))
            ),
            mode!(
                &[Effect::PreventNextDamage {
                    target: TargetSpec::AnyTarget,
                    amount: Amount::X
                }],
                targets = Some(TargetReq::one(TargetSpec::AnyTarget))
            )
        ]
    },],
);
