//! Disenchant — {1}{W} — Instant
//! Oracle: Destroy target artifact or enchantment.
//! Set: FDN #572 — Foundations | Scryfall ID: 7ac43e16-8b14-46f2-877a-600ea918766b | Oracle ID: a7e97fa9-4b72-4548-b854-5be5f18a6f1a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DISENCHANT,
    oracle_id = "a7e97fa9-4b72-4548-b854-5be5f18a6f1a",
    scryfall_id = "7ac43e16-8b14-46f2-877a-600ea918766b",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Disenchant",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(
            &Filter::ARTIFACT_OR_ENCHANTMENT
        ))],
        targets = Some(TargetReq::one(TargetSpec::Object(
            &Filter::ARTIFACT_OR_ENCHANTMENT
        )))
    ),],
);
