//! Eladamri's Call — {G}{W} — Instant
//! Oracle: Search your library for a creature card, reveal that card, put it into your hand, then shuffle.
//! Set: MH1 #197 — Modern Horizons | Scryfall ID: ea751fe2-b64a-4265-8885-a9016b29b5b3 | Oracle ID: 4acb6612-54e8-428d-acb6-c7259a5ad6a8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ELADAMRI_S_CALL,
    oracle_id = "4acb6612-54e8-428d-acb6-c7259a5ad6a8",
    scryfall_id = "ea751fe2-b64a-4265-8885-a9016b29b5b3",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Eladamri's Call",
        mana_cost = mana!("{G}{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &Filter::CREATURE,
        finds: &[Find::HAND],
        optional: false
    }]),],
);
