//! Flowstone Strike — {1}{R} — Instant
//! Oracle: Target creature gets +1/-1 and gains haste until end of turn.
//! Set: NEM #84 — Nemesis | Scryfall ID: a1203053-0829-4f46-a361-62cb9cd17280 | Oracle ID: d67048eb-eaf1-4b5b-a8e3-a004bab438f3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::FLOWSTONE_STRIKE,
    oracle_id = "d67048eb-eaf1-4b5b-a8e3-a004bab438f3",
    scryfall_id = "a1203053-0829-4f46-a361-62cb9cd17280",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Flowstone Strike",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::Fixed(1),
            toughness: Amount::NegXFixed(1),
            keywords: KeywordSet::HASTE,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
