//! Hisoka's Defiance — {1}{U} — Instant
//! Oracle: Counter target Spirit or Arcane spell.
//! Set: CHK #67 — Champions of Kamigawa | Scryfall ID: 09fd4d01-1204-46a3-b237-45c37985acac | Oracle ID: 2ac6f1c7-f4c5-4d45-9644-da49d8fe4758
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::creature::SPIRIT),
    Filter::HasSubtype(subtypes::spell::ARCANE),
]);

card!(
    index = index::HISOKA_S_DEFIANCE,
    oracle_id = "2ac6f1c7-f4c5-4d45-9644-da49d8fe4758",
    scryfall_id = "09fd4d01-1204-46a3-b237-45c37985acac",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Hisoka's Defiance",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::CounterTargetSpell],
        targets = Some(TargetReq::one(TargetSpec::Spell(&TARGET1)))
    ),],
);
