//! Hoodwink — {1}{U} — Instant
//! Oracle: Return target artifact, enchantment, or land to its owner's hand.
//! Set: MMQ #84 — Mercadian Masques | Scryfall ID: 8d505fbb-ec85-475b-a0e1-6670627ec017 | Oracle ID: a2fe10b8-857e-4881-85ef-24a0f96a3d79
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::Or(&[Filter::ARTIFACT, Filter::ENCHANTMENT, Filter::LAND]);

card!(
    index = index::HOODWINK,
    oracle_id = "a2fe10b8-857e-4881-85ef-24a0f96a3d79",
    scryfall_id = "8d505fbb-ec85-475b-a0e1-6670627ec017",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Hoodwink",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::bounce(TargetSpec::Object(&TARGET1))],
        targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
    ),],
);
