//! Mage's Guile — {1}{U} — Instant
//! Oracle: Target creature gains shroud until end of turn. (It can't be the target of spells or abilities.)
//! Oracle: Cycling {U} ({U}, Discard this card: Draw a card.)
//! Set: ONS #91 — Onslaught | Scryfall ID: 301cb538-a931-4916-927b-4986046b1158 | Oracle ID: f371cdaf-7ab8-4555-8c96-61dfbf8c0179
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MAGE_S_GUILE,
    oracle_id = "f371cdaf-7ab8-4555-8c96-61dfbf8c0179",
    scryfall_id = "301cb538-a931-4916-927b-4986046b1158",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mage's Guile",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{U}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::SHROUD,
                duration: Duration::UntilEndOfTurn
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
    ],
);
