//! Magma Jet — {1}{R} — Instant
//! Oracle: Magma Jet deals 2 damage to any target. Scry 2.
//! Set: JMP #346 — Jumpstart | Scryfall ID: 2975ce11-589a-4da8-a016-854bbaeb869c | Oracle ID: 2f292253-64d3-4cf2-881f-a3eea4fda388
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MAGMA_JET,
    oracle_id = "2f292253-64d3-4cf2-881f-a3eea4fda388",
    scryfall_id = "2975ce11-589a-4da8-a016-854bbaeb869c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Magma Jet",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::DealDamage {
                amount: Amount::Fixed(2),
                target: TargetSpec::AnyTarget
            },
            Effect::scry(2)
        ],
        targets = Some(TargetReq::one(TargetSpec::AnyTarget))
    ),],
);
