//! Tel-Jilad Justice — {1}{G} — Instant
//! Oracle: Destroy target artifact. Scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)
//! Set: 5DN #95 — Fifth Dawn | Scryfall ID: 99fefa37-c876-4039-8cc4-4b2138181a1d | Oracle ID: 6c853b95-3d98-44fd-b05a-02d05d5eb0b8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TEL_JILAD_JUSTICE,
    oracle_id = "6c853b95-3d98-44fd-b05a-02d05d5eb0b8",
    scryfall_id = "99fefa37-c876-4039-8cc4-4b2138181a1d",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tel-Jilad Justice",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT)),
            Effect::scry(2)
        ],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
    ),],
);
