//! Terminate — {B}{R} — Instant
//! Oracle: Destroy target creature. It can't be regenerated.
//! Set: MSC #189 — Marvel Super Heroes Commander | Scryfall ID: 379ffc67-4142-4ead-a871-0f851523745e | Oracle ID: 6257c2fd-005f-41e3-8a72-af76df1eb134
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TERMINATE,
    oracle_id = "6257c2fd-005f-41e3-8a72-af76df1eb134",
    scryfall_id = "379ffc67-4142-4ead-a871-0f851523745e",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Terminate",
        mana_cost = mana!("{B}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(&Filter::CREATURE))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
