//! Wipe Clean — {1}{W} — Instant
//! Oracle: Exile target enchantment.
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: SCG #26 — Scourge | Scryfall ID: cf7c14c9-cb5a-49f0-be2c-eb3166f02510 | Oracle ID: f5cbc4f3-4e73-405f-9daf-e5b7c73fa6ee
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::WIPE_CLEAN,
    oracle_id = "f5cbc4f3-4e73-405f-9daf-e5b7c73fa6ee",
    scryfall_id = "cf7c14c9-cb5a-49f0-be2c-eb3166f02510",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wipe Clean",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{3}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::exile(TargetSpec::Object(&Filter::ENCHANTMENT))],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ENCHANTMENT)))
        ),
    ],
);
