//! Command Bridge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, sacrifice it unless you tap an untapped permanent you control.
//! Oracle: {T}: Add one mana of any color.
//! Set: EOE #252 — Edge of Eternities | Scryfall ID: 247670d2-a7cd-4ed7-9c77-704c7962b815 | Oracle ID: 87c8e1ed-258a-4a89-bcc6-211405e49692
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::COMMAND_BRIDGE,
    oracle_id = "87c8e1ed-258a-4a89-bcc6-211405e49692",
    scryfall_id = "247670d2-a7cd-4ed7-9c77-704c7962b815",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Command Bridge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::TapOther(&Filter::ControlledByYou),
                effect: &Effect::SacrificeSelf
            }]
        ),
        mana_ability!(&[Effect::mana_of_any_color()]),
    ],
);
