//! Conservatory — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {W}.
//! Oracle: {4}, {T}: Investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
//! Set: CLU #14 — Ravnica: Clue Edition | Scryfall ID: 8bab22c5-4742-4f2e-bda1-26c72b09cd9c | Oracle ID: 8f88b0bf-81bd-4223-9dad-d8c49ff4b87a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::CONSERVATORY,
    oracle_id = "8f88b0bf-81bd-4223-9dad-d8c49ff4b87a",
    scryfall_id = "8bab22c5-4742-4f2e-bda1-26c72b09cd9c",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Conservatory",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::CLUE
            }]
        ),
    ],
);
