//! Coral Atoll — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, sacrifice it unless you return an untapped Island you control to its owner's hand.
//! Oracle: {T}: Add {C}{U}.
//! Set: CMR #480 — Commander Legends | Scryfall ID: 77e3ea71-ea9f-4bbf-93cb-0f6339f8a3ab | Oracle ID: 3f347ebf-e0d2-4ae0-ad84-df7a460404e0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::Untapped,
    Filter::ControlledByYou,
]);

card!(
    index = index::CORAL_ATOLL,
    oracle_id = "3f347ebf-e0d2-4ae0-ad84-df7a460404e0",
    scryfall_id = "77e3ea71-ea9f-4bbf-93cb-0f6339f8a3ab",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Coral Atoll",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::ReturnToHand(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
        mana_ability!(&[
            Effect::mana(ManaColor::Colorless, 1),
            Effect::mana(ManaColor::Blue, 1)
        ]),
    ],
);
