//! Crumbling Vestige — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, add one mana of any color.
//! Oracle: {T}: Add {C}. ({C} represents colorless mana.)
//! Set: OGW #170 — Oath of the Gatewatch | Scryfall ID: d491c13c-43e3-4ca3-b888-4edd34dfe14a | Oracle ID: 3c1fe86a-3696-4634-bc26-cd45846529ec
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card! {
    index: 389,
    oracle_id: "3c1fe86a-3696-4634-bc26-cd45846529ec",
    scryfall_id: "d491c13c-43e3-4ca3-b888-4edd34dfe14a",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Crumbling Vestige",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::mana_of_any_color()]),
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
    ],
}
