//! Dwarven Mine — (no cost) — Land — Mountain
//! Oracle: ({T}: Add {R}.)
//! Oracle: This land enters tapped unless you control three or more other Mountains.
//! Oracle: When this land enters untapped, create a 1/1 red Dwarf creature token.
//! Set: ELD #243 — Throne of Eldraine | Scryfall ID: 5c83074d-0c9b-4b58-94ca-d75240485579 | Oracle ID: 74ed0bd3-ac31-41a4-8220-d8e7c8c1c437
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::MOUNTAIN),
    Filter::ControlledByYou,
    Filter::Another,
]);

static TRIGGER2: Filter = Filter::And(&[Filter::This, Filter::Untapped]);

card!(
    index = index::DWARVEN_MINE,
    oracle_id = "74ed0bd3-ac31-41a4-8220-d8e7c8c1c437",
    scryfall_id = "5c83074d-0c9b-4b58-94ca-d75240485579",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dwarven Mine",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::MOUNTAIN],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK1,
            at_least: 3
        }],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        triggered!(
            Trigger::EntersBattlefield(&TRIGGER2),
            &[Effect::CreateToken {
                token: &generated_tokens::DWARF_1_1_RED
            }]
        ),
    ],
);
