//! Everglades — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, sacrifice it unless you return an untapped Swamp you control to its owner's hand.
//! Oracle: {T}: Add {C}{B}.
//! Set: C14 #294 — Commander 2014 | Scryfall ID: 5f82ffe7-c5a2-453d-9820-3c576b6f263c | Oracle ID: ef3b8b0c-cea7-4bae-934c-9c65fd64245d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::Untapped,
    Filter::ControlledByYou,
]);

card!(
    index = index::EVERGLADES,
    oracle_id = "ef3b8b0c-cea7-4bae-934c-9c65fd64245d",
    scryfall_id = "5f82ffe7-c5a2-453d-9820-3c576b6f263c",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Everglades",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Colorless, 1),
            Effect::mana(ManaColor::Black, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::ReturnToHand(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
    ],
);
