//! Foundry of the Consuls — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {5}, {T}, Sacrifice this land: Create two 1/1 colorless Thopter artifact creature tokens with flying.
//! Set: C18 #248 — Commander 2018 | Scryfall ID: 09d83c1d-6916-48e7-8a0d-b5abadc34b2a | Oracle ID: 0498ea14-53d9-4655-a616-0ff3cf73de4e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::FOUNDRY_OF_THE_CONSULS,
    oracle_id = "0498ea14-53d9-4655-a616-0ff3cf73de4e",
    scryfall_id = "09d83c1d-6916-48e7-8a0d-b5abadc34b2a",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Foundry of the Consuls",
        types = TypeSet::LAND,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{5}", TapSelf, SacrificeSelf),
            &[Effect::CreateTokenN {
                token: &generated_tokens::THOPTER_ARTIFACT_1_1_FLYING,
                amount: Amount::Fixed(2)
            }]
        ),
    ],
);
