//! Griffin Canyon — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Untap target Griffin. If it's a creature, it gets +1/+1 until end of turn.
//! Set: VIS #163 — Visions | Scryfall ID: 705d8194-3ad0-41b7-ae32-9c0cd8cd46b9 | Oracle ID: ba642c8b-9ade-4501-8393-672fd53d4955
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::HasSubtype(subtypes::creature::GRIFFIN);

card! {
    index: 580,
    oracle_id: "ba642c8b-9ade-4501-8393-672fd53d4955",
    scryfall_id: "705d8194-3ad0-41b7-ae32-9c0cd8cd46b9",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Griffin Canyon",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost::TAP, &[Effect::UntapTarget, Effect::PumpTarget { power: Amount::Fixed(1), toughness: Amount::Fixed(1), keywords: KeywordSet::EMPTY, duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
