//! Hidden Grotto — (no cost) — Land
//! Oracle: When this land enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add one mana of any color.
//! Set: BLB #254 — Bloomburrow | Scryfall ID: 4ba8f2e7-8357-4862-97dc-1942d066023a | Oracle ID: 382d18a2-438e-4ae7-a83f-1658ef1f9b07
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HIDDEN_GROTTO,
    oracle_id = "382d18a2-438e-4ae7-a83f-1658ef1f9b07",
    scryfall_id = "4ba8f2e7-8357-4862-97dc-1942d066023a",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Hidden Grotto", types = TypeSet::LAND,),],
    abilities = &[
        triggered!(Trigger::ETB, &[Effect::surveil(1)]),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(cost!("{1}", TapSelf), &[Effect::mana_of_any_color()]),
    ],
);
