//! High Market — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice a creature: You gain 1 life.
//! Set: SOC #380 — Secrets of Strixhaven Commander | Scryfall ID: 894aa6b6-0d08-4c43-8734-9cb7b31359c6 | Oracle ID: 86fb3749-37d6-48a6-8524-71e996850307
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HIGH_MARKET,
    oracle_id = "86fb3749-37d6-48a6-8524-71e996850307",
    scryfall_id = "894aa6b6-0d08-4c43-8734-9cb7b31359c6",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "High Market", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::gain_life(1)]
        ),
    ],
);
