//! Jungle Basin — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, sacrifice it unless you return an untapped Forest you control to its owner's hand.
//! Oracle: {T}: Add {C}{G}.
//! Set: CMR #484 — Commander Legends | Scryfall ID: d4929e39-fccc-450b-bb18-f5ad56a397bd | Oracle ID: f922f90a-b1a2-4630-9266-40726ca89f74
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::FOREST),
    Filter::Untapped,
    Filter::ControlledByYou,
]);

card!(
    index = index::JUNGLE_BASIN,
    oracle_id = "f922f90a-b1a2-4630-9266-40726ca89f74",
    scryfall_id = "d4929e39-fccc-450b-bb18-f5ad56a397bd",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Jungle Basin",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Colorless, 1),
            Effect::mana(ManaColor::Green, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::ReturnToHand(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
    ],
);
