//! Keldon Necropolis — (no cost) — Legendary Land
//! Oracle: {T}: Add {C}.
//! Oracle: {4}{R}, {T}, Sacrifice a creature: Keldon Necropolis deals 2 damage to any target.
//! Set: VMA #300 — Vintage Masters | Scryfall ID: 8d168f4d-e8f1-459f-a507-93730ddd20a4 | Oracle ID: ea4d6fcd-21e0-4e9f-b406-a89042998d98
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::KELDON_NECROPOLIS,
    oracle_id = "ea4d6fcd-21e0-4e9f-b406-a89042998d98",
    scryfall_id = "8d168f4d-e8f1-459f-a507-93730ddd20a4",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Keldon Necropolis",
        types = TypeSet::LAND,
        supertypes = SupertypeSet::LEGENDARY,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{4}{R}", TapSelf, Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::DealDamage {
                amount: Amount::Fixed(2),
                target: TargetSpec::AnyTarget
            }],
            target = Some(TargetSpec::AnyTarget)
        ),
    ],
);
