//! Kitchen — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {U}.
//! Oracle: {4}, {T}: Investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
//! Set: CLU #17 — Ravnica: Clue Edition | Scryfall ID: 4388ae8f-a2c4-4e0d-a6a1-0204ff3f469b | Oracle ID: 47f71408-5509-4651-9121-fd0867adae00
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::KITCHEN,
    oracle_id = "47f71408-5509-4651-9121-fd0867adae00",
    scryfall_id = "4388ae8f-a2c4-4e0d-a6a1-0204ff3f469b",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kitchen",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::CLUE
            }]
        ),
    ],
);
