//! Lounge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {G}.
//! Oracle: {4}, {T}: Investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
//! Set: CLU #19 — Ravnica: Clue Edition | Scryfall ID: 4b197079-488d-47c6-a494-8baf36c48667 | Oracle ID: 98a22879-d0b2-441f-bcf6-a67b4552b73c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::LOUNGE,
    oracle_id = "98a22879-d0b2-441f-bcf6-a67b4552b73c",
    scryfall_id = "4b197079-488d-47c6-a494-8baf36c48667",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lounge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::CLUE
            }]
        ),
    ],
);
