//! Memorial to Glory — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {3}{W}, {T}, Sacrifice this land: Create two 1/1 white Soldier creature tokens.
//! Set: DOM #244 — Dominaria | Scryfall ID: 564d6ff1-2be1-42f1-a919-fe8c2e148c3f | Oracle ID: eb8ec34c-ae07-4a09-940f-ee965146a787
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::MEMORIAL_TO_GLORY,
    oracle_id = "eb8ec34c-ae07-4a09-940f-ee965146a787",
    scryfall_id = "564d6ff1-2be1-42f1-a919-fe8c2e148c3f",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Memorial to Glory",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(
            cost!("{3}{W}", TapSelf, SacrificeSelf),
            &[Effect::CreateTokenN {
                token: &generated_tokens::SOLDIER_1_1_WHITE,
                amount: Amount::Fixed(2)
            }]
        ),
    ],
);
