//! Nephalia Drownyard — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}{U}{B}, {T}: Target player mills three cards.
//! Set: LCC #344 — The Lost Caverns of Ixalan Commander | Scryfall ID: fe2e25b7-f950-482b-9e35-266b1278a71a | Oracle ID: 6429b4ed-1845-4643-9a3d-85f7c12f2bba
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card! {
    index: 809,
    oracle_id: "6429b4ed-1845-4643-9a3d-85f7c12f2bba",
    scryfall_id: "fe2e25b7-f950-482b-9e35-266b1278a71a",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Nephalia Drownyard",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{U}{B}"), parts: &[CostPart::TapSelf] }, &[Effect::Mill { amount: Amount::Fixed(3), target: PlayerRel::You }], target: Some(TargetSpec::AnyPlayer)),
    ],
}
