//! Orzhova, the Church of Deals — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {3}{W}{B}, {T}: Target player loses 1 life and you gain 1 life.
//! Set: GPT #162 — Guildpact | Scryfall ID: 9015cc09-56c9-4d8f-b241-a0cfaec7e1f1 | Oracle ID: 8551a9cf-c54b-42d4-92d6-550f4890a3d7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ORZHOVA_THE_CHURCH_OF_DEALS,
    oracle_id = "8551a9cf-c54b-42d4-92d6-550f4890a3d7",
    scryfall_id = "9015cc09-56c9-4d8f-b241-a0cfaec7e1f1",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Orzhova, the Church of Deals",
        types = TypeSet::LAND,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{3}{W}{B}", TapSelf),
            &[
                Effect::LoseLife {
                    amount: Amount::Fixed(1),
                    target: PlayerRel::Chosen
                },
                Effect::GainLife {
                    amount: Amount::Fixed(1)
                }
            ],
            target = Some(TargetSpec::AnyPlayer)
        ),
    ],
);
