//! Rupture Spire — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, sacrifice it unless you pay {1}.
//! Oracle: {T}: Add one mana of any color.
//! Set: CMR #355 — Commander Legends | Scryfall ID: c7ef4b15-efab-4255-ac2d-7794f253aa52 | Oracle ID: 7eadffcb-1e15-44c1-b1db-78c71b8ec1ce
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RUPTURE_SPIRE,
    oracle_id = "7eadffcb-1e15-44c1-b1db-78c71b8ec1ce",
    scryfall_id = "c7ef4b15-efab-4255-ac2d-7794f253aa52",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rupture Spire",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayOr {
                player: PlayerRel::You,
                mana: Amount::Fixed(1),
                effect: &Effect::SacrificeSelf
            }]
        ),
        mana_ability!(&[Effect::mana_of_any_color()]),
    ],
);
