//! Seaside Haven — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {W}{U}, {T}, Sacrifice a Bird: Draw a card.
//! Set: ONS #323 — Onslaught | Scryfall ID: 9c940a6b-3c5e-4ce2-92b6-63e2cb575c15 | Oracle ID: 4adc39dd-8de1-4298-947c-ff666ec3adeb
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::BIRD),
    Filter::ControlledByYou,
]);

card!(
    index = index::SEASIDE_HAVEN,
    oracle_id = "4adc39dd-8de1-4298-947c-ff666ec3adeb",
    scryfall_id = "9c940a6b-3c5e-4ce2-92b6-63e2cb575c15",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Seaside Haven", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{W}{U}", TapSelf, Sacrifice(&COST1)),
            &[Effect::draw(1)]
        ),
    ],
);
