//! Secret Passage — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {B}.
//! Oracle: {4}, {T}: Investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
//! Set: CLU #20 — Ravnica: Clue Edition | Scryfall ID: 6b35ede8-e882-46fd-9eda-9d6f64c73ea1 | Oracle ID: c6a46fc2-fc8f-4dcd-bca7-682abfbf303d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::SECRET_PASSAGE,
    oracle_id = "c6a46fc2-fc8f-4dcd-bca7-682abfbf303d",
    scryfall_id = "6b35ede8-e882-46fd-9eda-9d6f64c73ea1",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Secret Passage",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::CLUE
            }]
        ),
    ],
);
