//! Skarrg, the Rage Pits — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {R}{G}, {T}: Target creature gets +1/+1 and gains trample until end of turn.
//! Set: PCA #127 — Planechase Anthology | Scryfall ID: 3340d094-fe13-4087-abba-27e8c9a7f3c7 | Oracle ID: 92bac34e-2045-4331-842f-185711c1ac56
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::CREATURE;

card! {
    index: 1039,
    oracle_id: "92bac34e-2045-4331-842f-185711c1ac56",
    scryfall_id: "3340d094-fe13-4087-abba-27e8c9a7f3c7",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Skarrg, the Rage Pits",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{R}{G}"), parts: &[CostPart::TapSelf] }, &[Effect::PumpTarget { power: Amount::Fixed(1), toughness: Amount::Fixed(1), keywords: KeywordSet::TRAMPLE, duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
