//! Slayers' Stronghold — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {R}{W}, {T}: Target creature gets +2/+0 and gains vigilance and haste until end of turn.
//! Set: MKC #295 — Murders at Karlov Manor Commander | Scryfall ID: 3b2c82ea-6793-407c-ac9f-5fc14d4d09ea | Oracle ID: 2de7367b-a5a4-43f4-8f8f-b931ea28150d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::CREATURE;

card! {
    index: 1048,
    oracle_id: "2de7367b-a5a4-43f4-8f8f-b931ea28150d",
    scryfall_id: "3b2c82ea-6793-407c-ac9f-5fc14d4d09ea",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Slayers' Stronghold",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{R}{W}"), parts: &[CostPart::TapSelf] }, &[Effect::PumpTarget { power: Amount::Fixed(2), toughness: Amount::Fixed(0), keywords: KeywordSet::VIGILANCE.union(KeywordSet::HASTE), duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
