//! Soaring Seacliff — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, target creature gains flying until end of turn.
//! Oracle: {T}: Add {U}.
//! Set: C20 #315 — Commander 2020 | Scryfall ID: 651a1a4f-bdaa-44d6-ac45-050894788063 | Oracle ID: a37544b6-0048-4213-8e40-76ba8a0b6d1b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::CREATURE;

card! {
    index: 1061,
    oracle_id: "a37544b6-0048-4213-8e40-76ba8a0b6d1b",
    scryfall_id: "651a1a4f-bdaa-44d6-ac45-050894788063",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Soaring Seacliff",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Blue, 1)]),
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::PumpTarget { power: Amount::Fixed(0), toughness: Amount::Fixed(0), keywords: KeywordSet::FLYING, duration: Duration::UntilEndOfTurn }], targets: Some(TargetReq::one(TargetSpec::Object(&TARGET1)))),
    ],
}
