//! Spawning Bed — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {6}, {T}, Sacrifice this land: Create three 1/1 colorless Eldrazi Scion creature tokens. They have "Sacrifice this token: Add {C}."
//! Set: BFZ #248 — Battle for Zendikar | Scryfall ID: e3a532b2-de88-40af-8961-b01eada05bd3 | Oracle ID: 49e43de3-460b-4562-aef6-da43bd56debc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPAWNING_BED,
    oracle_id = "49e43de3-460b-4562-aef6-da43bd56debc",
    scryfall_id = "e3a532b2-de88-40af-8961-b01eada05bd3",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Spawning Bed", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{6}", TapSelf, SacrificeSelf),
            &[Effect::CreateTokenN {
                token: &generated_tokens::ELDRAZI_SCION_1_1,
                amount: Amount::Fixed(3)
            }]
        ),
    ],
);
