//! Study — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {U}.
//! Oracle: {4}, {T}: Investigate. (Create a Clue token. It's an artifact with "{2}, Sacrifice this token: Draw a card.")
//! Set: CLU #21 — Ravnica: Clue Edition | Scryfall ID: c694bc39-3eae-4b40-8f85-34785f9e75f1 | Oracle ID: 7ffadb3f-0b88-416f-b1a1-876383c22720
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::STUDY,
    oracle_id = "7ffadb3f-0b88-416f-b1a1-876383c22720",
    scryfall_id = "c694bc39-3eae-4b40-8f85-34785f9e75f1",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Study",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::CLUE
            }]
        ),
    ],
);
