//! Sun-Blessed Peak — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {W}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #280 — Avatar: The Last Airbender | Scryfall ID: ae04c862-095f-41d2-8aef-21036d5a0cdc | Oracle ID: d188a397-c7d9-4f16-bc21-d9e1b5ffc951
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1107,
    oracle_id: "d188a397-c7d9-4f16-bc21-d9e1b5ffc951",
    scryfall_id: "ae04c862-095f-41d2-8aef-21036d5a0cdc",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sun-Blessed Peak",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
