//! Urza's Factory — (no cost) — Land — Urza's
//! Oracle: {T}: Add {C}.
//! Oracle: {7}, {T}: Create a 2/2 colorless Assembly-Worker artifact creature token.
//! Set: TSR #288 — Time Spiral Remastered | Scryfall ID: d03f17f1-b0fd-4b84-82ea-085c2f87eeda | Oracle ID: 5a620d20-f14e-43d0-8e57-c2a197e2ec51
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::URZA_S_FACTORY,
    oracle_id = "5a620d20-f14e-43d0-8e57-c2a197e2ec51",
    scryfall_id = "d03f17f1-b0fd-4b84-82ea-085c2f87eeda",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Urza's Factory",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::URZA_S],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{7}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::ASSEMBLY_WORKER_ARTIFACT_2_2
            }]
        ),
    ],
);
