//! Vitu-Ghazi, the City-Tree — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}{G}{W}, {T}: Create a 1/1 green Saproling creature token.
//! Set: AFC #272 — Forgotten Realms Commander | Scryfall ID: 33145080-077e-4231-96ca-e8b1852b6380 | Oracle ID: 88fb9e82-28b9-4275-a1e2-cb3a9bfda127
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

card!(
    index = index::VITU_GHAZI_THE_CITY_TREE,
    oracle_id = "88fb9e82-28b9-4275-a1e2-cb3a9bfda127",
    scryfall_id = "33145080-077e-4231-96ca-e8b1852b6380",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vitu-Ghazi, the City-Tree",
        types = TypeSet::LAND,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{2}{G}{W}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::SAPROLING_1_1_GREEN
            }]
        ),
    ],
);
