//! Triskelion — {6} — Artifact Creature — Construct
//! Oracle: This creature enters with three +1/+1 counters on it.
//! Oracle: Remove a +1/+1 counter from this creature: It deals 1 damage to any target.
//! Set: MOC #387 — March of the Machine Commander | Scryfall ID: 63349fa3-4462-413c-bd96-bbc1049165a0 | Oracle ID: 74f67dcf-5afb-45aa-8d4b-3cdb23f6f2a1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TRISKELION,
    oracle_id = "74f67dcf-5afb-45aa-8d4b-3cdb23f6f2a1",
    scryfall_id = "63349fa3-4462-413c-bd96-bbc1049165a0",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Triskelion",
        mana_cost = mana!("{6}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::CONSTRUCT],
        power = Some(1),
        toughness = Some(1),
        enter_modifiers = &[EnterModifier::WithCounters {
            kind: CounterKind::P1P1,
            amount: Amount::Fixed(3)
        }],
    ),],
    abilities = &[activated!(
        cost!(RemoveCounterSelf {
            kind: CounterKind::P1P1,
            n: 1
        }),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
