//! Diamond Kaleidoscope — {4} — Artifact
//! Oracle: {3}, {T}: Create a 0/1 colorless Prism artifact creature token.
//! Oracle: Sacrifice a Prism token: Add one mana of any color.
//! Set: VIS #143 — Visions | Scryfall ID: 548ff852-274d-4068-818d-58a883e74a5f | Oracle ID: bffa9256-aff4-476f-86f4-4f4c9e57fa69
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::PRISM),
    Filter::IsToken,
    Filter::ControlledByYou,
]);

card!(
    index = index::DIAMOND_KALEIDOSCOPE,
    oracle_id = "bffa9256-aff4-476f-86f4-4f4c9e57fa69",
    scryfall_id = "548ff852-274d-4068-818d-58a883e74a5f",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Diamond Kaleidoscope",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(
            cost!("{3}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::PRISM_ARTIFACT_0_1
            }]
        ),
        mana_ability!(cost!(Sacrifice(&COST1)), &[Effect::mana_of_any_color()]),
    ],
);
