//! Dingus Egg — {4} — Artifact
//! Oracle: Whenever a land is put into a graveyard from the battlefield, this artifact deals 2 damage to that land's controller.
//! Set: 8ED #297 — Eighth Edition | Scryfall ID: 30d893a2-400c-459d-a26d-31f1f3b0642e | Oracle ID: 1973f1e9-aa14-49dc-bafe-be17b30ba288
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DINGUS_EGG,
    oracle_id = "1973f1e9-aa14-49dc-bafe-be17b30ba288",
    scryfall_id = "30d893a2-400c-459d-a26d-31f1f3b0642e",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dingus Egg",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::LAND),
        &[Effect::DealDamage {
            amount: Amount::Fixed(2),
            target: TargetSpec::Player(PlayerRel::ControllerOfEvent)
        }]
    ),],
);
