//! Nevinyrral's Disk — {4} — Artifact
//! Oracle: This artifact enters tapped.
//! Oracle: {1}, {T}: Destroy all artifacts, creatures, and enchantments.
//! Set: CMM #965 — Commander Masters | Scryfall ID: 36fb6ee3-bd54-4e5b-b055-c2c42515c162 | Oracle ID: 96230edf-568a-47dd-b877-9d92aa58fac8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::NEVINYRRAL_S_DISK,
    oracle_id = "96230edf-568a-47dd-b877-9d92aa58fac8",
    scryfall_id = "36fb6ee3-bd54-4e5b-b055-c2c42515c162",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Nevinyrral's Disk",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[activated!(
        cost!("{1}", TapSelf),
        &[Effect::destroy_all(
            &Filter::ARTIFACT_CREATURE_OR_ENCHANTMENT
        )]
    ),],
);
