//! Staff of Zegon — {4} — Artifact
//! Oracle: {3}, {T}: Target creature gets -2/-0 until end of turn.
//! Set: ME4 #229 — Masters Edition IV | Scryfall ID: 397a16db-dcba-4fca-a58b-438e43d7d574 | Oracle ID: 52c53132-146a-4912-8e0f-1d4d9937fff3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STAFF_OF_ZEGON,
    oracle_id = "52c53132-146a-4912-8e0f-1d4d9937fff3",
    scryfall_id = "397a16db-dcba-4fca-a58b-438e43d7d574",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Staff of Zegon",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{3}", TapSelf),
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
