//! Tawnos's Wand — {4} — Artifact
//! Oracle: {2}, {T}: Target creature with power 2 or less can't be blocked this turn.
//! Set: ME4 #231 — Masters Edition IV | Scryfall ID: 9ee3ed1a-8475-4f6c-a800-1affd9eed86a | Oracle ID: 2138533a-d33c-477a-9765-7369d1ec30b0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::And(&[Filter::CREATURE, Filter::PowerAtMost(2)]);

card!(
    index = index::TAWNOS_S_WAND,
    oracle_id = "2138533a-d33c-477a-9765-7369d1ec30b0",
    scryfall_id = "9ee3ed1a-8475-4f6c-a800-1affd9eed86a",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tawnos's Wand",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(
        cost!("{2}", TapSelf),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::UNBLOCKABLE,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
