//! Thran Dynamo — {4} — Artifact
//! Oracle: {T}: Add {C}{C}{C}.
//! Set: CMM #415 — Commander Masters | Scryfall ID: 7ce5f12e-fc02-42f8-a5ca-b523050d4650 | Oracle ID: a699c663-8131-4045-9265-a83e86609374
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THRAN_DYNAMO,
    oracle_id = "a699c663-8131-4045-9265-a83e86609374",
    scryfall_id = "7ce5f12e-fc02-42f8-a5ca-b523050d4650",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thran Dynamo",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Colorless, 3)]),],
);
