//! Tower of Eons — {4} — Artifact
//! Oracle: {8}, {T}: You gain 10 life.
//! Set: MRD #266 — Mirrodin | Scryfall ID: 0eb67150-53e4-4164-bea5-dd3659469b8e | Oracle ID: 74a71bbd-c307-481c-b0cf-70e24b0c8ad4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TOWER_OF_EONS,
    oracle_id = "74a71bbd-c307-481c-b0cf-70e24b0c8ad4",
    scryfall_id = "0eb67150-53e4-4164-bea5-dd3659469b8e",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tower of Eons",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[activated!(cost!("{8}", TapSelf), &[Effect::gain_life(10)]),],
);
