//! Ur-Golem's Eye — {4} — Artifact
//! Oracle: {T}: Add {C}{C}.
//! Set: C14 #280 — Commander 2014 | Scryfall ID: 7a2ea921-8ef9-4a31-b484-73375e828d34 | Oracle ID: fb34fc00-e60d-41fc-9393-ca4248ec0a1c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::UR_GOLEM_S_EYE,
    oracle_id = "fb34fc00-e60d-41fc-9393-ca4248ec0a1c",
    scryfall_id = "7a2ea921-8ef9-4a31-b484-73375e828d34",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ur-Golem's Eye",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Colorless, 2)]),],
);
