//! Wand of the Elements — {4} — Artifact
//! Oracle: {T}, Sacrifice an Island: Create a 2/2 blue Elemental creature token with flying.
//! Oracle: {T}, Sacrifice a Mountain: Create a 3/3 red Elemental creature token.
//! Set: DST #158 — Darksteel | Scryfall ID: 1131c187-8fc3-4cee-9422-355ef6622de7 | Oracle ID: b4931b44-815e-40b5-b239-682d350f3347
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::ControlledByYou,
]);

static COST2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::MOUNTAIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::WAND_OF_THE_ELEMENTS,
    oracle_id = "b4931b44-815e-40b5-b239-682d350f3347",
    scryfall_id = "1131c187-8fc3-4cee-9422-355ef6622de7",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wand of the Elements",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(
            cost!(TapSelf, Sacrifice(&COST1)),
            &[Effect::CreateToken {
                token: &generated_tokens::ELEMENTAL_2_2_BLUE_FLYING
            }]
        ),
        activated!(
            cost!(TapSelf, Sacrifice(&COST2)),
            &[Effect::CreateToken {
                token: &generated_tokens::ELEMENTAL_3_3_RED
            }]
        ),
    ],
);
