//! Weakstone — {4} — Artifact
//! Oracle: Attacking creatures get -1/-0.
//! Set: ME4 #239 — Masters Edition IV | Scryfall ID: 5029bc71-29bf-47cf-a64b-7ab3d9af39ca | Oracle ID: 004584f8-fd89-4a3e-9782-c117dbe1532b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::WEAKSTONE,
    oracle_id = "004584f8-fd89-4a3e-9782-c117dbe1532b",
    scryfall_id = "5029bc71-29bf-47cf-a64b-7ab3d9af39ca",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Weakstone",
        mana_cost = mana!("{4}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[static_ability!(
        Filter::ATTACKING_CREATURE,
        Modifier::ModifyPT(-1, 0)
    ),],
);
