//! Scavenged Weaponry — {2}{B} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: When this Aura enters, draw a card.
//! Oracle: Enchanted creature gets +1/+1.
//! Set: INV #123 — Invasion | Scryfall ID: 4e8072a9-2699-4c6c-9556-67d91bd67a4b | Oracle ID: 2d3010d5-5c21-4342-ad79-a737b6731230
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SCAVENGED_WEAPONRY,
    oracle_id = "2d3010d5-5c21-4342-ad79-a737b6731230",
    scryfall_id = "4e8072a9-2699-4c6c-9556-67d91bd67a4b",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Scavenged Weaponry",
        mana_cost = mana!("{2}{B}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 1)
        ),
        triggered!(Trigger::ETB, &[Effect::draw(1)]),
    ],
);
