//! Sunder from Within — {2}{R}{R} — Sorcery — Arcane
//! Oracle: Destroy target artifact or land.
//! Set: SOK #117 — Saviors of Kamigawa | Scryfall ID: 46783ba7-6e23-43d0-b5aa-9a0ea75cfb67 | Oracle ID: 09f75f28-09b9-4a6e-a1b0-671208d274d3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[Filter::ARTIFACT, Filter::LAND]);

card!(
    index = index::SUNDER_FROM_WITHIN,
    oracle_id = "09f75f28-09b9-4a6e-a1b0-671208d274d3",
    scryfall_id = "46783ba7-6e23-43d0-b5aa-9a0ea75cfb67",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sunder from Within",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::SORCERY,
        subtypes = &[subtypes::spell::ARCANE],
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(&TARGET1))],
        targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
    ),],
);
