//! Touch of Brilliance — {3}{U} — Sorcery
//! Oracle: Draw two cards.
//! Set: S99 #57 — Starter 1999 | Scryfall ID: bddd159a-6a42-465c-afcc-69ad6695f35a | Oracle ID: 6365aba1-78d3-416c-89cd-9449578eedbf
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TOUCH_OF_BRILLIANCE,
    oracle_id = "6365aba1-78d3-416c-89cd-9449578eedbf",
    scryfall_id = "bddd159a-6a42-465c-afcc-69ad6695f35a",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Touch of Brilliance",
        mana_cost = mana!("{3}{U}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::draw(2)]),],
);
