//! Castle Ardenvale — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Plains.
//! Oracle: {T}: Add {W}.
//! Oracle: {2}{W}{W}, {T}: Create a 1/1 white Human creature token.
//! Set: TDC #346 — Tarkir: Dragonstorm Commander | Scryfall ID: 65e4de2e-47d2-4967-be31-9df0057a9c74 | Oracle ID: f8f4fc60-725d-46d8-8e8f-e68e00d20589
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::ControlledByYou,
]);

card!(
    index = index::CASTLE_ARDENVALE,
    oracle_id = "f8f4fc60-725d-46d8-8e8f-e68e00d20589",
    scryfall_id = "65e4de2e-47d2-4967-be31-9df0057a9c74",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Castle Ardenvale",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK1)],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(
            cost!("{2}{W}{W}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::HUMAN_1_1_WHITE
            }]
        ),
    ],
);
