//! Castle Locthwain — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Swamp.
//! Oracle: {T}: Add {B}.
//! Oracle: {1}{B}{B}, {T}: Draw a card, then you lose life equal to the number of cards in your hand.
//! Set: CLB #884 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 19336e3a-2242-4a30-a563-32f2e4fc18e9 | Oracle ID: be811e70-aaaa-41f3-bf9e-5d3f9f719b49
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::HasSubtype(subtypes::land::SWAMP),
]);

card! {
    index: 336,
    oracle_id: "be811e70-aaaa-41f3-bf9e-5d3f9f719b49",
    scryfall_id: "19336e3a-2242-4a30-a563-32f2e4fc18e9",
    color_identity: ColorSet::from_slice(&[Color::Black]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Castle Locthwain",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{B}{B}"), parts: &[CostPart::TapSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
