//! Drowned Catacomb — (no cost) — Land
//! Oracle: This land enters tapped unless you control an Island or a Swamp.
//! Oracle: {T}: Add {U} or {B}.
//! Set: MSC #239 — Marvel Super Heroes Commander | Scryfall ID: ebea49ab-e5cf-46d9-ae35-226a7321ede0 | Oracle ID: 819fc966-434e-470f-91e9-a38df974ad17
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSubtype(subtypes::land::SWAMP),
    ]),
]);

card!(
    index = 10405,
    oracle_id = "819fc966-434e-470f-91e9-a38df974ad17",
    scryfall_id = "ebea49ab-e5cf-46d9-ae35-226a7321ede0",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Drowned Catacomb",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK)],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Black
    ])]),],
);
