//! Glacial Fortress — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Plains or an Island.
//! Oracle: {T}: Add {W} or {U}.
//! Set: FRC #73 — Reality Fracture Commander | Scryfall ID: 3c726a60-8de7-4d5e-8ad5-8405e6ac36b5 | Oracle ID: 027dd013-baa7-4111-b3c9-f4d1414e9c45
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::LAND,
    Filter::ControlledByYou,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSubtype(subtypes::land::ISLAND),
    ]),
]);

card!(
    index = index::GLACIAL_FORTRESS,
    oracle_id = "027dd013-baa7-4111-b3c9-f4d1414e9c45",
    scryfall_id = "3c726a60-8de7-4d5e-8ad5-8405e6ac36b5",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Glacial Fortress",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK)],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
