//! Idyllic Grange — (no cost) — Land — Plains
//! Oracle: ({T}: Add {W}.)
//! Oracle: This land enters tapped unless you control three or more other Plains.
//! Oracle: When this land enters untapped, put a +1/+1 counter on target creature you control.
//! Set: ELD #246 — Throne of Eldraine | Scryfall ID: ca2c611c-3a6f-44b0-9daa-837a465845e0 | Oracle ID: 23d349a0-e441-40b8-b634-13e61440a7c8
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::ControlledByYou,
    Filter::Another,
]);

static TRIGGER2: Filter = Filter::And(&[Filter::This, Filter::Untapped]);

card!(
    index = index::IDYLLIC_GRANGE,
    oracle_id = "23d349a0-e441-40b8-b634-13e61440a7c8",
    scryfall_id = "ca2c611c-3a6f-44b0-9daa-837a465845e0",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Idyllic Grange",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::PLAINS],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK1,
            at_least: 3
        }],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        triggered!(
            Trigger::EntersBattlefield(&TRIGGER2),
            &[Effect::AddCounter {
                kind: CounterKind::P1P1,
                amount: Amount::Fixed(1)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::YOUR_CREATURE)))
        ),
    ],
);
