//! Isolated Chapel — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Plains or a Swamp.
//! Oracle: {T}: Add {W} or {B}.
//! Set: SOC #382 — Secrets of Strixhaven Commander | Scryfall ID: 78814c92-b52c-462a-866f-3e7da9db9f70 | Oracle ID: 7e5d9efe-48a9-434b-bb09-056e0e09cc9a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSubtype(subtypes::land::SWAMP),
    ]),
]);

card! {
    index: 75,
    oracle_id: "7e5d9efe-48a9-434b-bb09-056e0e09cc9a",
    scryfall_id: "78814c92-b52c-462a-866f-3e7da9db9f70",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Isolated Chapel",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
    ],
}
