//! Isolated Chapel — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Plains or a Swamp.
//! Oracle: {T}: Add {W} or {B}.
//! Set: FRC #74 — Reality Fracture Commander | Scryfall ID: b3169b9a-f5e3-402e-883a-08274d0c7b12 | Oracle ID: 7e5d9efe-48a9-434b-bb09-056e0e09cc9a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::LAND,
    Filter::ControlledByYou,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSubtype(subtypes::land::SWAMP),
    ]),
]);

card!(
    index = index::ISOLATED_CHAPEL,
    oracle_id = "7e5d9efe-48a9-434b-bb09-056e0e09cc9a",
    scryfall_id = "b3169b9a-f5e3-402e-883a-08274d0c7b12",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Isolated Chapel",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK)],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Black
    ])]),],
);
