//! Kishla Village — (no cost) — Land
//! Oracle: This land enters tapped unless you control an Island or a Swamp.
//! Oracle: {T}: Add {G}.
//! Oracle: {3}{G}, {T}: Surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)
//! Set: TDM #259 — Tarkir: Dragonstorm | Scryfall ID: 9f0ff90d-7312-44df-afc5-29c768fa7758 | Oracle ID: 4eb428ab-f5b0-46ca-98dd-b3466a91ef97
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::KISHLA_VILLAGE,
    oracle_id = "4eb428ab-f5b0-46ca-98dd-b3466a91ef97",
    scryfall_id = "9f0ff90d-7312-44df-afc5-29c768fa7758",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kishla Village",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK1)],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(cost!("{3}{G}", TapSelf), &[Effect::surveil(2)]),
    ],
);
