//! Festering Thicket — (no cost) — Land — Swamp Forest
//! Oracle: ({T}: Add {B} or {G}.)
//! Oracle: This land enters tapped.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: SOC #371 — Secrets of Strixhaven Commander | Scryfall ID: f71c87db-54ea-4611-8692-096d9714d854 | Oracle ID: bdb9b2ce-342c-4935-8943-d0c3971b1e38
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 489,
    oracle_id: "bdb9b2ce-342c-4935-8943-d0c3971b1e38",
    scryfall_id: "f71c87db-54ea-4611-8692-096d9714d854",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Festering Thicket",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::FOREST],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
