//! Fetid Pools — (no cost) — Land — Island Swamp
//! Oracle: ({T}: Add {U} or {B}.)
//! Oracle: This land enters tapped.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: MSC #243 — Marvel Super Heroes Commander | Scryfall ID: 5fa4556f-2fdc-42e6-98cb-291cee2ca3ac | Oracle ID: 32b03b48-06da-4a74-a7ac-e5ae39a4f428
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 490,
    oracle_id: "32b03b48-06da-4a74-a7ac-e5ae39a4f428",
    scryfall_id: "5fa4556f-2fdc-42e6-98cb-291cee2ca3ac",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Fetid Pools",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::ISLAND, subtypes::land::SWAMP],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
