//! Farseek — {1}{G} — Sorcery
//! Oracle: Search your library for a Plains, Island, Swamp, or Mountain card, put it onto the battlefield tapped, then shuffle.
//! Set: MSC #173 — Marvel Super Heroes Commander | Scryfall ID: c1aac0f5-1d01-4673-b8d3-878d9a1d423c | Oracle ID: 495e52e6-4c2b-4574-9474-eadbdcc8b4ac
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::HasSubtype(subtypes::land::MOUNTAIN),
]);

card! {
    index: 1349,
    oracle_id: "495e52e6-4c2b-4574-9474-eadbdcc8b4ac",
    scryfall_id: "c1aac0f5-1d01-4673-b8d3-878d9a1d423c",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Farseek",
        mana_cost: baylee_core::mana!("{1}{G}"),
        types: TypeSet::SORCERY,
    },
    ],
    abilities: &[
        spell!(&[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD_TAPPED], optional: false }]),
    ],
}
