//! Sacred Nectar — {1}{W} — Sorcery
//! Oracle: You gain 4 life.
//! Set: 9ED #38 — Ninth Edition | Scryfall ID: bcdd5e1c-47db-4960-860c-2af14b734b59 | Oracle ID: 30870ee5-6ad7-48a9-983e-d3b018f2344f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SACRED_NECTAR,
    oracle_id = "30870ee5-6ad7-48a9-983e-d3b018f2344f",
    scryfall_id = "bcdd5e1c-47db-4960-860c-2af14b734b59",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sacred Nectar",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::gain_life(4)]),],
);
