//! Time of Need — {1}{G} — Sorcery
//! Oracle: Search your library for a legendary creature card, reveal it, put it into your hand, then shuffle.
//! Set: CHK #247 — Champions of Kamigawa | Scryfall ID: 514577a5-c7ae-4cfc-872a-e3786d78a6c3 | Oracle ID: 4f2adfd0-c8ab-4bcc-ae55-cb0e798aec7f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TIME_OF_NEED,
    oracle_id = "4f2adfd0-c8ab-4bcc-ae55-cb0e798aec7f",
    scryfall_id = "514577a5-c7ae-4cfc-872a-e3786d78a6c3",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Time of Need",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &Filter::LEGENDARY_CREATURE,
        finds: &[Find::HAND],
        optional: false
    }]),],
);
