//! Abandoned Campground — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {W} or {U}.
//! Set: DSK #255 — Duskmourn: House of Horror | Scryfall ID: ee0565f5-ebdb-43f9-bbb4-0485b1968937 | Oracle ID: 0eec9984-cd11-4a52-9234-469c6a5fb9aa
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ABANDONED_CAMPGROUND,
    oracle_id = "0eec9984-cd11-4a52-9234-469c6a5fb9aa",
    scryfall_id = "ee0565f5-ebdb-43f9-bbb4-0485b1968937",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Abandoned Campground",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
