//! Bleeding Woods — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {R} or {G}.
//! Set: DSK #257 — Duskmourn: House of Horror | Scryfall ID: cb224874-aff5-461f-82ee-89b06663231a | Oracle ID: 47b6d2ae-d3d7-41eb-9172-2076eb8d028d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::BLEEDING_WOODS,
    oracle_id = "47b6d2ae-d3d7-41eb-9172-2076eb8d028d",
    scryfall_id = "cb224874-aff5-461f-82ee-89b06663231a",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Bleeding Woods",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::Green
    ])]),],
);
