//! Lakeside Shack — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {G} or {U}.
//! Set: DSK #262 — Duskmourn: House of Horror | Scryfall ID: a9367acd-393a-4966-ba60-af2ecd4e7596 | Oracle ID: c56cd2ec-5907-4282-9162-d93b7dfd63b5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::LAKESIDE_SHACK,
    oracle_id = "c56cd2ec-5907-4282-9162-d93b7dfd63b5",
    scryfall_id = "a9367acd-393a-4966-ba60-af2ecd4e7596",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lakeside Shack",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Green,
        ManaColor::Blue
    ])]),],
);
