//! Murky Sewer — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {U} or {B}.
//! Set: DSK #263 — Duskmourn: House of Horror | Scryfall ID: 6098d8be-4e3f-455d-8799-91435bf45a1c | Oracle ID: c2cdefeb-3176-4faf-be54-a62d31f777a5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MURKY_SEWER,
    oracle_id = "c2cdefeb-3176-4faf-be54-a62d31f777a5",
    scryfall_id = "6098d8be-4e3f-455d-8799-91435bf45a1c",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Murky Sewer",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Black
    ])]),],
);
