//! Neglected Manor — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {W} or {B}.
//! Set: DSK #264 — Duskmourn: House of Horror | Scryfall ID: 11cf1531-8a3c-4e28-a114-d3a342b33bb6 | Oracle ID: c8c632ab-14ec-44e1-ac00-81d48336320d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::NEGLECTED_MANOR,
    oracle_id = "c8c632ab-14ec-44e1-ac00-81d48336320d",
    scryfall_id = "11cf1531-8a3c-4e28-a114-d3a342b33bb6",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Neglected Manor",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Black
    ])]),],
);
