//! Peculiar Lighthouse — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {U} or {R}.
//! Set: DSK #265 — Duskmourn: House of Horror | Scryfall ID: 3a6e40c0-e70e-4353-a920-9851cfac71dd | Oracle ID: d55f7e20-11c6-44e2-8a21-dca67d3dbc68
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PECULIAR_LIGHTHOUSE,
    oracle_id = "d55f7e20-11c6-44e2-8a21-dca67d3dbc68",
    scryfall_id = "3a6e40c0-e70e-4353-a920-9851cfac71dd",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Peculiar Lighthouse",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Red
    ])]),],
);
