//! Razortrap Gorge — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {B} or {R}.
//! Set: DSK #267 — Duskmourn: House of Horror | Scryfall ID: 98d0d067-b52d-47ec-ba7b-8cfcd716c0e5 | Oracle ID: 8f69bd3a-244e-42d8-bfac-5a426f4b54b4
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RAZORTRAP_GORGE,
    oracle_id = "8f69bd3a-244e-42d8-bfac-5a426f4b54b4",
    scryfall_id = "98d0d067-b52d-47ec-ba7b-8cfcd716c0e5",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Razortrap Gorge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Red
    ])]),],
);
