//! Strangled Cemetery — (no cost) — Land
//! Oracle: This land enters tapped unless a player has 13 or less life.
//! Oracle: {T}: Add {B} or {G}.
//! Set: DSK #268 — Duskmourn: House of Horror | Scryfall ID: c1ce9250-bdbe-4c77-9243-6db9ffffe69b | Oracle ID: 3a5b3405-a1e3-4aad-ab4e-1b8db2d1f3a8
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, unlucky land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STRANGLED_CEMETERY,
    oracle_id = "3a5b3405-a1e3-4aad-ab4e-1b8db2d1f3a8",
    scryfall_id = "c1ce9250-bdbe-4c77-9243-6db9ffffe69b",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Strangled Cemetery",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessSomeoneAtOrBelow { life: 13 }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Green
    ])]),],
);
