//! Rivendell — (no cost) — Legendary Land
//! Oracle: Rivendell enters tapped unless you control a legendary creature.
//! Oracle: {T}: Add {U}.
//! Oracle: {1}{U}, {T}: Scry 2. Activate only if you control a legendary creature.
//! Set: LTR #259 — The Lord of the Rings: Tales of Middle-earth | Scryfall ID: bacd500c-1389-4314-a53e-0ad510d6fb79 | Oracle ID: 2550099d-b3e2-4eb6-9f36-0fc412828ca6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static CHECK1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
    Filter::ControlledByYou,
]);

static CHECK2: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
    Filter::ControlledByYou,
]);

card!(
    index = index::RIVENDELL,
    oracle_id = "2550099d-b3e2-4eb6-9f36-0fc412828ca6",
    scryfall_id = "bacd500c-1389-4314-a53e-0ad510d6fb79",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rivendell",
        types = TypeSet::LAND,
        supertypes = SupertypeSet::LEGENDARY,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK1)],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        activated!(
            cost!("{1}{U}", TapSelf),
            &[Effect::scry(2)],
            condition = Some(Condition::ControlCount(&CHECK2, 1))
        ),
    ],
);
