//! The Shire — (no cost) — Legendary Land
//! Oracle: The Shire enters tapped unless you control a legendary creature.
//! Oracle: {T}: Add {G}.
//! Oracle: {1}{G}, {T}, Tap an untapped creature you control: Create a Food token.
//! Set: LTR #260 — The Lord of the Rings: Tales of Middle-earth | Scryfall ID: d5178a1b-588b-4414-a370-ac6eed51187a | Oracle ID: 9abf9a0e-8e7d-406b-a01d-d4870b30134e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;

static CHECK1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
    Filter::ControlledByYou,
]);

card!(
    index = index::THE_SHIRE,
    oracle_id = "9abf9a0e-8e7d-406b-a01d-d4870b30134e",
    scryfall_id = "d5178a1b-588b-4414-a370-ac6eed51187a",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "The Shire",
        types = TypeSet::LAND,
        supertypes = SupertypeSet::LEGENDARY,
        enter_modifiers = &[EnterModifier::TappedUnless(&CHECK1)],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(
            cost!("{1}{G}", TapSelf, TapOther(&Filter::YOUR_CREATURE)),
            &[Effect::CreateToken {
                token: &generated_tokens::FOOD
            }]
        ),
    ],
);
