//! Ketria Triome — (no cost) — Land — Forest Island Mountain
//! Oracle: ({T}: Add {G}, {U}, or {R}.)
//! Oracle: This land enters tapped.
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: IKO #250 — Ikoria: Lair of Behemoths | Scryfall ID: a249b1f4-2b22-4b67-a207-e0c4ae95d2e1 | Oracle ID: 6bae00e8-06cf-4ac4-a1cc-757e454109fe
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 688,
    oracle_id: "6bae00e8-06cf-4ac4-a1cc-757e454109fe",
    scryfall_id: "a249b1f4-2b22-4b67-a207-e0c4ae95d2e1",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Ketria Triome",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::FOREST, subtypes::land::ISLAND, subtypes::land::MOUNTAIN],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue, ManaColor::Red])]),
        activated!(Cost { mana: baylee_core::mana!("{3}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
