//! Ziatora's Proving Ground — (no cost) — Land — Swamp Mountain Forest
//! Oracle: ({T}: Add {B}, {R}, or {G}.)
//! Oracle: This land enters tapped.
//! Oracle: Cycling {3} ({3}, Discard this card: Draw a card.)
//! Set: SNC #261 — Streets of New Capenna | Scryfall ID: 75fdce80-e338-4a50-bdc6-786511feaeef | Oracle ID: f7e7b78c-c769-4720-8585-1874773eb342
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1341,
    oracle_id: "f7e7b78c-c769-4720-8585-1874773eb342",
    scryfall_id: "75fdce80-e338-4a50-bdc6-786511feaeef",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Ziatora's Proving Ground",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::MOUNTAIN, subtypes::land::FOREST],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red, ManaColor::Green])]),
        activated!(Cost { mana: baylee_core::mana!("{3}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
