//! Lay of the Land — {G} — Sorcery
//! Oracle: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.
//! Set: CN2 #185 — Conspiracy: Take the Crown | Scryfall ID: 42018b2d-b8db-4d37-b42f-15ee0d1a22ee | Oracle ID: cedc52eb-66a6-4b43-87f1-9bb9f4d4871e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::LAY_OF_THE_LAND,
    oracle_id = "cedc52eb-66a6-4b43-87f1-9bb9f4d4871e",
    scryfall_id = "42018b2d-b8db-4d37-b42f-15ee0d1a22ee",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lay of the Land",
        mana_cost = mana!("{G}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &SEARCH1,
        finds: &[Find::HAND],
        optional: false
    }]),],
);
