//! Steelshaper's Gift — {W} — Sorcery
//! Oracle: Search your library for an Equipment card, reveal that card, put it into your hand, then shuffle.
//! Set: CMM #59 — Commander Masters | Scryfall ID: 55d61383-b739-4422-a76c-d8cbca13c5b2 | Oracle ID: d9abda7e-6ca2-42ea-ab24-c542e57014f1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::artifact::EQUIPMENT);

card!(
    index = index::STEELSHAPER_S_GIFT,
    oracle_id = "d9abda7e-6ca2-42ea-ab24-c542e57014f1",
    scryfall_id = "55d61383-b739-4422-a76c-d8cbca13c5b2",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Steelshaper's Gift",
        mana_cost = mana!("{W}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &SEARCH1,
        finds: &[Find::HAND],
        optional: false
    }]),],
);
