// GENERATED by `cargo xtask codegen` — do not edit by hand.
//
// The token ledger: every token there is, in the order ids were assigned
// to them. A token's id is its index in this table, and that number is
// what the engine stamps on the object it creates and what a client keys
// token art off — so the table is **append only**. An insertion in the
// middle renumbers every token after it and hands one of them another's
// picture.
//
// A hand-written token is named here and defined in `crate::tokens`,
// beside the comment saying which printing lent it its art. A generated
// one is defined here, because there is nowhere else for it to live.
//
// Source: `baylee_cards::tokens` and the card-script reference's token
// scripts (read as an automated lookup, never copied).
#![allow(missing_docs, clippy::all, clippy::pedantic)]

use crate::tokens;
use baylee_cards_dsl::TokenDef;

/// Every token there is, in the order ids were assigned.
pub static ALL: &[&TokenDef] = &[
    &tokens::ALLY_1_1_WHITE,
    &tokens::ANGEL_4_4_WHITE_FLYING,
    &tokens::BIRD_1_1_WHITE_FLYING,
    &tokens::BOAR_2_2_GREEN,
    &tokens::CONSTRUCT_ARTIFACT_0_0,
    &tokens::ILLUSION_X_BLUE,
    &tokens::SHAPESHIFTER_1_1_CHANGELING,
    &tokens::SHAPESHIFTER_2_2_BLUE_CHANGELING,
    &tokens::SOLDIER_1_1_WHITE,
    &tokens::TREASURE,
    &tokens::ARMY_0_0_BLACK,
    &tokens::BLOOD,
    &tokens::CLUE,
    &tokens::FOOD,
];

/// The entries a reader wrote, as a subset of [`ALL`] — never a second
/// table of ids.
pub static GENERATED: &[&TokenDef] = &[];
