// GENERATED by `cargo xtask codegen` — do not edit by hand.

#![allow(missing_docs, unused_imports, dead_code, clippy::all, clippy::pedantic)]

use crate::lines::FaceLines;

/// Per card by `CardIndex`, per face, in `abilities_for_face` order:
/// which printed sentence each ability came from. `&[]` is a card with
/// no abilities, a retired index, or one with no cached printing.
pub static ABILITY_LINES: &[&[FaceLines]] = &[
    // Aang and Katara
    &[FaceLines {
        sentences: 1,
        stackable: 2,
        lines: &[Some(0), Some(0)],
    }],
    // Abandoned Air Temple
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Aether Channeler
    &[FaceLines {
        sentences: 4,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Aminatou, the Fateshifter
    &[FaceLines {
        sentences: 4,
        stackable: 3,
        lines: &[Some(0), Some(1), Some(2)],
    }],
    // Ancestral Vision
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Arcane Sanctum
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Archaeomancer
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Arid Mesa
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Ashiok, Dream Render
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Badlands
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Baleful Strix
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Banishing Stroke
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Bleachbone Verge
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Bloodstained Mire
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Bojuka Bog
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Brainstorm
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Brightclimb Pathway
    &[
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
    ],
    // Cavern of Souls
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Charming Prince
    &[FaceLines {
        sentences: 4,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Chromatic Lantern
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // City of Brass
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(0), None],
    }],
    // Clearwater Pathway
    &[
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
    ],
    // Clever Concealment
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Command Tower
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Commander's Insight
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Counterspell
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Crib Swap
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Curse of the Swine
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Cursed Mirror
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Cyclonic Rift
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Damn
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Darksteel Forge
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Demonic Tutor
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Dig Through Time
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Double Major
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Doubling Season
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Drowned Catacomb
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Earth King's Lieutenant
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), Some(2)],
    }],
    // Eerie Interlude
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Elesh Norn, Mother of Machines
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Elspeth, Storm Slayer
    &[FaceLines {
        sentences: 4,
        stackable: 3,
        lines: &[None, Some(1), Some(2), Some(3)],
    }],
    // Emeritus of Woe
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Enlightened Tutor
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Entreat the Dead
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Ephemerate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Ertai Resurrected
    &[FaceLines {
        sentences: 4,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Esper Sentinel
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Everybody Lives!
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Exotic Orchard
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Fetid Heath
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Fierce Guardianship
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Flawless Maneuver
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Flooded Strand
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Force of Negation
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Force of Will
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Forest
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Fracture
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // General Tazri
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Gilded Drake
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Glacial Fortress
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Glasspool Mimic
    &[
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 2,
            stackable: 0,
            lines: &[None],
        },
    ],
    // Godless Shrine
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Great Divide Guide
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Hagra Diabolist
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Halimar Excavator
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Hallowed Fountain
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Harabaz Druid
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Heliod's Intervention
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Helm of the Host
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Hengegate Pathway
    &[
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
    ],
    // Heroic Intervention
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Homeward Path
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Indatha Triome
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Inspirit, Flagship Vessel
    &[FaceLines {
        sentences: 4,
        stackable: 2,
        lines: &[None, None, None, None, None],
    }],
    // Island
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Isolated Chapel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Jace, the Mind Sculptor
    &[FaceLines {
        sentences: 4,
        stackable: 4,
        lines: &[Some(0), Some(1), Some(2), Some(3)],
    }],
    // Jasmine Dragon Tea Shop
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, None, Some(2)],
    }],
    // Jin-Gitaxias, Progress Tyrant
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Karakas
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Karmic Guide
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[None, None, Some(2)],
    }],
    // Karn, the Great Creator
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[None, Some(1), Some(2)],
    }],
    // Katara, the Fearless
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Kazandu Blademaster
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Kor Haven
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Liquimetal Coating
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Liquimetal Torque
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Loran of the Third Path
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), Some(2)],
    }],
    // Luminarch Ascension
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Machine God's Effigy
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Mana Drain
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Marsh Flats
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Maskwood Nexus
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Maze of Ith
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Metamorphosis Fanatic
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Mirrorhall Mimic
    &[
        FaceLines {
            sentences: 2,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 3,
            stackable: 0,
            lines: &[],
        },
    ],
    // Misdirection
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Misty Rainforest
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Mox Opal
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Mulldrifter
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), None],
    }],
    // Mycosynth Lattice
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    // Mystic Gate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Mystical Tutor
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Nesting Dovehawk
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), Some(2)],
    }],
    // Ondu Cleric
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Opposition Agent
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Orcish Bowmasters
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(1), Some(1)],
    }],
    // Pact of Negation
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Padeem, Consul of Innovation
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Palace Jailer
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Panharmonicon
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Path of Ancestry
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Path to Exile
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Phantasmal Image
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[None, None],
    }],
    // Phyrexian Metamorph
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Plains
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Polluted Delta
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Prairie Stream
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Primaris Eliminator
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Privileged Position
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Profane Tutor
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Progenitor Mimic
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[None, None],
    }],
    // Raffine's Tower
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Raugrin Triome
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Ravenous Chupacabra
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Reanimate
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Recruiter of the Guard
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Recurring Nightmare
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Reflecting Pool
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Reflections of Littjara
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Reliquary Tower
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Restoration Angel
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(2)],
    }],
    // Reveillark
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), None],
    }],
    // Rhystic Study
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Riptide Laboratory
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Rite of Replication
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Roaming Throne
    &[FaceLines {
        sentences: 4,
        stackable: 0,
        lines: &[None, None],
    }],
    // Sakashima of a Thousand Faces
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Savannah
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Scalding Tarn
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Scrubland
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Sea Gate Loremaster
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Sensei's Divining Top
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Sheoldred
    &[
        FaceLines {
            sentences: 3,
            stackable: 2,
            lines: &[Some(1), Some(2)],
        },
        FaceLines {
            sentences: 4,
            stackable: 3,
            lines: &[Some(1), Some(2), Some(3)],
        },
    ],
    // Sheoldred's Edict
    &[FaceLines {
        sentences: 4,
        stackable: 0,
        lines: &[None],
    }],
    // Sheoldred, the Apocalypse
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), Some(2)],
    }],
    // Skyclave Apparition
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Smothering Tithe
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Snapcaster Mage
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Sokka, Tenacious Tactician
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Sol Ring
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Solemn Simulacrum
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Solitude
    &[FaceLines {
        sentences: 4,
        stackable: 2,
        lines: &[Some(2), None],
    }],
    // Soulherder
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(0), Some(1)],
    }],
    // Spark Double
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Spellseeker
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Spirit Water Revival
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Storm of Saruman
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Sun Titan
    &[FaceLines {
        sentences: 2,
        stackable: 2,
        lines: &[Some(1), Some(1)],
    }],
    // Sunken Hollow
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Supreme Verdict
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Surgical Metamorph
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Swamp
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Sword of Hearth and Home
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[None, None, None, Some(1), Some(2)],
    }],
    // Swords to Plowshares
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Taiga
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Teferi, Time Raveler
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[None, Some(1), Some(2)],
    }],
    // Temple Garden
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Temporal Mastery
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Thief of Blood
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Tishana's Tidebinder
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Tower of the Magistrate
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Toxic Deluge
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Tribute to the World Tree
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Tuktuk Scrapper
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Tundra
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Twining Twins
    &[
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
        FaceLines {
            sentences: 1,
            stackable: 0,
            lines: &[None],
        },
    ],
    // Umara Raptor
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Underground Sea
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Urza's Saga
    &[FaceLines {
        sentences: 4,
        stackable: 3,
        lines: &[None, Some(1), Some(2), Some(3)],
    }],
    // Vanishing Verse
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Vendilion Clique
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(2)],
    }],
    // Venser, Shaper Savant
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Venser, the Sojourner
    &[FaceLines {
        sentences: 3,
        stackable: 3,
        lines: &[Some(0), Some(1), Some(2)],
    }],
    // Vindicate
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Void Rend
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Volrath's Stronghold
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Wartime Protestors
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Wasteland
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Watery Grave
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Werefox Bodyguard
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(1), Some(2)],
    }],
    // Windswept Heath
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Wizard Class
    &[FaceLines {
        sentences: 6,
        stackable: 2,
        lines: &[None, Some(2), Some(4)],
    }],
    // Zagoth Triome
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Cultivate
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Kodama's Reach
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // A.I.M. Labs
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Abandoned Outpost
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Abraded Bluffs
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Adarkar Wastes
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Adventurer's Inn
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(0), None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Airship Engine Room
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Akoum Refuge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Ally Encampment
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, None, Some(2)],
    }],
    // Alpine Meadow
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // An-Havva Township
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    &[],
    // Ancient Den
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Ancient Spring
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Ancient Tomb
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Ancient Ziggurat
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Animal Sanctuary
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Archaeological Dig
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Arctic Flats
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Arctic Treeline
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Asgardian Citadel
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Avengers Hangar
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    // Aysen Abbey
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    &[],
    &[],
    // Azorius Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Bad River
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Baron, Airship Kingdom
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Barren Moor
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Battlefield Forge
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Bayou
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Birnin Zana Plaza
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Blasted Landscape
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Blighted Cataract
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Blighted Gorge
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Blinkmoth Well
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Blood Crypt
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Bloodfell Caves
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Blossoming Sands
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Bog Wreckage
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Boiling Rock Prison
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Boreal Shelf
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Boros Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Botanical Plaza
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Breeding Pool
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Bristling Backwoods
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Brushland
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Caldera Lake
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Canopy Vista
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Canyon Slough
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Capital City
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Castle Sengir
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    // Castle Vantress
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Caves of Koilos
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Celestial Colonnade
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Cinder Barrens
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Cinder Glade
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Clifftop Retreat
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Coastal Peak
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Coastal Tower
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Contaminated Aquifer
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Creosote Heath
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    // Crumbling Necropolis
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Crumbling Vestige
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Crypt of the Eternals
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(0), None, None],
    }],
    &[],
    &[],
    // Crystal Grotto
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(0), None, None],
    }],
    // Crystal Quarry
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Crystal Vein
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Darkmoss Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Darksteel Citadel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Darkwater Catacombs
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Daru Encampment
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Deathcap Glade
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Desert of the Fervent
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Desert of the Glorified
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Desert of the Indomitable
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Desert of the Mindful
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Desert of the True
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Deserted Beach
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Deserted Temple
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Desolate Mire
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Dimension X
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Dimir Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Dismal Backwater
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Dragonskull Summit
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Dreamroot Cascade
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Drifting Meadow
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Drossforge Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Duskmantle, House of Shadow
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    // Dwarven Ruins
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Ebon Stronghold
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Eclipsed Steppe
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Elfhame Palace
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Encroaching Wastes
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Eroded Canyon
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Evolving Wilds
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    &[],
    &[],
    &[],
    // Faerie Conclave
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Ferrous Lake
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Festering Gulch
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Festering Thicket
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Fetid Pools
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Fiery Islet
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Fisk Tower
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Flood Plain
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    &[],
    &[],
    // Foggy Bottom Swamp
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Foot Headquarters
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Forbidding Watchtower
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Forgotten Cave
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Forlorn Flats
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Forsaken Sanctuary
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Foul Orchard
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Frontier Bivouac
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Frost Marsh
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Gates of Istfell
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Geothermal Bog
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Geothermal Crevice
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Ghitu Encampment
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Glacial Floodplain
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Glittering Massif
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Goblin Burrows
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Gohn, Town of Ruin
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Goldmire Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Golgari Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Gongaga, Reactor Town
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Grand Coliseum
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Grasslands
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    &[],
    // Graypelt Refuge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Great Furnace
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Griffin Canyon
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Grove of the Burnwillows
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Gruul Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Guadosalam, Farplane Gateway
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Haunted Mire
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Haunted Ridge
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Havenwood Battleground
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    // Hell's Kitchen
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Henge of Ramos
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Highland Forest
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Highland Lake
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Highland Weald
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Hinterland Harbor
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Hissing Quagmire
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Horizon Canopy
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Ice Tunnel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Idyllic Beachfront
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Illegitimate Business
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Insomnia, Crown City
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Irrigated Farmland
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Irrigation Ditch
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Izzet Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Jagged Barrens
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Jetmir's Garden
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Jungle Hollow
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Jungle Shrine
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Jwar Isle Refuge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    // Kabira Crossroads
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    // Karplusan Forest
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Kazandu Refuge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Ketria Triome
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Koskun Keep
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    &[],
    // Kyoshi Village
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Llanowar Wastes
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Lonely Arroyo
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Lonely Sandbar
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Looming Spires
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Lorehold Campus
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Los Diablos Missile Base
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    // Lumbering Falls
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Lush Oasis
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Mana Confluence
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Meandering River
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Meditation Pools
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Memorial to Genius
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Memorial to War
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Mikokoro, Center of the Sea
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Minamo, School at Water's Edge
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Mishra's Workshop
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Mistvault Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Misty Palms Oasis
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Molten Tributary
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Mossfire Valley
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Mountain
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Mountain Valley
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Mutant Town
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Mystic Monastery
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Needle Spires
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Nephalia Drownyard
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // New Benalia
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    // Nomad Outpost
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // North Pole Gates
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Nurturing Peatland
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Okina, Temple to the Grandfathers
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Omashu City
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Opulent Palace
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Orzhov Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Orzhova, the Church of Deals
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Overflowing Basin
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Overgrown Farmland
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Overgrown Tomb
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Painted Bluffs
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Pine Barrens
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Piranha Marsh
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Plateau
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Polluted Mire
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Prismari Campus
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Pym Technologies
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Quandrix Campus
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Rabanastre, Royal City
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Racers' Ring
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Radiant Fountain
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(0), None],
    }],
    // Radiant Grove
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Radiant Summit
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Rain-Slicked Copse
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // Rakdos Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Ravaged Highlands
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Razortide Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Remote Isle
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Restless Bivouac
    &[FaceLines {
        sentences: 4,
        stackable: 2,
        lines: &[None, Some(2), Some(3)],
    }],
    &[],
    &[],
    &[],
    // Restless Reef
    &[FaceLines {
        sentences: 4,
        stackable: 2,
        lines: &[None, Some(2), Some(3)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Rimewood Falls
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Rishadan Port
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Rockfall Vale
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Rocky Tar Pit
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(1)],
    }],
    // Rogue's Passage
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Rootbound Crag
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Rugged Highlands
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Ruins of Trokair
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Rumble Arena
    &[FaceLines {
        sentences: 4,
        stackable: 1,
        lines: &[Some(1), None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Rustvale Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Sacred Foundry
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sacred Peaks
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Salt Flats
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Salt Marsh
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Sandsteppe Citadel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sandstone Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Savage Lands
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Savai Triome
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Scabland
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Scattered Groves
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // School of the Unseen
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Scorched Geyser
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Scoured Barrens
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Seafloor Debris
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Seaside Citadel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Seat of the Synod
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Secluded Steppe
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Sejiri Refuge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Selesnya Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Seraph Sanctuary
    &[FaceLines {
        sentences: 3,
        stackable: 2,
        lines: &[Some(0), Some(1), None],
    }],
    // Serpent's Pass
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Shadowblood Ridge
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Shambling Vent
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Sharlayan, Nation of Scholars
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Shattered Sanctum
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    // Sheltered Thicket
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    // Shimmering Grotto
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Shinka, the Bloodsoaked Keep
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Shipwreck Marsh
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Shivan Oasis
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Shivan Reef
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Shizo, Death's Storehouse
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Silent Clearing
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Silverbluff Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Silverquill Campus
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Simic Guildgate
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Skarrg, the Rage Pits
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Skybridge Towers
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Skycloud Expanse
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Skyshroud Forest
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Slagwoods Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    // Slayers' Stronghold
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Slippery Karst
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Smoldering Crater
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Smoldering Marsh
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Snow-Covered Forest
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snow-Covered Island
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snow-Covered Mountain
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snow-Covered Plains
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snow-Covered Swamp
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snow-Covered Wastes
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Snowfield Sinkhole
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Soaring Seacliff
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Sodden Verdure
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Soured Springs
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Spara's Headquarters
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Stark Industries
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Steam Vents
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Stirring Wildwood
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Stomping Ground
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Stone Quarry
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Stormcarved Coast
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Strip Mine
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    // Submerged Boneyard
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Subterranean Cavern
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Sulfur Falls
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sulfur Vent
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    // Sulfurous Mire
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sulfurous Springs
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Sun-Blessed Peak
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Sunbaked Canyon
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    // Sundown Pass
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sungrass Prairie
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Sunhome, Fortress of the Legion
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    // Sunlit Marsh
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Sunpetal Grove
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Sunscorched Divide
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Svyelunite Temple
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Swiftwater Cliffs
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // TCRI Building
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Tangled Islet
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Tanglepool Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Tarnished Citadel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Teetering Peaks
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    // Temple of Abandon
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Deceit
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Enlightenment
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Epiphany
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Malady
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Malice
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Mystery
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Plenty
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Silence
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Temple of Triumph
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Terramorphic Expanse
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    &[],
    &[],
    &[],
    // The Autonomous Furnace
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // The Dross Pits
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // The Fair Basilica
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // The Hunter Maze
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // The Surgical Bay
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Thornglint Bridge
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Thornwood Falls
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Timber Gorge
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Timberland Ruins
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Tinder Farm
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Tournament Grounds
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    // Tramway Station
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Tranquil Cove
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    // Tranquil Expanse
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Tranquil Thicket
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    // Tree of Tales
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Treetop Village
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    // Treno, Dark City
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Tresserhorn Sinks
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Tropical Island
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Turntimber Grove
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Umbral Expanse
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Underground River
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Unknown Shores
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Urborg Volcano
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Urborg, Tomb of Yawgmoth
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Urza's Cave
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Vault of Whispers
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    // Vector, Imperial Capital
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Verdant Catacombs
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Vernal Fen
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    // Viridescent Bog
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Volatile Fjord
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Volcanic Island
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // Wastes
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Waterfront District
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Waterlogged Grove
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
    // White Lotus Hideout
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    &[],
    &[],
    // Wind-Scarred Crag
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[Some(1), None],
    }],
    &[],
    &[],
    // Windurst, Federation Center
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Wirewood Lodge
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    &[],
    &[],
    &[],
    // Witherbloom Campus
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Wizards' School
    &[FaceLines {
        sentences: 3,
        stackable: 0,
        lines: &[None, None, None],
    }],
    &[],
    // Wooded Foothills
    &[FaceLines {
        sentences: 1,
        stackable: 1,
        lines: &[Some(0)],
    }],
    // Wooded Ridgeline
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Woodland Cemetery
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Woodland Chasm
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Woodland Stream
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Xander's Lounge
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    // Yavimaya Coast
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    &[],
    // Yavimaya, Cradle of Growth
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    // Zhalfirin Void
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[Some(0), None],
    }],
    // Ziatora's Proving Ground
    &[FaceLines {
        sentences: 3,
        stackable: 1,
        lines: &[None, Some(2)],
    }],
    &[],
    &[],
    // An Offer You Can't Refuse
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Arcane Signet
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Birds of Paradise
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None],
    }],
    // Commander's Sphere
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Dark Ritual
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Farseek
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Fellwar Stone
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Lightning Greaves
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Llanowar Elves
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Mind Stone
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Nature's Lore
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Negate
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Rampant Growth
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    // Swiftfoot Boots
    &[FaceLines {
        sentences: 2,
        stackable: 1,
        lines: &[None, Some(1)],
    }],
    // Thought Vessel
    &[FaceLines {
        sentences: 2,
        stackable: 0,
        lines: &[None, None],
    }],
    // Three Visits
    &[FaceLines {
        sentences: 1,
        stackable: 0,
        lines: &[None],
    }],
    &[],
    &[],
    &[],
    &[],
    &[],
];
