//! Angelic Shield — {W}{U} — Enchantment
//! Oracle: Creatures you control get +0/+1.
//! Oracle: Sacrifice this enchantment: Return target creature to its owner's hand.
//! Set: DDI #27 — Duel Decks: Venser vs. Koth | Scryfall ID: b5c268cc-891b-49df-8964-736d325b9403 | Oracle ID: 05b020fd-21be-495d-ae45-7de3b1224e6d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ANGELIC_SHIELD,
    oracle_id = "05b020fd-21be-495d-ae45-7de3b1224e6d",
    scryfall_id = "b5c268cc-891b-49df-8964-736d325b9403",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Angelic Shield",
        mana_cost = mana!("{W}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(Filter::YOUR_CREATURE, Modifier::ModifyPT(0, 1)),
        activated!(
            cost!(SacrificeSelf),
            &[Effect::bounce(TargetSpec::Object(&Filter::CREATURE))],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
