//! Circle of Protection: Artifacts — {1}{W} — Enchantment
//! Oracle: {2}: The next time an artifact source of your choice would deal damage to you this turn, prevent that damage.
//! Set: 5DN #8 — Fifth Dawn | Scryfall ID: b09e7267-3d71-4724-b3e7-ae5a6a1f002a | Oracle ID: 2e61e9c0-a2b9-4a24-8cb0-5160accce183
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CIRCLE_OF_PROTECTION_ARTIFACTS,
    oracle_id = "2e61e9c0-a2b9-4a24-8cb0-5160accce183",
    scryfall_id = "b09e7267-3d71-4724-b3e7-ae5a6a1f002a",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Circle of Protection: Artifacts",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{2}"),
        &[Effect::PreventNextFromChosenSource {
            sources: &Filter::ARTIFACT,
            combat_only: false,
            all_but: 0,
            gain_life: false
        }]
    ),],
);
