//! Circle of Protection: Black — {1}{W} — Enchantment
//! Oracle: {1}: The next time a black source of your choice would deal damage to you this turn, prevent that damage.
//! Set: 9ED #10 — Ninth Edition | Scryfall ID: edab2933-5970-4a17-ac00-abcd2c048fdc | Oracle ID: 7a5a8414-4da4-4dd0-93ae-210d50f4d6f6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SOURCE1: Filter = Filter::HasColor(ColorSet::from_slice(&[Color::Black]));

card!(
    index = index::CIRCLE_OF_PROTECTION_BLACK,
    oracle_id = "7a5a8414-4da4-4dd0-93ae-210d50f4d6f6",
    scryfall_id = "edab2933-5970-4a17-ac00-abcd2c048fdc",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Circle of Protection: Black",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{1}"),
        &[Effect::PreventNextFromChosenSource {
            sources: &SOURCE1,
            combat_only: false,
            all_but: 0,
            gain_life: false
        }]
    ),],
);
