//! Circle of Protection: Green — {1}{W} — Enchantment
//! Oracle: {1}: The next time a green source of your choice would deal damage to you this turn, prevent that damage.
//! Set: 8ED #12 — Eighth Edition | Scryfall ID: eecc0e7d-a15b-4930-93d1-832c4fed733b | Oracle ID: 41b0f347-1398-4778-bf3f-4007d8a77162
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SOURCE1: Filter = Filter::HasColor(ColorSet::from_slice(&[Color::Green]));

card!(
    index = index::CIRCLE_OF_PROTECTION_GREEN,
    oracle_id = "41b0f347-1398-4778-bf3f-4007d8a77162",
    scryfall_id = "eecc0e7d-a15b-4930-93d1-832c4fed733b",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Circle of Protection: Green",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{1}"),
        &[Effect::PreventNextFromChosenSource {
            sources: &SOURCE1,
            combat_only: false,
            all_but: 0,
            gain_life: false
        }]
    ),],
);
