//! Peace of Mind — {1}{W} — Enchantment
//! Oracle: {W}, Discard a card: You gain 3 life.
//! Set: EMN #36 — Eldritch Moon | Scryfall ID: 36e37aa2-d898-47f5-9679-5717bfa25688 | Oracle ID: 4f8c5fd7-f280-4b0c-bb84-6ff9b258c50f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PEACE_OF_MIND,
    oracle_id = "4f8c5fd7-f280-4b0c-bb84-6ff9b258c50f",
    scryfall_id = "36e37aa2-d898-47f5-9679-5717bfa25688",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Peace of Mind",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!("{W}", Discard(&Filter::Any)),
        &[Effect::gain_life(3)]
    ),],
);
