//! Primal Rage — {1}{G} — Enchantment
//! Oracle: Creatures you control have trample. (A creature with trample can deal excess combat damage to the player or planeswalker it's attacking.)
//! Set: 10E #286 — Tenth Edition | Scryfall ID: ebe3b738-703d-465c-bc76-2b66f1e0aff2 | Oracle ID: d6464ee4-23fc-4d68-bbda-3b53772015d1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PRIMAL_RAGE,
    oracle_id = "d6464ee4-23fc-4d68-bbda-3b53772015d1",
    scryfall_id = "ebe3b738-703d-465c-bc76-2b66f1e0aff2",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Primal Rage",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[static_ability!(
        Filter::YOUR_CREATURE,
        Modifier::AddKeyword(KeywordSet::TRAMPLE)
    ),],
);
