//! Stasis — {1}{U} — Enchantment
//! Oracle: Players skip their untap steps.
//! Oracle: At the beginning of your upkeep, sacrifice this enchantment unless you pay {U}.
//! Set: ME4 #64 — Masters Edition IV | Scryfall ID: 62f99124-6595-45f8-bece-1775e4c55a5c | Oracle ID: a8cf1379-0195-4e11-b994-481ef1284245
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STASIS,
    oracle_id = "a8cf1379-0195-4e11-b994-481ef1284245",
    scryfall_id = "62f99124-6595-45f8-bece-1775e4c55a5c",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stasis",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        static_ability!(
            Filter::Any,
            Modifier::SkipUntapStep {
                who: PlayerRel::EachPlayer
            }
        ),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::PlayerMayPayManaOr {
                player: PlayerRel::You,
                cost: mana!("{U}"),
                effect: &Effect::SacrificeSelf
            }]
        ),
    ],
);
