//! Trade Routes — {1}{U} — Enchantment
//! Oracle: {1}: Return target land you control to its owner's hand.
//! Oracle: {1}, Discard a land card: Draw a card.
//! Set: 9ED #108 — Ninth Edition | Scryfall ID: 57e5d7c9-36f7-4312-ada0-b6c2757487c8 | Oracle ID: 120fa67e-e5e0-4c23-9a78-d6171d357aee
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TRADE_ROUTES,
    oracle_id = "120fa67e-e5e0-4c23-9a78-d6171d357aee",
    scryfall_id = "57e5d7c9-36f7-4312-ada0-b6c2757487c8",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Trade Routes",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[
        activated!(
            cost!("{1}"),
            &[Effect::bounce(TargetSpec::Object(&Filter::YOUR_LAND))],
            target = Some(TargetSpec::Object(&Filter::YOUR_LAND))
        ),
        activated!(cost!("{1}", Discard(&Filter::LAND)), &[Effect::draw(1)]),
    ],
);
