//! Bountiful Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Forest, Island, or Mountain card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {G}{U}{R} ({G}{U}{R}, Discard this card: Draw a card.)
//! Set: TDC #342 — Tarkir: Dragonstorm Commander | Scryfall ID: f1c99617-6e38-4af7-a064-6db9a5e2cc6a | Oracle ID: 2eb69a8f-9456-4852-b868-85ae609d3441
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::BOUNTIFUL_LANDSCAPE,
    oracle_id = "2eb69a8f-9456-4852-b868-85ae609d3441",
    scryfall_id = "f1c99617-6e38-4af7-a064-6db9a5e2cc6a",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Bountiful Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{G}{U}{R}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
