//! Contaminated Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Plains, Island, or Swamp card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {W}{U}{B} ({W}{U}{B}, Discard this card: Draw a card.)
//! Set: FRC #68 — Reality Fracture Commander | Scryfall ID: f9274fad-3f30-454a-8d61-d487165090d7 | Oracle ID: 28196fd9-00c9-4cd0-b603-0eec8511ec79
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::CONTAMINATED_LANDSCAPE,
    oracle_id = "28196fd9-00c9-4cd0-b603-0eec8511ec79",
    scryfall_id = "f9274fad-3f30-454a-8d61-d487165090d7",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Contaminated Landscape",
        types = TypeSet::LAND,
    ),],
    abilities = &[
        activated!(
            cost!("{W}{U}{B}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
