//! Deceptive Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Plains, Swamp, or Forest card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {W}{B}{G} ({W}{B}{G}, Discard this card: Draw a card.)
//! Set: TDC #356 — Tarkir: Dragonstorm Commander | Scryfall ID: ba863744-929b-43f3-a773-342ba3437b18 | Oracle ID: 1831fe12-dbe0-437f-8fc8-f01bbb701fe1
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::DECEPTIVE_LANDSCAPE,
    oracle_id = "1831fe12-dbe0-437f-8fc8-f01bbb701fe1",
    scryfall_id = "ba863744-929b-43f3-a773-342ba3437b18",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Deceptive Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{W}{B}{G}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
