//! Grasslands — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}, Sacrifice this land: Search your library for a Forest or Plains card, put it onto the battlefield, then shuffle.
//! Set: CMM #1002 — Commander Masters | Scryfall ID: ecf52798-b2e0-4d0a-a41b-8927bfa60375 | Oracle ID: e80bd454-8bc5-4921-90cf-6ad28a27a88b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::FOREST),
    Filter::HasSubtype(subtypes::land::PLAINS),
]);

card! {
    index: 572,
    oracle_id: "e80bd454-8bc5-4921-90cf-6ad28a27a88b",
    scryfall_id: "ecf52798-b2e0-4d0a-a41b-8927bfa60375",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Grasslands",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        activated!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
