//! Jund Panorama — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}, Sacrifice this land: Search your library for a basic Swamp, Mountain, or Forest card, put it onto the battlefield tapped, then shuffle.
//! Set: NCC #408 — New Capenna Commander | Scryfall ID: 50d8346a-e0b5-41eb-be89-7d1eb0e84f28 | Oracle ID: f39f33ac-074d-442d-ae4c-1d694ee315f3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::JUND_PANORAMA,
    oracle_id = "f39f33ac-074d-442d-ae4c-1d694ee315f3",
    scryfall_id = "50d8346a-e0b5-41eb-be89-7d1eb0e84f28",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Jund Panorama", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
