//! Mountain Valley — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}, Sacrifice this land: Search your library for a Mountain or Forest card, put it onto the battlefield, then shuffle.
//! Set: EOC #61 — Edge of Eternities Commander | Scryfall ID: 3094800e-9994-47c3-9ebc-536bf5de13cd | Oracle ID: 0b7393aa-d563-45bc-9946-8e7d1729d498
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::MOUNTAIN),
    Filter::HasSubtype(subtypes::land::FOREST),
]);

card! {
    index: 788,
    oracle_id: "0b7393aa-d563-45bc-9946-8e7d1729d498",
    scryfall_id: "3094800e-9994-47c3-9ebc-536bf5de13cd",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Mountain Valley",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        activated!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
