//! Perilous Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Island, Mountain, or Plains card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {U}{R}{W} ({U}{R}{W}, Discard this card: Draw a card.)
//! Set: FRC #78 — Reality Fracture Commander | Scryfall ID: fec4ca25-ef4c-4500-9bec-60d29c060b83 | Oracle ID: e2b472dd-047d-47eb-9ebb-df6aa4b52dd4
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::PERILOUS_LANDSCAPE,
    oracle_id = "e2b472dd-047d-47eb-9ebb-df6aa4b52dd4",
    scryfall_id = "fec4ca25-ef4c-4500-9bec-60d29c060b83",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Perilous Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{U}{R}{W}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
