//! Prismatic Vista — (no cost) — Land
//! Oracle: {T}, Pay 1 life, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield, then shuffle.
//! Set: MH1 #244 — Modern Horizons | Scryfall ID: e37da81e-be12-45a2-9128-376f1ad7b3e8 | Oracle ID: 032b8a0d-491a-4a12-ab9f-689010054d5b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::PRISMATIC_VISTA,
    oracle_id = "032b8a0d-491a-4a12-ab9f-689010054d5b",
    scryfall_id = "e37da81e-be12-45a2-9128-376f1ad7b3e8",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Prismatic Vista", types = TypeSet::LAND,),],
    abilities = &[activated!(
        cost!(TapSelf, PayLife(1), SacrificeSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD],
            optional: false
        }]
    ),],
);
