//! Seething Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Island, Swamp, or Mountain card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {U}{B}{R} ({U}{B}{R}, Discard this card: Draw a card.)
//! Set: MH3 #225 — Modern Horizons 3 | Scryfall ID: 661fc907-7003-45c6-820c-9616e9a71c30 | Oracle ID: 2d8635bd-ed96-4bb1-8718-6962a0eee3d5
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::SEETHING_LANDSCAPE,
    oracle_id = "2d8635bd-ed96-4bb1-8718-6962a0eee3d5",
    scryfall_id = "661fc907-7003-45c6-820c-9616e9a71c30",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Seething Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{U}{B}{R}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
