//! Shattered Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Mountain, Plains, or Swamp card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {R}{W}{B} ({R}{W}{B}, Discard this card: Draw a card.)
//! Set: TDC #390 — Tarkir: Dragonstorm Commander | Scryfall ID: f8373e5a-94bb-4aa0-bd09-13a01e0cb02a | Oracle ID: 7fbad3f2-66f6-4e3a-b9e0-1ddbcd94d42a
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::SHATTERED_LANDSCAPE,
    oracle_id = "7fbad3f2-66f6-4e3a-b9e0-1ddbcd94d42a",
    scryfall_id = "f8373e5a-94bb-4aa0-bd09-13a01e0cb02a",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Shattered Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{R}{W}{B}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
