//! Sheltering Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Mountain, Forest, or Plains card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {R}{G}{W} ({R}{G}{W}, Discard this card: Draw a card.)
//! Set: MH3 #227 — Modern Horizons 3 | Scryfall ID: 0fe070f4-8877-4280-b8fd-869f3ac34ab6 | Oracle ID: 5b932be0-4dac-41b9-9c59-f79e4cecc31a
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::SHELTERING_LANDSCAPE,
    oracle_id = "5b932be0-4dac-41b9-9c59-f79e4cecc31a",
    scryfall_id = "0fe070f4-8877-4280-b8fd-869f3ac34ab6",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Sheltering Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{R}{G}{W}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
