//! Shire Terrace — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.
//! Set: LTR #261 — The Lord of the Rings: Tales of Middle-earth | Scryfall ID: 25932483-58cd-4ae5-82bf-ab455177d117 | Oracle ID: 619173f4-0403-49cd-9659-2fedd5028a90
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::SHIRE_TERRACE,
    oracle_id = "619173f4-0403-49cd-9659-2fedd5028a90",
    scryfall_id = "25932483-58cd-4ae5-82bf-ab455177d117",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Shire Terrace", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
