//! Terminal Moraine — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}, Sacrifice this land: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
//! Set: DMR #259 — Dominaria Remastered | Scryfall ID: 9029f22b-f153-4f9a-a60f-ba2d0b6e0a1d | Oracle ID: 58eaaa8b-45c6-439b-bdd1-5f4e77a75a8c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::TERMINAL_MORAINE,
    oracle_id = "58eaaa8b-45c6-439b-bdd1-5f4e77a75a8c",
    scryfall_id = "9029f22b-f153-4f9a-a60f-ba2d0b6e0a1d",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Terminal Moraine", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{2}", TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
