//! Tranquil Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Search your library for a basic Forest, Plains, or Island card, put it onto the battlefield tapped, then shuffle.
//! Oracle: Cycling {G}{W}{U} ({G}{W}{U}, Discard this card: Draw a card.)
//! Set: MH3 #231 — Modern Horizons 3 | Scryfall ID: 113f48b9-a972-4e2c-af95-05ab078e01f2 | Oracle ID: d4eb65d5-99fd-4daf-b7d3-8ebf99ee9c61
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::HasSupertype(SupertypeSet::BASIC),
    ]),
]);

card!(
    index = index::TRANQUIL_LANDSCAPE,
    oracle_id = "d4eb65d5-99fd-4daf-b7d3-8ebf99ee9c61",
    scryfall_id = "113f48b9-a972-4e2c-af95-05ab078e01f2",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Tranquil Landscape", types = TypeSet::LAND,),],
    abilities = &[
        activated!(
            cost!("{G}{W}{U}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
