//! Verdant Catacombs — (no cost) — Land
//! Oracle: {T}, Pay 1 life, Sacrifice this land: Search your library for a Swamp or Forest card, put it onto the battlefield, then shuffle.
//! Set: MH2 #260 — Modern Horizons 2 | Scryfall ID: 94c229ea-90da-4aa0-bfda-b162fb3b5b8b | Oracle ID: 67d60b24-d429-4ded-90d9-06e49f28c396
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::HasSubtype(subtypes::land::FOREST),
]);

card! {
    index: 1285,
    oracle_id: "67d60b24-d429-4ded-90d9-06e49f28c396",
    scryfall_id: "94c229ea-90da-4aa0-bfda-b162fb3b5b8b",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Verdant Catacombs",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        activated!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::PayLife(1), CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
