//! Vibrant Cityscape — (no cost) — Land
//! Oracle: {T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.
//! Set: TMC #82 — Teenage Mutant Ninja Turtles Eternal | Scryfall ID: b5e7cdb4-7b4d-4c6c-b016-d6cd3f9a04f2 | Oracle ID: 6a7f3e1f-6798-4644-b64c-7765f81f0938
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::VIBRANT_CITYSCAPE,
    oracle_id = "6a7f3e1f-6798-4644-b64c-7765f81f0938",
    scryfall_id = "b5e7cdb4-7b4d-4c6c-b016-d6cd3f9a04f2",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Vibrant Cityscape", types = TypeSet::LAND,),],
    abilities = &[activated!(
        cost!(TapSelf, SacrificeSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD_TAPPED],
            optional: false
        }]
    ),],
);
