//! Warped Landscape — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.
//! Set: C18 #291 — Commander 2018 | Scryfall ID: 3d313741-af67-47fd-9beb-8abc7d554715 | Oracle ID: 543e6bb3-a867-43bf-a737-2f5d6d8dc631
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::WARPED_LANDSCAPE,
    oracle_id = "543e6bb3-a867-43bf-a737-2f5d6d8dc631",
    scryfall_id = "3d313741-af67-47fd-9beb-8abc7d554715",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Warped Landscape", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{2}", TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
