//! Airship Engine Room — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {R}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #265 — Avatar: The Last Airbender | Scryfall ID: 0b98ba34-f251-4bd0-9d75-1d4445be5cfd | Oracle ID: 01ed9139-293d-4477-a145-3c6fe59266c7
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 213,
    oracle_id: "01ed9139-293d-4477-a145-3c6fe59266c7",
    scryfall_id: "0b98ba34-f251-4bd0-9d75-1d4445be5cfd",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Airship Engine Room",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
