//! Ally Encampment — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add one mana of any color. Spend this mana only to cast an Ally spell.
//! Oracle: {1}, {T}, Sacrifice this land: Return target Ally you control to its owner's hand.
//! Set: BFZ #228 — Battle for Zendikar | Scryfall ID: bcb7124c-ba69-4da8-ad81-58f00fd0181d | Oracle ID: 9d293b69-12b7-4b50-a0a7-c4f493dee30b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SPEND1: Filter = Filter::HasSubtype(subtypes::creature::ALLY);

static TARGET2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::ALLY),
    Filter::ControlledByYou,
]);

card! {
    index: 217,
    oracle_id: "9d293b69-12b7-4b50-a0a7-c4f493dee30b",
    scryfall_id: "bcb7124c-ba69-4da8-ad81-58f00fd0181d",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Ally Encampment",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(Cost::TAP, &[Effect::mana_of_any_color().restricted(&SPEND1, SpendRider::None)]),
        activated!(Cost { mana: baylee_core::mana!("{1}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::ReturnToHand { target: TargetSpec::Object(&TARGET2) }], target: Some(TargetSpec::Object(&TARGET2))),
    ],
}
