//! Animal Sanctuary — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}: Put a +1/+1 counter on target Bird, Cat, Dog, Goat, Ox, or Snake.
//! Set: M21 #242 — Core Set 2021 | Scryfall ID: f8d7a2c7-666d-4fc6-bac8-ef8eb66e355d | Oracle ID: f3c40943-1d7c-4ea2-b34f-8df8b6775701
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::creature::BIRD),
    Filter::HasSubtype(subtypes::creature::CAT),
    Filter::HasSubtype(subtypes::creature::DOG),
    Filter::HasSubtype(subtypes::creature::GOAT),
    Filter::HasSubtype(subtypes::creature::OX),
    Filter::HasSubtype(subtypes::creature::SNAKE),
]);

card! {
    index: 226,
    oracle_id: "f3c40943-1d7c-4ea2-b34f-8df8b6775701",
    scryfall_id: "f8d7a2c7-666d-4fc6-bac8-ef8eb66e355d",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Animal Sanctuary",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::TapSelf] }, &[Effect::AddCounter { kind: CounterKind::P1P1, amount: Amount::Fixed(1) }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
