//! Archaeological Dig — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Sacrifice this land: Add one mana of any color.
//! Set: INV #320 — Invasion | Scryfall ID: 35f55af0-5a46-4900-b3d0-ca796b710e07 | Oracle ID: cf438848-da86-4db6-b3b8-4dd8570be3b8
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ARCHAEOLOGICAL_DIG,
    oracle_id = "cf438848-da86-4db6-b3b8-4dd8570be3b8",
    scryfall_id = "35f55af0-5a46-4900-b3d0-ca796b710e07",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Archaeological Dig", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::mana_of_any_color()]
        ),
    ],
);
