//! Bad River — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}, Sacrifice this land: Search your library for an Island or Swamp card, put it onto the battlefield, then shuffle.
//! Set: DMC #197 — Dominaria United Commander | Scryfall ID: ca79caa8-9893-49be-bc39-f021adb28220 | Oracle ID: 259fc423-d078-4668-9e95-8c1a0d2e49ba
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::HasSubtype(subtypes::land::SWAMP),
]);

card! {
    index: 251,
    oracle_id: "259fc423-d078-4668-9e95-8c1a0d2e49ba",
    scryfall_id: "ca79caa8-9893-49be-bc39-f021adb28220",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bad River",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        activated!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD], optional: false }]),
    ],
}
