//! Bazaar of Baghdad — (no cost) — Land
//! Oracle: {T}: Draw two cards, then discard three cards.
//! Set: VMA #294 — Vintage Masters | Scryfall ID: c88acaa8-ad4d-4321-a6f6-9361916e5b5e | Oracle ID: 54022a10-c9f0-458d-a0ed-228843cd9a40
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 268,
    oracle_id: "54022a10-c9f0-458d-a0ed-228843cd9a40",
    scryfall_id: "c88acaa8-ad4d-4321-a6f6-9361916e5b5e",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bazaar of Baghdad",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        activated!(Cost::TAP, &[Effect::DrawCards { amount: Amount::Fixed(2) }]),
    ],
}
