//! Cascading Cataracts — (no cost) — Land
//! Oracle: Indestructible
//! Oracle: {T}: Add {C}.
//! Oracle: {5}, {T}: Add five mana in any combination of colors.
//! Set: DMC #202 — Dominaria United Commander | Scryfall ID: 2f3fbd9b-91ab-4691-a916-e20db8ebc513 | Oracle ID: d98b4250-3492-4864-9c4c-42db09b3ccd4
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CASCADING_CATARACTS,
    oracle_id = "d98b4250-3492-4864-9c4c-42db09b3ccd4",
    scryfall_id = "2f3fbd9b-91ab-4691-a916-e20db8ebc513",
    keywords = KeywordSet::INDESTRUCTIBLE,
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Cascading Cataracts", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!("{5}", TapSelf),
            &[Effect::mana_combination(ALL_MANA_COLORS, Amount::Fixed(5))]
        ),
    ],
);
