//! Castle Sengir — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add {B}.
//! Oracle: {2}, {T}: Add {U} or {R}.
//! Set: HML #113 — Homelands | Scryfall ID: 16bfba30-4075-4bd6-9e4b-3a37641d43ce | Oracle ID: c7f0251a-9341-4ff2-8b15-31c06eb4f2e7
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CASTLE_SENGIR,
    oracle_id = "c7f0251a-9341-4ff2-8b15-31c06eb4f2e7",
    scryfall_id = "16bfba30-4075-4bd6-9e4b-3a37641d43ce",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Castle Sengir", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(cost!("{1}", TapSelf), &[Effect::mana(ManaColor::Black, 1)]),
        mana_ability!(
            cost!("{2}", TapSelf),
            &[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]
        ),
    ],
);
