//! Dragonskull Summit — (no cost) — Land
//! Oracle: This land enters tapped unless you control a Swamp or a Mountain.
//! Oracle: {T}: Add {B} or {R}.
//! Set: MSC #238 — Marvel Super Heroes Commander | Scryfall ID: d20e433a-eb62-4301-bc20-bfe27468b033 | Oracle ID: 63398c02-6fb1-481d-9d9f-81063532fbc0
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, checkland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[
    Filter::ControlledByYou,
    Filter::LAND,
    Filter::Or(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
    ]),
]);

card! {
    index: 436,
    oracle_id: "63398c02-6fb1-481d-9d9f-81063532fbc0",
    scryfall_id: "d20e433a-eb62-4301-bc20-bfe27468b033",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Dragonskull Summit",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::TappedUnless(&CHECK)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
