//! Ebon Stronghold — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B}.
//! Oracle: {T}, Sacrifice this land: Add {B}{B}.
//! Set: ME2 #228 — Masters Edition II | Scryfall ID: add84934-3067-4f01-9b43-5af4ff247de3 | Oracle ID: 4d4b9512-d29d-4b99-9249-d37e1199a1f5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 454,
    oracle_id: "4d4b9512-d29d-4b99-9249-d37e1199a1f5",
    scryfall_id: "add84934-3067-4f01-9b43-5af4ff247de3",
    color_identity: ColorSet::from_slice(&[Color::Black]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Ebon Stronghold",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana(ManaColor::Black, 2)]),
    ],
}
