//! Gates of Istfell — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {2}{W}{U}{U}, {T}, Sacrifice this land: You gain 2 life and draw two cards.
//! Set: KHM #256 — Kaldheim | Scryfall ID: 2627acb7-57d9-4429-9bc5-e7dd444d8d48 | Oracle ID: 6f85c26e-3c87-4112-ad1a-8a5708555a93
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card! {
    index: 536,
    oracle_id: "6f85c26e-3c87-4112-ad1a-8a5708555a93",
    scryfall_id: "2627acb7-57d9-4429-9bc5-e7dd444d8d48",
    color_identity: ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Gates of Istfell",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::White, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}{W}{U}{U}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::GainLife { amount: Amount::Fixed(2) }, Effect::DrawCards { amount: Amount::Fixed(2) }]),
    ],
}
