//! Gemstone Mine — (no cost) — Land
//! Oracle: This land enters with three mining counters on it.
//! Oracle: {T}, Remove a mining counter from this land: Add one mana of any color. If there are no mining counters on this land, sacrifice it.
//! Set: DMR #247 — Dominaria Remastered | Scryfall ID: ee152618-761f-43b4-942a-f63b16c182cc | Oracle ID: 0c828f10-4775-492f-9224-1e2814ad2cad
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters with counters.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::GEMSTONE_MINE,
    oracle_id = "0c828f10-4775-492f-9224-1e2814ad2cad",
    scryfall_id = "ee152618-761f-43b4-942a-f63b16c182cc",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gemstone Mine",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::WithCounters {
            kind: counters::MINING,
            n: 3
        }],
    ),],
    abilities = &[mana_ability!(
        cost!(
            TapSelf,
            RemoveCounterSelf {
                kind: counters::MINING,
                n: 1
            }
        ),
        &[
            Effect::mana_of_any_color(),
            Effect::IfNoCountersOnSelf {
                kind: counters::MINING,
                then: &[Effect::SacrificeSelf]
            }
        ]
    ),],
);
