//! Goblin Burrows — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}{R}, {T}: Target Goblin creature gets +2/+0 until end of turn.
//! Set: EVG #58 — Duel Decks Anthology: Elves vs. Goblins | Scryfall ID: dc36acc6-db4b-45b7-b526-7966ff82a44f | Oracle ID: ad65bb8e-57de-49f3-ba7c-be62cf3fe3df
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSubtype(subtypes::creature::GOBLIN),
]);

card! {
    index: 559,
    oracle_id: "ad65bb8e-57de-49f3-ba7c-be62cf3fe3df",
    scryfall_id: "dc36acc6-db4b-45b7-b526-7966ff82a44f",
    color_identity: ColorSet::from_slice(&[Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Goblin Burrows",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{R}"), parts: &[CostPart::TapSelf] }, &[Effect::PumpTarget { power: Amount::Fixed(2), toughness: Amount::Fixed(0), keywords: KeywordSet::EMPTY, duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
