//! Jwar Isle Refuge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {U} or {B}.
//! Set: ZNC #133 — Zendikar Rising Commander | Scryfall ID: 6d103181-25a1-4928-ac37-adf11038d5b5 | Oracle ID: 8b96f837-7c32-473a-b5ae-1d66527eaf7b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 674,
    oracle_id: "8b96f837-7c32-473a-b5ae-1d66527eaf7b",
    scryfall_id: "6d103181-25a1-4928-ac37-adf11038d5b5",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Jwar Isle Refuge",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
