//! Kazandu Refuge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {R} or {G}.
//! Set: C19 #256 — Commander 2019 | Scryfall ID: 6ca097f1-eef0-4e18-ab5d-49bb4aeb74e2 | Oracle ID: 03332772-18b0-446a-a7e2-a4bdf38c4f0c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 683,
    oracle_id: "03332772-18b0-446a-a7e2-a4bdf38c4f0c",
    scryfall_id: "6ca097f1-eef0-4e18-ab5d-49bb4aeb74e2",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Kazandu Refuge",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
    ],
}
