//! Kyoshi Village — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {W}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #271 — Avatar: The Last Airbender | Scryfall ID: 8d5f3008-2af8-4e81-8847-1c91f524e747 | Oracle ID: da81b78b-89fd-4fc1-9395-b5b01b96be70
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 697,
    oracle_id: "da81b78b-89fd-4fc1-9395-b5b01b96be70",
    scryfall_id: "8d5f3008-2af8-4e81-8847-1c91f524e747",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Kyoshi Village",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::White])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
