//! Meditation Pools — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {U}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #272 — Avatar: The Last Airbender | Scryfall ID: cc078fc6-4470-473f-9e24-d2c470e09141 | Oracle ID: 66208129-20fb-4cb4-8f00-8d4574c9c653
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 746,
    oracle_id: "66208129-20fb-4cb4-8f00-8d4574c9c653",
    scryfall_id: "cc078fc6-4470-473f-9e24-d2c470e09141",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Meditation Pools",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
