//! Misty Palms Oasis — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {B}.
//! Oracle: {4}, {T}, Sacrifice this land: Draw a card.
//! Set: TLA #273 — Avatar: The Last Airbender | Scryfall ID: 7cc29ddb-8f44-4493-985d-2fac35f9f34d | Oracle ID: dfd2c57a-4557-4df1-8f6f-da2cbd317f12
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 773,
    oracle_id: "dfd2c57a-4557-4df1-8f6f-da2cbd317f12",
    scryfall_id: "7cc29ddb-8f44-4493-985d-2fac35f9f34d",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Misty Palms Oasis",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
