//! Okina, Temple to the Grandfathers — (no cost) — Legendary Land
//! Oracle: {T}: Add {G}.
//! Oracle: {G}, {T}: Target legendary creature gets +1/+1 until end of turn.
//! Set: CHK #280 — Champions of Kamigawa | Scryfall ID: ee8cf7aa-388c-47ec-be59-6ba98f3853cb | Oracle ID: 3ad69bfb-2e51-4fe9-8d2f-7d071a4f1c69
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
]);

card! {
    index: 830,
    oracle_id: "3ad69bfb-2e51-4fe9-8d2f-7d071a4f1c69",
    scryfall_id: "ee8cf7aa-388c-47ec-be59-6ba98f3853cb",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Okina, Temple to the Grandfathers",
        types: TypeSet::LAND,
        supertypes: SupertypeSet::LEGENDARY,
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Green, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{G}"), parts: &[CostPart::TapSelf] }, &[Effect::PumpTarget { power: Amount::Fixed(1), toughness: Amount::Fixed(1), keywords: KeywordSet::EMPTY, duration: Duration::UntilEndOfTurn }], target: Some(TargetSpec::Object(&TARGET1))),
    ],
}
