//! Prismari Campus — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {R}.
//! Oracle: {4}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Set: SOC #394 — Secrets of Strixhaven Commander | Scryfall ID: 7c464dee-dd89-4955-ae40-8bb74e9ff42a | Oracle ID: 3a3a1b35-ae4d-49d5-ae09-5a1693ad53ce
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 876,
    oracle_id: "3a3a1b35-ae4d-49d5-ae09-5a1693ad53ce",
    scryfall_id: "7c464dee-dd89-4955-ae40-8bb74e9ff42a",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Prismari Campus",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf] }, &[Effect::Scry { amount: Amount::Fixed(1) }]),
    ],
}
