//! Pym Technologies — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {G} or {U}.
//! Set: MSH #271 — Marvel Super Heroes | Scryfall ID: 1de583ce-e805-45f1-907f-198bc82fd3b5 | Oracle ID: 5a8977fc-0732-4807-b876-01819aedd70b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 881,
    oracle_id: "5a8977fc-0732-4807-b876-01819aedd70b",
    scryfall_id: "1de583ce-e805-45f1-907f-198bc82fd3b5",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Pym Technologies",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
    ],
}
