//! Roadside Reliquary — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {2}, {T}, Sacrifice this land: Draw a card if you control an artifact. Draw a card if you control an enchantment.
//! Set: NEO #272 — Kamigawa: Neon Dynasty | Scryfall ID: 8002de90-93fb-48ea-a849-40fdad0aef5a | Oracle ID: 2fb13687-0518-4ba0-a5ae-dd609464b026
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 932,
    oracle_id: "2fb13687-0518-4ba0-a5ae-dd609464b026",
    scryfall_id: "8002de90-93fb-48ea-a849-40fdad0aef5a",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Roadside Reliquary",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{2}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }, Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
