//! Rugged Highlands — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {R} or {G}.
//! Set: TDM #265 — Tarkir: Dragonstorm | Scryfall ID: 31261eca-28ad-407c-84ef-0c124d0d7451 | Oracle ID: 6c922206-6e68-4dcd-9559-88da1074f2c4
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 940,
    oracle_id: "6c922206-6e68-4dcd-9559-88da1074f2c4",
    scryfall_id: "31261eca-28ad-407c-84ef-0c124d0d7451",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Rugged Highlands",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
    ],
}
