//! Rumble Arena — (no cost) — Land
//! Oracle: Vigilance
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put it on the bottom.)
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add one mana of any color.
//! Set: TLA #277 — Avatar: The Last Airbender | Scryfall ID: 3f5d2c38-663c-4f64-8cfc-c102462e82ef | Oracle ID: 83f2470e-2114-4cd9-ab1a-21b76e9cdf63
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card! {
    index: 944,
    oracle_id: "83f2470e-2114-4cd9-ab1a-21b76e9cdf63",
    scryfall_id: "3f5d2c38-663c-4f64-8cfc-c102462e82ef",
    keywords: KeywordSet::VIGILANCE,
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Rumble Arena",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(Cost { mana: baylee_core::mana!("{1}"), parts: &[CostPart::TapSelf] }, &[Effect::mana_of_any_color()]),
    ],
}
