//! Salt Flats — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {W} or {B}. This land deals 1 damage to you.
//! Set: TPR #242 — Tempest Remastered | Scryfall ID: 93e98e1f-5a51-41b4-b636-86a58e712849 | Oracle ID: 7a951bd7-4f7d-44ea-9c2f-fe2f6b2f5289
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 953,
    oracle_id: "7a951bd7-4f7d-44ea-9c2f-fe2f6b2f5289",
    scryfall_id: "93e98e1f-5a51-41b4-b636-86a58e712849",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Salt Flats",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black]), Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::You) }]),
    ],
}
