//! Sandstone Bridge — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, target creature gets +1/+1 and gains vigilance until end of turn.
//! Oracle: {T}: Add {W}.
//! Set: BFZ #243 — Battle for Zendikar | Scryfall ID: c781e932-4605-47aa-add1-4ee62f4e7ead | Oracle ID: 08911e8e-cd67-4960-a927-958c33632469
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::CREATURE;

card! {
    index: 960,
    oracle_id: "08911e8e-cd67-4960-a927-958c33632469",
    scryfall_id: "c781e932-4605-47aa-add1-4ee62f4e7ead",
    color_identity: ColorSet::from_slice(&[Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Sandstone Bridge",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::PumpTarget { power: Amount::Fixed(1), toughness: Amount::Fixed(1), keywords: KeywordSet::VIGILANCE, duration: Duration::UntilEndOfTurn }], targets: Some(TargetReq::one(TargetSpec::Object(&TARGET1)))),
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::White, 1)]),
    ],
}
