//! Scoured Barrens — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {W} or {B}.
//! Set: TDM #267 — Tarkir: Dragonstorm | Scryfall ID: b4b47b80-69ed-44b0-afa0-ca90206dc16d | Oracle ID: d37f858e-03c8-4594-9b92-cd03699a1591
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 976,
    oracle_id: "d37f858e-03c8-4594-9b92-cd03699a1591",
    scryfall_id: "b4b47b80-69ed-44b0-afa0-ca90206dc16d",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Scoured Barrens",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
    ],
}
