//! Seraph Sanctuary — (no cost) — Land
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: Whenever an Angel you control enters, you gain 1 life.
//! Oracle: {T}: Add {C}.
//! Set: DDQ #33 — Duel Decks: Blessed vs. Cursed | Scryfall ID: e1c1fa29-362f-40b4-b67f-513f6592fb3b | Oracle ID: 0b504dc6-61cc-4a72-907c-145fa4c72466
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::ANGEL),
    Filter::ControlledByYou,
]);

card! {
    index: 1003,
    oracle_id: "0b504dc6-61cc-4a72-907c-145fa4c72466",
    scryfall_id: "e1c1fa29-362f-40b4-b67f-513f6592fb3b",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Seraph Sanctuary",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        triggered!(Trigger::EntersBattlefield(&TRIGGER1), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
    ],
}
