//! Shambling Vent — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {B}.
//! Oracle: {1}{W}{B}: Until end of turn, this land becomes a 2/3 white and black Elemental creature with lifelink. It's still a land.
//! Set: CLB #914 — Commander Legends: Battle for Baldur's Gate | Scryfall ID: 1f5bf05a-04a1-4dde-845b-eced21a785fa | Oracle ID: 4725abd4-06bc-464a-bc5b-c9e0f71ec079
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1008,
    oracle_id: "4725abd4-06bc-464a-bc5b-c9e0f71ec079",
    scryfall_id: "1f5bf05a-04a1-4dde-845b-eced21a785fa",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Shambling Vent",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{1}{W}{B}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::ELEMENTAL), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::White, Color::Black])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Ability, filter: &Filter::This, modifier: Modifier::AddKeyword(KeywordSet::LIFELINK), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(2, 3), duration: Duration::UntilEndOfTurn }]),
    ],
}
