//! Silverquill Campus — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {B}.
//! Oracle: {4}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Set: SOC #405 — Secrets of Strixhaven Commander | Scryfall ID: 354efff0-aea5-4274-94d6-9fce02430255 | Oracle ID: 2b65eb80-6fb7-429f-81f2-2fe125eba634
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1034,
    oracle_id: "2b65eb80-6fb7-429f-81f2-2fe125eba634",
    scryfall_id: "354efff0-aea5-4274-94d6-9fce02430255",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Silverquill Campus",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf] }, &[Effect::Scry { amount: Amount::Fixed(1) }]),
    ],
}
