//! Svyelunite Temple — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U}.
//! Oracle: {T}, Sacrifice this land: Add {U}{U}.
//! Set: ME2 #237 — Masters Edition II | Scryfall ID: 21fe2f1b-bfd1-4682-ae23-069300de3791 | Oracle ID: 5578cf33-62f5-456c-a58c-f744a25df79b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1127,
    oracle_id: "5578cf33-62f5-456c-a58c-f744a25df79b",
    scryfall_id: "21fe2f1b-bfd1-4682-ae23-069300de3791",
    color_identity: ColorSet::from_slice(&[Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Svyelunite Temple",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        mana_ability!(Cost { mana: ManaCost::ZERO, parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::mana(ManaColor::Blue, 2)]),
    ],
}
