//! Temple of Deceit — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {U} or {B}.
//! Set: FDN #697 — Foundations | Scryfall ID: e18748ce-e52e-4cd1-89d4-cd2578a0d574 | Oracle ID: 33b9b3bd-33ca-46f3-b8bb-a978bc3d1085
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1147,
    oracle_id: "33b9b3bd-33ca-46f3-b8bb-a978bc3d1085",
    scryfall_id: "e18748ce-e52e-4cd1-89d4-cd2578a0d574",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Deceit",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
