//! Temple of Malady — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: {T}: Add {B} or {G}.
//! Set: SOC #413 — Secrets of Strixhaven Commander | Scryfall ID: 1ca36218-db87-4e44-8606-2a516504ed20 | Oracle ID: dc55421f-dee8-4263-9df0-2365df5f14bb
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1150,
    oracle_id: "dc55421f-dee8-4263-9df0-2365df5f14bb",
    scryfall_id: "1ca36218-db87-4e44-8606-2a516504ed20",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Temple of Malady",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::Scry { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
