//! Wind-Scarred Crag — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, you gain 1 life.
//! Oracle: {T}: Add {R} or {W}.
//! Set: TDM #271 — Tarkir: Dragonstorm | Scryfall ID: 4912e4d0-b16a-4aa6-a583-3430d26bd591 | Oracle ID: b0af0c54-2a59-4075-8543-d41ff20c4c87
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1318,
    oracle_id: "b0af0c54-2a59-4075-8543-d41ff20c4c87",
    scryfall_id: "4912e4d0-b16a-4aa6-a583-3430d26bd591",
    color_identity: ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Wind-Scarred Crag",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::GainLife { amount: Amount::Fixed(1) }]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
    ],
}
