//! Deserted Beach — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {W} or {U}.
//! Set: FRA #176 — Reality Fracture | Scryfall ID: 56dae4c4-3e71-4a32-979b-4e26d9c9e96c | Oracle ID: f0ec8681-da50-466b-8cdd-1dc710deccd9
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DESERTED_BEACH,
    oracle_id = "f0ec8681-da50-466b-8cdd-1dc710deccd9",
    scryfall_id = "56dae4c4-3e71-4a32-979b-4e26d9c9e96c",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Deserted Beach",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
