//! Deserted Beach — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {W} or {U}.
//! Set: INR #276 — Innistrad Remastered | Scryfall ID: c819de09-dac2-407a-98c8-775865e9bdf8 | Oracle ID: f0ec8681-da50-466b-8cdd-1dc710deccd9
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::LAND]);

card!(
    index = 419,
    oracle_id = "f0ec8681-da50-466b-8cdd-1dc710deccd9",
    scryfall_id = "c819de09-dac2-407a-98c8-775865e9bdf8",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Deserted Beach",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
