//! Haunted Ridge — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {B} or {R}.
//! Set: FRA #180 — Reality Fracture | Scryfall ID: a4e4966b-8963-4fac-a8bf-e778e063c7dd | Oracle ID: e2a37967-4212-4553-9f77-bcb613405807
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HAUNTED_RIDGE,
    oracle_id = "e2a37967-4212-4553-9f77-bcb613405807",
    scryfall_id = "a4e4966b-8963-4fac-a8bf-e778e063c7dd",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Haunted Ridge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Red
    ])]),],
);
