//! Haunted Ridge — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {B} or {R}.
//! Set: INR #280 — Innistrad Remastered | Scryfall ID: 32f1e668-89b8-4f82-afc1-6c3efb1fef3b | Oracle ID: e2a37967-4212-4553-9f77-bcb613405807
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::LAND]);

card!(
    index = 607,
    oracle_id = "e2a37967-4212-4553-9f77-bcb613405807",
    scryfall_id = "32f1e668-89b8-4f82-afc1-6c3efb1fef3b",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Haunted Ridge",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Black,
        ManaColor::Red
    ])]),],
);
