//! Overgrown Farmland — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {G} or {W}.
//! Set: FRA #185 — Reality Fracture | Scryfall ID: 178e61e4-472f-42cd-9d3b-4880c2acc527 | Oracle ID: 709d2f10-1585-48c3-9058-ddd5f62f0452
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::LAND]);

card!(
    index = index::OVERGROWN_FARMLAND,
    oracle_id = "709d2f10-1585-48c3-9058-ddd5f62f0452",
    scryfall_id = "178e61e4-472f-42cd-9d3b-4880c2acc527",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Overgrown Farmland",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Green,
        ManaColor::White
    ])]),],
);
