//! Rockfall Vale — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {R} or {G}.
//! Set: TDC #387 — Tarkir: Dragonstorm Commander | Scryfall ID: dcdea659-ecaf-4abe-be0f-64e105abb104 | Oracle ID: 185c70c1-8403-4ae5-b45d-3679d4ee092a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::LAND]);

card!(
    index = 22263,
    oracle_id = "185c70c1-8403-4ae5-b45d-3679d4ee092a",
    scryfall_id = "dcdea659-ecaf-4abe-be0f-64e105abb104",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rockfall Vale",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::Green
    ])]),],
);
