//! Rockfall Vale — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {R} or {G}.
//! Set: FRA #186 — Reality Fracture | Scryfall ID: e3c8a8b6-23ba-45ad-80d1-8e2dc79897f7 | Oracle ID: 185c70c1-8403-4ae5-b45d-3679d4ee092a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ROCKFALL_VALE,
    oracle_id = "185c70c1-8403-4ae5-b45d-3679d4ee092a",
    scryfall_id = "e3c8a8b6-23ba-45ad-80d1-8e2dc79897f7",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rockfall Vale",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::Green
    ])]),],
);
