//! Shipwreck Marsh — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {U} or {B}.
//! Set: FRA #189 — Reality Fracture | Scryfall ID: 9e944c5b-68ac-4a30-bbd4-09a4288319ce | Oracle ID: 5f42b67f-87fd-4f98-a0e8-0c8313f4bbc8
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SHIPWRECK_MARSH,
    oracle_id = "5f42b67f-87fd-4f98-a0e8-0c8313f4bbc8",
    scryfall_id = "9e944c5b-68ac-4a30-bbd4-09a4288319ce",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shipwreck Marsh",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Black
    ])]),],
);
