//! Sundown Pass — (no cost) — Land
//! Oracle: This land enters tapped unless you control two or more other lands.
//! Oracle: {T}: Add {R} or {W}.
//! Set: SOS #264 — Secrets of Strixhaven | Scryfall ID: b34000e9-ff20-4fb4-9d0b-03a172a92457 | Oracle ID: 5ad0b405-cca4-475e-985c-4d7e3599d87e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, slow land.

use baylee_cards_dsl::prelude::*;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::LAND]);

card!(
    index = 22597,
    oracle_id = "5ad0b405-cca4-475e-985c-4d7e3599d87e",
    scryfall_id = "b34000e9-ff20-4fb4-9d0b-03a172a92457",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sundown Pass",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::White
    ])]),],
);
