//! Gohn, Town of Ruin — (no cost) — Land — Town
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {G}.
//! Set: FIN #278 — Final Fantasy | Scryfall ID: 99582781-613e-4a33-aec7-7569b4a961aa | Oracle ID: 13fbd525-c9ee-4bd6-b269-94fb264024b6
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 562,
    oracle_id: "13fbd525-c9ee-4bd6-b269-94fb264024b6",
    scryfall_id: "99582781-613e-4a33-aec7-7569b4a961aa",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Gohn, Town of Ruin",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::TOWN],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
    ],
}
