//! Treno, Dark City — (no cost) — Land — Town
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {B}.
//! Set: FIN #290 — Final Fantasy | Scryfall ID: f6285535-bc44-4274-a886-b14d7c7aaba8 | Oracle ID: 6d5bb714-1bf4-4f75-9ea8-bdbd18b0425b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1227,
    oracle_id: "6d5bb714-1bf4-4f75-9ea8-bdbd18b0425b",
    scryfall_id: "f6285535-bc44-4274-a886-b14d7c7aaba8",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Treno, Dark City",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::TOWN],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
