//! Calciform Pools — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Put a storage counter on this land.
//! Oracle: {1}, Remove X storage counters from this land: Add X mana in any combination of {W} and/or {U}.
//! Set: TSR #275 — Time Spiral Remastered | Scryfall ID: 297a2b09-562a-46d8-905d-0b32e854e9d2 | Oracle ID: 2031bc31-81cc-407a-8615-29832f586bbc
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::CALCIFORM_POOLS,
    oracle_id = "2031bc31-81cc-407a-8615-29832f586bbc",
    scryfall_id = "297a2b09-562a-46d8-905d-0b32e854e9d2",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Calciform Pools", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf),
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                "{1}",
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_combination(
                &[ManaColor::White, ManaColor::Blue],
                Amount::X
            )]
        ),
    ],
);
