//! Fountain of Cho — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {W} for each storage counter removed this way.
//! Set: MMQ #317 — Mercadian Masques | Scryfall ID: 41f352c3-4b63-4174-b2b4-6c19fb8c06ff | Oracle ID: 0799df10-b489-4f79-bf98-7a0c500b46a1
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::FOUNTAIN_OF_CHO,
    oracle_id = "0799df10-b489-4f79-bf98-7a0c500b46a1",
    scryfall_id = "41f352c3-4b63-4174-b2b4-6c19fb8c06ff",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fountain of Cho",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::White, Amount::X)]
        ),
    ],
);
