//! Hollow Trees — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: You may choose not to untap this land during your untap step.
//! Oracle: At the beginning of your upkeep, if this land is tapped, put a storage counter on it.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {G} for each storage counter removed this way.
//! Set: 5ED #418 — Fifth Edition | Scryfall ID: 3d6d30a4-a24e-4537-9230-bf6f57fbcd98 | Oracle ID: 3348df85-e61c-47b5-857d-c79befb38a8a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, may choose not to untap, upkeep trigger with an intervening if.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HOLLOW_TREES,
    oracle_id = "3348df85-e61c-47b5-857d-c79befb38a8a",
    scryfall_id = "3d6d30a4-a24e-4537-9230-bf6f57fbcd98",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Hollow Trees",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        static_ability!(Filter::This, Modifier::MayChooseNotToUntap),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }],
            condition = Some(Condition::SourceMatches(&Filter::Tapped))
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Green, Amount::X)]
        ),
    ],
);
