//! Icatian Store — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: You may choose not to untap this land during your untap step.
//! Oracle: At the beginning of your upkeep, if this land is tapped, put a storage counter on it.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {W} for each storage counter removed this way.
//! Set: 5ED #419 — Fifth Edition | Scryfall ID: e68c45d3-0f3c-4429-a93e-4ca70ea6b1a4 | Oracle ID: 87a0e0b9-6c2d-47a4-a3ed-7e0ae62fbffc
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, may choose not to untap, upkeep trigger with an intervening if.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ICATIAN_STORE,
    oracle_id = "87a0e0b9-6c2d-47a4-a3ed-7e0ae62fbffc",
    scryfall_id = "e68c45d3-0f3c-4429-a93e-4ca70ea6b1a4",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Icatian Store",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        static_ability!(Filter::This, Modifier::MayChooseNotToUntap),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }],
            condition = Some(Condition::SourceMatches(&Filter::Tapped))
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::White, Amount::X)]
        ),
    ],
);
