//! Mage-Ring Network — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {C} for each storage counter removed this way.
//! Set: CMM #1009 — Commander Masters | Scryfall ID: f060ea2b-717a-47ae-a4d6-b0594e838459 | Oracle ID: 136596a0-b179-40be-b42d-c0b992621c95
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MAGE_RING_NETWORK,
    oracle_id = "136596a0-b179-40be-b42d-c0b992621c95",
    scryfall_id = "f060ea2b-717a-47ae-a4d6-b0594e838459",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Mage-Ring Network", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf),
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Colorless, Amount::X)]
        ),
    ],
);
