//! Mercadian Bazaar — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {R} for each storage counter removed this way.
//! Set: MMQ #321 — Mercadian Masques | Scryfall ID: 6f787cb6-78cb-4baa-a9cf-cee8b7d8d6b1 | Oracle ID: b02ab3c7-fe4a-443c-b860-ba971d3301b0
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MERCADIAN_BAZAAR,
    oracle_id = "b02ab3c7-fe4a-443c-b860-ba971d3301b0",
    scryfall_id = "6f787cb6-78cb-4baa-a9cf-cee8b7d8d6b1",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mercadian Bazaar",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Red, Amount::X)]
        ),
    ],
);
