//! Molten Slagheap — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Put a storage counter on this land.
//! Oracle: {1}, Remove X storage counters from this land: Add X mana in any combination of {B} and/or {R}.
//! Set: TSR #282 — Time Spiral Remastered | Scryfall ID: 4d952491-3a33-42af-9748-d2cb9c5a2f76 | Oracle ID: 33587cb2-0fd3-4e4c-bc5e-e7299cc9dab5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MOLTEN_SLAGHEAP,
    oracle_id = "33587cb2-0fd3-4e4c-bc5e-e7299cc9dab5",
    scryfall_id = "4d952491-3a33-42af-9748-d2cb9c5a2f76",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Molten Slagheap", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf),
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                "{1}",
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_combination(
                &[ManaColor::Black, ManaColor::Red],
                Amount::X
            )]
        ),
    ],
);
