//! Rushwood Grove — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {G} for each storage counter removed this way.
//! Set: MMQ #325 — Mercadian Masques | Scryfall ID: c315c72c-3e2f-4aff-b7d7-2f709ccec332 | Oracle ID: ccb2f92e-69c0-415c-81cd-52c384b3b233
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RUSHWOOD_GROVE,
    oracle_id = "ccb2f92e-69c0-415c-81cd-52c384b3b233",
    scryfall_id = "c315c72c-3e2f-4aff-b7d7-2f709ccec332",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rushwood Grove",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Green, Amount::X)]
        ),
    ],
);
