//! Saltcrusted Steppe — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Put a storage counter on this land.
//! Oracle: {1}, Remove X storage counters from this land: Add X mana in any combination of {G} and/or {W}.
//! Set: TSR #283 — Time Spiral Remastered | Scryfall ID: f4d757f1-9398-494f-9a24-b01c5c8c6db5 | Oracle ID: 021e4165-2f02-4bd4-86ca-cb7bf4c9e23d
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SALTCRUSTED_STEPPE,
    oracle_id = "021e4165-2f02-4bd4-86ca-cb7bf4c9e23d",
    scryfall_id = "f4d757f1-9398-494f-9a24-b01c5c8c6db5",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Saltcrusted Steppe", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf),
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                "{1}",
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_combination(
                &[ManaColor::Green, ManaColor::White],
                Amount::X
            )]
        ),
    ],
);
