//! Sand Silos — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: You may choose not to untap this land during your untap step.
//! Oracle: At the beginning of your upkeep, if this land is tapped, put a storage counter on it.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {U} for each storage counter removed this way.
//! Set: 5ED #423 — Fifth Edition | Scryfall ID: 6769de45-903f-4269-a100-9ceca1df26ac | Oracle ID: 48a830f1-8965-4f97-b3d8-ca98eab1ba33
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, may choose not to untap, upkeep trigger with an intervening if.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SAND_SILOS,
    oracle_id = "48a830f1-8965-4f97-b3d8-ca98eab1ba33",
    scryfall_id = "6769de45-903f-4269-a100-9ceca1df26ac",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sand Silos",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        static_ability!(Filter::This, Modifier::MayChooseNotToUntap),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }],
            condition = Some(Condition::SourceMatches(&Filter::Tapped))
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Blue, Amount::X)]
        ),
    ],
);
