//! Saprazzan Cove — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {U} for each storage counter removed this way.
//! Set: MMQ #327 — Mercadian Masques | Scryfall ID: 52a69122-19c0-47ec-8bea-478511ba88e6 | Oracle ID: f7dda04a-c9c6-4952-9bbc-87e3c7480347
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SAPRAZZAN_COVE,
    oracle_id = "f7dda04a-c9c6-4952-9bbc-87e3c7480347",
    scryfall_id = "52a69122-19c0-47ec-8bea-478511ba88e6",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Saprazzan Cove",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Blue, Amount::X)]
        ),
    ],
);
