//! Subterranean Hangar — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Put a storage counter on this land.
//! Oracle: {T}, Remove any number of storage counters from this land: Add {B} for each storage counter removed this way.
//! Set: MMQ #329 — Mercadian Masques | Scryfall ID: edc199d1-970b-489f-b713-8285151f16ae | Oracle ID: 0bbd5a04-c281-4afb-98a1-657b4eca102c
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SUBTERRANEAN_HANGAR,
    oracle_id = "0bbd5a04-c281-4afb-98a1-657b4eca102c",
    scryfall_id = "edc199d1-970b-489f-b713-8285151f16ae",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Subterranean Hangar",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        activated!(
            Cost::TAP,
            &[Effect::AddCounter {
                kind: counters::STORAGE,
                amount: Amount::Fixed(1)
            }]
        ),
        mana_ability!(
            cost!(
                TapSelf,
                RemoveCounterSelfX {
                    kind: counters::STORAGE
                }
            ),
            &[Effect::mana_dynamic(ManaColor::Black, Amount::X)]
        ),
    ],
);
