//! Promising Vein — (no cost) — Land — Cave
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.
//! Set: LCI #279 — The Lost Caverns of Ixalan | Scryfall ID: e9681a54-6413-4ff4-b6b1-ee4decb25bfa | Oracle ID: 861eb7d7-7616-4620-a4fd-4b8c3bf00dd1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::PROMISING_VEIN,
    oracle_id = "861eb7d7-7616-4620-a4fd-4b8c3bf00dd1",
    scryfall_id = "e9681a54-6413-4ff4-b6b1-ee4decb25bfa",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Promising Vein",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::CAVE],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(
            cost!("{1}", TapSelf, SacrificeSelf),
            &[Effect::SearchLibrary {
                filter: &SEARCH1,
                finds: &[Find::BATTLEFIELD_TAPPED],
                optional: false
            }]
        ),
    ],
);
