//! Urza's Cave — (no cost) — Land — Urza's Cave
//! Oracle: {T}: Add {C}.
//! Oracle: {3}, {T}, Sacrifice this land: Search your library for a land card, put it onto the battlefield tapped, then shuffle.
//! Set: MH3 #234 — Modern Horizons 3 | Scryfall ID: 926916ed-2f22-4ba9-9427-194886ad6c1e | Oracle ID: 4474ecee-0ec3-409b-90df-738d9313fe3c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::LAND;

card! {
    index: 1266,
    oracle_id: "4474ecee-0ec3-409b-90df-738d9313fe3c",
    scryfall_id: "926916ed-2f22-4ba9-9427-194886ad6c1e",
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Urza's Cave",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::URZA_S, subtypes::land::CAVE],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{3}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::SearchLibrary { filter: &SEARCH1, finds: &[Find::BATTLEFIELD_TAPPED], optional: false }]),
    ],
}
