//! Bristling Backwoods — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, it deals 1 damage to target opponent.
//! Oracle: {T}: Add {R} or {G}.
//! Set: OTJ #253 — Outlaws of Thunder Junction | Scryfall ID: d61dfeb7-7f6b-4601-8396-2cbb98165489 | Oracle ID: 9cbc9f83-8979-42a5-a466-a8d89c8e6de8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 313,
    oracle_id: "9cbc9f83-8979-42a5-a466-a8d89c8e6de8",
    scryfall_id: "d61dfeb7-7f6b-4601-8396-2cbb98165489",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Bristling Backwoods",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::Chosen) }], targets: Some(TargetReq::one(TargetSpec::AnyOpponent))),
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
    ],
}
