//! Conduit Pylons — (no cost) — Land — Desert
//! Oracle: When this land enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Oracle: {T}: Add {C}.
//! Oracle: {1}, {T}: Add one mana of any color.
//! Set: OTJ #254 — Outlaws of Thunder Junction | Scryfall ID: 5ffa48cc-b991-4d47-b7ec-cf678915c758 | Oracle ID: 37f924e1-7c25-4f06-88bb-054693a21e5a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CONDUIT_PYLONS,
    oracle_id = "37f924e1-7c25-4f06-88bb-054693a21e5a",
    scryfall_id = "5ffa48cc-b991-4d47-b7ec-cf678915c758",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Conduit Pylons",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::DESERT],
    ),],
    abilities = &[
        triggered!(Trigger::ETB, &[Effect::surveil(1)]),
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(cost!("{1}", TapSelf), &[Effect::mana_of_any_color()]),
    ],
);
