//! Creosote Heath — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, it deals 1 damage to target opponent.
//! Oracle: {T}: Add {G} or {W}.
//! Set: OTJ #255 — Outlaws of Thunder Junction | Scryfall ID: c5523dac-7aa0-4486-89c8-3b22a1411f26 | Oracle ID: c116b787-5f7e-47ef-a694-58709770dd32
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 384,
    oracle_id: "c116b787-5f7e-47ef-a694-58709770dd32",
    scryfall_id: "c5523dac-7aa0-4486-89c8-3b22a1411f26",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Creosote Heath",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::Chosen) }], targets: Some(TargetReq::one(TargetSpec::AnyOpponent))),
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::White, ManaColor::Green])]),
    ],
}
