//! Desert of the Indomitable — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G}.
//! Oracle: Cycling {1}{G} ({1}{G}, Discard this card: Draw a card.)
//! Set: OTC #285 — Outlaws of Thunder Junction Commander | Scryfall ID: 5728f3ec-62bc-4c56-9242-bc2a5fa175ee | Oracle ID: 852d4dc3-404d-4565-99e9-1eac8f6eca5e
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 416,
    oracle_id: "852d4dc3-404d-4565-99e9-1eac8f6eca5e",
    scryfall_id: "5728f3ec-62bc-4c56-9242-bc2a5fa175ee",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Desert of the Indomitable",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{G}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
