//! Desert of the Glorified — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B}.
//! Oracle: Cycling {1}{B} ({1}{B}, Discard this card: Draw a card.)
//! Set: HOU #171 — Hour of Devastation | Scryfall ID: 04a19aea-209d-4354-8c59-d08244185eb8 | Oracle ID: 190e664b-9875-4335-af46-353886ed18ff
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped, cycling.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 415,
    oracle_id: "190e664b-9875-4335-af46-353886ed18ff",
    scryfall_id: "04a19aea-209d-4354-8c59-d08244185eb8",
    color_identity: ColorSet::from_slice(&[Color::Black]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Desert of the Glorified",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{B}"), parts: &[CostPart::DiscardSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }], zone: ActivationZone::Hand),
    ],
}
