//! Ipnu Rivulet — (no cost) — Land — Desert
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Pay 1 life: Add {U}.
//! Oracle: {1}{U}, {T}, Sacrifice a Desert: Target player mills four cards. (They put the top four cards of their library into their graveyard.)
//! Set: HOU #180 — Hour of Devastation | Scryfall ID: 203011ef-3737-4fd1-bd23-0e531b5a7c32 | Oracle ID: c17d799f-adc9-4c41-87cf-b243b5ea3be1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::DESERT),
    Filter::ControlledByYou,
]);

card!(
    index = index::IPNU_RIVULET,
    oracle_id = "c17d799f-adc9-4c41-87cf-b243b5ea3be1",
    scryfall_id = "203011ef-3737-4fd1-bd23-0e531b5a7c32",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ipnu Rivulet",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::DESERT],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!(TapSelf, PayLife(1)),
            &[Effect::mana(ManaColor::Blue, 1)]
        ),
        activated!(
            cost!("{1}{U}", TapSelf, Sacrifice(&COST1)),
            &[Effect::Mill {
                amount: Amount::Fixed(4),
                target: PlayerRel::Chosen
            }],
            target = Some(TargetSpec::AnyPlayer)
        ),
    ],
);
