//! Mirage Mesa — (no cost) — Land — Desert
//! Oracle: This land enters tapped. As it enters, choose a color.
//! Oracle: {T}: Add one mana of the chosen color.
//! Set: OTJ #262 — Outlaws of Thunder Junction | Scryfall ID: c3d2e816-c06d-4c5d-98fe-c350d8cfab27 | Oracle ID: e103f422-85c0-43f8-8a2f-8b7863e503fa
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MIRAGE_MESA,
    oracle_id = "e103f422-85c0-43f8-8a2f-8b7863e503fa",
    scryfall_id = "c3d2e816-c06d-4c5d-98fe-c350d8cfab27",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mirage Mesa",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::DESERT],
        enter_modifiers = &[EnterModifier::ChooseColor, EnterModifier::Tapped],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_chosen()]),],
);
