//! Soured Springs — (no cost) — Land — Desert
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, it deals 1 damage to target opponent.
//! Oracle: {T}: Add {U} or {B}.
//! Set: OTJ #264 — Outlaws of Thunder Junction | Scryfall ID: 67daa31c-d9c4-4c22-b29c-1b8a17d577e5 | Oracle ID: e579edd7-4f6c-4f22-a72f-0a20d7a698a2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1068,
    oracle_id: "e579edd7-4f6c-4f22-a72f-0a20d7a698a2",
    scryfall_id: "67daa31c-d9c4-4c22-b29c-1b8a17d577e5",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Soured Springs",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::DESERT],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        triggered!(Trigger::EntersBattlefield(&Filter::This), &[Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::Chosen) }], targets: Some(TargetReq::one(TargetSpec::AnyOpponent))),
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
    ],
}
