//! Cave of the Frost Dragon — (no cost) — Land
//! Oracle: If you control two or more other lands, this land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {4}{W}: This land becomes a 3/4 white Dragon creature with flying until end of turn. It's still a land.
//! Set: AFR #253 — Adventures in the Forgotten Realms | Scryfall ID: bdb41396-5008-4a5f-92ca-54ecac42e926 | Oracle ID: 1e4146d2-cfa0-4f5e-9761-3c83519b90c3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CAVE_OF_THE_FROST_DRAGON,
    oracle_id = "1e4146d2-cfa0-4f5e-9761-3c83519b90c3",
    scryfall_id = "bdb41396-5008-4a5f-92ca-54ecac42e926",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Cave of the Frost Dragon",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::TappedUnlessAtMost {
            filter: &Filter::YOUR_LAND,
            at_most: 1
        }],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(
            cost!("{4}{W}"),
            &[
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddType(TypeSet::CREATURE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddSubtype(subtypes::creature::DRAGON),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetColor(ColorSet::from_slice(&[Color::White])),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddKeyword(KeywordSet::FLYING),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetPT(3, 4),
                    Duration::UntilEndOfTurn
                )
            ]
        ),
    ],
);
