//! Celestial Colonnade — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {U}.
//! Oracle: {3}{W}{U}: Until end of turn, this land becomes a 4/4 white and blue Elemental creature with flying and vigilance. It's still a land.
//! Set: UMA #238 — Ultimate Masters | Scryfall ID: 4c830a99-595b-4aed-9f6b-85a78917f498 | Oracle ID: 876ac6f6-74de-4666-84c6-83d81f054723
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CELESTIAL_COLONNADE,
    oracle_id = "876ac6f6-74de-4666-84c6-83d81f054723",
    scryfall_id = "4c830a99-595b-4aed-9f6b-85a78917f498",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Celestial Colonnade",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Blue])]),
        activated!(
            cost!("{3}{W}{U}"),
            &[
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddType(TypeSet::CREATURE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddSubtype(subtypes::creature::ELEMENTAL),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetColor(ColorSet::from_slice(&[Color::White, Color::Blue])),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddKeyword(KeywordSet::FLYING.union(KeywordSet::VIGILANCE)),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetPT(4, 4),
                    Duration::UntilEndOfTurn
                )
            ]
        ),
    ],
);
