//! Faerie Conclave — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U}.
//! Oracle: {1}{U}: This land becomes a 2/1 blue Faerie creature with flying until end of turn. It's still a land.
//! Set: CMA #248 — Commander Anthology | Scryfall ID: 8f4ab639-b439-462e-acc3-69b5d6bb29da | Oracle ID: 0c25f6b1-8fb3-4406-9605-0282d2dbbcec
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FAERIE_CONCLAVE,
    oracle_id = "0c25f6b1-8fb3-4406-9605-0282d2dbbcec",
    scryfall_id = "8f4ab639-b439-462e-acc3-69b5d6bb29da",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Faerie Conclave",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        activated!(
            cost!("{1}{U}"),
            &[
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddType(TypeSet::CREATURE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddSubtype(subtypes::creature::FAERIE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetColor(ColorSet::from_slice(&[Color::Blue])),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddKeyword(KeywordSet::FLYING),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetPT(2, 1),
                    Duration::UntilEndOfTurn
                )
            ]
        ),
    ],
);
