//! Forbidding Watchtower — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {1}{W}: This land becomes a 1/5 white Soldier creature until end of turn. It's still a land.
//! Set: TD2 #39 — Duel Decks: Mirrodin Pure vs. New Phyrexia | Scryfall ID: ac2d2959-6d31-4547-8c04-c19009c94434 | Oracle ID: cabf7953-0fac-4dbb-b3ae-05e85e02b3fc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FORBIDDING_WATCHTOWER,
    oracle_id = "cabf7953-0fac-4dbb-b3ae-05e85e02b3fc",
    scryfall_id = "ac2d2959-6d31-4547-8c04-c19009c94434",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Forbidding Watchtower",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(
            cost!("{1}{W}"),
            &[
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddType(TypeSet::CREATURE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddSubtype(subtypes::creature::SOLDIER),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetColor(ColorSet::from_slice(&[Color::White])),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetPT(1, 5),
                    Duration::UntilEndOfTurn
                )
            ]
        ),
    ],
);
