//! Forbidding Watchtower — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {1}{W}: This land becomes a 1/5 white Soldier creature until end of turn. It's still a land.
//! Set: TD2 #39 — Duel Decks: Mirrodin Pure vs. New Phyrexia | Scryfall ID: ac2d2959-6d31-4547-8c04-c19009c94434 | Oracle ID: cabf7953-0fac-4dbb-b3ae-05e85e02b3fc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 508,
    oracle_id: "cabf7953-0fac-4dbb-b3ae-05e85e02b3fc",
    scryfall_id: "ac2d2959-6d31-4547-8c04-c19009c94434",
    color_identity: ColorSet::from_slice(&[Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Forbidding Watchtower",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana(ManaColor::White, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{W}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::SOLDIER), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::White])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(1, 5), duration: Duration::UntilEndOfTurn }]),
    ],
}
