//! Hissing Quagmire — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {G}.
//! Oracle: {1}{B}{G}: Until end of turn, this land becomes a 2/2 black and green Elemental creature with deathtouch. It's still a land.
//! Set: OGW #171 — Oath of the Gatewatch | Scryfall ID: 6ef11b54-205a-48e9-92d0-5d416be869ef | Oracle ID: 7fff5224-c002-4a32-86fe-9a4b18d78b50
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 631,
    oracle_id: "7fff5224-c002-4a32-86fe-9a4b18d78b50",
    scryfall_id: "6ef11b54-205a-48e9-92d0-5d416be869ef",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Hissing Quagmire",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(Cost::TAP, &[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
        activated!(Cost { mana: baylee_core::mana!("{1}{B}{G}"), parts: &[] }, &[Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddType(TypeSet::CREATURE), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Type, filter: &Filter::This, modifier: Modifier::AddSubtype(subtypes::creature::ELEMENTAL), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Color, filter: &Filter::This, modifier: Modifier::SetColor(ColorSet::from_slice(&[Color::Black, Color::Green])), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::Ability, filter: &Filter::This, modifier: Modifier::AddKeyword(KeywordSet::DEATHTOUCH), duration: Duration::UntilEndOfTurn }, Effect::CreateContinuousEffect { layer: Layer::PtSet, filter: &Filter::This, modifier: Modifier::SetPT(2, 2), duration: Duration::UntilEndOfTurn }]),
    ],
}
