//! Restless Bivouac — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {W}.
//! Oracle: {1}{R}{W}: This land becomes a 2/2 red and white Ox creature until end of turn. It's still a land.
//! Oracle: Whenever this land attacks, put a +1/+1 counter on target creature you control.
//! Set: WOE #257 — Wilds of Eldraine | Scryfall ID: b85e0aed-bfb2-4aa8-a754-849c4d9a6a58 | Oracle ID: b3c7b46f-c9ab-40ca-b50b-a4e0d0bd9be8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[Filter::CREATURE, Filter::ControlledByYou]);

card!(
    index = index::RESTLESS_BIVOUAC,
    oracle_id = "b3c7b46f-c9ab-40ca-b50b-a4e0d0bd9be8",
    scryfall_id = "b85e0aed-bfb2-4aa8-a754-849c4d9a6a58",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Restless Bivouac",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::White])]),
        activated!(
            cost!("{1}{R}{W}"),
            &[
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddType(TypeSet::CREATURE),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::AddSubtype(subtypes::creature::OX),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetColor(ColorSet::from_slice(&[Color::Red, Color::White])),
                    Duration::UntilEndOfTurn
                ),
                Effect::continuous(
                    &Filter::This,
                    Modifier::SetPT(2, 2),
                    Duration::UntilEndOfTurn
                )
            ]
        ),
        triggered!(
            Trigger::Attacks(&Filter::This),
            &[Effect::AddCounter {
                kind: CounterKind::P1P1,
                amount: Amount::Fixed(1)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
        ),
    ],
);
