//! Horror of Horrors — {3}{B}{B} — Enchantment
//! Oracle: Sacrifice a Swamp: Regenerate target black creature. (The next time that creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)
//! Set: 9ED #140 — Ninth Edition | Scryfall ID: fcae6a15-733d-44ae-ab23-a202ed071f28 | Oracle ID: b2e1a1c4-9147-4dfc-b202-c3d3f9c2d3dc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::HasColor(ColorSet::from_slice(&[Color::Black])),
]);

static COST2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::HORROR_OF_HORRORS,
    oracle_id = "b2e1a1c4-9147-4dfc-b202-c3d3f9c2d3dc",
    scryfall_id = "fcae6a15-733d-44ae-ab23-a202ed071f28",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Horror of Horrors",
        mana_cost = mana!("{3}{B}{B}"),
        types = TypeSet::ENCHANTMENT,
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&COST2)),
        &[Effect::regenerate(TargetSpec::Object(&TARGET1))],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
