//! Artifact Blast — {R} — Instant
//! Oracle: Counter target artifact spell.
//! Set: ME4 #108 — Masters Edition IV | Scryfall ID: 9ccecb44-a697-44dd-afd2-3d2546c4595f | Oracle ID: 2d4aedc5-31c5-4281-98e1-b0c2233c3c8a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ARTIFACT_BLAST,
    oracle_id = "2d4aedc5-31c5-4281-98e1-b0c2233c3c8a",
    scryfall_id = "9ccecb44-a697-44dd-afd2-3d2546c4595f",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Artifact Blast",
        mana_cost = mana!("{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::CounterTargetSpell],
        targets = Some(TargetReq::one(TargetSpec::Spell(&Filter::ARTIFACT)))
    ),],
);
