//! Demystify — {W} — Instant
//! Oracle: Destroy target enchantment.
//! Set: XLN #8 — Ixalan | Scryfall ID: e3979b88-ac58-420a-8c03-37ea5d93d0f1 | Oracle ID: fd591199-9f7a-4147-a150-13279dbb4498
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DEMYSTIFY,
    oracle_id = "fd591199-9f7a-4147-a150-13279dbb4498",
    scryfall_id = "e3979b88-ac58-420a-8c03-37ea5d93d0f1",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Demystify",
        mana_cost = mana!("{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ENCHANTMENT)))
    ),],
);
