//! Enrage — {X}{R} — Instant
//! Oracle: Target creature gets +X/+0 until end of turn.
//! Set: 9ED #180 — Ninth Edition | Scryfall ID: 2f10e9f0-32c6-40cc-b16d-5590662cdb33 | Oracle ID: 0f6e66d5-4f27-485b-999d-ee55c1e218b9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ENRAGE,
    oracle_id = "0f6e66d5-4f27-485b-999d-ee55c1e218b9",
    scryfall_id = "2f10e9f0-32c6-40cc-b16d-5590662cdb33",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Enrage",
        mana_cost = mana!("{X}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::X,
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
