//! Flash Flood — {U} — Instant
//! Oracle: Choose one —
//! Oracle: • Destroy target red permanent.
//! Oracle: • Return target Mountain to its owner's hand.
//! Set: ME3 #35 — Masters Edition III | Scryfall ID: 1d0aa638-6e51-4fd0-90e3-685db31b2c7a | Oracle ID: c2b5d847-f52a-43e3-a5d2-d53cae3d8936
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::HasColor(ColorSet::from_slice(&[Color::Red]));

static TARGET2: Filter = Filter::HasSubtype(subtypes::land::MOUNTAIN);

card!(
    index = index::FLASH_FLOOD,
    oracle_id = "c2b5d847-f52a-43e3-a5d2-d53cae3d8936",
    scryfall_id = "1d0aa638-6e51-4fd0-90e3-685db31b2c7a",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Flash Flood",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[AbilityDef::ModalSpell {
        choose: ModeCount::ONE,
        modes: &[
            mode!(
                &[Effect::destroy(TargetSpec::Object(&TARGET1))],
                targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
            ),
            mode!(
                &[Effect::bounce(TargetSpec::Object(&TARGET2))],
                targets = Some(TargetReq::one(TargetSpec::Object(&TARGET2)))
            )
        ]
    },],
);
