//! Healing Salve — {W} — Instant
//! Oracle: Choose one —
//! Oracle: • Target player gains 3 life.
//! Oracle: • Prevent the next 3 damage that would be dealt to any target this turn.
//! Set: DVD #14 — Duel Decks Anthology: Divine vs. Demonic | Scryfall ID: 0ff82aba-9022-4eff-a6dc-67365360d646 | Oracle ID: 8da8644c-75a1-4fe9-8e94-900d948d631c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::HEALING_SALVE,
    oracle_id = "8da8644c-75a1-4fe9-8e94-900d948d631c",
    scryfall_id = "0ff82aba-9022-4eff-a6dc-67365360d646",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Healing Salve",
        mana_cost = mana!("{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[AbilityDef::ModalSpell {
        choose: ModeCount::ONE,
        modes: &[
            mode!(
                &[Effect::GainLifeFor {
                    amount: Amount::Fixed(3),
                    who: PlayerRel::Chosen
                }],
                targets = Some(TargetReq::one(TargetSpec::AnyPlayer))
            ),
            mode!(
                &[Effect::PreventNextDamage {
                    target: TargetSpec::AnyTarget,
                    amount: Amount::Fixed(3)
                }],
                targets = Some(TargetReq::one(TargetSpec::AnyTarget))
            )
        ]
    },],
);
