//! Iron Will — {W} — Instant
//! Oracle: Target creature gets +0/+4 until end of turn.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: ULG #10 — Urza's Legacy | Scryfall ID: bee0ee84-6c22-4649-b621-e3fdb08bbe45 | Oracle ID: dc0decb9-32da-47aa-a51a-0d9c623c534a
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::IRON_WILL,
    oracle_id = "dc0decb9-32da-47aa-a51a-0d9c623c534a",
    scryfall_id = "bee0ee84-6c22-4649-b621-e3fdb08bbe45",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Iron Will",
        mana_cost = mana!("{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{2}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(4),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
    ],
);
