//! Jump — {U} — Instant
//! Oracle: Target creature gains flying until end of turn.
//! Set: M10 #59 — Magic 2010 | Scryfall ID: 2edd7be9-9334-4684-b642-1aaf2000e054 | Oracle ID: f7518456-45ed-41d4-bd3c-5aacea28eb35
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::JUMP,
    oracle_id = "f7518456-45ed-41d4-bd3c-5aacea28eb35",
    scryfall_id = "2edd7be9-9334-4684-b642-1aaf2000e054",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Jump",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
