//! Leap — {U} — Instant
//! Oracle: Target creature gains flying until end of turn.
//! Oracle: Draw a card.
//! Set: STH #35 — Stronghold | Scryfall ID: 0841423d-7a27-4bc5-9ac2-0ba47648c6f1 | Oracle ID: e89a3ce0-6b38-4326-a7af-8575af371baa
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::LEAP,
    oracle_id = "e89a3ce0-6b38-4326-a7af-8575af371baa",
    scryfall_id = "0841423d-7a27-4bc5-9ac2-0ba47648c6f1",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Leap",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FLYING,
                duration: Duration::UntilEndOfTurn
            },
            Effect::draw(1)
        ],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
