//! Opt — {U} — Instant
//! Oracle: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Oracle: Draw a card.
//! Set: TDC #158 — Tarkir: Dragonstorm Commander | Scryfall ID: bbc99a51-1501-4525-a3cc-f48249b64bed | Oracle ID: 713332c1-5bd8-400f-bfff-c1ca0697a043
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::OPT,
    oracle_id = "713332c1-5bd8-400f-bfff-c1ca0697a043",
    scryfall_id = "bbc99a51-1501-4525-a3cc-f48249b64bed",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Opt",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(&[Effect::scry(1), Effect::draw(1)]),],
);
