//! Red Elemental Blast — {R} — Instant
//! Oracle: Choose one —
//! Oracle: • Counter target blue spell.
//! Oracle: • Destroy target blue permanent.
//! Set: A25 #147 — Masters 25 | Scryfall ID: 70a45e9b-699e-425a-9f3d-267274830d3e | Oracle ID: bb329a5c-b9f9-4973-a53f-090024146325
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static TARGET1: Filter = Filter::HasColor(ColorSet::from_slice(&[Color::Blue]));

card!(
    index = index::RED_ELEMENTAL_BLAST,
    oracle_id = "bb329a5c-b9f9-4973-a53f-090024146325",
    scryfall_id = "70a45e9b-699e-425a-9f3d-267274830d3e",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Red Elemental Blast",
        mana_cost = mana!("{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[AbilityDef::ModalSpell {
        choose: ModeCount::ONE,
        modes: &[
            mode!(
                &[Effect::CounterTargetSpell],
                targets = Some(TargetReq::one(TargetSpec::Spell(&TARGET1)))
            ),
            mode!(
                &[Effect::destroy(TargetSpec::Object(&TARGET1))],
                targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
            )
        ]
    },],
);
