//! Rescue — {U} — Instant
//! Oracle: Return target permanent you control to its owner's hand.
//! Set: DOM #63 — Dominaria | Scryfall ID: 08050607-b558-4f99-b716-bbbab54e9b68 | Oracle ID: f0ae687a-7222-4521-a514-ba10373fed7e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RESCUE,
    oracle_id = "f0ae687a-7222-4521-a514-ba10373fed7e",
    scryfall_id = "08050607-b558-4f99-b716-bbbab54e9b68",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rescue",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::bounce(TargetSpec::Object(&Filter::ControlledByYou))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ControlledByYou)))
    ),],
);
