//! Sandstorm — {G} — Instant
//! Oracle: Sandstorm deals 1 damage to each attacking creature.
//! Set: DMR #174 — Dominaria Remastered | Scryfall ID: 25fb3d07-a128-455a-a632-c1aba4a4ceb8 | Oracle ID: 7bb41690-f8ec-462a-ba29-be453eb86fca
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SANDSTORM,
    oracle_id = "7bb41690-f8ec-462a-ba29-be453eb86fca",
    scryfall_id = "25fb3d07-a128-455a-a632-c1aba4a4ceb8",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sandstorm",
        mana_cost = mana!("{G}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(&[Effect::DealDamageEach {
        amount: Amount::Fixed(1),
        filter: &Filter::ATTACKING_CREATURE
    }]),],
);
