//! Spark Spray — {R} — Instant
//! Oracle: Spark Spray deals 1 damage to any target.
//! Oracle: Cycling {R} ({R}, Discard this card: Draw a card.)
//! Set: DMR #141 — Dominaria Remastered | Scryfall ID: 22844a75-7064-4108-921f-6a590aa2e71c | Oracle ID: c37f1921-7ac3-4185-8579-1dfdfe647ea2
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPARK_SPRAY,
    oracle_id = "c37f1921-7ac3-4185-8579-1dfdfe647ea2",
    scryfall_id = "22844a75-7064-4108-921f-6a590aa2e71c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spark Spray",
        mana_cost = mana!("{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{R}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::AnyTarget
            }],
            targets = Some(TargetReq::one(TargetSpec::AnyTarget))
        ),
    ],
);
