//! Stand Firm — {W} — Instant
//! Oracle: Target creature gets +1/+1 until end of turn. Scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)
//! Set: DDL #21 — Duel Decks: Heroes vs. Monsters | Scryfall ID: 8b5b719d-9527-4df1-b51f-f1827952cab4 | Oracle ID: c0406e70-8131-4e13-b1d5-4e943ad296b8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STAND_FIRM,
    oracle_id = "c0406e70-8131-4e13-b1d5-4e943ad296b8",
    scryfall_id = "8b5b719d-9527-4df1-b51f-f1827952cab4",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stand Firm",
        mana_cost = mana!("{W}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            },
            Effect::scry(2)
        ],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
