//! Thoughtlace — {U} — Instant
//! Oracle: Target spell or permanent becomes blue. (Mana symbols on that permanent remain unchanged.)
//! Set: 4ED #107 — Fourth Edition | Scryfall ID: 185674a4-db97-444d-b0e9-7dcfc245ce4b | Oracle ID: 6452b6a6-6235-46a3-a712-a26592450438
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::THOUGHTLACE,
    oracle_id = "6452b6a6-6235-46a3-a712-a26592450438",
    scryfall_id = "185674a4-db97-444d-b0e9-7dcfc245ce4b",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thoughtlace",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::continuous(
            &Filter::This,
            Modifier::SetColor(ColorSet::from_slice(&[Color::Blue])),
            Duration::Indefinitely
        )],
        targets = Some(TargetReq::one(TargetSpec::StackOrBattlefield(&Filter::Any)))
    ),],
);
