//! Unsummon — {U} — Instant
//! Oracle: Return target creature to its owner's hand.
//! Set: FRA #46 — Reality Fracture | Scryfall ID: ddad9f16-52d5-49de-82b0-b1a5294a9c44 | Oracle ID: 837182db-1bf3-4a2c-bd01-1af9d9873561
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::UNSUMMON,
    oracle_id = "837182db-1bf3-4a2c-bd01-1af9d9873561",
    scryfall_id = "ddad9f16-52d5-49de-82b0-b1a5294a9c44",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Unsummon",
        mana_cost = mana!("{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::bounce(TargetSpec::Object(&Filter::CREATURE))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
