//! Shifting Wall — {X} — Artifact Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: This creature enters with X +1/+1 counters on it.
//! Set: STH #140 — Stronghold | Scryfall ID: 49b7a950-bf79-46fa-8b29-b7856b38e0fd | Oracle ID: 7c852dfe-8238-461e-814e-9667807f2cf5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SHIFTING_WALL,
    oracle_id = "7c852dfe-8238-461e-814e-9667807f2cf5",
    scryfall_id = "49b7a950-bf79-46fa-8b29-b7856b38e0fd",
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shifting Wall",
        mana_cost = mana!("{X}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(0),
        enter_modifiers = &[EnterModifier::WithCounters {
            kind: CounterKind::P1P1,
            amount: Amount::X
        }],
    ),],
);
