//! Shivan Reef — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {U} or {R}. This land deals 1 damage to you.
//! Set: FRC #83 — Reality Fracture Commander | Scryfall ID: 9fb3938c-9ecf-46cc-865a-0091455419f9 | Oracle ID: 0fe16212-66c3-4e45-a641-7391e9b2e304
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SHIVAN_REEF,
    oracle_id = "0fe16212-66c3-4e45-a641-7391e9b2e304",
    scryfall_id = "9fb3938c-9ecf-46cc-865a-0091455419f9",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Shivan Reef", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[
            Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red]),
            Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }
        ]),
    ],
);
