//! Yavimaya Coast — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {G} or {U}. This land deals 1 damage to you.
//! Set: SOC #425 — Secrets of Strixhaven Commander | Scryfall ID: f4c1500b-1f4c-4d33-810c-25e3bb0a4666 | Oracle ID: 40b36bc6-c185-4bda-99e7-0118953c2c97
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, printed abilities.

use baylee_cards_dsl::prelude::*;

card! {
    index: 1336,
    oracle_id: "40b36bc6-c185-4bda-99e7-0118953c2c97",
    scryfall_id: "f4c1500b-1f4c-4d33-810c-25e3bb0a4666",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Yavimaya Coast",
        types: TypeSet::LAND,
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue]), Effect::DealDamage { amount: Amount::Fixed(1), target: TargetSpec::Player(PlayerRel::You) }]),
    ],
}
