//! Quandrix Campus — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {U}.
//! Oracle: {4}, {T}: Scry 1. (Look at the top card of your library. You may put that card on the bottom.)
//! Set: SOC #395 — Secrets of Strixhaven Commander | Scryfall ID: ce75bbae-99ff-4822-9835-5372ebaedb07 | Oracle ID: 172f86b6-9580-4eb2-b7dc-2a44277d978b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;

card! {
    index: 882,
    oracle_id: "172f86b6-9580-4eb2-b7dc-2a44277d978b",
    scryfall_id: "ce75bbae-99ff-4822-9835-5372ebaedb07",
    color_identity: ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Quandrix Campus",
        types: TypeSet::LAND,
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
        activated!(Cost { mana: baylee_core::mana!("{4}"), parts: &[CostPart::TapSelf] }, &[Effect::Scry { amount: Amount::Fixed(1) }]),
    ],
}
