//! Black Ward — {W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has protection from black. This effect doesn't remove this Aura.
//! Set: 4ED #8 — Fourth Edition | Scryfall ID: 218b1327-5f76-4ee2-a93d-d2ba412043c2 | Oracle ID: 7861ac9b-3024-4935-804c-2ca4c5a46bf4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BLACK_WARD,
    oracle_id = "7861ac9b-3024-4935-804c-2ca4c5a46bf4",
    scryfall_id = "218b1327-5f76-4ee2-a93d-d2ba412043c2",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Black Ward",
        mana_cost = mana!("{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ProtectionFrom(&Filter::And(&[
                Filter::HasColor(ColorSet::from_slice(&[Color::Black])),
                Filter::Not(&Filter::This)
            ]))
        ),
    ],
);
