//! Capashen Standard — {W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +1/+1.
//! Oracle: {2}, Sacrifice this Aura: Draw a card.
//! Set: UDS #4 — Urza's Destiny | Scryfall ID: 16665386-405e-48c9-8c69-c21b03931c2f | Oracle ID: 75510429-41bb-409e-b6fe-04a8bb174c6b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CAPASHEN_STANDARD,
    oracle_id = "75510429-41bb-409e-b6fe-04a8bb174c6b",
    scryfall_id = "16665386-405e-48c9-8c69-c21b03931c2f",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Capashen Standard",
        mana_cost = mana!("{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 1)
        ),
        activated!(cost!("{2}", SacrificeSelf), &[Effect::draw(1)]),
    ],
);
