//! Crackling Club — {R} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets +1/+0.
//! Oracle: Sacrifice this Aura: It deals 1 damage to target creature.
//! Set: TOR #93 — Torment | Scryfall ID: 0810f7e3-03ff-4c46-a88f-2f8144540780 | Oracle ID: 876affb5-155d-4268-9e46-4437a9fbccc7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CRACKLING_CLUB,
    oracle_id = "876affb5-155d-4268-9e46-4437a9fbccc7",
    scryfall_id = "0810f7e3-03ff-4c46-a88f-2f8144540780",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crackling Club",
        mana_cost = mana!("{R}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 0)
        ),
        activated!(
            cost!(SacrificeSelf),
            &[Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
