//! Frog Tongue — {G} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: When this Aura enters, draw a card.
//! Oracle: Enchanted creature has reach. (It can block creatures with flying.)
//! Set: TMP #228 — Tempest | Scryfall ID: 3941e799-a254-423e-90bb-091dbe56ca6a | Oracle ID: 861c5374-a8e7-4684-9a1b-e6ce3b98e4a2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FROG_TONGUE,
    oracle_id = "861c5374-a8e7-4684-9a1b-e6ce3b98e4a2",
    scryfall_id = "3941e799-a254-423e-90bb-091dbe56ca6a",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Frog Tongue",
        mana_cost = mana!("{G}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::REACH)
        ),
        triggered!(Trigger::ETB, &[Effect::draw(1)]),
    ],
);
