//! Green Ward — {W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has protection from green. This effect doesn't remove this Aura.
//! Set: 4ED #27 — Fourth Edition | Scryfall ID: b7548dc7-11dc-4611-85a5-71bdb48d8a62 | Oracle ID: 727ab7f2-741e-4442-b5cb-e3032549fa87
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GREEN_WARD,
    oracle_id = "727ab7f2-741e-4442-b5cb-e3032549fa87",
    scryfall_id = "b7548dc7-11dc-4611-85a5-71bdb48d8a62",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Green Ward",
        mana_cost = mana!("{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ProtectionFrom(&Filter::And(&[
                Filter::HasColor(ColorSet::from_slice(&[Color::Green])),
                Filter::Not(&Filter::This)
            ]))
        ),
    ],
);
