//! Imposing Visage — {R} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has menace. (It can't be blocked except by two or more creatures.)
//! Set: 5ED #241 — Fifth Edition | Scryfall ID: 24a256b0-e25b-43c6-9f7a-2ad76b268d22 | Oracle ID: 6f67058b-ed14-4e3c-9af3-d61570870e36
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::IMPOSING_VISAGE,
    oracle_id = "6f67058b-ed14-4e3c-9af3-d61570870e36",
    scryfall_id = "24a256b0-e25b-43c6-9f7a-2ad76b268d22",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Imposing Visage",
        mana_cost = mana!("{R}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::MENACE)
        ),
    ],
);
