//! Paralyze — {B} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: When this Aura enters, tap enchanted creature.
//! Oracle: Enchanted creature doesn't untap during its controller's untap step.
//! Oracle: At the beginning of the upkeep of enchanted creature's controller, that player may pay {4}. If the player does, untap the creature.
//! Set: VMA #132 — Vintage Masters | Scryfall ID: fe85610f-b17e-4628-8f6b-544ea7b34327 | Oracle ID: e9b4e857-39e5-4a06-89ad-3dd94b3f252a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PARALYZE,
    oracle_id = "e9b4e857-39e5-4a06-89ad-3dd94b3f252a",
    scryfall_id = "fe85610f-b17e-4628-8f6b-544ea7b34327",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Paralyze",
        mana_cost = mana!("{B}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        triggered!(
            Trigger::ETB,
            &[Effect::TapAll {
                filter: &Filter::AttachedToBySource
            }]
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::DoesNotUntap
        ),
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::ControllerOfAttached
            },
            &[Effect::PlayerMayPayThen {
                player: PlayerRel::ControllerOfAttached,
                mana: Amount::Fixed(4),
                effects: &[Effect::UntapAll {
                    filter: &Filter::AttachedToBySource
                }]
            }]
        ),
    ],
);
