//! Red Ward — {W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has protection from red. This effect doesn't remove this Aura.
//! Set: 4ED #44 — Fourth Edition | Scryfall ID: 543e8ec0-f36a-46a6-b7b1-e983e90a091a | Oracle ID: 73f84440-425f-4cf5-b01a-3ae89f1f6e37
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RED_WARD,
    oracle_id = "73f84440-425f-4cf5-b01a-3ae89f1f6e37",
    scryfall_id = "543e8ec0-f36a-46a6-b7b1-e983e90a091a",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Red Ward",
        mana_cost = mana!("{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ProtectionFrom(&Filter::And(&[
                Filter::HasColor(ColorSet::from_slice(&[Color::Red])),
                Filter::Not(&Filter::This)
            ]))
        ),
    ],
);
