//! Robe of Mirrors — {U} — Enchantment — Aura
//! Oracle: Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
//! Oracle: Enchanted creature has shroud. (It can't be the target of spells or abilities.)
//! Set: 10E #101 — Tenth Edition | Scryfall ID: 9948fcc3-6e95-4b39-accd-a4083fff1244 | Oracle ID: 093a20e5-ff14-41c7-b16c-1f745ddf6942
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ROBE_OF_MIRRORS,
    oracle_id = "093a20e5-ff14-41c7-b16c-1f745ddf6942",
    scryfall_id = "9948fcc3-6e95-4b39-accd-a4083fff1244",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Robe of Mirrors",
        mana_cost = mana!("{U}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::SHROUD)
        ),
    ],
);
