//! Sicken — {B} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature gets -1/-1.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: USG #156 — Urza's Saga | Scryfall ID: aa1beb5d-0ef2-4013-932b-5e4a5d0af559 | Oracle ID: 5208a5f2-eebe-4adc-8f29-543b60116817
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SICKEN,
    oracle_id = "5208a5f2-eebe-4adc-8f29-543b60116817",
    scryfall_id = "aa1beb5d-0ef2-4013-932b-5e4a5d0af559",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sicken",
        mana_cost = mana!("{B}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        activated!(
            cost!("{2}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(-1, -1)
        ),
    ],
);
