//! Web — {G} — Enchantment — Aura
//! Oracle: Enchant creature (Target a creature as you cast this. This card enters attached to that creature.)
//! Oracle: Enchanted creature gets +0/+2 and has reach. (It can block creatures with flying.)
//! Set: 9ED #281 — Ninth Edition | Scryfall ID: 91173ce1-62a9-4d0e-8b2a-9bc33858c4fc | Oracle ID: 5aa12aff-db3c-4be5-822b-3afdf536b33e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WEB,
    oracle_id = "5aa12aff-db3c-4be5-822b-3afdf536b33e",
    scryfall_id = "91173ce1-62a9-4d0e-8b2a-9bc33858c4fc",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Web",
        mana_cost = mana!("{G}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(0, 2)
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::REACH)
        ),
    ],
);
