//! White Ward — {W} — Enchantment — Aura
//! Oracle: Enchant creature
//! Oracle: Enchanted creature has protection from white. This effect doesn't remove this Aura.
//! Set: 4ED #57 — Fourth Edition | Scryfall ID: 2d3c467f-0e33-43e8-b108-0ea00d6adcc2 | Oracle ID: 860468b3-625a-4663-a5ae-336ae10fc7d0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WHITE_WARD,
    oracle_id = "860468b3-625a-4663-a5ae-336ae10fc7d0",
    scryfall_id = "2d3c467f-0e33-43e8-b108-0ea00d6adcc2",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "White Ward",
        mana_cost = mana!("{W}"),
        types = TypeSet::ENCHANTMENT,
        subtypes = &[subtypes::enchantment::AURA],
    ),],
    abilities = &[
        spell!(
            &[Effect::AttachSelf {
                target: TargetSpec::Object(&Filter::CREATURE)
            }],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
        ),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ProtectionFrom(&Filter::And(&[
                Filter::HasColor(ColorSet::from_slice(&[Color::White])),
                Filter::Not(&Filter::This)
            ]))
        ),
    ],
);
