//! Agent of Stromgald — {R} — Creature — Human Knight
//! Oracle: {R}: Add {B}.
//! Set: ALL #64a — Alliances | Scryfall ID: 4a7506f8-cf09-46ca-ad80-3c398c487ae2 | Oracle ID: 099fd4b3-92fd-4b5f-bb4f-eefa6f09700c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AGENT_OF_STROMGALD,
    oracle_id = "099fd4b3-92fd-4b5f-bb4f-eefa6f09700c",
    scryfall_id = "4a7506f8-cf09-46ca-ad80-3c398c487ae2",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Agent of Stromgald",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::KNIGHT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(
        cost!("{R}"),
        &[Effect::mana(ManaColor::Black, 1)]
    ),],
);
