//! Akki Avalanchers — {R} — Creature — Goblin Warrior
//! Oracle: Sacrifice a land: This creature gets +2/+0 until end of turn. Activate only once each turn.
//! Set: CHK #151 — Champions of Kamigawa | Scryfall ID: bfef6acb-a11c-4a3f-9cfb-9394dece2675 | Oracle ID: 5a98decb-30ba-4c34-a88a-424b7f4e03bc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AKKI_AVALANCHERS,
    oracle_id = "5a98decb-30ba-4c34-a88a-424b7f4e03bc",
    scryfall_id = "bfef6acb-a11c-4a3f-9cfb-9394dece2675",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Akki Avalanchers",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::WARRIOR],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&Filter::YOUR_LAND)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
