//! Ana Disciple — {G} — Creature — Human Wizard
//! Oracle: {U}, {T}: Target creature gains flying until end of turn.
//! Oracle: {B}, {T}: Target creature gets -2/-0 until end of turn.
//! Set: APC #73 — Apocalypse | Scryfall ID: 7efe00f9-bf42-4d6f-9a22-b357b1c1e092 | Oracle ID: f543dfcd-015e-48bc-851d-08002d0241fa
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ANA_DISCIPLE,
    oracle_id = "f543dfcd-015e-48bc-851d-08002d0241fa",
    scryfall_id = "7efe00f9-bf42-4d6f-9a22-b357b1c1e092",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ana Disciple",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{U}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FLYING,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{B}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::NegXFixed(2),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
