//! Aven Envoy — {U} — Creature — Bird Soldier
//! Oracle: Flying
//! Set: LGN #30 — Legions | Scryfall ID: 40ead30e-9f96-4fca-b619-fdc8d1b5e2e0 | Oracle ID: 73cd8461-7930-4e2d-9a14-4d10db91e93e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AVEN_ENVOY,
    oracle_id = "73cd8461-7930-4e2d-9a14-4d10db91e93e",
    scryfall_id = "40ead30e-9f96-4fca-b619-fdc8d1b5e2e0",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aven Envoy",
        mana_cost = mana!("{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD, subtypes::creature::SOLDIER],
        power = Some(0),
        toughness = Some(2),
    ),],
);
