//! Blood Pet — {B} — Creature — Thrull
//! Oracle: Sacrifice this creature: Add {B}.
//! Set: 7ED #121 — Seventh Edition | Scryfall ID: 9ff08225-82a5-4636-be6a-d38d32f5663f | Oracle ID: e05c6c80-a91a-45e0-b991-0014fd5a6472
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BLOOD_PET,
    oracle_id = "e05c6c80-a91a-45e0-b991-0014fd5a6472",
    scryfall_id = "9ff08225-82a5-4636-be6a-d38d32f5663f",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Blood Pet",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::THRULL],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(
        cost!(SacrificeSelf),
        &[Effect::mana(ManaColor::Black, 1)]
    ),],
);
