//! Cabal Trainee — {B} — Creature — Human Minion
//! Oracle: Sacrifice this creature: Target creature gets -2/-0 until end of turn.
//! Set: JUD #63 — Judgment | Scryfall ID: d345d702-b205-4391-985a-6201e707f0ba | Oracle ID: fce68545-c31d-4dc2-9f1b-aadf924a07d1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CABAL_TRAINEE,
    oracle_id = "fce68545-c31d-4dc2-9f1b-aadf924a07d1",
    scryfall_id = "d345d702-b205-4391-985a-6201e707f0ba",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Cabal Trainee",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MINION],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(SacrificeSelf),
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
