//! Dega Disciple — {W} — Creature — Human Wizard
//! Oracle: {B}, {T}: Target creature gets -2/-0 until end of turn.
//! Oracle: {R}, {T}: Target creature gets +2/+0 until end of turn.
//! Set: APC #4 — Apocalypse | Scryfall ID: fb9cd7d9-8aad-4607-890c-9c8efe016a92 | Oracle ID: c6c53277-daad-4aa3-b29a-11378d550651
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DEGA_DISCIPLE,
    oracle_id = "c6c53277-daad-4aa3-b29a-11378d550651",
    scryfall_id = "fb9cd7d9-8aad-4607-890c-9c8efe016a92",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dega Disciple",
        mana_cost = mana!("{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{B}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::NegXFixed(2),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{R}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
