//! Electric Eel — {U} — Creature — Fish
//! Oracle: When this creature enters, it deals 1 damage to you.
//! Oracle: {R}{R}: This creature gets +2/+0 until end of turn and deals 1 damage to you.
//! Set: DRK #25 — The Dark | Scryfall ID: b8834c18-0e4e-4785-9d15-b33345e3789b | Oracle ID: ad8213db-074d-475c-b94a-9f1e81c8f4fd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ELECTRIC_EEL,
    oracle_id = "ad8213db-074d-475c-b94a-9f1e81c8f4fd",
    scryfall_id = "b8834c18-0e4e-4785-9d15-b33345e3789b",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Electric Eel",
        mana_cost = mana!("{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FISH],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{R}{R}"),
            &[
                Effect::PumpFilter {
                    filter: &Filter::This,
                    controlled_by: None,
                    power: Amount::Fixed(2),
                    toughness: Amount::Fixed(0),
                    keywords: KeywordSet::EMPTY,
                    duration: Duration::UntilEndOfTurn
                },
                Effect::DealDamage {
                    amount: Amount::Fixed(1),
                    target: TargetSpec::Player(PlayerRel::You)
                }
            ]
        ),
        triggered!(
            Trigger::ETB,
            &[Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::Player(PlayerRel::You)
            }]
        ),
    ],
);
