//! Elvish Herder — {G} — Creature — Elf
//! Oracle: {G}: Target creature gains trample until end of turn.
//! Set: USG #247 — Urza's Saga | Scryfall ID: 3cb2b07e-3d50-4b85-be2a-c99e9c8ebf25 | Oracle ID: 7832b90a-23b9-448c-9019-8ee2e8dfab31
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ELVISH_HERDER,
    oracle_id = "7832b90a-23b9-448c-9019-8ee2e8dfab31",
    scryfall_id = "3cb2b07e-3d50-4b85-be2a-c99e9c8ebf25",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Elvish Herder",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{G}"),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::TRAMPLE,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
