//! Elvish Lyrist — {G} — Creature — Elf
//! Oracle: {G}, {T}, Sacrifice this creature: Destroy target enchantment.
//! Set: 8ED #242 — Eighth Edition | Scryfall ID: 4a1da8da-12b2-47aa-9565-92d305061798 | Oracle ID: e0de1c9b-f71f-4498-a968-d3c635cb4c5c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ELVISH_LYRIST,
    oracle_id = "e0de1c9b-f71f-4498-a968-d3c635cb4c5c",
    scryfall_id = "4a1da8da-12b2-47aa-9565-92d305061798",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Elvish Lyrist",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{G}", TapSelf, SacrificeSelf),
        &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
        target = Some(TargetSpec::Object(&Filter::ENCHANTMENT))
    ),],
);
