//! Festering Goblin — {B} — Creature — Zombie Goblin
//! Oracle: When this creature dies, target creature gets -1/-1 until end of turn.
//! Set: DMR #85 — Dominaria Remastered | Scryfall ID: b039f65e-1287-4c6e-a1c2-773a008fc0a3 | Oracle ID: 66fb4764-d309-4c30-a2a4-474f9030dc87
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FESTERING_GOBLIN,
    oracle_id = "66fb4764-d309-4c30-a2a4-474f9030dc87",
    scryfall_id = "b039f65e-1287-4c6e-a1c2-773a008fc0a3",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Festering Goblin",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ZOMBIE, subtypes::creature::GOBLIN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::This),
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(1),
            toughness: Amount::NegXFixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
