//! Goblin Sledder — {R} — Creature — Goblin
//! Oracle: Sacrifice a Goblin: Target creature gets +1/+1 until end of turn.
//! Set: EVG #41 — Duel Decks Anthology: Elves vs. Goblins | Scryfall ID: 12af10e9-19b7-4177-b556-a446f2788da7 | Oracle ID: ae93292a-458a-441b-a7de-4b10f0d20cc0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::GOBLIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::GOBLIN_SLEDDER,
    oracle_id = "ae93292a-458a-441b-a7de-4b10f0d20cc0",
    scryfall_id = "12af10e9-19b7-4177-b556-a446f2788da7",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Goblin Sledder",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&COST1)),
        &[Effect::PumpTarget {
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
