//! Icatian Priest — {W} — Creature — Human Cleric
//! Oracle: {1}{W}{W}: Target creature gets +1/+1 until end of turn.
//! Set: DVD #2 — Duel Decks Anthology: Divine vs. Demonic | Scryfall ID: f48ce122-b966-4c48-9b6c-b84dd0584cb9 | Oracle ID: 3a9d29ce-e8e2-402f-b0c2-873f70418234
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ICATIAN_PRIEST,
    oracle_id = "3a9d29ce-e8e2-402f-b0c2-873f70418234",
    scryfall_id = "f48ce122-b966-4c48-9b6c-b84dd0584cb9",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Icatian Priest",
        mana_cost = mana!("{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::CLERIC],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{1}{W}{W}"),
        &[Effect::PumpTarget {
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
