//! Kird Ape — {R} — Creature — Ape
//! Oracle: This creature gets +1/+2 as long as you control a Forest.
//! Set: EMA #137 — Eternal Masters | Scryfall ID: e14a5c79-29a3-4415-9b70-b287a474a0e0 | Oracle ID: fbbc3acb-c917-44ff-ac6f-9dd6ebe3f4ad
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::FOREST),
    Filter::ControlledByYou,
]);

card!(
    index = index::KIRD_APE,
    oracle_id = "fbbc3acb-c917-44ff-ac6f-9dd6ebe3f4ad",
    scryfall_id = "e14a5c79-29a3-4415-9b70-b287a474a0e0",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kird Ape",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::APE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[static_ability!(
        Filter::This,
        Modifier::ModifyPT(1, 2),
        condition = Some(Condition::ControlCount(&CHECK1, 1))
    ),],
);
