//! Kris Mage — {R} — Creature — Human Spellshaper
//! Oracle: {R}, {T}, Discard a card: This creature deals 1 damage to any target.
//! Set: MMQ #195 — Mercadian Masques | Scryfall ID: 4389fbcd-182a-4cac-b14f-aa971948cf8e | Oracle ID: d53623b0-f7d8-401f-a8f1-80034f6f20df
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KRIS_MAGE,
    oracle_id = "d53623b0-f7d8-401f-a8f1-80034f6f20df",
    scryfall_id = "4389fbcd-182a-4cac-b14f-aa971948cf8e",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kris Mage",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SPELLSHAPER],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{R}", TapSelf, Discard(&Filter::Any)),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
