//! Merfolk of the Pearl Trident — {U} — Creature — Merfolk
//! Set: M13 #60 — Magic 2013 | Scryfall ID: a360fe4e-c9a6-42fa-a97a-8b5a0c19ef93 | Oracle ID: 218d9277-c179-4de3-9c7f-79b5a6d4fa38
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MERFOLK_OF_THE_PEARL_TRIDENT,
    oracle_id = "218d9277-c179-4de3-9c7f-79b5a6d4fa38",
    scryfall_id = "a360fe4e-c9a6-42fa-a97a-8b5a0c19ef93",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Merfolk of the Pearl Trident",
        mana_cost = mana!("{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MERFOLK],
        power = Some(1),
        toughness = Some(1),
    ),],
);
