//! Raging Goblin — {R} — Creature — Goblin Berserker
//! Oracle: Haste (This creature can attack and {T} as soon as it comes under your control.)
//! Set: OANA #43 — Arena New Player Experience Cards | Scryfall ID: 3480927c-10da-4817-9954-10aea2bc7100 | Oracle ID: 30997b43-fc13-41d3-8064-1ccc2cb6fd2b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RAGING_GOBLIN,
    oracle_id = "30997b43-fc13-41d3-8064-1ccc2cb6fd2b",
    scryfall_id = "3480927c-10da-4817-9954-10aea2bc7100",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::HASTE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Raging Goblin",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::BERSERKER],
        power = Some(1),
        toughness = Some(1),
    ),],
);
