//! Scryb Sprites — {G} — Creature — Faerie
//! Oracle: Flying
//! Set: ME3 #132 — Masters Edition III | Scryfall ID: 26f191de-8c59-458c-a1ab-80e2bccdb974 | Oracle ID: a1f20695-6f08-4d5c-9fba-b0018bee298e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SCRYB_SPRITES,
    oracle_id = "a1f20695-6f08-4d5c-9fba-b0018bee298e",
    scryfall_id = "26f191de-8c59-458c-a1ab-80e2bccdb974",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Scryb Sprites",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FAERIE],
        power = Some(1),
        toughness = Some(1),
    ),],
);
