//! Serra Zealot — {W} — Creature — Human Soldier
//! Oracle: First strike
//! Set: USG #46 — Urza's Saga | Scryfall ID: 0b311542-599f-4d2f-a871-18d5b0b7bbe5 | Oracle ID: 989a7353-8d3d-4ea2-ab5e-8535d95dddae
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SERRA_ZEALOT,
    oracle_id = "989a7353-8d3d-4ea2-ab5e-8535d95dddae",
    scryfall_id = "0b311542-599f-4d2f-a871-18d5b0b7bbe5",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Serra Zealot",
        mana_cost = mana!("{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(1),
        toughness = Some(1),
    ),],
);
