//! Sewer Rats — {B} — Creature — Rat
//! Oracle: {B}, Pay 1 life: This creature gets +1/+0 until end of turn. Activate no more than three times each turn.
//! Set: MIR #139 — Mirage | Scryfall ID: 42fe08c3-5024-486c-ba03-19d371ceccb0 | Oracle ID: bf526a0d-65cc-445f-b2b8-19a2cfdd836b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SEWER_RATS,
    oracle_id = "bf526a0d-65cc-445f-b2b8-19a2cfdd836b",
    scryfall_id = "42fe08c3-5024-486c-ba03-19d371ceccb0",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sewer Rats",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::RAT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{B}", PayLife(1)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(3)
    ),],
);
