//! Shaper Guildmage — {U} — Creature — Human Wizard
//! Oracle: {W}, {T}: Target creature gains first strike until end of turn.
//! Oracle: {B}, {T}: Target creature gets +1/+0 until end of turn.
//! Set: MIR #91 — Mirage | Scryfall ID: 4a9304e1-f403-404d-9fe9-169da75e0d62 | Oracle ID: dfbce321-d3c1-4b76-a3fa-27f875015085
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SHAPER_GUILDMAGE,
    oracle_id = "dfbce321-d3c1-4b76-a3fa-27f875015085",
    scryfall_id = "4a9304e1-f403-404d-9fe9-169da75e0d62",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shaper Guildmage",
        mana_cost = mana!("{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{W}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FIRST_STRIKE,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{B}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
