//! Stone-Throwing Devils — {B} — Creature — Devil
//! Oracle: First strike
//! Set: ARN #33 — Arabian Nights | Scryfall ID: d1c387dd-1347-4443-91ce-b71f7ccdceba | Oracle ID: 124c8663-21f3-4cd8-a060-9d04be35c43f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STONE_THROWING_DEVILS,
    oracle_id = "124c8663-21f3-4cd8-a060-9d04be35c43f",
    scryfall_id = "d1c387dd-1347-4443-91ce-b71f7ccdceba",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stone-Throwing Devils",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DEVIL],
        power = Some(1),
        toughness = Some(1),
    ),],
);
