//! Thornscape Apprentice — {G} — Creature — Human Wizard
//! Oracle: {R}, {T}: Target creature gains first strike until end of turn.
//! Oracle: {W}, {T}: Tap target creature.
//! Set: DDE #37 — Duel Decks: Phyrexia vs. the Coalition | Scryfall ID: ef276e2e-7e4d-48a0-af51-70cd843c6561 | Oracle ID: ebb68e03-b2a5-4c5c-8e3b-968cd241d1f0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::THORNSCAPE_APPRENTICE,
    oracle_id = "ebb68e03-b2a5-4c5c-8e3b-968cd241d1f0",
    scryfall_id = "ef276e2e-7e4d-48a0-af51-70cd843c6561",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thornscape Apprentice",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{R}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FIRST_STRIKE,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{W}", TapSelf),
            &[Effect::TapTarget],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
