//! Thunderscape Apprentice — {R} — Creature — Human Wizard
//! Oracle: {B}, {T}: Target player loses 1 life.
//! Oracle: {G}, {T}: Target creature gets +1/+1 until end of turn.
//! Set: INV #174 — Invasion | Scryfall ID: 75a0b075-5414-48d3-a2b1-47dc20213e96 | Oracle ID: 34e325f0-b66f-44b9-a25c-da88357dbac4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::THUNDERSCAPE_APPRENTICE,
    oracle_id = "34e325f0-b66f-44b9-a25c-da88357dbac4",
    scryfall_id = "75a0b075-5414-48d3-a2b1-47dc20213e96",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Thunderscape Apprentice",
        mana_cost = mana!("{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!("{B}", TapSelf),
            &[Effect::LoseLife {
                amount: Amount::Fixed(1),
                target: PlayerRel::Chosen
            }],
            target = Some(TargetSpec::AnyPlayer)
        ),
        activated!(
            cost!("{G}", TapSelf),
            &[Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
