//! Tireless Tribe — {W} — Creature — Human Nomad
//! Oracle: Discard a card: This creature gets +0/+4 until end of turn.
//! Set: ODY #56 — Odyssey | Scryfall ID: 1d23e47a-21d5-4d7e-8aa0-3b3064da5967 | Oracle ID: 5dfbcdb4-d2ad-477d-b37d-db4725410b27
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TIRELESS_TRIBE,
    oracle_id = "5dfbcdb4-d2ad-477d-b37d-db4725410b27",
    scryfall_id = "1d23e47a-21d5-4d7e-8aa0-3b3064da5967",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tireless Tribe",
        mana_cost = mana!("{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::NOMAD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(Discard(&Filter::Any)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(4),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
