//! Tundra Wolves — {W} — Creature — Wolf
//! Oracle: First strike (This creature deals combat damage before creatures without first strike.)
//! Set: 10E #54 — Tenth Edition | Scryfall ID: 15f573db-f4f8-4311-ba47-234e5171da3d | Oracle ID: 2155864e-5788-4e72-a800-e2cf25cf59a7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TUNDRA_WOLVES,
    oracle_id = "2155864e-5788-4e72-a800-e2cf25cf59a7",
    scryfall_id = "15f573db-f4f8-4311-ba47-234e5171da3d",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tundra Wolves",
        mana_cost = mana!("{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WOLF],
        power = Some(1),
        toughness = Some(1),
    ),],
);
