//! Vampire Bats — {B} — Creature — Bat
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: {B}: This creature gets +1/+0 until end of turn. Activate no more than twice each turn.
//! Set: GVL #35 — Duel Decks Anthology: Garruk vs. Liliana | Scryfall ID: 573c35a4-543b-47fe-80b4-d6462abfb82f | Oracle ID: da66f1db-0fde-4112-ae8e-0e63fc686835
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VAMPIRE_BATS,
    oracle_id = "da66f1db-0fde-4112-ae8e-0e63fc686835",
    scryfall_id = "573c35a4-543b-47fe-80b4-d6462abfb82f",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vampire Bats",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BAT],
        power = Some(0),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{B}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        limit = ActivationLimit::PerTurn(2)
    ),],
);
