//! Viridian Acolyte — {G} — Creature — Elf Shaman
//! Oracle: {1}, {T}: Add one mana of any color.
//! Set: DST #89 — Darksteel | Scryfall ID: 64448241-978c-43e0-b0ea-b4bb3e25b715 | Oracle ID: 9db7d8f0-0712-4e32-825c-1339e7a8d768
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VIRIDIAN_ACOLYTE,
    oracle_id = "9db7d8f0-0712-4e32-825c-1339e7a8d768",
    scryfall_id = "64448241-978c-43e0-b0ea-b4bb3e25b715",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Viridian Acolyte",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::SHAMAN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[mana_ability!(
        cost!("{1}", TapSelf),
        &[Effect::mana_of_any_color()]
    ),],
);
