//! Will-o'-the-Wisp — {B} — Creature — Spirit
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: {B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)
//! Set: A25 #115 — Masters 25 | Scryfall ID: 066a1cd2-6778-45bb-84b8-4a9958cf10d7 | Oracle ID: 8b60fcfe-fb90-4a00-a708-25b59bfc9b5a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WILL_O_THE_WISP,
    oracle_id = "8b60fcfe-fb90-4a00-a708-25b59bfc9b5a",
    scryfall_id = "066a1cd2-6778-45bb-84b8-4a9958cf10d7",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Will-o'-the-Wisp",
        mana_cost = mana!("{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(0),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{B}"),
        &[Effect::regenerate(TargetSpec::ThisObject)]
    ),],
);
