//! Wirewood Symbiote — {G} — Creature — Insect
//! Oracle: Return an Elf you control to its owner's hand: Untap target creature. Activate only once each turn.
//! Set: MH3 #288 — Modern Horizons 3 | Scryfall ID: d237f5cc-2b9b-4929-9697-72078bac4c77 | Oracle ID: 67a52a74-9474-4f4e-8785-6ff54078a8ca
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::ELF),
    Filter::ControlledByYou,
]);

card!(
    index = index::WIREWOOD_SYMBIOTE,
    oracle_id = "67a52a74-9474-4f4e-8785-6ff54078a8ca",
    scryfall_id = "d237f5cc-2b9b-4929-9697-72078bac4c77",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wirewood Symbiote",
        mana_cost = mana!("{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::INSECT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(ReturnToHand(&COST1)),
        &[Effect::UntapTarget],
        target = Some(TargetSpec::Object(&Filter::CREATURE)),
        limit = ActivationLimit::PerTurn(1)
    ),],
);
