//! Coal Golem — {5} — Artifact Creature — Golem
//! Oracle: {3}, Sacrifice this creature: Add {R}{R}{R}.
//! Set: ME3 #193 — Masters Edition III | Scryfall ID: bdc28e20-0e48-4803-a8e2-1c1e8f518d89 | Oracle ID: 64b63847-27dd-469b-aad3-58e061f92817
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::COAL_GOLEM,
    oracle_id = "64b63847-27dd-469b-aad3-58e061f92817",
    scryfall_id = "bdc28e20-0e48-4803-a8e2-1c1e8f518d89",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Coal Golem",
        mana_cost = mana!("{5}"),
        types = TypeSet::ARTIFACT.union(TypeSet::CREATURE),
        subtypes = &[subtypes::creature::GOLEM],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[mana_ability!(
        cost!("{3}", SacrificeSelf),
        &[Effect::mana(ManaColor::Red, 3)]
    ),],
);
