//! Forum of Amity — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W} or {B}.
//! Oracle: {2}{W}{B}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SOS #256 — Secrets of Strixhaven | Scryfall ID: 1de6c6cc-0c55-4997-8623-d7f796bd9ab8 | Oracle ID: 349ea6c7-6b3e-417f-b082-b712e2b1635b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::FORUM_OF_AMITY,
    oracle_id = "349ea6c7-6b3e-417f-b082-b712e2b1635b",
    scryfall_id = "1de6c6cc-0c55-4997-8623-d7f796bd9ab8",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Forum of Amity",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])]),
        activated!(cost!("{2}{W}{B}", TapSelf), &[Effect::surveil(1)]),
    ],
);
