//! Hedge Maze — (no cost) — Land — Forest Island
//! Oracle: ({T}: Add {G} or {U}.)
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: MKM #262 — Murders at Karlov Manor | Scryfall ID: 5260f8ae-805b-4eae-badf-62de0f768867 | Oracle ID: ca4b6689-04ee-4227-9bdc-cb5a9590c745
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::HEDGE_MAZE,
    oracle_id = "ca4b6689-04ee-4227-9bdc-cb5a9590c745",
    scryfall_id = "5260f8ae-805b-4eae-badf-62de0f768867",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Hedge Maze",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::FOREST, subtypes::land::ISLAND],
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
        triggered!(Trigger::ETB, &[Effect::surveil(1)]),
    ],
);
