//! Paradox Gardens — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G} or {U}.
//! Oracle: {2}{G}{U}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SOS #258 — Secrets of Strixhaven | Scryfall ID: dbc3447e-1329-4ea1-b4ca-b321b0ffec8f | Oracle ID: 638ff242-63d5-457d-a7a6-40ad51052e2e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::PARADOX_GARDENS,
    oracle_id = "638ff242-63d5-457d-a7a6-40ad51052e2e",
    scryfall_id = "dbc3447e-1329-4ea1-b4ca-b321b0ffec8f",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Paradox Gardens",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Green, ManaColor::Blue])]),
        activated!(cost!("{2}{G}{U}", TapSelf), &[Effect::surveil(1)]),
    ],
);
