//! Savage Mansion — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {R} or {G}.
//! Oracle: {4}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SPM #183 — Marvel's Spider-Man | Scryfall ID: 855f59a5-17a8-4aca-8a4d-f98111eba14c | Oracle ID: 1af15c1d-a41c-44cc-9614-d72694dd26e8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SAVAGE_MANSION,
    oracle_id = "1af15c1d-a41c-44cc-9614-d72694dd26e8",
    scryfall_id = "855f59a5-17a8-4aca-8a4d-f98111eba14c",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Savage Mansion",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Red, ManaColor::Green])]),
        activated!(cost!("{4}", TapSelf), &[Effect::surveil(1)]),
    ],
);
