//! Sinister Hideout — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {B}.
//! Oracle: {4}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SPM #184 — Marvel's Spider-Man | Scryfall ID: 23190d7e-5165-49bd-b307-bf81877d228d | Oracle ID: 80f08b47-a237-4efd-8d86-dfe35a816b0e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SINISTER_HIDEOUT,
    oracle_id = "80f08b47-a237-4efd-8d86-dfe35a816b0e",
    scryfall_id = "23190d7e-5165-49bd-b307-bf81877d228d",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sinister Hideout",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])]),
        activated!(cost!("{4}", TapSelf), &[Effect::surveil(1)]),
    ],
);
