//! Spectacle Summit — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {U} or {R}.
//! Oracle: {2}{U}{R}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SOS #262 — Secrets of Strixhaven | Scryfall ID: a0a66f7b-eab4-45da-8895-c2c2c7eb05f8 | Oracle ID: 33a4e73d-d93a-4b6f-88ff-cd53f20d178c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPECTACLE_SUMMIT,
    oracle_id = "33a4e73d-d93a-4b6f-88ff-cd53f20d178c",
    scryfall_id = "a0a66f7b-eab4-45da-8895-c2c2c7eb05f8",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spectacle Summit",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Red])]),
        activated!(cost!("{2}{U}{R}", TapSelf), &[Effect::surveil(1)]),
    ],
);
