//! Titan's Grave — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {B} or {G}.
//! Oracle: {2}{B}{G}, {T}: Surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: SOS #266 — Secrets of Strixhaven | Scryfall ID: a9ab41c8-3ee2-4676-9b8b-20c34d9f5f21 | Oracle ID: 595f0eb5-f521-4174-9c48-b89e85ea907c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::TITAN_S_GRAVE,
    oracle_id = "595f0eb5-f521-4174-9c48-b89e85ea907c",
    scryfall_id = "a9ab41c8-3ee2-4676-9b8b-20c34d9f5f21",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Titan's Grave",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
        activated!(cost!("{2}{B}{G}", TapSelf), &[Effect::surveil(1)]),
    ],
);
