//! Underground Mortuary — (no cost) — Land — Swamp Forest
//! Oracle: ({T}: Add {B} or {G}.)
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)
//! Set: MKM #271 — Murders at Karlov Manor | Scryfall ID: f6ca59cd-8779-4a84-a54b-e863b79c61f0 | Oracle ID: 840119bf-e60f-4ff7-9c9b-d420d09df545
// IMPLEMENTED — generated by `xtask codegen`: intrinsic type mana, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::UNDERGROUND_MORTUARY,
    oracle_id = "840119bf-e60f-4ff7-9c9b-d420d09df545",
    scryfall_id = "f6ca59cd-8779-4a84-a54b-e863b79c61f0",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Underground Mortuary",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::SWAMP, subtypes::land::FOREST],
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])]),
        triggered!(Trigger::ETB, &[Effect::surveil(1)]),
    ],
);
