//! Basilisk Collar — {1} — Artifact — Equipment
//! Oracle: Equipped creature has deathtouch and lifelink. (Any amount of damage it deals to a creature is enough to destroy it. Damage dealt by this creature also causes you to gain that much life.)
//! Oracle: Equip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: FDN #669 — Foundations | Scryfall ID: 7b36fba7-71f7-4b7f-bde5-b3a9752ad21c | Oracle ID: f5f4dd28-f4ae-4d39-b9b8-6ebfd63c93fe
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BASILISK_COLLAR,
    oracle_id = "f5f4dd28-f4ae-4d39-b9b8-6ebfd63c93fe",
    scryfall_id = "7b36fba7-71f7-4b7f-bde5-b3a9752ad21c",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Basilisk Collar",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{2}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::DEATHTOUCH.union(KeywordSet::LIFELINK))
        ),
    ],
);
