//! Neurok Hoversail — {1} — Artifact — Equipment
//! Oracle: Equipped creature has flying.
//! Oracle: Equip {2} ({2}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: MRD #218 — Mirrodin | Scryfall ID: 0fa5790b-5388-4bf9-9caa-44d8cbb64708 | Oracle ID: 3cc02a23-93b7-445a-9c3e-0e4942ef927b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::NEUROK_HOVERSAIL,
    oracle_id = "3cc02a23-93b7-445a-9c3e-0e4942ef927b",
    scryfall_id = "0fa5790b-5388-4bf9-9caa-44d8cbb64708",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Neurok Hoversail",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{2}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::AddKeyword(KeywordSet::FLYING)
        ),
    ],
);
