//! Shuko — {1} — Artifact — Equipment
//! Oracle: Equipped creature gets +1/+0.
//! Oracle: Equip {0} ({0}: Attach to target creature you control. Equip only as a sorcery.)
//! Set: BOK #159 — Betrayers of Kamigawa | Scryfall ID: a47456b8-cef8-4085-90b1-92788e16fd27 | Oracle ID: 8abe0577-8fdb-4e4a-a871-01b21732c961
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SHUKO,
    oracle_id = "8abe0577-8fdb-4e4a-a871-01b21732c961",
    scryfall_id = "a47456b8-cef8-4085-90b1-92788e16fd27",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shuko",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{0}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(1, 0)
        ),
    ],
);
