//! Slagwurm Armor — {1} — Artifact — Equipment
//! Oracle: Equipped creature gets +0/+6.
//! Oracle: Equip {3} ({3}: Attach to target creature you control. Equip only as a sorcery. This card enters unattached and stays on the battlefield if the creature leaves.)
//! Set: TD2 #21 — Duel Decks: Mirrodin Pure vs. New Phyrexia | Scryfall ID: 8a4a4d2d-7080-404c-83ca-90a584aa02c8 | Oracle ID: 20b60c93-124b-42c8-93fb-63bbd1888658
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SLAGWURM_ARMOR,
    oracle_id = "20b60c93-124b-42c8-93fb-63bbd1888658",
    scryfall_id = "8a4a4d2d-7080-404c-83ca-90a584aa02c8",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Slagwurm Armor",
        mana_cost = mana!("{1}"),
        types = TypeSet::ARTIFACT,
        subtypes = &[subtypes::artifact::EQUIPMENT],
    ),],
    abilities = &[
        equip!(cost!("{3}")),
        static_ability!(
            Filter::And(&[Filter::CREATURE, Filter::AttachedToBySource]),
            Modifier::ModifyPT(0, 6)
        ),
    ],
);
