//! Blazemire Verge — (no cost) — Land
//! Oracle: {T}: Add {B}.
//! Oracle: {T}: Add {R}. Activate only if you control a Swamp or a Mountain.
//! Set: DSK #256 — Duskmourn: House of Horror | Scryfall ID: d151c8e2-d715-470d-868a-f45191db9fa0 | Oracle ID: 977c2f33-b622-4172-9efb-7f523becd32b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::SWAMP),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::BLAZEMIRE_VERGE,
    oracle_id = "977c2f33-b622-4172-9efb-7f523becd32b",
    scryfall_id = "d151c8e2-d715-470d-868a-f45191db9fa0",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Blazemire Verge", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::Red, 1)],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
