//! Floodfarm Verge — (no cost) — Land
//! Oracle: {T}: Add {W}.
//! Oracle: {T}: Add {U}. Activate only if you control a Plains or an Island.
//! Set: DSK #259 — Duskmourn: House of Horror | Scryfall ID: d53ed0db-1199-44b3-8eda-8189dfcf53d1 | Oracle ID: f1e9abfb-c3c8-483e-b446-5c2afc9f6394
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::ISLAND),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::FLOODFARM_VERGE,
    oracle_id = "f1e9abfb-c3c8-483e-b446-5c2afc9f6394",
    scryfall_id = "d53ed0db-1199-44b3-8eda-8189dfcf53d1",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Floodfarm Verge", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::Blue, 1)],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
