//! Hushwood Verge — (no cost) — Land
//! Oracle: {T}: Add {G}.
//! Oracle: {T}: Add {W}. Activate only if you control a Forest or a Plains.
//! Set: DSK #261 — Duskmourn: House of Horror | Scryfall ID: ec288d76-c1f5-471b-8a53-504f88469c1b | Oracle ID: cce328b9-6100-417e-9ddf-808bbe3e3bc5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::PLAINS),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::HUSHWOOD_VERGE,
    oracle_id = "cce328b9-6100-417e-9ddf-808bbe3e3bc5",
    scryfall_id = "ec288d76-c1f5-471b-8a53-504f88469c1b",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Hushwood Verge", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::White, 1)],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
