//! Nimbus Maze — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {W}. Activate only if you control an Island.
//! Oracle: {T}: Add {U}. Activate only if you control a Plains.
//! Set: AFC #252 — Forgotten Realms Commander | Scryfall ID: 711dbdb1-7ec3-4fb4-8364-d34f5e143fd1 | Oracle ID: d7e1d4eb-1d4e-460e-9304-7db9ab50ccb5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::ControlledByYou,
]);

static CHECK2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::ControlledByYou,
]);

card!(
    index = index::NIMBUS_MAZE,
    oracle_id = "d7e1d4eb-1d4e-460e-9304-7db9ab50ccb5",
    scryfall_id = "711dbdb1-7ec3-4fb4-8364-d34f5e143fd1",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Nimbus Maze", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::White, 1)],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::Blue, 1)],
            condition = Some(Condition::ControlCount(&CHECK2, 1))
        ),
    ],
);
