//! Sliver Hive — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add one mana of any color. Spend this mana only to cast a Sliver spell.
//! Oracle: {5}, {T}: Create a 1/1 colorless Sliver creature token. Activate only if you control a Sliver.
//! Set: M15 #247 — Magic 2015 | Scryfall ID: 91cef7ce-aa9f-4659-ac24-394c5ab9f77c | Oracle ID: e7286688-ffbe-4d25-ad55-27990f005368
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SPEND1: Filter = Filter::HasSubtype(subtypes::creature::SLIVER);

static CHECK2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::SLIVER),
    Filter::ControlledByYou,
]);

card!(
    index = index::SLIVER_HIVE,
    oracle_id = "e7286688-ffbe-4d25-ad55-27990f005368",
    scryfall_id = "91cef7ce-aa9f-4659-ac24-394c5ab9f77c",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Sliver Hive", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(&[Effect::mana_of_any_color().restricted(&SPEND1, SpendRider::None)]),
        activated!(
            cost!("{5}", TapSelf),
            &[Effect::CreateToken {
                token: &generated_tokens::SLIVER_1_1
            }],
            condition = Some(Condition::ControlCount(&CHECK2, 1))
        ),
    ],
);
