//! Spire of Industry — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}, Pay 1 life: Add one mana of any color. Activate only if you control an artifact.
//! Set: EOC #183 — Edge of Eternities Commander | Scryfall ID: 35e9ec06-a848-4230-84a2-19cb8034e0f0 | Oracle ID: 55a519b4-61cb-448a-875b-4d6dbe00580f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SPIRE_OF_INDUSTRY,
    oracle_id = "55a519b4-61cb-448a-875b-4d6dbe00580f",
    scryfall_id = "35e9ec06-a848-4230-84a2-19cb8034e0f0",
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Spire of Industry", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            cost!(TapSelf, PayLife(1)),
            &[Effect::mana_of_any_color()],
            condition = Some(Condition::ControlCount(&Filter::YOUR_ARTIFACT, 1))
        ),
    ],
);
