//! Tainted Isle — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {U} or {B}. Activate only if you control a Swamp.
//! Set: DSC #303 — Duskmourn: House of Horror Commander | Scryfall ID: 70e8e7e2-e9ea-4358-805e-c5110c8d8443 | Oracle ID: 0222414f-98b5-458a-a0fd-831a66cd8b07
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::TAINTED_ISLE,
    oracle_id = "0222414f-98b5-458a-a0fd-831a66cd8b07",
    scryfall_id = "70e8e7e2-e9ea-4358-805e-c5110c8d8443",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Tainted Isle", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana_choice(&[ManaColor::Blue, ManaColor::Black])],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
