//! Tainted Field — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {W} or {B}. Activate only if you control a Swamp.
//! Set: DSC #302 — Duskmourn: House of Horror Commander | Scryfall ID: c6eeab6f-a738-4005-91c2-a5f81df5c569 | Oracle ID: 439de49b-1091-4688-9ffb-80a025df31c2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::TAINTED_FIELD,
    oracle_id = "439de49b-1091-4688-9ffb-80a025df31c2",
    scryfall_id = "c6eeab6f-a738-4005-91c2-a5f81df5c569",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Tainted Field", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana_choice(&[ManaColor::White, ManaColor::Black])],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
