//! Tainted Wood — (no cost) — Land
//! Oracle: {T}: Add {C}.
//! Oracle: {T}: Add {B} or {G}. Activate only if you control a Swamp.
//! Set: DSC #305 — Duskmourn: House of Horror Commander | Scryfall ID: 3da7ab6b-b10a-4786-b1eb-92de7e66690e | Oracle ID: fa6d05a1-3df4-4751-b1a0-8d9693faec73
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::TAINTED_WOOD,
    oracle_id = "fa6d05a1-3df4-4751-b1a0-8d9693faec73",
    scryfall_id = "3da7ab6b-b10a-4786-b1eb-92de7e66690e",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Tainted Wood", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana_choice(&[ManaColor::Black, ManaColor::Green])],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
