//! Thornspire Verge — (no cost) — Land
//! Oracle: {T}: Add {R}.
//! Oracle: {T}: Add {G}. Activate only if you control a Mountain or a Forest.
//! Set: DSK #270 — Duskmourn: House of Horror | Scryfall ID: 7e1cdc03-6faa-4138-9a52-caafbe34fb59 | Oracle ID: e861bc08-4f0b-4d22-9b85-9d20227fd5b4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::MOUNTAIN),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::land::FOREST),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::THORNSPIRE_VERGE,
    oracle_id = "e861bc08-4f0b-4d22-9b85-9d20227fd5b4",
    scryfall_id = "7e1cdc03-6faa-4138-9a52-caafbe34fb59",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(name = "Thornspire Verge", types = TypeSet::LAND,),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Red, 1)]),
        mana_ability!(
            Cost::TAP,
            &[Effect::mana(ManaColor::Green, 1)],
            condition = Some(Condition::ControlCount(&CHECK1, 1))
        ),
    ],
);
