//! Blood Crypt — (no cost) — Land — Swamp Mountain
//! Oracle: ({T}: Add {B} or {R}.)
//! Oracle: As this land enters, you may pay 2 life. If you don't, it enters tapped.
//! Set: TRK #278 — Star Trek | Scryfall ID: 1b7eb998-3ec0-4cbc-a416-5a1e3e5a7316 | Oracle ID: 43985bbc-a0f6-4812-984e-392bc8562633
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, shockland.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 288,
    oracle_id: "43985bbc-a0f6-4812-984e-392bc8562633",
    scryfall_id: "1b7eb998-3ec0-4cbc-a416-5a1e3e5a7316",
    color_identity: ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "Blood Crypt",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SWAMP, subtypes::land::MOUNTAIN],
        enter_modifiers: &[EnterModifier::TappedOrPayLife(2)],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana_choice(&[ManaColor::Black, ManaColor::Red])]),
    ],
}
