//! Abomination — {3}{B}{B} — Creature — Horror
//! Oracle: Whenever this creature blocks or becomes blocked by a green or white creature, destroy that creature at end of combat.
//! Set: 4ED #117 — Fourth Edition | Scryfall ID: a363bc91-8278-448e-9d5c-564e4b51eb62 | Oracle ID: 2c57c4e9-0a46-45d6-92db-9203fb722b60
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::CREATURE,
        Filter::HasColor(ColorSet::from_slice(&[Color::Green])),
    ]),
    Filter::And(&[
        Filter::CREATURE,
        Filter::HasColor(ColorSet::from_slice(&[Color::White])),
    ]),
]);

card!(
    index = index::ABOMINATION,
    oracle_id = "2c57c4e9-0a46-45d6-92db-9203fb722b60",
    scryfall_id = "a363bc91-8278-448e-9d5c-564e4b51eb62",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Abomination",
        mana_cost = mana!("{3}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HORROR],
        power = Some(2),
        toughness = Some(6),
    ),],
    abilities = &[triggered!(
        Trigger::BlocksOrBecomesBlockedBy(&TRIGGER1),
        &[Effect::AtEndOfCombat {
            about: TargetSpec::EventObject,
            effects: &[Effect::destroy(TargetSpec::EventObject)]
        }]
    ),],
);
