//! Acidic Slime — {3}{G}{G} — Creature — Ooze
//! Oracle: Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.)
//! Oracle: When this creature enters, destroy target artifact, enchantment, or land.
//! Set: CMM #270 — Commander Masters | Scryfall ID: 932d48fb-42b5-4aaa-a91c-d35cdb5e41a3 | Oracle ID: 21f45043-5419-4019-8b6c-e5294bd5f549
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[Filter::ARTIFACT, Filter::ENCHANTMENT, Filter::LAND]);

card!(
    index = index::ACIDIC_SLIME,
    oracle_id = "21f45043-5419-4019-8b6c-e5294bd5f549",
    scryfall_id = "932d48fb-42b5-4aaa-a91c-d35cdb5e41a3",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::DEATHTOUCH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Acidic Slime",
        mana_cost = mana!("{3}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::OOZE],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::destroy(TargetSpec::Object(&TARGET1))],
        targets = Some(TargetReq::one(TargetSpec::Object(&TARGET1)))
    ),],
);
