//! Aven Flock — {4}{W} — Creature — Bird Soldier
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: {W}: This creature gets +0/+1 until end of turn.
//! Set: 9ED #4 — Ninth Edition | Scryfall ID: 43c97d63-d0f9-402d-948a-b73f73bed919 | Oracle ID: fcf0bb85-bca9-4f4c-b954-ca3bc5f91dd8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AVEN_FLOCK,
    oracle_id = "fcf0bb85-bca9-4f4c-b954-ca3bc5f91dd8",
    scryfall_id = "43c97d63-d0f9-402d-948a-b73f73bed919",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aven Flock",
        mana_cost = mana!("{4}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{W}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
