//! Boris Devilboon — {3}{B}{R} — Legendary Creature — Zombie Wizard
//! Oracle: {2}{B}{R}, {T}: Create a 1/1 black and red Demon creature token named Minor Demon.
//! Set: ME3 #146 — Masters Edition III | Scryfall ID: b61e5753-d11d-4ef5-ae0e-510c4d5809a9 | Oracle ID: 913aed6d-60c3-4d08-baf8-359e2c41a797
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BORIS_DEVILBOON,
    oracle_id = "913aed6d-60c3-4d08-baf8-359e2c41a797",
    scryfall_id = "b61e5753-d11d-4ef5-ae0e-510c4d5809a9",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Boris Devilboon",
        mana_cost = mana!("{3}{B}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ZOMBIE, subtypes::creature::WIZARD],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{2}{B}{R}", TapSelf),
        &[Effect::CreateToken {
            token: &generated_tokens::MINOR_DEMON_1_1_BLACK_RED
        }]
    ),],
);
