//! Charging Bandits — {4}{B} — Creature — Human Rogue
//! Oracle: Whenever this creature attacks, it gets +2/+0 until end of turn.
//! Set: POR #84 — Portal | Scryfall ID: 1721ee11-c7ee-4878-b2ab-4f090e0c5def | Oracle ID: 0c67133b-be15-47d7-8cf6-79987a42044d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CHARGING_BANDITS,
    oracle_id = "0c67133b-be15-47d7-8cf6-79987a42044d",
    scryfall_id = "1721ee11-c7ee-4878-b2ab-4f090e0c5def",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Charging Bandits",
        mana_cost = mana!("{4}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ROGUE],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
