//! Endless Wurm — {3}{G}{G} — Creature — Wurm
//! Oracle: Trample
//! Oracle: At the beginning of your upkeep, sacrifice this creature unless you sacrifice an enchantment.
//! Set: USG #249 — Urza's Saga | Scryfall ID: 53772435-e20e-4b9e-a2f1-c1c6a4dcac79 | Oracle ID: ce4d714c-c22b-47be-a372-a3139c4e5b1c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[Filter::ENCHANTMENT, Filter::ControlledByYou]);

card!(
    index = index::ENDLESS_WURM,
    oracle_id = "ce4d714c-c22b-47be-a372-a3139c4e5b1c",
    scryfall_id = "53772435-e20e-4b9e-a2f1-c1c6a4dcac79",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Endless Wurm",
        mana_cost = mana!("{3}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WURM],
        power = Some(9),
        toughness = Some(9),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::PlayerMayPayCostOr {
            player: PlayerRel::You,
            cost: &CostPart::Sacrifice(&COST1),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
