//! Fangren Hunter — {3}{G}{G} — Creature — Beast
//! Oracle: Trample
//! Set: MRD #119 — Mirrodin | Scryfall ID: 2dbc8eef-f032-490a-b487-da1af71b7ff2 | Oracle ID: c5dc5546-e9e5-4b5b-b812-5716d4bdee0e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FANGREN_HUNTER,
    oracle_id = "c5dc5546-e9e5-4b5b-b812-5716d4bdee0e",
    scryfall_id = "2dbc8eef-f032-490a-b487-da1af71b7ff2",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fangren Hunter",
        mana_cost = mana!("{3}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BEAST],
        power = Some(4),
        toughness = Some(4),
    ),],
);
