//! Fire Snake — {4}{R} — Creature — Snake
//! Oracle: When this creature dies, destroy target land.
//! Set: POR #127 — Portal | Scryfall ID: d4c36e32-59e8-4e3d-903e-a264211f2a82 | Oracle ID: e96542ed-1931-4da1-9d9e-d10878c4ae6b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FIRE_SNAKE,
    oracle_id = "e96542ed-1931-4da1-9d9e-d10878c4ae6b",
    scryfall_id = "d4c36e32-59e8-4e3d-903e-a264211f2a82",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fire Snake",
        mana_cost = mana!("{4}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SNAKE],
        power = Some(3),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::This),
        &[Effect::destroy(TargetSpec::Object(&Filter::LAND))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::LAND)))
    ),],
);
