//! Folk of the Pines — {4}{G} — Creature — Dryad
//! Oracle: {1}{G}: This creature gets +1/+0 until end of turn.
//! Set: ME2 #162 — Masters Edition II | Scryfall ID: ee55f1d0-5bb7-4c11-8534-76b3efd12169 | Oracle ID: 6cd8cf2a-972f-41b7-ab0c-b4953accc2fe
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FOLK_OF_THE_PINES,
    oracle_id = "6cd8cf2a-972f-41b7-ab0c-b4953accc2fe",
    scryfall_id = "ee55f1d0-5bb7-4c11-8534-76b3efd12169",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Folk of the Pines",
        mana_cost = mana!("{4}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRYAD],
        power = Some(2),
        toughness = Some(5),
    ),],
    abilities = &[activated!(
        cost!("{1}{G}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
