//! Gerrard's Irregulars — {4}{R} — Creature — Human Soldier
//! Oracle: Trample, haste
//! Set: MMQ #192 — Mercadian Masques | Scryfall ID: 8a88f507-3d78-4f7f-a91f-8489ad9250f2 | Oracle ID: 595cbe23-4969-4fc2-8386-e5f3e6adfd5f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GERRARD_S_IRREGULARS,
    oracle_id = "595cbe23-4969-4fc2-8386-e5f3e6adfd5f",
    scryfall_id = "8a88f507-3d78-4f7f-a91f-8489ad9250f2",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::HASTE.union(KeywordSet::TRAMPLE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gerrard's Irregulars",
        mana_cost = mana!("{4}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(4),
        toughness = Some(2),
    ),],
);
