//! Glintwing Invoker — {4}{U} — Creature — Human Wizard Mutant
//! Oracle: {7}{U}: This creature gets +3/+3 and gains flying until end of turn.
//! Set: DMR #52 — Dominaria Remastered | Scryfall ID: f1b26379-0007-450e-9b94-2932eef6ac2c | Oracle ID: c8a9bdaa-55ef-4baa-9dfa-9068583360f6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GLINTWING_INVOKER,
    oracle_id = "c8a9bdaa-55ef-4baa-9dfa-9068583360f6",
    scryfall_id = "f1b26379-0007-450e-9b94-2932eef6ac2c",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Glintwing Invoker",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::WIZARD,
            subtypes::creature::MUTANT
        ],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{7}{U}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(3),
            toughness: Amount::Fixed(3),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
