//! Grandmother Sengir — {4}{B} — Legendary Creature — Human Wizard
//! Oracle: {1}{B}, {T}: Target creature gets -1/-1 until end of turn.
//! Set: ME2 #93 — Masters Edition II | Scryfall ID: b43b2370-fe1b-491b-9dd0-b49a30bb2b93 | Oracle ID: 4f92804f-a231-4406-9a16-f4e102517b06
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GRANDMOTHER_SENGIR,
    oracle_id = "4f92804f-a231-4406-9a16-f4e102517b06",
    scryfall_id = "b43b2370-fe1b-491b-9dd0-b49a30bb2b93",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Grandmother Sengir",
        mana_cost = mana!("{4}{B}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{1}{B}", TapSelf),
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(1),
            toughness: Amount::NegXFixed(1),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
