//! Kami of Tattered Shoji — {4}{W} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, this creature gains flying until end of turn.
//! Set: BOK #11 — Betrayers of Kamigawa | Scryfall ID: dc6deb57-4ee3-4716-8644-28283704f994 | Oracle ID: a7cb1da6-e56a-42b6-8087-cf822783373f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::KAMI_OF_TATTERED_SHOJI,
    oracle_id = "a7cb1da6-e56a-42b6-8087-cf822783373f",
    scryfall_id = "dc6deb57-4ee3-4716-8644-28283704f994",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kami of Tattered Shoji",
        mana_cost = mana!("{4}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(2),
        toughness = Some(5),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
