//! Kodama of the North Tree — {2}{G}{G}{G} — Legendary Creature — Spirit
//! Oracle: Trample
//! Oracle: Shroud (This creature can't be the target of spells or abilities.)
//! Set: CHK #222 — Champions of Kamigawa | Scryfall ID: 2d9b5c33-63c4-4ddd-9f04-37bb36970b43 | Oracle ID: 15d8f129-2518-45f4-9f34-a4fcd4d859af
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KODAMA_OF_THE_NORTH_TREE,
    oracle_id = "15d8f129-2518-45f4-9f34-a4fcd4d859af",
    scryfall_id = "2d9b5c33-63c4-4ddd-9f04-37bb36970b43",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::TRAMPLE.union(KeywordSet::SHROUD),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kodama of the North Tree",
        mana_cost = mana!("{2}{G}{G}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(6),
        toughness = Some(4),
    ),],
);
