//! Lovisa Coldeyes — {3}{R}{R} — Legendary Creature — Human
//! Oracle: Each creature that's a Barbarian, a Warrior, or a Berserker gets +2/+2 and has haste.
//! Set: DDS #34 — Duel Decks: Mind vs. Might | Scryfall ID: ad4d4662-2c9b-42fc-9c08-162c822f436c | Oracle ID: 720879dc-7593-41c0-ab3d-936069f26930
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LOVISA_COLDEYES,
    oracle_id = "720879dc-7593-41c0-ab3d-936069f26930",
    scryfall_id = "ad4d4662-2c9b-42fc-9c08-162c822f436c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lovisa Coldeyes",
        mana_cost = mana!("{3}{R}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[
        static_ability!(
            Filter::Or(&[
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::WARRIOR)
                ]),
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::BERSERKER)
                ]),
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::BARBARIAN)
                ])
            ]),
            Modifier::ModifyPT(2, 2)
        ),
        static_ability!(
            Filter::Or(&[
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::WARRIOR)
                ]),
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::BERSERKER)
                ]),
                Filter::And(&[
                    Filter::CREATURE,
                    Filter::HasSubtype(subtypes::creature::BARBARIAN)
                ])
            ]),
            Modifier::AddKeyword(KeywordSet::HASTE)
        ),
    ],
);
