//! Loxodon Mystic — {3}{W}{W} — Creature — Elephant Cleric
//! Oracle: {W}, {T}: Tap target creature.
//! Set: 10E #26 — Tenth Edition | Scryfall ID: 83bf030b-4e20-49b0-837f-935f96b5d1fe | Oracle ID: f3e22884-a9ca-4479-b400-df1c1d2fd153
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LOXODON_MYSTIC,
    oracle_id = "f3e22884-a9ca-4479-b400-df1c1d2fd153",
    scryfall_id = "83bf030b-4e20-49b0-837f-935f96b5d1fe",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Loxodon Mystic",
        mana_cost = mana!("{3}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELEPHANT, subtypes::creature::CLERIC],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{W}", TapSelf),
        &[Effect::TapTarget],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
