//! Meloku the Clouded Mirror — {4}{U} — Legendary Creature — Moonfolk Wizard
//! Oracle: Flying
//! Oracle: {1}, Return a land you control to its owner's hand: Create a 1/1 blue Illusion creature token with flying.
//! Set: CMR #399 — Commander Legends | Scryfall ID: 60b9db96-a6ab-454b-99a7-910ef77560d7 | Oracle ID: 3b96b8c3-b9c8-4712-a3b1-243a67cc013a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MELOKU_THE_CLOUDED_MIRROR,
    oracle_id = "3b96b8c3-b9c8-4712-a3b1-243a67cc013a",
    scryfall_id = "60b9db96-a6ab-454b-99a7-910ef77560d7",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Meloku the Clouded Mirror",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::MOONFOLK, subtypes::creature::WIZARD],
        power = Some(2),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{1}", ReturnToHand(&Filter::YOUR_LAND)),
        &[Effect::CreateToken {
            token: &generated_tokens::ILLUSION_1_1_BLUE_FLYING
        }]
    ),],
);
