//! Morphling — {3}{U}{U} — Creature — Shapeshifter
//! Oracle: {U}: Untap this creature.
//! Oracle: {U}: This creature gains flying until end of turn.
//! Oracle: {U}: This creature gains shroud until end of turn. (It can't be the target of spells or abilities.)
//! Oracle: {1}: This creature gets +1/-1 until end of turn.
//! Oracle: {1}: This creature gets -1/+1 until end of turn.
//! Set: VMA #81 — Vintage Masters | Scryfall ID: a0d09164-f53f-4f80-8166-8faeacaff418 | Oracle ID: 19f233b2-8be6-4172-abf9-b132fc3393d9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MORPHLING,
    oracle_id = "19f233b2-8be6-4172-abf9-b132fc3393d9",
    scryfall_id = "a0d09164-f53f-4f80-8166-8faeacaff418",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Morphling",
        mana_cost = mana!("{3}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SHAPESHIFTER],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[
        activated!(cost!("{U}"), &[Effect::UntapSelf]),
        activated!(
            cost!("{U}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FLYING,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{U}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::SHROUD,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{1}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(1),
                toughness: Amount::NegXFixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{1}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::NegXFixed(1),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
    ],
);
