//! Ore Gorger — {3}{R}{R} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, you may destroy target nonbasic land.
//! Set: CHK #182 — Champions of Kamigawa | Scryfall ID: ecc8bbb9-d6a1-474b-8f34-594b5a9d4178 | Oracle ID: e5a9d34b-c7d4-4682-8e26-dd82e38ee84e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::ORE_GORGER,
    oracle_id = "e5a9d34b-c7d4-4682-8e26-dd82e38ee84e",
    scryfall_id = "ecc8bbb9-d6a1-474b-8f34-594b5a9d4178",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ore Gorger",
        mana_cost = mana!("{3}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(3),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::MayDo {
            effects: &[Effect::destroy(TargetSpec::Object(&Filter::NONBASIC_LAND))]
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::NONBASIC_LAND)))
    ),],
);
