//! Phyrexian Plaguelord — {3}{B}{B} — Creature — Phyrexian Carrier
//! Oracle: {T}, Sacrifice this creature: Target creature gets -4/-4 until end of turn.
//! Oracle: Sacrifice a creature: Target creature gets -1/-1 until end of turn.
//! Set: CMA #61 — Commander Anthology | Scryfall ID: d0894a99-13e0-406c-8ca3-5552c64e3154 | Oracle ID: aff9e844-9e03-490b-b44f-10d385738cc6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PHYREXIAN_PLAGUELORD,
    oracle_id = "aff9e844-9e03-490b-b44f-10d385738cc6",
    scryfall_id = "d0894a99-13e0-406c-8ca3-5552c64e3154",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Phyrexian Plaguelord",
        mana_cost = mana!("{3}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::CARRIER],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[
        activated!(
            cost!(TapSelf, SacrificeSelf),
            &[Effect::PumpTarget {
                power: Amount::NegXFixed(4),
                toughness: Amount::NegXFixed(4),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!(Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::PumpTarget {
                power: Amount::NegXFixed(1),
                toughness: Amount::NegXFixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
