//! Pirate Ship — {4}{U} — Creature — Human Pirate
//! Oracle: This creature can't attack unless defending player controls an Island.
//! Oracle: {T}: This creature deals 1 damage to any target.
//! Oracle: When you control no Islands, sacrifice this creature.
//! Set: TSB #28 — Time Spiral Timeshifted | Scryfall ID: 4f91724c-0e3b-4289-9af6-9de489d811eb | Oracle ID: c6b3f924-806d-47d3-b044-72b48470196c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static DEFENDER_CONTROLS1: Filter = Filter::HasSubtype(subtypes::land::ISLAND);

static CHECK2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::ControlledByYou,
]);

static STATE3: Condition = Condition::ControlCountAtMost(&CHECK2, 0);

card!(
    index = index::PIRATE_SHIP,
    oracle_id = "c6b3f924-806d-47d3-b044-72b48470196c",
    scryfall_id = "4f91724c-0e3b-4289-9af6-9de489d811eb",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Pirate Ship",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::PIRATE],
        power = Some(4),
        toughness = Some(3),
    ),],
    abilities = &[
        static_ability!(
            Filter::This,
            Modifier::CantAttackUnlessDefenderControls(&DEFENDER_CONTROLS1)
        ),
        triggered!(Trigger::State(&STATE3), &[Effect::SacrificeSelf]),
        activated!(
            Cost::TAP,
            &[Effect::DealDamage {
                amount: Amount::Fixed(1),
                target: TargetSpec::AnyTarget
            }],
            target = Some(TargetSpec::AnyTarget)
        ),
    ],
);
