//! Righteous Avengers — {4}{W} — Creature — Human Soldier
//! Oracle: Plainswalk (This creature can't be blocked as long as defending player controls a Plains.)
//! Set: ME1 #25 — Masters Edition | Scryfall ID: 3d5e7afd-57b9-4052-a1b9-45d324955d72 | Oracle ID: e7c07e41-3654-47da-afe3-88aae4c034b6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RIGHTEOUS_AVENGERS,
    oracle_id = "e7c07e41-3654-47da-afe3-88aae4c034b6",
    scryfall_id = "3d5e7afd-57b9-4052-a1b9-45d324955d72",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::PLAINSWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Righteous Avengers",
        mana_cost = mana!("{4}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(3),
        toughness = Some(1),
    ),],
);
