//! Sandbar Serpent — {4}{U} — Creature — Serpent
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: USG #95 — Urza's Saga | Scryfall ID: b3b430ec-28e1-4b2c-bea8-3bfd3a0e8cf8 | Oracle ID: 30fce201-03a8-4afc-a1ad-7a9b3fd59836
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SANDBAR_SERPENT,
    oracle_id = "30fce201-03a8-4afc-a1ad-7a9b3fd59836",
    scryfall_id = "b3b430ec-28e1-4b2c-bea8-3bfd3a0e8cf8",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sandbar Serpent",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SERPENT],
        power = Some(3),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{2}", DiscardSelf),
        &[Effect::draw(1)],
        zone = ActivationZone::Hand
    ),],
);
