//! Savage Gorilla — {4}{G} — Creature — Ape
//! Oracle: {U}{B}, {T}, Sacrifice this creature: Target creature gets -3/-3 until end of turn. Draw a card.
//! Set: APC #85 — Apocalypse | Scryfall ID: 32ad3f87-9f25-455f-9933-3b0b0eaad467 | Oracle ID: 6c876a57-c567-4d26-8ab6-a9c051e83ace
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SAVAGE_GORILLA,
    oracle_id = "6c876a57-c567-4d26-8ab6-a9c051e83ace",
    scryfall_id = "32ad3f87-9f25-455f-9933-3b0b0eaad467",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Savage Gorilla",
        mana_cost = mana!("{4}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::APE],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{U}{B}", TapSelf, SacrificeSelf),
        &[
            Effect::PumpTarget {
                power: Amount::NegXFixed(3),
                toughness: Amount::NegXFixed(3),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            },
            Effect::draw(1)
        ],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
