//! Segovian Leviathan — {4}{U} — Creature — Leviathan
//! Oracle: Islandwalk (This creature can't be blocked as long as defending player controls an Island.)
//! Set: 6ED #97 — Classic Sixth Edition | Scryfall ID: 8f796dd2-9ecf-490a-86c0-acb46130518b | Oracle ID: 853b02e1-fc0a-413b-8381-88596624440f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SEGOVIAN_LEVIATHAN,
    oracle_id = "853b02e1-fc0a-413b-8381-88596624440f",
    scryfall_id = "8f796dd2-9ecf-490a-86c0-acb46130518b",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::ISLANDWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Segovian Leviathan",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::LEVIATHAN],
        power = Some(3),
        toughness = Some(3),
    ),],
);
