//! Siege-Gang Commander — {3}{R}{R} — Creature — Goblin
//! Oracle: When this creature enters, create three 1/1 red Goblin creature tokens.
//! Oracle: {1}{R}, Sacrifice a Goblin: This creature deals 2 damage to any target.
//! Set: PLST #DMR-136 — The List | Scryfall ID: 7d67e614-03d2-4034-b82f-25962fc378d4 | Oracle ID: ddc7f59a-bbb1-4ba1-82c8-6813fd191940
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::GOBLIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::SIEGE_GANG_COMMANDER,
    oracle_id = "ddc7f59a-bbb1-4ba1-82c8-6813fd191940",
    scryfall_id = "7d67e614-03d2-4034-b82f-25962fc378d4",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Siege-Gang Commander",
        mana_cost = mana!("{3}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[
        activated!(
            cost!("{1}{R}", Sacrifice(&COST1)),
            &[Effect::DealDamage {
                amount: Amount::Fixed(2),
                target: TargetSpec::AnyTarget
            }],
            target = Some(TargetSpec::AnyTarget)
        ),
        triggered!(
            Trigger::ETB,
            &[Effect::CreateTokenN {
                token: &generated_tokens::GOBLIN_1_1_RED,
                amount: Amount::Fixed(3)
            }]
        ),
    ],
);
