//! Sol'kanar the Swamp King — {2}{U}{B}{R} — Legendary Creature — Demon
//! Oracle: Swampwalk (This creature can't be blocked as long as defending player controls a Swamp.)
//! Oracle: Whenever a player casts a black spell, you gain 1 life.
//! Set: DMR #200 — Dominaria Remastered | Scryfall ID: 88b4cb6a-ac4f-48ac-8c94-ba2b8e6b32a8 | Oracle ID: b8aac8e8-4588-4cb9-8b95-5c4abab1c48b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::HasColor(ColorSet::from_slice(&[Color::Black]));

card!(
    index = index::SOL_KANAR_THE_SWAMP_KING,
    oracle_id = "b8aac8e8-4588-4cb9-8b95-5c4abab1c48b",
    scryfall_id = "88b4cb6a-ac4f-48ac-8c94-ba2b8e6b32a8",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::SWAMPWALK,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sol'kanar the Swamp King",
        mana_cost = mana!("{2}{U}{B}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::DEMON],
        power = Some(5),
        toughness = Some(5),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::gain_life(1)]
    ),],
);
