//! Soul of Magma — {3}{R}{R} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, this creature deals 1 damage to target creature.
//! Set: CHK #189 — Champions of Kamigawa | Scryfall ID: 40b20126-da96-4d79-8d3f-8d7da8e94f4a | Oracle ID: 1566af29-bd7b-41bb-a589-499348fbd32c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::SOUL_OF_MAGMA,
    oracle_id = "1566af29-bd7b-41bb-a589-499348fbd32c",
    scryfall_id = "40b20126-da96-4d79-8d3f-8d7da8e94f4a",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Soul of Magma",
        mana_cost = mana!("{3}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Object(&Filter::CREATURE)
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
