//! Tatyova, Benthic Druid — {3}{G}{U} — Legendary Creature — Merfolk Druid
//! Oracle: Landfall — Whenever a land you control enters, you gain 1 life and draw a card.
//! Set: FDN #247 — Foundations | Scryfall ID: eabc978a-0666-472d-bdc6-d4b29d29eca4 | Oracle ID: 0715e860-3b3b-4331-9718-207973e94fee
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TATYOVA_BENTHIC_DRUID,
    oracle_id = "0715e860-3b3b-4331-9718-207973e94fee",
    scryfall_id = "eabc978a-0666-472d-bdc6-d4b29d29eca4",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tatyova, Benthic Druid",
        mana_cost = mana!("{3}{G}{U}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::MERFOLK, subtypes::creature::DRUID],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::EntersBattlefield(&Filter::YOUR_LAND),
        &[Effect::gain_life(1), Effect::draw(1)]
    ),],
);
