//! Tor Wauki — {2}{B}{B}{R} — Legendary Creature — Human Archer
//! Oracle: {T}: Tor Wauki deals 2 damage to target attacking or blocking creature.
//! Set: ME3 #182 — Masters Edition III | Scryfall ID: b37c8bc5-5b9e-431f-afee-09f961e4a7d0 | Oracle ID: 9439dfa0-daf8-4dac-af32-755fc2984126
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::And(&[Filter::CREATURE, Filter::Attacking]),
    Filter::And(&[Filter::CREATURE, Filter::Blocking]),
]);

card!(
    index = index::TOR_WAUKI,
    oracle_id = "9439dfa0-daf8-4dac-af32-755fc2984126",
    scryfall_id = "b37c8bc5-5b9e-431f-afee-09f961e4a7d0",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tor Wauki",
        mana_cost = mana!("{2}{B}{B}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ARCHER],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DealDamage {
            amount: Amount::Fixed(2),
            target: TargetSpec::Object(&TARGET1)
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
