//! Totem Speaker — {4}{G} — Creature — Elf Druid
//! Oracle: Whenever a Beast enters, you may gain 3 life.
//! Set: LGN #141 — Legions | Scryfall ID: ce12115b-2667-47f7-bd24-17c982a4f79a | Oracle ID: 61aa0e56-e8d9-4223-895f-e54cdc5a3f0f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::HasSubtype(subtypes::creature::BEAST);

card!(
    index = index::TOTEM_SPEAKER,
    oracle_id = "61aa0e56-e8d9-4223-895f-e54cdc5a3f0f",
    scryfall_id = "ce12115b-2667-47f7-bd24-17c982a4f79a",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Totem Speaker",
        mana_cost = mana!("{4}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::DRUID],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::EntersBattlefield(&TRIGGER1),
        &[Effect::MayDo {
            effects: &[Effect::gain_life(3)]
        }]
    ),],
);
