//! Wind Spirit — {4}{U} — Creature — Elemental Spirit
//! Oracle: Flying
//! Oracle: Menace (This creature can't be blocked except by two or more creatures.)
//! Set: ME2 #75 — Masters Edition II | Scryfall ID: da614b44-a70a-454b-954b-a420e7f3d62f | Oracle ID: d4c22b68-c4cb-447a-97df-431e2f1e31f2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WIND_SPIRIT,
    oracle_id = "d4c22b68-c4cb-447a-97df-431e2f1e31f2",
    scryfall_id = "da614b44-a70a-454b-954b-a420e7f3d62f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING.union(KeywordSet::MENACE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wind Spirit",
        mana_cost = mana!("{4}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELEMENTAL, subtypes::creature::SPIRIT],
        power = Some(3),
        toughness = Some(2),
    ),],
);
