//! Crosis's Catacombs — (no cost) — Land — Lair
//! Oracle: When this land enters, sacrifice it unless you return a non-Lair land you control to its owner's hand.
//! Oracle: {T}: Add {U}, {B}, or {R}.
//! Set: DMR #242 — Dominaria Remastered | Scryfall ID: 52ce462b-e4de-4972-9e96-2e3d3a20d1fc | Oracle ID: e9a7dede-3968-4b0e-a707-419d46a6fec9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::LAND,
    Filter::Not(&Filter::HasSubtype(subtypes::land::LAIR)),
    Filter::ControlledByYou,
]);

card!(
    index = index::CROSIS_S_CATACOMBS,
    oracle_id = "e9a7dede-3968-4b0e-a707-419d46a6fec9",
    scryfall_id = "52ce462b-e4de-4972-9e96-2e3d3a20d1fc",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crosis's Catacombs",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::LAIR],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[
            ManaColor::Blue,
            ManaColor::Black,
            ManaColor::Red
        ])]),
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::ReturnToHand(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
    ],
);
