//! Treva's Ruins — (no cost) — Land — Lair
//! Oracle: When this land enters, sacrifice it unless you return a non-Lair land you control to its owner's hand.
//! Oracle: {T}: Add {G}, {W}, or {U}.
//! Set: DMR #260 — Dominaria Remastered | Scryfall ID: 4f39366c-00df-4528-a324-6a89d0c53f0a | Oracle ID: 7b2c7758-2b89-49ff-8838-8dc9880c7209
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::LAND,
    Filter::Not(&Filter::HasSubtype(subtypes::land::LAIR)),
    Filter::ControlledByYou,
]);

card!(
    index = index::TREVA_S_RUINS,
    oracle_id = "7b2c7758-2b89-49ff-8838-8dc9880c7209",
    scryfall_id = "4f39366c-00df-4528-a324-6a89d0c53f0a",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Treva's Ruins",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::LAIR],
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana_choice(&[
            ManaColor::Green,
            ManaColor::White,
            ManaColor::Blue
        ])]),
        triggered!(
            Trigger::ETB,
            &[Effect::PlayerMayPayCostOr {
                player: PlayerRel::You,
                cost: &CostPart::ReturnToHand(&COST1),
                effect: &Effect::SacrificeSelf
            }]
        ),
    ],
);
