//! Ferocious Charge — {2}{G} — Instant
//! Oracle: Target creature gets +4/+4 until end of turn. Scry 2. (Look at the top two cards of your library, then put any number of them on the bottom and the rest on top in any order.)
//! Set: 5DN #88 — Fifth Dawn | Scryfall ID: 3749181f-7b4e-4b9d-aaf3-94f707c306aa | Oracle ID: a7796af7-d41c-42a6-9033-a4d79dee84d6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::FEROCIOUS_CHARGE,
    oracle_id = "a7796af7-d41c-42a6-9033-a4d79dee84d6",
    scryfall_id = "3749181f-7b4e-4b9d-aaf3-94f707c306aa",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ferocious Charge",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::PumpTarget {
                power: Amount::Fixed(4),
                toughness: Amount::Fixed(4),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            },
            Effect::scry(2)
        ],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
