//! Rescind — {1}{U}{U} — Instant
//! Oracle: Return target permanent to its owner's hand.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: VMA #90 — Vintage Masters | Scryfall ID: 0f138d4b-64ab-490f-a79b-94e516b1c047 | Oracle ID: 3f487c8e-a923-4031-b0a7-04f778544fe0
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RESCIND,
    oracle_id = "3f487c8e-a923-4031-b0a7-04f778544fe0",
    scryfall_id = "0f138d4b-64ab-490f-a79b-94e516b1c047",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rescind",
        mana_cost = mana!("{1}{U}{U}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{2}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::bounce(TargetSpec::Object(&Filter::Any))],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::Any)))
        ),
    ],
);
