//! Scrap — {2}{R} — Instant
//! Oracle: Destroy target artifact.
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: USG #213 — Urza's Saga | Scryfall ID: 3f070430-59d6-462f-9f04-306ffc2ae01b | Oracle ID: 0ad3b788-eb3d-4876-9c89-893429595e0e
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SCRAP,
    oracle_id = "0ad3b788-eb3d-4876-9c89-893429595e0e",
    scryfall_id = "3f070430-59d6-462f-9f04-306ffc2ae01b",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Scrap",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[
        activated!(
            cost!("{2}", DiscardSelf),
            &[Effect::draw(1)],
            zone = ActivationZone::Hand
        ),
        spell!(
            &[Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT))],
            targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
        ),
    ],
);
