//! Smash — {2}{R} — Instant
//! Oracle: Destroy target artifact.
//! Oracle: Draw a card.
//! Set: 10E #235 — Tenth Edition | Scryfall ID: 40c39852-efd3-4a25-b33b-3c13dad96e7d | Oracle ID: 1602f8c7-fe00-4bc9-b4fc-b26b7223ac75
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SMASH,
    oracle_id = "1602f8c7-fe00-4bc9-b4fc-b26b7223ac75",
    scryfall_id = "40c39852-efd3-4a25-b33b-3c13dad96e7d",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Smash",
        mana_cost = mana!("{2}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT)),
            Effect::draw(1)
        ],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
    ),],
);
