//! Verdigris — {2}{G} — Instant
//! Oracle: Destroy target artifact.
//! Set: TPR #204 — Tempest Remastered | Scryfall ID: 683c74be-ba8a-4c6b-b637-ce22f98a7cda | Oracle ID: fb41ea1d-3491-4193-a390-8eb202fbae12
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::VERDIGRIS,
    oracle_id = "fb41ea1d-3491-4193-a390-8eb202fbae12",
    scryfall_id = "683c74be-ba8a-4c6b-b637-ce22f98a7cda",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Verdigris",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(&Filter::ARTIFACT))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ARTIFACT)))
    ),],
);
