//! baylee-core — shared, wasm-safe foundations for the whole platform.
//!
//! - [`ids`]: typed integer handles (no strings in rules code)
//! - [`color`]: colors and color sets
//! - [`types`]: card types, supertypes, subtype identifiers
//! - [`mana`]: mana symbols, costs, pools (see `docs/mana-notation.md`)
//! - [`preset`]: reproducible game start definitions incl. the print table

#![warn(missing_docs)]

pub mod acceptance;
pub mod color;
pub mod deckrow;
pub mod generated {
    //! Generated constants — regenerated by `cargo xtask codegen`, never edited by hand.
    pub mod subtypes;

    #[cfg(test)]
    mod subtype_tests {
        use super::subtypes;

        /// `NAMES` is a dense array indexed by subtype id. If codegen ever
        /// emitted the constants and the name table out of step, every type
        /// line a client builds would be silently wrong — off by one, with
        /// plausible-looking output. Length and round trip are what catch it.
        #[test]
        fn every_subtype_id_has_a_name_that_maps_back_to_it() {
            assert_eq!(subtypes::NAMES.len(), subtypes::COUNT as usize);
            for id in 0..subtypes::COUNT {
                let id = crate::ids::SubtypeId::new(id);
                let name = subtypes::name(id).expect("every id in range is named");
                assert_eq!(
                    subtypes::by_name(name),
                    Some(id),
                    "{name} does not map back to its own id"
                );
            }
        }

        /// The names are the printed spelling, not the constant spelling —
        /// a type line says `Assembly-Worker`, never `ASSEMBLY_WORKER`.
        #[test]
        fn names_are_printed_spelling() {
            assert_eq!(
                subtypes::name(subtypes::creature::ASSEMBLY_WORKER),
                Some("Assembly-Worker")
            );
            assert_eq!(subtypes::name(subtypes::land::FOREST), Some("Forest"));
        }
    }
}
pub mod ids;
pub mod mana;
pub mod preset;
pub mod types;

/// Parses a mana cost literal **at compile time**; invalid literals are
/// compile errors. See `docs/mana-notation.md`.
///
/// ```
/// let cost = baylee_core::mana!("{2}{W/U}{W/P}");
/// assert_eq!(cost.cmc(), 4);
/// ```
///
/// ```compile_fail
/// let _ = baylee_core::mana!("not a cost");
/// ```
#[macro_export]
macro_rules! mana {
    ($s:literal) => {{
        const COST: $crate::mana::ManaCost = $crate::mana::ManaCost::parse($s);
        COST
    }};
}
