//! baylee-core — shared, wasm-safe foundations for the whole platform.
//!
//! - [`ids`]: typed integer handles (no strings in rules code)
//! - [`color`]: colors and color sets
//! - [`types`]: card types, supertypes, subtype identifiers
//! - [`mana`]: mana symbols, costs, pools (see `docs/mana-notation.md`)
//! - [`preset`]: reproducible game start definitions incl. the print table

#![warn(missing_docs)]

pub mod color;
pub mod generated {
    //! Generated constants — regenerated by `cargo xtask codegen`, never edited by hand.
    pub mod subtypes;
}
pub mod ids;
pub mod mana;
pub mod preset;
pub mod types;

/// Parses a mana cost literal **at compile time**; invalid literals are
/// compile errors. See `docs/mana-notation.md`.
///
/// ```
/// let cost = baylee_core::mana!("{2}{W/U}{W/P}");
/// assert_eq!(cost.cmc(), 4);
/// ```
///
/// ```compile_fail
/// let _ = baylee_core::mana!("not a cost");
/// ```
#[macro_export]
macro_rules! mana {
    ($s:literal) => {{
        const COST: $crate::mana::ManaCost = $crate::mana::ManaCost::parse($s);
        COST
    }};
}
