//! The Fair Basilica — (no cost) — Land — Sphere
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {W}.
//! Oracle: {1}{W}, {T}, Sacrifice this land: Draw a card.
//! Set: ONE #252 — Phyrexia: All Will Be One | Scryfall ID: 01d6ba55-7bc0-41c6-84be-8cd528e46a05 | Oracle ID: 8618f8e8-fd86-47e3-905d-e6624b599b9b
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1171,
    oracle_id: "8618f8e8-fd86-47e3-905d-e6624b599b9b",
    scryfall_id: "01d6ba55-7bc0-41c6-84be-8cd528e46a05",
    color_identity: ColorSet::from_slice(&[Color::White]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "The Fair Basilica",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SPHERE],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::White, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{W}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
