//! The Hunter Maze — (no cost) — Land — Sphere
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {G}.
//! Oracle: {1}{G}, {T}, Sacrifice this land: Draw a card.
//! Set: ONE #253 — Phyrexia: All Will Be One | Scryfall ID: 6389c242-2139-4f12-af30-2b080a1c5e83 | Oracle ID: b0ea4975-a944-4585-8711-60f203cffa4a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, enters tapped.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card! {
    index: 1175,
    oracle_id: "b0ea4975-a944-4585-8711-60f203cffa4a",
    scryfall_id: "6389c242-2139-4f12-af30-2b080a1c5e83",
    color_identity: ColorSet::from_slice(&[Color::Green]),
    coverage: Coverage::Implemented,
    faces: &[
    face! {
        name: "The Hunter Maze",
        types: TypeSet::LAND,
        subtypes: &[subtypes::land::SPHERE],
        enter_modifiers: &[EnterModifier::Tapped],
    },
    ],
    abilities: &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(Cost { mana: baylee_core::mana!("{1}{G}"), parts: &[CostPart::TapSelf, CostPart::SacrificeSelf] }, &[Effect::DrawCards { amount: Amount::Fixed(1) }]),
    ],
}
