//! Akki Raider — {1}{R} — Creature — Goblin Warrior
//! Oracle: Whenever a land is put into a graveyard from the battlefield, this creature gets +1/+0 until end of turn.
//! Set: BOK #92 — Betrayers of Kamigawa | Scryfall ID: c8fb34ae-157c-4f4b-bb47-2a9dc394a20c | Oracle ID: bf9c5c0d-86a5-467a-863c-653279f2e6e7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AKKI_RAIDER,
    oracle_id = "bf9c5c0d-86a5-467a-863c-653279f2e6e7",
    scryfall_id = "c8fb34ae-157c-4f4b-bb47-2a9dc394a20c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Akki Raider",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::WARRIOR],
        power = Some(2),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::LAND),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
