//! Alaborn Musketeer — {1}{W} — Creature — Human Soldier
//! Oracle: Reach (This creature can block creatures with flying.)
//! Set: ME4 #1 — Masters Edition IV | Scryfall ID: 1a40c1ed-acdf-464a-8625-5cd35e7533d5 | Oracle ID: 61daa88d-fca4-4019-97f3-568346157ba6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ALABORN_MUSKETEER,
    oracle_id = "61daa88d-fca4-4019-97f3-568346157ba6",
    scryfall_id = "1a40c1ed-acdf-464a-8625-5cd35e7533d5",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::REACH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Alaborn Musketeer",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(1),
    ),],
);
