//! Amrou Kithkin — {W}{W} — Creature — Kithkin
//! Oracle: This creature can't be blocked by creatures with power 3 or greater.
//! Set: ME3 #3 — Masters Edition III | Scryfall ID: 278d86b4-8d62-4932-a66d-062971295631 | Oracle ID: 79644192-8f99-4d04-b151-6f74a4dbda0a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static BLOCKER1: Filter = Filter::And(&[Filter::CREATURE, Filter::PowerAtLeast(3)]);

card!(
    index = index::AMROU_KITHKIN,
    oracle_id = "79644192-8f99-4d04-b151-6f74a4dbda0a",
    scryfall_id = "278d86b4-8d62-4932-a66d-062971295631",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Amrou Kithkin",
        mana_cost = mana!("{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KITHKIN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[static_ability!(
        Filter::And(&[Filter::CREATURE, Filter::This]),
        Modifier::CantBeBlockedBy(&BLOCKER1)
    ),],
);
