//! Argothian Enchantress — {1}{G} — Creature — Human Druid
//! Oracle: Shroud (This creature can't be the target of spells or abilities.)
//! Oracle: Whenever you cast an enchantment spell, draw a card.
//! Set: EMA #158 — Eternal Masters | Scryfall ID: b99ff81f-08d9-4b4a-a879-de5e5e402802 | Oracle ID: 11f17f85-ca97-4551-838f-7cb32f0e5f10
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::And(&[Filter::ENCHANTMENT, Filter::ControlledByYou]);

card!(
    index = index::ARGOTHIAN_ENCHANTRESS,
    oracle_id = "11f17f85-ca97-4551-838f-7cb32f0e5f10",
    scryfall_id = "b99ff81f-08d9-4b4a-a879-de5e5e402802",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::SHROUD,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Argothian Enchantress",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::DRUID],
        power = Some(0),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::draw(1)]
    ),],
);
