//! Basal Thrull — {B}{B} — Creature — Thrull
//! Oracle: {T}, Sacrifice this creature: Add {B}{B}.
//! Set: ME1 #59 — Masters Edition | Scryfall ID: f4cf027e-2021-4ce7-b156-199cf1ca25eb | Oracle ID: 9da50130-3f83-4968-983c-7dcba257cf1b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BASAL_THRULL,
    oracle_id = "9da50130-3f83-4968-983c-7dcba257cf1b",
    scryfall_id = "f4cf027e-2021-4ce7-b156-199cf1ca25eb",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Basal Thrull",
        mana_cost = mana!("{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::THRULL],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[mana_ability!(
        cost!(TapSelf, SacrificeSelf),
        &[Effect::mana(ManaColor::Black, 2)]
    ),],
);
