//! Blighted Shaman — {1}{B} — Creature — Human Cleric Shaman
//! Oracle: {T}, Sacrifice a Swamp: Target creature gets +1/+1 until end of turn.
//! Oracle: {T}, Sacrifice a creature: Target creature gets +2/+2 until end of turn.
//! Set: 6ED #114 — Classic Sixth Edition | Scryfall ID: 1d46c90a-215a-4897-94f8-52a02abf25c4 | Oracle ID: 2f14e92d-307f-4854-b7ec-a2f6ce03dced
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::ControlledByYou,
]);

card!(
    index = index::BLIGHTED_SHAMAN,
    oracle_id = "2f14e92d-307f-4854-b7ec-a2f6ce03dced",
    scryfall_id = "1d46c90a-215a-4897-94f8-52a02abf25c4",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Blighted Shaman",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::CLERIC,
            subtypes::creature::SHAMAN
        ],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!(TapSelf, Sacrifice(&COST1)),
            &[Effect::PumpTarget {
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!(TapSelf, Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(2),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
    ],
);
