//! Blood Artist — {1}{B} — Creature — Vampire
//! Oracle: Whenever this creature or another creature dies, target player loses 1 life and you gain 1 life.
//! Set: SOC #209 — Secrets of Strixhaven Commander | Scryfall ID: b5275d76-2947-4219-be21-614c7421614a | Oracle ID: 310f141c-7f37-4729-aed6-dd9c09db448d
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::This,
    Filter::And(&[Filter::CREATURE, Filter::Another]),
]);

card!(
    index = index::BLOOD_ARTIST,
    oracle_id = "310f141c-7f37-4729-aed6-dd9c09db448d",
    scryfall_id = "b5275d76-2947-4219-be21-614c7421614a",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Blood Artist",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::VAMPIRE],
        power = Some(0),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&TRIGGER1),
        &[
            Effect::LoseLife {
                amount: Amount::Fixed(1),
                target: PlayerRel::Chosen
            },
            Effect::gain_life(1)
        ],
        targets = Some(TargetReq::one(TargetSpec::AnyPlayer))
    ),],
);
