//! Brine Shaman — {1}{B} — Creature — Human Cleric Shaman
//! Oracle: {T}, Sacrifice a creature: Target creature gets +2/+2 until end of turn.
//! Oracle: {1}{U}{U}, Sacrifice a creature: Counter target creature spell.
//! Set: ME2 #80 — Masters Edition II | Scryfall ID: 4b2dfbde-be23-42ea-be68-76e2c019c317 | Oracle ID: 3e3e2f71-2159-4f83-a9c1-a67ecac8a711
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::BRINE_SHAMAN,
    oracle_id = "3e3e2f71-2159-4f83-a9c1-a67ecac8a711",
    scryfall_id = "4b2dfbde-be23-42ea-be68-76e2c019c317",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Brine Shaman",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::CLERIC,
            subtypes::creature::SHAMAN
        ],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        activated!(
            cost!(TapSelf, Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::PumpTarget {
                power: Amount::Fixed(2),
                toughness: Amount::Fixed(2),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{1}{U}{U}", Sacrifice(&Filter::YOUR_CREATURE)),
            &[Effect::CounterTargetSpell],
            target = Some(TargetSpec::Spell(&Filter::CREATURE))
        ),
    ],
);
