//! Capashen Knight — {1}{W} — Creature — Human Knight
//! Oracle: First strike (This creature deals combat damage before creatures without first strike.)
//! Oracle: {1}{W}: This creature gets +1/+0 until end of turn.
//! Set: M14 #11 — Magic 2014 | Scryfall ID: 78802af4-46b5-4bac-8cdf-5b77d0b19895 | Oracle ID: e295d207-128f-419a-866a-c9ac6248c199
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CAPASHEN_KNIGHT,
    oracle_id = "e295d207-128f-419a-866a-c9ac6248c199",
    scryfall_id = "78802af4-46b5-4bac-8cdf-5b77d0b19895",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Capashen Knight",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::KNIGHT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{1}{W}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(1),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
