//! Consumptive Goo — {B}{B} — Creature — Ooze
//! Oracle: {2}{B}{B}: Target creature gets -1/-1 until end of turn. Put a +1/+1 counter on this creature.
//! Set: SCG #62 — Scourge | Scryfall ID: 0f0f549f-6607-483a-9d89-2019ca9ef571 | Oracle ID: 4bbfa49e-4460-439e-8f31-2e54316fbb5f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CONSUMPTIVE_GOO,
    oracle_id = "4bbfa49e-4460-439e-8f31-2e54316fbb5f",
    scryfall_id = "0f0f549f-6607-483a-9d89-2019ca9ef571",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Consumptive Goo",
        mana_cost = mana!("{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::OOZE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{2}{B}{B}"),
        &[
            Effect::PumpTarget {
                power: Amount::NegXFixed(1),
                toughness: Amount::NegXFixed(1),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            },
            Effect::AddCounterFilter {
                filter: &Filter::This,
                kind: CounterKind::P1P1,
                amount: Amount::Fixed(1)
            }
        ],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
