//! Dandân — {U}{U} — Creature — Fish
//! Oracle: This creature can't attack unless defending player controls an Island.
//! Oracle: When you control no Islands, sacrifice this creature.
//! Set: TSB #19 — Time Spiral Timeshifted | Scryfall ID: ac2e32d0-f172-4934-9d73-1bc2ab86586e | Oracle ID: 88929373-b2c8-4a81-a809-fed87fd5b0d7
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static DEFENDER_CONTROLS1: Filter = Filter::HasSubtype(subtypes::land::ISLAND);

static CHECK2: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::ControlledByYou,
]);

static STATE3: Condition = Condition::ControlCountAtMost(&CHECK2, 0);

card!(
    index = index::DANDAN,
    oracle_id = "88929373-b2c8-4a81-a809-fed87fd5b0d7",
    scryfall_id = "ac2e32d0-f172-4934-9d73-1bc2ab86586e",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dandân",
        mana_cost = mana!("{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FISH],
        power = Some(4),
        toughness = Some(1),
    ),],
    abilities = &[
        static_ability!(
            Filter::This,
            Modifier::CantAttackUnlessDefenderControls(&DEFENDER_CONTROLS1)
        ),
        triggered!(Trigger::State(&STATE3), &[Effect::SacrificeSelf]),
    ],
);
