//! Devoted Druid — {1}{G} — Creature — Elf Druid
//! Oracle: {T}: Add {G}.
//! Oracle: Put a -1/-1 counter on this creature: Untap this creature.
//! Set: ECC #104 — Lorwyn Eclipsed Commander | Scryfall ID: 22589a81-3ea8-4e78-98c9-c015e7539cf9 | Oracle ID: cb814e16-acf7-41d5-a357-1323dcc369f3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DEVOTED_DRUID,
    oracle_id = "cb814e16-acf7-41d5-a357-1323dcc369f3",
    scryfall_id = "22589a81-3ea8-4e78-98c9-c015e7539cf9",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Devoted Druid",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::DRUID],
        power = Some(0),
        toughness = Some(2),
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(
            cost!(PutCounterSelf {
                kind: CounterKind::M1M1,
                n: 1
            }),
            &[Effect::UntapSelf]
        ),
    ],
);
