//! Drudge Skeletons — {1}{B} — Creature — Skeleton
//! Oracle: {B}: Regenerate this creature. (The next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal all damage on it.)
//! Set: GVL #36 — Duel Decks Anthology: Garruk vs. Liliana | Scryfall ID: bd6f73bc-3181-40fa-9156-b73e4280e747 | Oracle ID: c180ed02-07f4-4538-9bea-8c249234a8e2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DRUDGE_SKELETONS,
    oracle_id = "c180ed02-07f4-4538-9bea-8c249234a8e2",
    scryfall_id = "bd6f73bc-3181-40fa-9156-b73e4280e747",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Drudge Skeletons",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SKELETON],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{B}"),
        &[Effect::regenerate(TargetSpec::ThisObject)]
    ),],
);
