//! Dwarven Miner — {1}{R} — Creature — Dwarf
//! Oracle: {2}{R}, {T}: Destroy target nonbasic land.
//! Set: MIR #169 — Mirage | Scryfall ID: b7142196-c379-4932-9402-97642ad2ebdb | Oracle ID: 0935377b-384f-4e4c-9fbb-8d2a7d5dc280
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::DWARVEN_MINER,
    oracle_id = "0935377b-384f-4e4c-9fbb-8d2a7d5dc280",
    scryfall_id = "b7142196-c379-4932-9402-97642ad2ebdb",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dwarven Miner",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DWARF],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{2}{R}", TapSelf),
        &[Effect::destroy(TargetSpec::Object(&Filter::NONBASIC_LAND))],
        target = Some(TargetSpec::Object(&Filter::NONBASIC_LAND))
    ),],
);
