//! Earthblighter — {1}{B} — Creature — Human Cleric
//! Oracle: {2}{B}, {T}, Sacrifice a Goblin: Destroy target land.
//! Set: LGN #68 — Legions | Scryfall ID: 830a4048-48ac-4856-9af9-5052ec146518 | Oracle ID: 86b8fdad-0025-4b6f-8527-23686820a5cd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::GOBLIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::EARTHBLIGHTER,
    oracle_id = "86b8fdad-0025-4b6f-8527-23686820a5cd",
    scryfall_id = "830a4048-48ac-4856-9af9-5052ec146518",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Earthblighter",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::CLERIC],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{2}{B}", TapSelf, Sacrifice(&COST1)),
        &[Effect::destroy(TargetSpec::Object(&Filter::LAND))],
        target = Some(TargetSpec::Object(&Filter::LAND))
    ),],
);
