//! Elvish Archers — {1}{G} — Creature — Elf Archer
//! Oracle: First strike
//! Set: 7ED #239 — Seventh Edition | Scryfall ID: 0e8411c9-4f6f-4301-ac36-386016a32852 | Oracle ID: 534ce8e2-53a1-407c-9881-d3b5347d43c3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ELVISH_ARCHERS,
    oracle_id = "534ce8e2-53a1-407c-9881-d3b5347d43c3",
    scryfall_id = "0e8411c9-4f6f-4301-ac36-386016a32852",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Elvish Archers",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::ARCHER],
        power = Some(2),
        toughness = Some(1),
    ),],
);
