//! Emerald Dragonfly — {1}{G} — Creature — Insect
//! Oracle: Flying
//! Oracle: {G}{G}: This creature gains first strike until end of turn.
//! Set: CHR #63 — Chronicles | Scryfall ID: 931f2093-4d43-449e-82e8-beb97d25a0e8 | Oracle ID: b067aa04-5977-4371-85d1-78d2884df03f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::EMERALD_DRAGONFLY,
    oracle_id = "b067aa04-5977-4371-85d1-78d2884df03f",
    scryfall_id = "931f2093-4d43-449e-82e8-beb97d25a0e8",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Emerald Dragonfly",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::INSECT],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{G}{G}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FIRST_STRIKE,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
