//! Femeref Enchantress — {G}{W} — Creature — Human Druid
//! Oracle: Whenever an enchantment is put into a graveyard from the battlefield, draw a card.
//! Set: VIS #129 — Visions | Scryfall ID: 20ba72c7-7957-4d02-b41e-c0132fe1f2e6 | Oracle ID: 8b983a46-580f-4a94-8ef3-5253e503148e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FEMEREF_ENCHANTRESS,
    oracle_id = "8b983a46-580f-4a94-8ef3-5253e503148e",
    scryfall_id = "20ba72c7-7957-4d02-b41e-c0132fe1f2e6",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Femeref Enchantress",
        mana_cost = mana!("{G}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::DRUID],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&Filter::ENCHANTMENT),
        &[Effect::draw(1)]
    ),],
);
