//! Fledgling Djinn — {1}{B} — Creature — Djinn
//! Oracle: Flying
//! Oracle: At the beginning of your upkeep, this creature deals 1 damage to you.
//! Set: VMA #121 — Vintage Masters | Scryfall ID: 0863567a-13d6-4876-99eb-c592c3ea49a3 | Oracle ID: 2c73ef77-ae58-401f-8747-538c4cd075d0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FLEDGLING_DJINN,
    oracle_id = "2c73ef77-ae58-401f-8747-538c4cd075d0",
    scryfall_id = "0863567a-13d6-4876-99eb-c592c3ea49a3",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Fledgling Djinn",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DJINN],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Player(PlayerRel::You)
        }]
    ),],
);
