//! Floodbringer — {1}{U} — Creature — Moonfolk Wizard
//! Oracle: Flying
//! Oracle: {2}, Return a land you control to its owner's hand: Tap target land.
//! Set: BOK #34 — Betrayers of Kamigawa | Scryfall ID: 0058be07-a8a1-448e-8c3d-61718cb384ec | Oracle ID: 6c8bba8b-44de-4bbf-bf6a-3045e7313995
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FLOODBRINGER,
    oracle_id = "6c8bba8b-44de-4bbf-bf6a-3045e7313995",
    scryfall_id = "0058be07-a8a1-448e-8c3d-61718cb384ec",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Floodbringer",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MOONFOLK, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{2}", ReturnToHand(&Filter::YOUR_LAND)),
        &[Effect::TapTarget],
        target = Some(TargetSpec::Object(&Filter::LAND))
    ),],
);
