//! Gaea's Skyfolk — {G}{U} — Creature — Elf Merfolk
//! Oracle: Flying
//! Set: APC #101 — Apocalypse | Scryfall ID: 8a564432-c2b3-4cf6-b4bc-2e2600b92911 | Oracle ID: dd0da475-55d0-462e-bfac-6eeb5d39a099
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GAEA_S_SKYFOLK,
    oracle_id = "dd0da475-55d0-462e-bfac-6eeb5d39a099",
    scryfall_id = "8a564432-c2b3-4cf6-b4bc-2e2600b92911",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gaea's Skyfolk",
        mana_cost = mana!("{G}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::MERFOLK],
        power = Some(2),
        toughness = Some(2),
    ),],
);
