//! Giant Tortoise — {1}{U} — Creature — Turtle
//! Oracle: This creature gets +0/+3 as long as it's untapped.
//! Set: EMA #52 — Eternal Masters | Scryfall ID: 5124c4bd-d9a4-4f17-80fc-c64d4a77a614 | Oracle ID: 2dd50d7f-941f-4deb-a15c-ee2357844c35
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GIANT_TORTOISE,
    oracle_id = "2dd50d7f-941f-4deb-a15c-ee2357844c35",
    scryfall_id = "5124c4bd-d9a4-4f17-80fc-c64d4a77a614",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Giant Tortoise",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::TURTLE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[static_ability!(
        Filter::And(&[Filter::This, Filter::Untapped]),
        Modifier::ModifyPT(0, 3)
    ),],
);
