//! Grizzly Bears — {1}{G} — Creature — Bear
//! Set: 10E #268 — Tenth Edition | Scryfall ID: 409f9b88-f03e-40b6-9883-68c14c37c0de | Oracle ID: 14c8f55d-d177-4c25-a931-ebeb9e6062a0
// IMPLEMENTED — generated by `xtask codegen`: no rules text.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GRIZZLY_BEARS,
    oracle_id = "14c8f55d-d177-4c25-a931-ebeb9e6062a0",
    scryfall_id = "409f9b88-f03e-40b6-9883-68c14c37c0de",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Grizzly Bears",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BEAR],
        power = Some(2),
        toughness = Some(2),
    ),],
);
