//! Guardian of Solitude — {1}{U} — Creature — Spirit
//! Oracle: Whenever you cast a Spirit or Arcane spell, target creature gains flying until end of turn.
//! Set: CHK #64 — Champions of Kamigawa | Scryfall ID: 85d16011-956b-40ac-afb6-6c7ad774802f | Oracle ID: 712ec339-ffa8-43bb-a826-a7b0f0120b1f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::And(&[
        Filter::HasSubtype(subtypes::creature::SPIRIT),
        Filter::ControlledByYou,
    ]),
    Filter::And(&[
        Filter::HasSubtype(subtypes::spell::ARCANE),
        Filter::ControlledByYou,
    ]),
]);

card!(
    index = index::GUARDIAN_OF_SOLITUDE,
    oracle_id = "712ec339-ffa8-43bb-a826-a7b0f0120b1f",
    scryfall_id = "85d16011-956b-40ac-afb6-6c7ad774802f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Guardian of Solitude",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&TRIGGER1),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
