//! Heart Warden — {1}{G} — Creature — Elf Druid
//! Oracle: {T}: Add {G}.
//! Oracle: {2}, Sacrifice this creature: Draw a card.
//! Set: UDS #108 — Urza's Destiny | Scryfall ID: 96e42dbe-3eeb-4367-bb6d-0f5c71f5da80 | Oracle ID: babcc551-39bb-4b1c-92a0-e60b236a59b2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::HEART_WARDEN,
    oracle_id = "babcc551-39bb-4b1c-92a0-e60b236a59b2",
    scryfall_id = "96e42dbe-3eeb-4367-bb6d-0f5c71f5da80",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Heart Warden",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::DRUID],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),
        activated!(cost!("{2}", SacrificeSelf), &[Effect::draw(1)]),
    ],
);
