//! Kami of Ancient Law — {1}{W} — Creature — Spirit
//! Oracle: Sacrifice this creature: Destroy target enchantment.
//! Set: SOC #150 — Secrets of Strixhaven Commander | Scryfall ID: 4edbce98-bfc1-4c66-bd04-16100d9e22d3 | Oracle ID: e937e0f5-ca35-4dce-9f05-8f2075731628
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KAMI_OF_ANCIENT_LAW,
    oracle_id = "e937e0f5-ca35-4dce-9f05-8f2075731628",
    scryfall_id = "4edbce98-bfc1-4c66-bd04-16100d9e22d3",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kami of Ancient Law",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(SacrificeSelf),
        &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
        target = Some(TargetSpec::Object(&Filter::ENCHANTMENT))
    ),],
);
