//! Kobold Drill Sergeant — {1}{R} — Creature — Kobold Soldier
//! Oracle: Other Kobold creatures you control get +0/+1 and have trample.
//! Set: ME3 #104 — Masters Edition III | Scryfall ID: 2e918e64-66dd-4037-ba1a-1c569a9907f7 | Oracle ID: a6409aa6-035c-4859-8135-90d34d67f72c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KOBOLD_DRILL_SERGEANT,
    oracle_id = "a6409aa6-035c-4859-8135-90d34d67f72c",
    scryfall_id = "2e918e64-66dd-4037-ba1a-1c569a9907f7",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kobold Drill Sergeant",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KOBOLD, subtypes::creature::SOLDIER],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::KOBOLD),
                Filter::Another,
                Filter::ControlledByYou
            ]),
            Modifier::ModifyPT(0, 1)
        ),
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::KOBOLD),
                Filter::Another,
                Filter::ControlledByYou
            ]),
            Modifier::AddKeyword(KeywordSet::TRAMPLE)
        ),
    ],
);
