//! Llanowar Dead — {B}{G} — Creature — Zombie Elf
//! Oracle: {T}: Add {B}.
//! Set: APC #109 — Apocalypse | Scryfall ID: f271969e-1529-42d1-878b-011f80ab0f05 | Oracle ID: 3a48541a-240b-4406-945c-1d0d032eca25
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LLANOWAR_DEAD,
    oracle_id = "3a48541a-240b-4406-945c-1d0d032eca25",
    scryfall_id = "f271969e-1529-42d1-878b-011f80ab0f05",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Llanowar Dead",
        mana_cost = mana!("{B}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ZOMBIE, subtypes::creature::ELF],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Black, 1)]),],
);
