//! Master Decoy — {1}{W} — Creature — Human Soldier
//! Oracle: {W}, {T}: Tap target creature.
//! Set: TPR #18 — Tempest Remastered | Scryfall ID: 88bd93e9-4fc8-4c10-8183-c87363601033 | Oracle ID: 94a16609-8529-4301-8a3d-47ced194f7cd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MASTER_DECOY,
    oracle_id = "94a16609-8529-4301-8a3d-47ced194f7cd",
    scryfall_id = "88bd93e9-4fc8-4c10-8183-c87363601033",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Master Decoy",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{W}", TapSelf),
        &[Effect::TapTarget],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
