//! Moon Sprite — {1}{G} — Creature — Faerie
//! Oracle: Flying
//! Set: S00 #42 — Starter 2000 | Scryfall ID: 49d0acb1-bc07-42d5-a327-1617f0ed2c60 | Oracle ID: 1e41136b-afa7-45ee-8d04-d0c7514b5387
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MOON_SPRITE,
    oracle_id = "1e41136b-afa7-45ee-8d04-d0c7514b5387",
    scryfall_id = "49d0acb1-bc07-42d5-a327-1617f0ed2c60",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Moon Sprite",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FAERIE],
        power = Some(1),
        toughness = Some(1),
    ),],
);
