//! Nomadic Elf — {1}{G} — Creature — Elf Nomad
//! Oracle: {1}{G}: Add one mana of any color.
//! Set: DDE #38 — Duel Decks: Phyrexia vs. the Coalition | Scryfall ID: fc4a26f7-36df-4018-8dab-a1294c36b0f0 | Oracle ID: 025bbfc8-bccd-4062-b758-7f9e1f8ad420
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::NOMADIC_ELF,
    oracle_id = "025bbfc8-bccd-4062-b758-7f9e1f8ad420",
    scryfall_id = "fc4a26f7-36df-4018-8dab-a1294c36b0f0",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Nomadic Elf",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::NOMAD],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[mana_ability!(
        cost!("{1}{G}"),
        &[Effect::mana_of_any_color()]
    ),],
);
