//! Oboro Breezecaller — {1}{U} — Creature — Moonfolk Wizard
//! Oracle: Flying
//! Oracle: {2}, Return a land you control to its owner's hand: Untap target land.
//! Set: SOK #48 — Saviors of Kamigawa | Scryfall ID: a382a9b8-0b19-46c2-a547-a22d6e23d0ac | Oracle ID: 257ee9a0-5ee0-49c4-8619-e75e1134d7ac
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::OBORO_BREEZECALLER,
    oracle_id = "257ee9a0-5ee0-49c4-8619-e75e1134d7ac",
    scryfall_id = "a382a9b8-0b19-46c2-a547-a22d6e23d0ac",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Oboro Breezecaller",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MOONFOLK, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{2}", ReturnToHand(&Filter::YOUR_LAND)),
        &[Effect::UntapTarget],
        target = Some(TargetSpec::Object(&Filter::LAND))
    ),],
);
