//! Plant Elemental — {1}{G} — Creature — Plant Elemental
//! Oracle: When this creature enters, sacrifice it unless you sacrifice a Forest.
//! Set: POR #181 — Portal | Scryfall ID: 892594db-1d66-4c45-bd54-608a9972ca77 | Oracle ID: e822bf3d-3a29-4a02-9ae8-e2830ce70f15
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::FOREST),
    Filter::ControlledByYou,
]);

card!(
    index = index::PLANT_ELEMENTAL,
    oracle_id = "e822bf3d-3a29-4a02-9ae8-e2830ce70f15",
    scryfall_id = "892594db-1d66-4c45-bd54-608a9972ca77",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Plant Elemental",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PLANT, subtypes::creature::ELEMENTAL],
        power = Some(3),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::PlayerMayPayCostOr {
            player: PlayerRel::You,
            cost: &CostPart::Sacrifice(&COST1),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
