//! Sakura-Tribe Elder — {1}{G} — Creature — Snake Shaman
//! Oracle: Sacrifice this creature: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
//! Set: SOC #285 — Secrets of Strixhaven Commander | Scryfall ID: 7a8b1c49-8594-426d-b585-41140235bb0e | Oracle ID: e3afc704-220f-498f-9eaa-0821b17dc24c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::SAKURA_TRIBE_ELDER,
    oracle_id = "e3afc704-220f-498f-9eaa-0821b17dc24c",
    scryfall_id = "7a8b1c49-8594-426d-b585-41140235bb0e",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sakura-Tribe Elder",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SNAKE, subtypes::creature::SHAMAN],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!(SacrificeSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD_TAPPED],
            optional: false
        }]
    ),],
);
