//! Shimmering Barrier — {1}{W} — Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: First strike
//! Oracle: Cycling {2} ({2}, Discard this card: Draw a card.)
//! Set: USG #50 — Urza's Saga | Scryfall ID: 2aa7158a-5c00-4969-a116-c40cefdf4591 | Oracle ID: 94674840-c73c-4659-80b9-11140d1deaa3
// IMPLEMENTED — generated by `xtask codegen`: cycling, transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SHIMMERING_BARRIER,
    oracle_id = "94674840-c73c-4659-80b9-11140d1deaa3",
    scryfall_id = "2aa7158a-5c00-4969-a116-c40cefdf4591",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::DEFENDER.union(KeywordSet::FIRST_STRIKE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Shimmering Barrier",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WALL],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{2}", DiscardSelf),
        &[Effect::draw(1)],
        zone = ActivationZone::Hand
    ),],
);
