//! Silverglade Pathfinder — {1}{G} — Creature — Dryad Spellshaper
//! Oracle: {1}{G}, {T}, Discard a card: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
//! Set: MMQ #270 — Mercadian Masques | Scryfall ID: 9bc99b33-ce06-4a44-8b23-300b41b2b2fe | Oracle ID: ac00d3db-d9e4-4fc3-a4ea-dd1187f406bb
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::And(&[Filter::LAND, Filter::HasSupertype(SupertypeSet::BASIC)]);

card!(
    index = index::SILVERGLADE_PATHFINDER,
    oracle_id = "ac00d3db-d9e4-4fc3-a4ea-dd1187f406bb",
    scryfall_id = "9bc99b33-ce06-4a44-8b23-300b41b2b2fe",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Silverglade Pathfinder",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRYAD, subtypes::creature::SPELLSHAPER],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{1}{G}", TapSelf, Discard(&Filter::Any)),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD_TAPPED],
            optional: false
        }]
    ),],
);
