//! Skittering Skirge — {B}{B} — Creature — Phyrexian Imp
//! Oracle: Flying
//! Oracle: When you cast a creature spell, sacrifice this creature.
//! Set: USG #158 — Urza's Saga | Scryfall ID: 93aba9d5-5f96-4aba-8248-74398b8bfe9d | Oracle ID: fae1d5d9-a50e-423e-8692-3e41f39df081
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SKITTERING_SKIRGE,
    oracle_id = "fae1d5d9-a50e-423e-8692-3e41f39df081",
    scryfall_id = "93aba9d5-5f96-4aba-8248-74398b8bfe9d",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Skittering Skirge",
        mana_cost = mana!("{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::IMP],
        power = Some(3),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::SpellCast(&Filter::YOUR_CREATURE),
        &[Effect::SacrificeSelf]
    ),],
);
