//! Skyshroud Falcon — {1}{W} — Creature — Bird
//! Oracle: Flying, vigilance
//! Set: 7ED #45 — Seventh Edition | Scryfall ID: a41aec1d-d86f-4a52-a446-5cef71d1ebd4 | Oracle ID: 877ab494-da90-4c26-a184-c6ba64ec30b5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SKYSHROUD_FALCON,
    oracle_id = "877ab494-da90-4c26-a184-c6ba64ec30b5",
    scryfall_id = "a41aec1d-d86f-4a52-a446-5cef71d1ebd4",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::VIGILANCE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Skyshroud Falcon",
        mana_cost = mana!("{1}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD],
        power = Some(1),
        toughness = Some(1),
    ),],
);
