//! Slobad, Goblin Tinkerer — {1}{R} — Legendary Creature — Goblin Artificer
//! Oracle: Sacrifice an artifact: Target artifact gains indestructible until end of turn.
//! Set: C16 #133 — Commander 2016 | Scryfall ID: 4256dcc1-0eee-4385-9a5c-70abb212bf49 | Oracle ID: 1f2d6cf4-b8f4-440f-ac08-ca47ada868ac
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SLOBAD_GOBLIN_TINKERER,
    oracle_id = "1f2d6cf4-b8f4-440f-ac08-ca47ada868ac",
    scryfall_id = "4256dcc1-0eee-4385-9a5c-70abb212bf49",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Slobad, Goblin Tinkerer",
        mana_cost = mana!("{1}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::GOBLIN, subtypes::creature::ARTIFICER],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&Filter::YOUR_ARTIFACT)),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::INDESTRUCTIBLE,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::ARTIFACT))
    ),],
);
