//! Steadfast Guard — {W}{W} — Creature — Human Rebel
//! Oracle: Vigilance (Attacking doesn't cause this creature to tap.)
//! Set: 10E #48 — Tenth Edition | Scryfall ID: 42a5c12b-c947-4a71-b54f-e310150858a3 | Oracle ID: 0c3b3c04-017d-4741-90c8-4b6c0bd46e49
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STEADFAST_GUARD,
    oracle_id = "0c3b3c04-017d-4741-90c8-4b6c0bd46e49",
    scryfall_id = "42a5c12b-c947-4a71-b54f-e310150858a3",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::VIGILANCE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Steadfast Guard",
        mana_cost = mana!("{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::REBEL],
        power = Some(2),
        toughness = Some(2),
    ),],
);
