//! Stern Proctor — {U}{U} — Creature — Human Wizard
//! Oracle: When this creature enters, return target artifact or enchantment to its owner's hand.
//! Set: USG #99 — Urza's Saga | Scryfall ID: 7042fdc8-e2dd-4f9a-97b9-00d95c9eae74 | Oracle ID: 5120bfdc-7201-420d-85a1-eeb4aba6632b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STERN_PROCTOR,
    oracle_id = "5120bfdc-7201-420d-85a1-eeb4aba6632b",
    scryfall_id = "7042fdc8-e2dd-4f9a-97b9-00d95c9eae74",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stern Proctor",
        mana_cost = mana!("{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(1),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::bounce(TargetSpec::Object(
            &Filter::ARTIFACT_OR_ENCHANTMENT
        ))],
        targets = Some(TargetReq::one(TargetSpec::Object(
            &Filter::ARTIFACT_OR_ENCHANTMENT
        )))
    ),],
);
