//! Veteran Cavalier — {W}{W} — Creature — Human Knight
//! Oracle: Vigilance (Attacking doesn't cause this creature to tap.)
//! Set: 9ED #52 — Ninth Edition | Scryfall ID: 31072355-0b20-4830-9d46-ca71783af84b | Oracle ID: 2d02cfce-a142-4b3b-a01f-4e156e75164e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VETERAN_CAVALIER,
    oracle_id = "2d02cfce-a142-4b3b-a01f-4e156e75164e",
    scryfall_id = "31072355-0b20-4830-9d46-ca71783af84b",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::VIGILANCE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Veteran Cavalier",
        mana_cost = mana!("{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::KNIGHT],
        power = Some(2),
        toughness = Some(2),
    ),],
);
