//! Vine Trellis — {1}{G} — Creature — Plant Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {T}: Add {G}.
//! Set: GVL #4 — Duel Decks Anthology: Garruk vs. Liliana | Scryfall ID: 4683fa31-da33-4313-82b5-0ed91f33e8d3 | Oracle ID: 57de8fe7-3d1b-41cd-8354-38aff3d2d052
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VINE_TRELLIS,
    oracle_id = "57de8fe7-3d1b-41cd-8354-38aff3d2d052",
    scryfall_id = "4683fa31-da33-4313-82b5-0ed91f33e8d3",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vine Trellis",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PLANT, subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(4),
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),],
);
