//! Wall of Mulch — {1}{G} — Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {G}, Sacrifice a Wall: Draw a card.
//! Set: M15 #208 — Magic 2015 | Scryfall ID: a76ec859-59a6-45b2-bbd8-6f89453fe3ec | Oracle ID: afd2141f-1b0f-46b5-b1ac-aa28982d16c0
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::WALL),
    Filter::ControlledByYou,
]);

card!(
    index = index::WALL_OF_MULCH,
    oracle_id = "afd2141f-1b0f-46b5-b1ac-aa28982d16c0",
    scryfall_id = "a76ec859-59a6-45b2-bbd8-6f89453fe3ec",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wall of Mulch",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{G}", Sacrifice(&COST1)),
        &[Effect::draw(1)]
    ),],
);
