//! Wall of Roots — {1}{G} — Creature — Plant Wall
//! Oracle: Defender
//! Oracle: Put a -0/-1 counter on this creature: Add {G}. Activate only once each turn.
//! Set: TDC #278 — Tarkir: Dragonstorm Commander | Scryfall ID: e4e7d3b7-9b0c-463d-975c-ef81d7fd8dad | Oracle ID: 3a21a6ae-b2f2-4f0c-acfd-5f3e8d63fd2f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WALL_OF_ROOTS,
    oracle_id = "3a21a6ae-b2f2-4f0c-acfd-5f3e8d63fd2f",
    scryfall_id = "e4e7d3b7-9b0c-463d-975c-ef81d7fd8dad",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wall of Roots",
        mana_cost = mana!("{1}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PLANT, subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(5),
    ),],
    abilities = &[mana_ability!(
        cost!(PutCounterSelf {
            kind: CounterKind::Minus {
                power: 0,
                toughness: 1
            },
            n: 1
        }),
        &[Effect::mana(ManaColor::Green, 1)],
        limit = ActivationLimit::PerTurn(1)
    ),],
);
