//! Wall of Kelp — {U}{U} — Creature — Plant Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {U}{U}, {T}: Create a 0/1 blue Plant Wall creature token with defender named Kelp.
//! Set: ME2 #74 — Masters Edition II | Scryfall ID: 8c13f0b9-191b-4509-9dd8-a9aa494511ad | Oracle ID: 64722c32-975b-43b9-9b4a-9511c75740d9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use crate::generated_tokens;
use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WALL_OF_KELP,
    oracle_id = "64722c32-975b-43b9-9b4a-9511c75740d9",
    scryfall_id = "8c13f0b9-191b-4509-9dd8-a9aa494511ad",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wall of Kelp",
        mana_cost = mana!("{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PLANT, subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{U}{U}", TapSelf),
        &[Effect::CreateToken {
            token: &generated_tokens::KELP_0_1_BLUE_DEFENDER
        }]
    ),],
);
