//! Waterfront Bouncer — {1}{U} — Creature — Merfolk Spellshaper
//! Oracle: {U}, {T}, Discard a card: Return target creature to its owner's hand.
//! Set: VMA #102 — Vintage Masters | Scryfall ID: d4dab9a1-19e6-4d90-a79c-275b47d7073c | Oracle ID: b53a8cde-494c-43d0-8d08-7bdfe2e84064
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WATERFRONT_BOUNCER,
    oracle_id = "b53a8cde-494c-43d0-8d08-7bdfe2e84064",
    scryfall_id = "d4dab9a1-19e6-4d90-a79c-275b47d7073c",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Waterfront Bouncer",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MERFOLK, subtypes::creature::SPELLSHAPER],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        cost!("{U}", TapSelf, Discard(&Filter::Any)),
        &[Effect::bounce(TargetSpec::Object(&Filter::CREATURE))],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
