//! Wind Dancer — {1}{U} — Creature — Faerie
//! Oracle: Flying
//! Oracle: {T}: Target creature gains flying until end of turn.
//! Set: TPR #80 — Tempest Remastered | Scryfall ID: 469d217a-0f8c-48f8-bfc0-cf5e202c0ddc | Oracle ID: e9903d75-f71d-45d0-ac5f-955c0c227e02
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::WIND_DANCER,
    oracle_id = "e9903d75-f71d-45d0-ac5f-955c0c227e02",
    scryfall_id = "469d217a-0f8c-48f8-bfc0-cf5e202c0ddc",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wind Dancer",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::FAERIE],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
