//! Zephyr Falcon — {1}{U} — Creature — Bird
//! Oracle: Flying, vigilance
//! Set: 5ED #137 — Fifth Edition | Scryfall ID: 6d11923e-98c6-4041-b115-f4847fb71149 | Oracle ID: b5e44bd6-0b67-4770-868d-c46af5b6a42f
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ZEPHYR_FALCON,
    oracle_id = "b5e44bd6-0b67-4770-868d-c46af5b6a42f",
    scryfall_id = "6d11923e-98c6-4041-b115-f4847fb71149",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING.union(KeywordSet::VIGILANCE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Zephyr Falcon",
        mana_cost = mana!("{1}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD],
        power = Some(1),
        toughness = Some(1),
    ),],
);
