//! Zulaport Cutthroat — {1}{B} — Creature — Human Rogue Ally
//! Oracle: Whenever this creature or another creature you control dies, each opponent loses 1 life and you gain 1 life.
//! Set: SOC #233 — Secrets of Strixhaven Commander | Scryfall ID: c43609fb-3cee-44e0-98d0-3ecaba1d5767 | Oracle ID: 76b003e0-15af-4f22-bdf2-1ade5430964a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::Or(&[
    Filter::This,
    Filter::And(&[Filter::CREATURE, Filter::Another, Filter::ControlledByYou]),
]);

card!(
    index = index::ZULAPORT_CUTTHROAT,
    oracle_id = "76b003e0-15af-4f22-bdf2-1ade5430964a",
    scryfall_id = "c43609fb-3cee-44e0-98d0-3ecaba1d5767",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Zulaport Cutthroat",
        mana_cost = mana!("{1}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::ROGUE,
            subtypes::creature::ALLY
        ],
        power = Some(1),
        toughness = Some(1),
    ),],
    abilities = &[triggered!(
        Trigger::Dies(&TRIGGER1),
        &[
            Effect::LoseLife {
                amount: Amount::Fixed(1),
                target: PlayerRel::Opponent
            },
            Effect::gain_life(1)
        ]
    ),],
);
