//! Arena of the Ancients — {3} — Artifact
//! Oracle: Legendary creatures don't untap during their controllers' untap steps.
//! Oracle: When this artifact enters, tap all legendary creatures.
//! Set: ME3 #188 — Masters Edition III | Scryfall ID: 68ebdcc2-4449-4b10-82fb-51f5e14eab37 | Oracle ID: 12584f75-77c1-4b6b-ae9d-1882792b6b94
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ARENA_OF_THE_ANCIENTS,
    oracle_id = "12584f75-77c1-4b6b-ae9d-1882792b6b94",
    scryfall_id = "68ebdcc2-4449-4b10-82fb-51f5e14eab37",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Arena of the Ancients",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        static_ability!(Filter::LEGENDARY_CREATURE, Modifier::DoesNotUntap),
        triggered!(
            Trigger::ETB,
            &[Effect::TapAll {
                filter: &Filter::LEGENDARY_CREATURE
            }]
        ),
    ],
);
