//! Eye of Ramos — {3} — Artifact
//! Oracle: {T}: Add {U}.
//! Oracle: Sacrifice this artifact: Add {U}.
//! Set: MMQ #294 — Mercadian Masques | Scryfall ID: 78d22400-39f6-444d-b508-783a7df7e945 | Oracle ID: a1bdea9f-56d0-411a-9da8-601dd6dc6d32
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::EYE_OF_RAMOS,
    oracle_id = "a1bdea9f-56d0-411a-9da8-601dd6dc6d32",
    scryfall_id = "78d22400-39f6-444d-b508-783a7df7e945",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Eye of Ramos",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Blue, 1)]),
        mana_ability!(cost!(SacrificeSelf), &[Effect::mana(ManaColor::Blue, 1)]),
    ],
);
