//! Honor-Worn Shaku — {3} — Artifact
//! Oracle: {T}: Add {C}.
//! Oracle: Tap an untapped legendary permanent you control: Untap this artifact.
//! Set: CMM #954 — Commander Masters | Scryfall ID: dd39f563-2ea9-4ddd-8d76-900fa14b480c | Oracle ID: babeeaf6-0fe4-491f-bbf5-63a0568b3d6e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

static COST1: Filter = Filter::And(&[
    Filter::HasSupertype(SupertypeSet::LEGENDARY),
    Filter::ControlledByYou,
]);

card!(
    index = index::HONOR_WORN_SHAKU,
    oracle_id = "babeeaf6-0fe4-491f-bbf5-63a0568b3d6e",
    scryfall_id = "dd39f563-2ea9-4ddd-8d76-900fa14b480c",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Honor-Worn Shaku",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        mana_ability!(&[Effect::mana(ManaColor::Colorless, 1)]),
        activated!(cost!(TapOther(&COST1)), &[Effect::UntapSelf]),
    ],
);
