//! Staff of Domination — {3} — Artifact
//! Oracle: {1}: Untap this artifact.
//! Oracle: {2}, {T}: You gain 1 life.
//! Oracle: {3}, {T}: Untap target creature.
//! Oracle: {4}, {T}: Tap target creature.
//! Oracle: {5}, {T}: Draw a card.
//! Set: CMR #343 — Commander Legends | Scryfall ID: fde838c8-2f32-4e7d-a236-0bc42dd7abd9 | Oracle ID: d7888719-647d-4022-a211-822fa09f0791
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STAFF_OF_DOMINATION,
    oracle_id = "d7888719-647d-4022-a211-822fa09f0791",
    scryfall_id = "fde838c8-2f32-4e7d-a236-0bc42dd7abd9",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Staff of Domination",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[
        activated!(cost!("{1}"), &[Effect::UntapSelf]),
        activated!(cost!("{2}", TapSelf), &[Effect::gain_life(1)]),
        activated!(
            cost!("{3}", TapSelf),
            &[Effect::UntapTarget],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(
            cost!("{4}", TapSelf),
            &[Effect::TapTarget],
            target = Some(TargetSpec::Object(&Filter::CREATURE))
        ),
        activated!(cost!("{5}", TapSelf), &[Effect::draw(1)]),
    ],
);
