//! Standing Stones — {3} — Artifact
//! Oracle: {1}, {T}, Pay 1 life: Add one mana of any color.
//! Set: DRK #110 — The Dark | Scryfall ID: 6d4c853e-2231-4af2-bcb0-1781c18ec3be | Oracle ID: 2cc8c24f-cca8-462c-a5ad-1f8662e69a8a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::STANDING_STONES,
    oracle_id = "2cc8c24f-cca8-462c-a5ad-1f8662e69a8a",
    scryfall_id = "6d4c853e-2231-4af2-bcb0-1781c18ec3be",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Standing Stones",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(
        cost!("{1}", TapSelf, PayLife(1)),
        &[Effect::mana_of_any_color()]
    ),],
);
