//! Worn Powerstone — {3} — Artifact
//! Oracle: This artifact enters tapped.
//! Oracle: {T}: Add {C}{C}.
//! Set: MH3 #298 — Modern Horizons 3 | Scryfall ID: ace686ad-9e3f-41b3-b8eb-d1b6d45eb4e1 | Oracle ID: b166b670-febc-4821-855e-f8d465644c03
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::WORN_POWERSTONE,
    oracle_id = "b166b670-febc-4821-855e-f8d465644c03",
    scryfall_id = "ace686ad-9e3f-41b3-b8eb-d1b6d45eb4e1",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Worn Powerstone",
        mana_cost = mana!("{3}"),
        types = TypeSet::ARTIFACT,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Colorless, 2)]),],
);
