//! Mox Emerald — {0} — Artifact
//! Oracle: {T}: Add {G}.
//! Set: VMA #5 — Vintage Masters | Scryfall ID: aced2c55-7543-4076-bcdd-36c4d649b8ae | Oracle ID: 376ee366-e082-402f-b4db-6592fcfcacd2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::MOX_EMERALD,
    oracle_id = "376ee366-e082-402f-b4db-6592fcfcacd2",
    scryfall_id = "aced2c55-7543-4076-bcdd-36c4d649b8ae",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mox Emerald",
        mana_cost = mana!("{0}"),
        types = TypeSet::ARTIFACT,
    ),],
    abilities = &[mana_ability!(&[Effect::mana(ManaColor::Green, 1)]),],
);
