//! Canopy Vista — (no cost) — Land — Forest Plains
//! Oracle: ({T}: Add {G} or {W}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: MSC #227 — Marvel Super Heroes Commander | Scryfall ID: 369e6485-fbc7-45f9-ac9d-2e26dd94f2d5 | Oracle ID: dcb7e046-f01b-497c-88e5-57794eb30ce5
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::BASIC_LAND]);

card!(
    index = index::CANOPY_VISTA,
    oracle_id = "dcb7e046-f01b-497c-88e5-57794eb30ce5",
    scryfall_id = "369e6485-fbc7-45f9-ac9d-2e26dd94f2d5",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Canopy Vista",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::FOREST, subtypes::land::PLAINS],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Green,
        ManaColor::White
    ])]),],
);
