//! Prairie Stream — (no cost) — Land — Plains Island
//! Oracle: ({T}: Add {W} or {U}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: FRC #79 — Reality Fracture Commander | Scryfall ID: a93c2e0b-3fca-476e-ae5b-a331ccacae19 | Oracle ID: 5330e24a-8568-446e-840a-594cd08bd1bc
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PRAIRIE_STREAM,
    oracle_id = "5330e24a-8568-446e-840a-594cd08bd1bc",
    scryfall_id = "a93c2e0b-3fca-476e-ae5b-a331ccacae19",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Prairie Stream",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::PLAINS, subtypes::land::ISLAND],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_BASIC_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
