//! Prairie Stream — (no cost) — Land — Plains Island
//! Oracle: ({T}: Add {W} or {U}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: MSC #257 — Marvel Super Heroes Commander | Scryfall ID: b2e133b4-2263-4ac2-8d16-7bf307d5e104 | Oracle ID: 5330e24a-8568-446e-840a-594cd08bd1bc
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::BASIC_LAND]);

card!(
    index = 117,
    oracle_id = "5330e24a-8568-446e-840a-594cd08bd1bc",
    scryfall_id = "b2e133b4-2263-4ac2-8d16-7bf307d5e104",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Prairie Stream",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::PLAINS, subtypes::land::ISLAND],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::White,
        ManaColor::Blue
    ])]),],
);
