//! Radiant Summit — (no cost) — Land — Mountain Plains
//! Oracle: ({T}: Add {R} or {W}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: MSC #258 — Marvel Super Heroes Commander | Scryfall ID: 81b619cc-900c-4d65-83da-8b9dcb370984 | Oracle ID: 5dd0cc44-4647-4857-ad3b-22494099d08a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::BASIC_LAND]);

card!(
    index = index::RADIANT_SUMMIT,
    oracle_id = "5dd0cc44-4647-4857-ad3b-22494099d08a",
    scryfall_id = "81b619cc-900c-4d65-83da-8b9dcb370984",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Radiant Summit",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::MOUNTAIN, subtypes::land::PLAINS],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::White
    ])]),],
);
