//! Radiant Summit — (no cost) — Land — Mountain Plains
//! Oracle: ({T}: Add {R} or {W}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: FRC #80 — Reality Fracture Commander | Scryfall ID: f8cd6aae-a1cb-43b1-aca9-09fe2778969f | Oracle ID: 5dd0cc44-4647-4857-ad3b-22494099d08a
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RADIANT_SUMMIT,
    oracle_id = "5dd0cc44-4647-4857-ad3b-22494099d08a",
    scryfall_id = "f8cd6aae-a1cb-43b1-aca9-09fe2778969f",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Radiant Summit",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::MOUNTAIN, subtypes::land::PLAINS],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &Filter::YOUR_BASIC_LAND,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Red,
        ManaColor::White
    ])]),],
);
