//! Sunken Hollow — (no cost) — Land — Island Swamp
//! Oracle: ({T}: Add {U} or {B}.)
//! Oracle: This land enters tapped unless you control two or more basic lands.
//! Set: MSC #271 — Marvel Super Heroes Commander | Scryfall ID: 3a8eef9b-9b03-42cd-a27a-07021bf0b33f | Oracle ID: cd2c90ac-2b04-461c-92f3-939871b6b6a3
// IMPLEMENTED — generated by `xtask codegen`: read from the printed text, intrinsic type mana, battle land.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK: Filter = Filter::And(&[Filter::ControlledByYou, Filter::BASIC_LAND]);

card!(
    index = index::SUNKEN_HOLLOW,
    oracle_id = "cd2c90ac-2b04-461c-92f3-939871b6b6a3",
    scryfall_id = "3a8eef9b-9b03-42cd-a27a-07021bf0b33f",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Sunken Hollow",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::ISLAND, subtypes::land::SWAMP],
        enter_modifiers = &[EnterModifier::TappedUnlessCount {
            filter: &CHECK,
            at_least: 2
        }],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice(&[
        ManaColor::Blue,
        ManaColor::Black
    ])]),],
);
