//! Angelic Blessing — {2}{W} — Sorcery
//! Oracle: Target creature gets +3/+3 and gains flying until end of turn. (It can't be blocked except by creatures with flying or reach.)
//! Set: TPR #1 — Tempest Remastered | Scryfall ID: 731fa8e8-2329-4e1a-9ffa-0b4b95b93274 | Oracle ID: d3758fca-0522-4b5a-a1cc-3b2b3ab299ba
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ANGELIC_BLESSING,
    oracle_id = "d3758fca-0522-4b5a-a1cc-3b2b3ab299ba",
    scryfall_id = "731fa8e8-2329-4e1a-9ffa-0b4b95b93274",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Angelic Blessing",
        mana_cost = mana!("{2}{W}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(
        &[Effect::PumpTarget {
            power: Amount::Fixed(3),
            toughness: Amount::Fixed(3),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
