//! Eerie Procession — {2}{U} — Sorcery — Arcane
//! Oracle: Search your library for an Arcane card, reveal that card, put it into your hand, then shuffle.
//! Set: CHK #58 — Champions of Kamigawa | Scryfall ID: 3af326c1-fcc8-45c3-b75e-ae4dbbd59ced | Oracle ID: 58dde1b0-bb01-4f72-9408-21c0404c1cfd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::spell::ARCANE);

card!(
    index = index::EERIE_PROCESSION,
    oracle_id = "58dde1b0-bb01-4f72-9408-21c0404c1cfd",
    scryfall_id = "3af326c1-fcc8-45c3-b75e-ae4dbbd59ced",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Eerie Procession",
        mana_cost = mana!("{2}{U}"),
        types = TypeSet::SORCERY,
        subtypes = &[subtypes::spell::ARCANE],
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &SEARCH1,
        finds: &[Find::HAND],
        optional: false
    }]),],
);
