//! Ice Storm — {2}{G} — Sorcery
//! Oracle: Destroy target land.
//! Set: ME1 #122 — Masters Edition | Scryfall ID: 68cc9670-6faf-41c3-b111-358c46d8812d | Oracle ID: a0b97e33-2d0c-4800-a9f5-9cd9be651ea8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ICE_STORM,
    oracle_id = "a0b97e33-2d0c-4800-a9f5-9cd9be651ea8",
    scryfall_id = "68cc9670-6faf-41c3-b111-358c46d8812d",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ice Storm",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(
        &[Effect::destroy(TargetSpec::Object(&Filter::LAND))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::LAND)))
    ),],
);
