//! Spoils of Victory — {2}{G} — Sorcery
//! Oracle: Search your library for a Plains, Island, Swamp, Mountain, or Forest card and put that card onto the battlefield. Then shuffle.
//! Set: C13 #172 — Commander 2013 | Scryfall ID: 8a7ee186-b25f-4185-830d-e8e7cf23d4e5 | Oracle ID: 852bd598-6e48-43c8-9211-740ae9e0c42e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::Or(&[
    Filter::HasSubtype(subtypes::land::PLAINS),
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::HasSubtype(subtypes::land::SWAMP),
    Filter::HasSubtype(subtypes::land::MOUNTAIN),
    Filter::HasSubtype(subtypes::land::FOREST),
]);

card!(
    index = index::SPOILS_OF_VICTORY,
    oracle_id = "852bd598-6e48-43c8-9211-740ae9e0c42e",
    scryfall_id = "8a7ee186-b25f-4185-830d-e8e7cf23d4e5",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Spoils of Victory",
        mana_cost = mana!("{2}{G}"),
        types = TypeSet::SORCERY,
    ),],
    abilities = &[spell!(&[Effect::SearchLibrary {
        filter: &SEARCH1,
        finds: &[Find::BATTLEFIELD],
        optional: false
    }]),],
);
