//! Ember Shot — {6}{R} — Instant
//! Oracle: Ember Shot deals 3 damage to any target.
//! Oracle: Draw a card.
//! Set: JUD #87 — Judgment | Scryfall ID: 6a9eb72b-9ae2-4b64-bbb9-187446b5fd2f | Oracle ID: 1f300320-ad98-4812-b34b-54885a86aee9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::EMBER_SHOT,
    oracle_id = "1f300320-ad98-4812-b34b-54885a86aee9",
    scryfall_id = "6a9eb72b-9ae2-4b64-bbb9-187446b5fd2f",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ember Shot",
        mana_cost = mana!("{6}{R}"),
        types = TypeSet::INSTANT,
    ),],
    abilities = &[spell!(
        &[
            Effect::DealDamage {
                amount: Amount::Fixed(3),
                target: TargetSpec::AnyTarget
            },
            Effect::draw(1)
        ],
        targets = Some(TargetReq::one(TargetSpec::AnyTarget))
    ),],
);
