//! Cloudpost — (no cost) — Land — Locus
//! Oracle: This land enters tapped.
//! Oracle: {T}: Add {C} for each Locus on the battlefield.
//! Set: MRD #280 — Mirrodin | Scryfall ID: 2f28ecdc-a4f0-4327-a78c-340be41555ee | Oracle ID: f705c0eb-9c6c-4315-a860-208ed0c5d93e
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COUNT1: Filter = Filter::HasSubtype(subtypes::land::LOCUS);

card!(
    index = index::CLOUDPOST,
    oracle_id = "f705c0eb-9c6c-4315-a860-208ed0c5d93e",
    scryfall_id = "2f28ecdc-a4f0-4327-a78c-340be41555ee",
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Cloudpost",
        types = TypeSet::LAND,
        subtypes = &[subtypes::land::LOCUS],
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[mana_ability!(&[Effect::mana_dynamic(
        ManaColor::Colorless,
        Amount::CountOf {
            filter: &COUNT1,
            zone: ZoneSel::Battlefield
        }
    )]),],
);
