//! Nicol Bolas — {2}{U}{U}{B}{B}{R}{R} — Legendary Creature — Elder Dragon
//! Oracle: Flying
//! Oracle: At the beginning of your upkeep, sacrifice Nicol Bolas unless you pay {U}{B}{R}.
//! Oracle: Whenever Nicol Bolas deals damage to an opponent, that player discards their hand.
//! Set: A25 #209 — Masters 25 | Scryfall ID: 8e92ba96-372c-418d-b271-45e1bf5c7af5 | Oracle ID: e26bf6a9-b31c-4bc0-b55b-c01f2f69be6b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::NICOL_BOLAS,
    oracle_id = "e26bf6a9-b31c-4bc0-b55b-c01f2f69be6b",
    scryfall_id = "8e92ba96-372c-418d-b271-45e1bf5c7af5",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Nicol Bolas",
        mana_cost = mana!("{2}{U}{U}{B}{B}{R}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ELDER, subtypes::creature::DRAGON],
        power = Some(7),
        toughness = Some(7),
    ),],
    abilities = &[
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::PlayerMayPayManaOr {
                player: PlayerRel::You,
                cost: mana!("{U}{B}{R}"),
                effect: &Effect::SacrificeSelf
            }]
        ),
        triggered!(
            Trigger::DealsDamageToOpponent(&Filter::This),
            &[Effect::DiscardHand {
                who: PlayerRel::DamagedPlayer
            }]
        ),
    ],
);
