//! Palladia-Mors — {2}{R}{R}{G}{G}{W}{W} — Legendary Creature — Elder Dragon
//! Oracle: Flying, trample
//! Oracle: At the beginning of your upkeep, sacrifice Palladia-Mors unless you pay {R}{G}{W}.
//! Set: ME3 #164 — Masters Edition III | Scryfall ID: ede0ce7a-0799-40b9-b725-665dc9c1cede | Oracle ID: d7121ac7-e425-46cd-b006-1af391d97f87
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PALLADIA_MORS,
    oracle_id = "d7121ac7-e425-46cd-b006-1af391d97f87",
    scryfall_id = "ede0ce7a-0799-40b9-b725-665dc9c1cede",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red, Color::White]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING.union(KeywordSet::TRAMPLE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Palladia-Mors",
        mana_cost = mana!("{2}{R}{R}{G}{G}{W}{W}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ELDER, subtypes::creature::DRAGON],
        power = Some(7),
        toughness = Some(7),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::PlayerMayPayManaOr {
            player: PlayerRel::You,
            cost: mana!("{R}{G}{W}"),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
