//! Vaevictis Asmadi — {2}{B}{B}{R}{R}{G}{G} — Legendary Creature — Elder Dragon
//! Oracle: Flying
//! Oracle: At the beginning of your upkeep, sacrifice Vaevictis Asmadi unless you pay {B}{R}{G}.
//! Oracle: {B}: Vaevictis Asmadi gets +1/+0 until end of turn.
//! Oracle: {R}: Vaevictis Asmadi gets +1/+0 until end of turn.
//! Oracle: {G}: Vaevictis Asmadi gets +1/+0 until end of turn.
//! Set: ME3 #185 — Masters Edition III | Scryfall ID: df01b548-9738-4c84-beb6-9a375f41d496 | Oracle ID: 4d2cc2a8-e08a-420a-8922-c63e39129e23
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VAEVICTIS_ASMADI,
    oracle_id = "4d2cc2a8-e08a-420a-8922-c63e39129e23",
    scryfall_id = "df01b548-9738-4c84-beb6-9a375f41d496",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Green, Color::Red]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vaevictis Asmadi",
        mana_cost = mana!("{2}{B}{B}{R}{R}{G}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::ELDER, subtypes::creature::DRAGON],
        power = Some(7),
        toughness = Some(7),
    ),],
    abilities = &[
        triggered!(
            Trigger::StepBegin {
                step: StepKind::Upkeep,
                whose: PlayerRel::You
            },
            &[Effect::PlayerMayPayManaOr {
                player: PlayerRel::You,
                cost: mana!("{B}{R}{G}"),
                effect: &Effect::SacrificeSelf
            }]
        ),
        activated!(
            cost!("{B}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{R}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
        activated!(
            cost!("{G}"),
            &[Effect::PumpFilter {
                filter: &Filter::This,
                controlled_by: None,
                power: Amount::Fixed(1),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::EMPTY,
                duration: Duration::UntilEndOfTurn
            }]
        ),
    ],
);
