//! Azorius Chancery — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {W}{U}.
//! Set: DSC #261 — Duskmourn: House of Horror Commander | Scryfall ID: 50ef0ac3-e911-4d67-a751-8d86160ae843 | Oracle ID: 189fc8f4-17ac-4f1d-82c8-8401445bdaf4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::AZORIUS_CHANCERY,
    oracle_id = "189fc8f4-17ac-4f1d-82c8-8401445bdaf4",
    scryfall_id = "50ef0ac3-e911-4d67-a751-8d86160ae843",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Azorius Chancery",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::White, 1),
            Effect::mana(ManaColor::Blue, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
