//! Dimir Aqueduct — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {U}{B}.
//! Set: DSC #270 — Duskmourn: House of Horror Commander | Scryfall ID: 84bf9d60-64b8-4209-acfe-e07eefc6bf1f | Oracle ID: 378a1d57-e2f1-4b84-9692-1564602e9e99
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::DIMIR_AQUEDUCT,
    oracle_id = "378a1d57-e2f1-4b84-9692-1564602e9e99",
    scryfall_id = "84bf9d60-64b8-4209-acfe-e07eefc6bf1f",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Dimir Aqueduct",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Blue, 1),
            Effect::mana(ManaColor::Black, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
