//! Gruul Turf — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {R}{G}.
//! Set: ECC #152 — Lorwyn Eclipsed Commander | Scryfall ID: f19d2b68-1415-4a0c-bb68-cfacb611c4d2 | Oracle ID: 657243dd-e479-4f4b-99d2-09b55d833a35
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::GRUUL_TURF,
    oracle_id = "657243dd-e479-4f4b-99d2-09b55d833a35",
    scryfall_id = "f19d2b68-1415-4a0c-bb68-cfacb611c4d2",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gruul Turf",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Red, 1),
            Effect::mana(ManaColor::Green, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
