//! Izzet Boilerworks — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {U}{R}.
//! Set: OTC #302 — Outlaws of Thunder Junction Commander | Scryfall ID: bfac9395-7ca5-48dd-ab83-7c26ada12f61 | Oracle ID: 1cb9d94a-3039-4f2e-8fcc-6996f9a45f74
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::IZZET_BOILERWORKS,
    oracle_id = "1cb9d94a-3039-4f2e-8fcc-6996f9a45f74",
    scryfall_id = "bfac9395-7ca5-48dd-ab83-7c26ada12f61",
    color_identity = ColorSet::from_slice(&[Color::Red, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Izzet Boilerworks",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Blue, 1),
            Effect::mana(ManaColor::Red, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
