//! Orzhov Basilica — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {W}{B}.
//! Set: DSC #292 — Duskmourn: House of Horror Commander | Scryfall ID: 9c7c08fc-b6ee-498c-8ab6-fd6be27c9d97 | Oracle ID: aa00ae0b-7c0f-427e-8102-ce0e2a6af5df
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::ORZHOV_BASILICA,
    oracle_id = "aa00ae0b-7c0f-427e-8102-ce0e2a6af5df",
    scryfall_id = "9c7c08fc-b6ee-498c-8ab6-fd6be27c9d97",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Orzhov Basilica",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
        mana_ability!(&[
            Effect::mana(ManaColor::White, 1),
            Effect::mana(ManaColor::Black, 1)
        ]),
    ],
);
