//! Rakdos Carnarium — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {B}{R}.
//! Set: ECC #161 — Lorwyn Eclipsed Commander | Scryfall ID: 20c799a9-ab94-46e6-9111-00505e071c41 | Oracle ID: 0a023964-2905-4928-9c3e-dc63e6ebd218
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::RAKDOS_CARNARIUM,
    oracle_id = "0a023964-2905-4928-9c3e-dc63e6ebd218",
    scryfall_id = "20c799a9-ab94-46e6-9111-00505e071c41",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Rakdos Carnarium",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Black, 1),
            Effect::mana(ManaColor::Red, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
