//! Simic Growth Chamber — (no cost) — Land
//! Oracle: This land enters tapped.
//! Oracle: When this land enters, return a land you control to its owner's hand.
//! Oracle: {T}: Add {G}{U}.
//! Set: DSC #298 — Duskmourn: House of Horror Commander | Scryfall ID: 212d97c5-c144-483b-b42e-00623477e928 | Oracle ID: 046f5783-cc7b-416a-8cf6-2bcef9c2cc1a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;

card!(
    index = index::SIMIC_GROWTH_CHAMBER,
    oracle_id = "046f5783-cc7b-416a-8cf6-2bcef9c2cc1a",
    scryfall_id = "212d97c5-c144-483b-b42e-00623477e928",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Simic Growth Chamber",
        types = TypeSet::LAND,
        enter_modifiers = &[EnterModifier::Tapped],
    ),],
    abilities = &[
        mana_ability!(&[
            Effect::mana(ManaColor::Green, 1),
            Effect::mana(ManaColor::Blue, 1)
        ]),
        triggered!(
            Trigger::ETB,
            &[Effect::ReturnChosenToHand {
                who: PlayerRel::You,
                filter: &Filter::YOUR_LAND
            }]
        ),
    ],
);
