//! Advanced Hoverguard — {3}{U} — Creature — Drone
//! Oracle: Flying
//! Oracle: {U}: This creature gains shroud until end of turn. (It can't be the target of spells or abilities.)
//! Set: 5DN #22 — Fifth Dawn | Scryfall ID: 7384d50a-5801-47ed-ab9f-5c7e4f1f20dd | Oracle ID: 65dc61a4-9052-49d4-bce8-9c16f0339382
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ADVANCED_HOVERGUARD,
    oracle_id = "65dc61a4-9052-49d4-bce8-9c16f0339382",
    scryfall_id = "7384d50a-5801-47ed-ab9f-5c7e4f1f20dd",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Advanced Hoverguard",
        mana_cost = mana!("{3}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DRONE],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{U}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::SHROUD,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
