//! Anaba Bodyguard — {3}{R} — Creature — Minotaur
//! Oracle: First strike (This creature deals combat damage before creatures without first strike.)
//! Set: 10E #187 — Tenth Edition | Scryfall ID: 6fdd01bd-ab41-4005-8807-46db0cfc4da4 | Oracle ID: 8c64db66-879e-46ad-9d11-8a95b6cf5d19
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::ANABA_BODYGUARD,
    oracle_id = "8c64db66-879e-46ad-9d11-8a95b6cf5d19",
    scryfall_id = "6fdd01bd-ab41-4005-8807-46db0cfc4da4",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FIRST_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Anaba Bodyguard",
        mana_cost = mana!("{3}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MINOTAUR],
        power = Some(2),
        toughness = Some(3),
    ),],
);
