//! Aurochs — {3}{G} — Creature — Aurochs
//! Oracle: Trample
//! Oracle: Whenever this creature attacks, it gets +1/+0 until end of turn for each other attacking Aurochs.
//! Set: ME2 #153 — Masters Edition II | Scryfall ID: dfd8874e-55a8-4da1-9fbf-6aaa96800a83 | Oracle ID: 3961ef7c-4eb4-482e-9cda-d49d6a29c5a9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AUROCHS,
    oracle_id = "3961ef7c-4eb4-482e-9cda-d49d6a29c5a9",
    scryfall_id = "dfd8874e-55a8-4da1-9fbf-6aaa96800a83",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::TRAMPLE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aurochs",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::AUROCHS],
        power = Some(2),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::X,
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
