//! Aven Cloudchaser — {3}{W} — Creature — Bird Soldier
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: When this creature enters, destroy target enchantment.
//! Set: 10E #7 — Tenth Edition | Scryfall ID: 407110e9-19af-4ff5-97b2-c03225031a73 | Oracle ID: 48bda7dd-d023-41e8-8c28-e0cfda0d07ca
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::AVEN_CLOUDCHASER,
    oracle_id = "48bda7dd-d023-41e8-8c28-e0cfda0d07ca",
    scryfall_id = "407110e9-19af-4ff5-97b2-c03225031a73",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Aven Cloudchaser",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BIRD, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::destroy(TargetSpec::Object(&Filter::ENCHANTMENT))],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::ENCHANTMENT)))
    ),],
);
