//! Clickslither — {1}{R}{R}{R} — Creature — Insect
//! Oracle: Haste
//! Oracle: Sacrifice a Goblin: This creature gets +2/+2 and gains trample until end of turn.
//! Set: EVG #34 — Duel Decks Anthology: Elves vs. Goblins | Scryfall ID: 3ab74f04-8aaa-438e-97b4-bfa1db4c5442 | Oracle ID: 436f9a5d-ec26-4c88-9851-b88fe742fa67
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::GOBLIN),
    Filter::ControlledByYou,
]);

card!(
    index = index::CLICKSLITHER,
    oracle_id = "436f9a5d-ec26-4c88-9851-b88fe742fa67",
    scryfall_id = "3ab74f04-8aaa-438e-97b4-bfa1db4c5442",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::HASTE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Clickslither",
        mana_cost = mana!("{1}{R}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::INSECT],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&COST1)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::TRAMPLE,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
