//! Crazed Skirge — {3}{B} — Creature — Phyrexian Imp
//! Oracle: Flying, haste
//! Set: USG #125 — Urza's Saga | Scryfall ID: 816272de-f134-45fa-ac1f-70d35d30c7e1 | Oracle ID: 72a53d9e-0645-4024-a90f-73b05c2284c6
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::CRAZED_SKIRGE,
    oracle_id = "72a53d9e-0645-4024-a90f-73b05c2284c6",
    scryfall_id = "816272de-f134-45fa-ac1f-70d35d30c7e1",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING.union(KeywordSet::HASTE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crazed Skirge",
        mana_cost = mana!("{3}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::IMP],
        power = Some(2),
        toughness = Some(2),
    ),],
);
