//! Crimson Manticore — {2}{R}{R} — Creature — Manticore
//! Oracle: Flying
//! Oracle: {R}, {T}: This creature deals 1 damage to target attacking or blocking creature.
//! Set: ME3 #94 — Masters Edition III | Scryfall ID: 9de6ffe8-70af-4505-bc2d-b0113cd6db99 | Oracle ID: 35d4e500-28c8-44c9-990f-3aa25ed5dd14
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::Or(&[
    Filter::And(&[Filter::CREATURE, Filter::Attacking]),
    Filter::And(&[Filter::CREATURE, Filter::Blocking]),
]);

card!(
    index = index::CRIMSON_MANTICORE,
    oracle_id = "35d4e500-28c8-44c9-990f-3aa25ed5dd14",
    scryfall_id = "9de6ffe8-70af-4505-bc2d-b0113cd6db99",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Crimson Manticore",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::MANTICORE],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{R}", TapSelf),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Object(&TARGET1)
        }],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
