//! Ekundu Griffin — {3}{W} — Creature — Griffin
//! Oracle: Flying, first strike
//! Set: 6ED #18 — Classic Sixth Edition | Scryfall ID: a1eec4ac-7d28-4f76-a1d5-a0a19c142514 | Oracle ID: 852b6e19-4594-41ea-9267-0911df643af5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::EKUNDU_GRIFFIN,
    oracle_id = "852b6e19-4594-41ea-9267-0911df643af5",
    scryfall_id = "a1eec4ac-7d28-4f76-a1d5-a0a19c142514",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::FIRST_STRIKE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ekundu Griffin",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GRIFFIN],
        power = Some(2),
        toughness = Some(2),
    ),],
);
