//! Flanking Troops — {2}{W}{W} — Creature — Human Soldier
//! Oracle: Whenever this creature attacks, you may tap target creature.
//! Set: PTK #5 — Portal Three Kingdoms | Scryfall ID: a219a031-2466-4850-b646-79a09e30cf18 | Oracle ID: 47bbb630-2bf7-47a2-93bb-266e491803c3
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::FLANKING_TROOPS,
    oracle_id = "47bbb630-2bf7-47a2-93bb-266e491803c3",
    scryfall_id = "a219a031-2466-4850-b646-79a09e30cf18",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Flanking Troops",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::MayDo {
            effects: &[Effect::TapTarget]
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
