//! Glimmering Angel — {3}{W} — Creature — Angel
//! Oracle: Flying
//! Oracle: {U}: This creature gains shroud until end of turn. (It can't be the target of spells or abilities.)
//! Set: INV #17 — Invasion | Scryfall ID: f14f55e4-eded-4a86-87f4-b8fa6f30bc0f | Oracle ID: 9629ab26-f231-481d-8392-e2450ca02b67
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GLIMMERING_ANGEL,
    oracle_id = "9629ab26-f231-481d-8392-e2450ca02b67",
    scryfall_id = "f14f55e4-eded-4a86-87f4-b8fa6f30bc0f",
    color_identity = ColorSet::from_slice(&[Color::Blue, Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Glimmering Angel",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ANGEL],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{U}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::SHROUD,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
