//! Glowing Anemone — {3}{U} — Creature — Jellyfish Beast
//! Oracle: When this creature enters, you may return target land to its owner's hand.
//! Set: MMQ #81 — Mercadian Masques | Scryfall ID: 708593e6-787b-4f76-a86c-1d52857493ea | Oracle ID: 52305f9d-2bfd-4b35-92b3-c08cdd758cde
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GLOWING_ANEMONE,
    oracle_id = "52305f9d-2bfd-4b35-92b3-c08cdd758cde",
    scryfall_id = "708593e6-787b-4f76-a86c-1d52857493ea",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Glowing Anemone",
        mana_cost = mana!("{3}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::JELLYFISH, subtypes::creature::BEAST],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::MayDo {
            effects: &[Effect::bounce(TargetSpec::Object(&Filter::LAND))]
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::LAND)))
    ),],
);
