//! Gwendlyn Di Corci — {U}{B}{B}{R} — Legendary Creature — Human Rogue
//! Oracle: {T}: Target player discards a card at random. Activate only during your turn.
//! Set: ME3 #149 — Masters Edition III | Scryfall ID: a496823b-c864-4591-b395-5493383d11a7 | Oracle ID: de44e7c8-01f9-44f9-9716-9e8a5b82b1ff
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::GWENDLYN_DI_CORCI,
    oracle_id = "de44e7c8-01f9-44f9-9716-9e8a5b82b1ff",
    scryfall_id = "a496823b-c864-4591-b395-5493383d11a7",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red, Color::Blue]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Gwendlyn Di Corci",
        mana_cost = mana!("{U}{B}{B}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ROGUE],
        power = Some(3),
        toughness = Some(5),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DiscardRandom {
            who: PlayerRel::Chosen,
            count: Amount::Fixed(1)
        }],
        target = Some(TargetSpec::AnyPlayer),
        condition = Some(Condition::YourTurn)
    ),],
);
