//! Harmattan Efreet — {2}{U}{U} — Creature — Efreet
//! Oracle: Flying
//! Oracle: {1}{U}{U}: Target creature gains flying until end of turn.
//! Set: 6ED #73 — Classic Sixth Edition | Scryfall ID: d8fc0ba3-6ffa-4fd4-b332-88da41b8778a | Oracle ID: 84b1d4e1-ca8a-4eed-b5c4-364876938aee
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::HARMATTAN_EFREET,
    oracle_id = "84b1d4e1-ca8a-4eed-b5c4-364876938aee",
    scryfall_id = "d8fc0ba3-6ffa-4fd4-b332-88da41b8778a",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Harmattan Efreet",
        mana_cost = mana!("{2}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::EFREET],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{1}{U}{U}"),
        &[Effect::PumpTarget {
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FLYING,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
