//! Highway Robber — {2}{B}{B} — Creature — Human Mercenary
//! Oracle: When this creature enters, target opponent loses 2 life and you gain 2 life.
//! Set: DDM #61 — Duel Decks: Jace vs. Vraska | Scryfall ID: 2126c83b-75ce-4526-8f91-5cd8b6ec74a5 | Oracle ID: 5de0769e-5141-42d5-aaa6-549cfc154de8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::HIGHWAY_ROBBER,
    oracle_id = "5de0769e-5141-42d5-aaa6-549cfc154de8",
    scryfall_id = "2126c83b-75ce-4526-8f91-5cd8b6ec74a5",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Highway Robber",
        mana_cost = mana!("{2}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MERCENARY],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[
            Effect::LoseLife {
                amount: Amount::Fixed(2),
                target: PlayerRel::Chosen
            },
            Effect::gain_life(2)
        ],
        targets = Some(TargetReq::one(TargetSpec::AnyOpponent))
    ),],
);
