//! Jeska, Warrior Adept — {2}{R}{R} — Legendary Creature — Human Barbarian Warrior
//! Oracle: First strike, haste
//! Oracle: {T}: Jeska deals 1 damage to any target.
//! Set: JUD #93 — Judgment | Scryfall ID: 1cf96a59-8b7d-4a5b-adfd-17eeedd95db5 | Oracle ID: 3186fddd-23fd-440c-ad61-b4130e00f765
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::JESKA_WARRIOR_ADEPT,
    oracle_id = "3186fddd-23fd-440c-ad61-b4130e00f765",
    scryfall_id = "1cf96a59-8b7d-4a5b-adfd-17eeedd95db5",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FIRST_STRIKE.union(KeywordSet::HASTE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Jeska, Warrior Adept",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[
            subtypes::creature::HUMAN,
            subtypes::creature::BARBARIAN,
            subtypes::creature::WARRIOR
        ],
        power = Some(3),
        toughness = Some(1),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
