//! Jungle Barrier — {2}{G}{U} — Creature — Plant Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: When this creature enters, draw a card.
//! Set: IMA #202 — Iconic Masters | Scryfall ID: a8097e6e-c04e-4266-a8f4-07e5fb0638d4 | Oracle ID: dcf65293-14a0-46a5-a0b0-ca2b7fda8bef
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::JUNGLE_BARRIER,
    oracle_id = "dcf65293-14a0-46a5-a0b0-ca2b7fda8bef",
    scryfall_id = "a8097e6e-c04e-4266-a8f4-07e5fb0638d4",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Jungle Barrier",
        mana_cost = mana!("{2}{G}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PLANT, subtypes::creature::WALL],
        power = Some(2),
        toughness = Some(6),
    ),],
    abilities = &[triggered!(Trigger::ETB, &[Effect::draw(1)]),],
);
