//! Juzám Djinn — {2}{B}{B} — Creature — Djinn
//! Oracle: At the beginning of your upkeep, this creature deals 1 damage to you.
//! Set: ME1 #74 — Masters Edition | Scryfall ID: b03bc922-782b-4254-897c-90d202b4cda4 | Oracle ID: 4e81596c-9225-43d1-bd35-798212144f2c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::JUZAM_DJINN,
    oracle_id = "4e81596c-9225-43d1-bd35-798212144f2c",
    scryfall_id = "b03bc922-782b-4254-897c-90d202b4cda4",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Juzám Djinn",
        mana_cost = mana!("{2}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DJINN],
        power = Some(5),
        toughness = Some(5),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Player(PlayerRel::You)
        }]
    ),],
);
