//! Kavu Monarch — {2}{R}{R} — Creature — Kavu
//! Oracle: Kavu creatures have trample.
//! Oracle: Whenever another Kavu enters, put a +1/+1 counter on this creature.
//! Set: INV #149 — Invasion | Scryfall ID: ea63dfd5-d8d7-45b8-8219-1cc2b3de5666 | Oracle ID: 98cc734d-16d5-4c3c-98ca-a45efad27127
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TRIGGER1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::creature::KAVU),
    Filter::Another,
]);

card!(
    index = index::KAVU_MONARCH,
    oracle_id = "98cc734d-16d5-4c3c-98ca-a45efad27127",
    scryfall_id = "ea63dfd5-d8d7-45b8-8219-1cc2b3de5666",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kavu Monarch",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::KAVU],
        power = Some(3),
        toughness = Some(3),
    ),],
    abilities = &[
        static_ability!(
            Filter::And(&[
                Filter::CREATURE,
                Filter::HasSubtype(subtypes::creature::KAVU)
            ]),
            Modifier::AddKeyword(KeywordSet::TRAMPLE)
        ),
        triggered!(
            Trigger::EntersBattlefield(&TRIGGER1),
            &[Effect::AddCounter {
                kind: CounterKind::P1P1,
                amount: Amount::Fixed(1)
            }]
        ),
    ],
);
