//! Keening Banshee — {2}{B}{B} — Creature — Spirit
//! Oracle: Flying
//! Oracle: When this creature enters, target creature gets -2/-2 until end of turn.
//! Set: GVL #44 — Duel Decks Anthology: Garruk vs. Liliana | Scryfall ID: 80031bc4-28a8-4f57-916f-fcf01dc252f9 | Oracle ID: 56b69e46-a1e4-4545-99e2-ee4385b7e429
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KEENING_BANSHEE,
    oracle_id = "56b69e46-a1e4-4545-99e2-ee4385b7e429",
    scryfall_id = "80031bc4-28a8-4f57-916f-fcf01dc252f9",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Keening Banshee",
        mana_cost = mana!("{2}{B}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SPIRIT],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(2),
            toughness: Amount::NegXFixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
