//! Kei Takahashi — {2}{G}{W} — Legendary Creature — Human Cleric
//! Oracle: {T}: Prevent the next 2 damage that would be dealt to target creature this turn.
//! Set: ME3 #155 — Masters Edition III | Scryfall ID: 82703d7c-0759-46ac-b41e-12deeffa10e0 | Oracle ID: f3229980-994e-4492-be98-267b781614c1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KEI_TAKAHASHI,
    oracle_id = "f3229980-994e-4492-be98-267b781614c1",
    scryfall_id = "82703d7c-0759-46ac-b41e-12deeffa10e0",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::White]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kei Takahashi",
        mana_cost = mana!("{2}{G}{W}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::CLERIC],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[Effect::PreventNextDamage {
            target: TargetSpec::Object(&Filter::CREATURE),
            amount: Amount::Fixed(2)
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
