//! King Cheetah — {3}{G} — Creature — Cat
//! Oracle: Flash
//! Set: 9ED #250 — Ninth Edition | Scryfall ID: 82fc34b5-7558-41b1-97e4-1ee13527dec4 | Oracle ID: f9ca35e1-24c5-46f4-a666-0dfe2c920e8b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KING_CHEETAH,
    oracle_id = "f9ca35e1-24c5-46f4-a666-0dfe2c920e8b",
    scryfall_id = "82fc34b5-7558-41b1-97e4-1ee13527dec4",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::FLASH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "King Cheetah",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::CAT],
        power = Some(3),
        toughness = Some(2),
    ),],
);
