//! Kongming, "Sleeping Dragon" — {2}{W}{W} — Legendary Creature — Human Advisor
//! Oracle: Other creatures you control get +1/+1.
//! Set: A25 #20 — Masters 25 | Scryfall ID: 70c9e4fd-e987-4653-abb1-e32971745db2 | Oracle ID: 21e9e1a9-5d6d-473e-adab-6a1e8e2b0ebd
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KONGMING_SLEEPING_DRAGON,
    oracle_id = "21e9e1a9-5d6d-473e-adab-6a1e8e2b0ebd",
    scryfall_id = "70c9e4fd-e987-4653-abb1-e32971745db2",
    color_identity = ColorSet::from_slice(&[Color::White]),
    commander = CommanderRule::Legendary,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Kongming, \"Sleeping Dragon\"",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::ADVISOR],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[static_ability!(
        Filter::And(&[Filter::CREATURE, Filter::Another, Filter::ControlledByYou]),
        Modifier::ModifyPT(1, 1)
    ),],
);
