//! Krosan Archer — {3}{G} — Creature — Centaur Archer
//! Oracle: Reach (This creature can block creatures with flying.)
//! Oracle: {G}, Discard a card: This creature gets +0/+2 until end of turn.
//! Set: ODY #246 — Odyssey | Scryfall ID: e188562f-8219-4fb0-ac2c-5618cfb00bca | Oracle ID: be886ff5-e004-420f-b7d5-01f1ab5021cb
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::KROSAN_ARCHER,
    oracle_id = "be886ff5-e004-420f-b7d5-01f1ab5021cb",
    scryfall_id = "e188562f-8219-4fb0-ac2c-5618cfb00bca",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    keywords = KeywordSet::REACH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Krosan Archer",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::CENTAUR, subtypes::creature::ARCHER],
        power = Some(2),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{G}", Discard(&Filter::Any)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
