//! Lava Hounds — {2}{R}{R} — Creature — Dog
//! Oracle: Haste
//! Oracle: When this creature enters, it deals 4 damage to you.
//! Set: 8ED #198 — Eighth Edition | Scryfall ID: cf83d5c7-a17c-4350-9432-92a01421b39a | Oracle ID: 86c0dc85-d146-4dfa-819e-f78835bfffff
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LAVA_HOUNDS,
    oracle_id = "86c0dc85-d146-4dfa-819e-f78835bfffff",
    scryfall_id = "cf83d5c7-a17c-4350-9432-92a01421b39a",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::HASTE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Lava Hounds",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DOG],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::DealDamage {
            amount: Amount::Fixed(4),
            target: TargetSpec::Player(PlayerRel::You)
        }]
    ),],
);
