//! Leonin Abunas — {3}{W} — Creature — Cat Cleric
//! Oracle: Artifacts you control have hexproof. (They can't be the targets of spells or abilities your opponents control.)
//! Set: 2XM #21 — Double Masters | Scryfall ID: 14397b59-ff0d-4838-92c3-9728bf6b0af5 | Oracle ID: 10064324-34a0-47eb-a58e-01db10234ed9
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::LEONIN_ABUNAS,
    oracle_id = "10064324-34a0-47eb-a58e-01db10234ed9",
    scryfall_id = "14397b59-ff0d-4838-92c3-9728bf6b0af5",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Leonin Abunas",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::CAT, subtypes::creature::CLERIC],
        power = Some(2),
        toughness = Some(5),
    ),],
    abilities = &[static_ability!(
        Filter::YOUR_ARTIFACT,
        Modifier::AddKeyword(KeywordSet::HEXPROOF)
    ),],
);
