//! Moggcatcher — {2}{R}{R} — Creature — Human Mercenary
//! Oracle: {3}, {T}: Search your library for a Goblin permanent card, put it onto the battlefield, then shuffle.
//! Set: NEM #96 — Nemesis | Scryfall ID: 9ba582d7-1dce-4664-8bd9-6b419596788c | Oracle ID: 4845dc21-7534-4896-b298-4d44cd7a3b27
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::creature::GOBLIN);

card!(
    index = index::MOGGCATCHER,
    oracle_id = "4845dc21-7534-4896-b298-4d44cd7a3b27",
    scryfall_id = "9ba582d7-1dce-4664-8bd9-6b419596788c",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Moggcatcher",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MERCENARY],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{3}", TapSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD],
            optional: false
        }]
    ),],
);
