//! Mystic Snake — {1}{G}{U}{U} — Creature — Snake
//! Oracle: Flash
//! Oracle: When this creature enters, counter target spell.
//! Set: A25 #208 — Masters 25 | Scryfall ID: 2d4bacd1-b602-4bcc-9aea-1229949a7d20 | Oracle ID: 161b6d06-e6a7-488e-9f9c-d266c1402a3a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::MYSTIC_SNAKE,
    oracle_id = "161b6d06-e6a7-488e-9f9c-d266c1402a3a",
    scryfall_id = "2d4bacd1-b602-4bcc-9aea-1229949a7d20",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Blue]),
    keywords = KeywordSet::FLASH,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Mystic Snake",
        mana_cost = mana!("{1}{G}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::SNAKE],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::ETB,
        &[Effect::CounterTargetSpell],
        targets = Some(TargetReq::one(TargetSpec::Spell(&Filter::Any)))
    ),],
);
