//! Nettletooth Djinn — {3}{G} — Creature — Djinn
//! Oracle: At the beginning of your upkeep, this creature deals 1 damage to you.
//! Set: MIR #232 — Mirage | Scryfall ID: 7b5aa60d-91aa-4eee-9d13-55a357c8eced | Oracle ID: f1d300b6-f9cf-40a9-8520-d78cd7d813cf
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::NETTLETOOTH_DJINN,
    oracle_id = "f1d300b6-f9cf-40a9-8520-d78cd7d813cf",
    scryfall_id = "7b5aa60d-91aa-4eee-9d13-55a357c8eced",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Nettletooth Djinn",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DJINN],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::Player(PlayerRel::You)
        }]
    ),],
);
