//! Phyrexian Debaser — {3}{B} — Creature — Phyrexian Carrier
//! Oracle: Flying
//! Oracle: {T}, Sacrifice this creature: Target creature gets -2/-2 until end of turn.
//! Set: DMR #97 — Dominaria Remastered | Scryfall ID: f3e2c6ac-455e-4d99-983b-1b154fd8bb24 | Oracle ID: 554de904-086c-428c-9f32-b0b2498a6fd5
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::PHYREXIAN_DEBASER,
    oracle_id = "554de904-086c-428c-9f32-b0b2498a6fd5",
    scryfall_id = "f3e2c6ac-455e-4d99-983b-1b154fd8bb24",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Phyrexian Debaser",
        mana_cost = mana!("{3}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::PHYREXIAN, subtypes::creature::CARRIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!(TapSelf, SacrificeSelf),
        &[Effect::PumpTarget {
            power: Amount::NegXFixed(2),
            toughness: Amount::NegXFixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
