//! Razorfoot Griffin — {3}{W} — Creature — Griffin
//! Oracle: Flying (This creature can't be blocked except by creatures with flying or reach.)
//! Oracle: First strike (This creature deals combat damage before creatures without first strike.)
//! Set: M15 #27 — Magic 2015 | Scryfall ID: 662d812f-4936-48e4-acbe-abccf9ab21c7 | Oracle ID: c7ecb785-2bfc-4953-b356-db7c27406dbb
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RAZORFOOT_GRIFFIN,
    oracle_id = "c7ecb785-2bfc-4953-b356-db7c27406dbb",
    scryfall_id = "662d812f-4936-48e4-acbe-abccf9ab21c7",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING.union(KeywordSet::FIRST_STRIKE),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Razorfoot Griffin",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GRIFFIN],
        power = Some(2),
        toughness = Some(2),
    ),],
);
