//! Reclusive Wight — {3}{B} — Creature — Zombie Minion
//! Oracle: At the beginning of your upkeep, if you control another nonland permanent, sacrifice this creature.
//! Set: USG #153 — Urza's Saga | Scryfall ID: 384b14c6-78a0-4e82-924e-781719c8defb | Oracle ID: dbde53c1-c6b7-4775-87d3-e95166392e60
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static CHECK1: Filter = Filter::And(&[Filter::NONLAND, Filter::ControlledByYou]);

card!(
    index = index::RECLUSIVE_WIGHT,
    oracle_id = "dbde53c1-c6b7-4775-87d3-e95166392e60",
    scryfall_id = "384b14c6-78a0-4e82-924e-781719c8defb",
    color_identity = ColorSet::from_slice(&[Color::Black]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Reclusive Wight",
        mana_cost = mana!("{3}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ZOMBIE, subtypes::creature::MINION],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::SacrificeSelf],
        condition = Some(Condition::ControlCount(&CHECK1, 2))
    ),],
);
