//! Ridgetop Raptor — {3}{R} — Creature — Dinosaur Beast
//! Oracle: Double strike (This creature deals both first-strike and regular combat damage.)
//! Set: DMR #134 — Dominaria Remastered | Scryfall ID: 720a0e44-0675-488e-bfa5-ae557337e9c4 | Oracle ID: 600a8c9e-e158-4fff-8c4d-c3a1bfd006e8
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::RIDGETOP_RAPTOR,
    oracle_id = "600a8c9e-e158-4fff-8c4d-c3a1bfd006e8",
    scryfall_id = "720a0e44-0675-488e-bfa5-ae557337e9c4",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::DOUBLE_STRIKE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Ridgetop Raptor",
        mana_cost = mana!("{3}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DINOSAUR, subtypes::creature::BEAST],
        power = Some(2),
        toughness = Some(1),
    ),],
);
