//! Seahunter — {2}{U}{U} — Creature — Human Mercenary
//! Oracle: {3}, {T}: Search your library for a Merfolk permanent card, put it onto the battlefield, then shuffle.
//! Set: NEM #41 — Nemesis | Scryfall ID: c375f65a-6d88-4d3c-a7a7-8c7a5cc5807f | Oracle ID: 59e1899f-a9e8-48aa-b3fb-0b7d9fd6859c
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::creature::MERFOLK);

card!(
    index = index::SEAHUNTER,
    oracle_id = "59e1899f-a9e8-48aa-b3fb-0b7d9fd6859c",
    scryfall_id = "c375f65a-6d88-4d3c-a7a7-8c7a5cc5807f",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Seahunter",
        mana_cost = mana!("{2}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::MERCENARY],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{3}", TapSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD],
            optional: false
        }]
    ),],
);
