//! Seasoned Marshal — {2}{W}{W} — Creature — Human Soldier
//! Oracle: Whenever this creature attacks, you may tap target creature.
//! Set: DDF #15 — Duel Decks: Elspeth vs. Tezzeret | Scryfall ID: 11fafc94-543b-4e9d-83aa-ac510aed87ea | Oracle ID: 0c7239bf-dc8a-4d79-867e-7a4225568c49
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::SEASONED_MARSHAL,
    oracle_id = "0c7239bf-dc8a-4d79-867e-7a4225568c49",
    scryfall_id = "11fafc94-543b-4e9d-83aa-ac510aed87ea",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Seasoned Marshal",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(
        Trigger::Attacks(&Filter::This),
        &[Effect::MayDo {
            effects: &[Effect::TapTarget]
        }],
        targets = Some(TargetReq::one(TargetSpec::Object(&Filter::CREATURE)))
    ),],
);
