//! Skyshroud Poacher — {2}{G}{G} — Creature — Human Rebel
//! Oracle: {3}, {T}: Search your library for an Elf permanent card, put it onto the battlefield, then shuffle.
//! Set: NEM #119 — Nemesis | Scryfall ID: 0fb4e44e-656e-4294-a53b-1f7aa96fab31 | Oracle ID: 4f5921c1-b932-4d6b-bb8e-01992578abdc
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::creature::ELF);

card!(
    index = index::SKYSHROUD_POACHER,
    oracle_id = "4f5921c1-b932-4d6b-bb8e-01992578abdc",
    scryfall_id = "0fb4e44e-656e-4294-a53b-1f7aa96fab31",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Skyshroud Poacher",
        mana_cost = mana!("{2}{G}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::REBEL],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{3}", TapSelf),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::BATTLEFIELD],
            optional: false
        }]
    ),],
);
