//! Steelshaper Apprentice — {2}{W}{W} — Creature — Human Soldier
//! Oracle: {W}, {T}, Return this creature to its owner's hand: Search your library for an Equipment card, reveal that card, put it into your hand, then shuffle.
//! Set: DST #15 — Darksteel | Scryfall ID: a4793de1-4d5d-4538-b48f-db5d31757bcc | Oracle ID: bf325b3a-0b28-4660-8b51-4334b59a9034
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static SEARCH1: Filter = Filter::HasSubtype(subtypes::artifact::EQUIPMENT);

card!(
    index = index::STEELSHAPER_APPRENTICE,
    oracle_id = "bf325b3a-0b28-4660-8b51-4334b59a9034",
    scryfall_id = "a4793de1-4d5d-4538-b48f-db5d31757bcc",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Steelshaper Apprentice",
        mana_cost = mana!("{2}{W}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::SOLDIER],
        power = Some(1),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!("{W}", TapSelf, ReturnSelfToHand),
        &[Effect::SearchLibrary {
            filter: &SEARCH1,
            finds: &[Find::HAND],
            optional: false
        }]
    ),],
);
