//! Stinging Barrier — {2}{U}{U} — Creature — Wall
//! Oracle: Defender (This creature can't attack.)
//! Oracle: {U}, {T}: This creature deals 1 damage to any target.
//! Set: MMQ #107 — Mercadian Masques | Scryfall ID: ca7f7cd5-4e91-474a-9f60-a66f3f462b1c | Oracle ID: b56f375f-35b3-4d96-9749-c059c2d29c8b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STINGING_BARRIER,
    oracle_id = "b56f375f-35b3-4d96-9749-c059c2d29c8b",
    scryfall_id = "ca7f7cd5-4e91-474a-9f60-a66f3f462b1c",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::DEFENDER,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stinging Barrier",
        mana_cost = mana!("{2}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::WALL],
        power = Some(0),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        cost!("{U}", TapSelf),
        &[Effect::DealDamage {
            amount: Amount::Fixed(1),
            target: TargetSpec::AnyTarget
        }],
        target = Some(TargetSpec::AnyTarget)
    ),],
);
