//! Stone Giant — {2}{R}{R} — Creature — Giant
//! Oracle: {T}: Target creature you control with toughness less than this creature's power gains flying until end of turn. Destroy that creature at the beginning of the next end step.
//! Set: DDI #55 — Duel Decks: Venser vs. Koth | Scryfall ID: fbd9a10e-2bf7-4af7-bb34-52de01e03523 | Oracle ID: 0b8e3f9b-a4da-49a3-8545-ce7a265e5856
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static TARGET1: Filter = Filter::And(&[
    Filter::CREATURE,
    Filter::ControlledByYou,
    Filter::ToughnessLessThanSourcePower,
]);

card!(
    index = index::STONE_GIANT,
    oracle_id = "0b8e3f9b-a4da-49a3-8545-ce7a265e5856",
    scryfall_id = "fbd9a10e-2bf7-4af7-bb34-52de01e03523",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Stone Giant",
        mana_cost = mana!("{2}{R}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::GIANT],
        power = Some(3),
        toughness = Some(4),
    ),],
    abilities = &[activated!(
        Cost::TAP,
        &[
            Effect::PumpTarget {
                power: Amount::Fixed(0),
                toughness: Amount::Fixed(0),
                keywords: KeywordSet::FLYING,
                duration: Duration::UntilEndOfTurn
            },
            Effect::AtNextEndStep {
                effects: &[Effect::destroy(TargetSpec::EventObject)]
            }
        ],
        target = Some(TargetSpec::Object(&TARGET1))
    ),],
);
