//! Striped Bears — {3}{G} — Creature — Bear
//! Oracle: When this creature enters, draw a card.
//! Set: WTH #140 — Weatherlight | Scryfall ID: 0bf54365-56ae-485d-b931-784a4cf9d8f2 | Oracle ID: ac856e91-1b88-464b-9420-dc311ce814ea
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::STRIPED_BEARS,
    oracle_id = "ac856e91-1b88-464b-9420-dc311ce814ea",
    scryfall_id = "0bf54365-56ae-485d-b931-784a4cf9d8f2",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Striped Bears",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::BEAR],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[triggered!(Trigger::ETB, &[Effect::draw(1)]),],
);
