//! Teroh's Faithful — {3}{W} — Creature — Human Cleric
//! Oracle: When this creature enters, you gain 4 life.
//! Set: VMA #52 — Vintage Masters | Scryfall ID: ce1de3e4-d6b5-4c91-858c-94d62e69d1c7 | Oracle ID: 875c96ce-f6e4-438b-929d-de53afdd99a1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TEROH_S_FAITHFUL,
    oracle_id = "875c96ce-f6e4-438b-929d-de53afdd99a1",
    scryfall_id = "ce1de3e4-d6b5-4c91-858c-94d62e69d1c7",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Teroh's Faithful",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::CLERIC],
        power = Some(1),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(Trigger::ETB, &[Effect::gain_life(4)]),],
);
