//! Tormented Angel — {3}{W} — Creature — Angel
//! Oracle: Flying
//! Set: UDS #22 — Urza's Destiny | Scryfall ID: 00d4d751-50df-4d8f-a6d9-4e76797c429a | Oracle ID: 176eeafd-0482-4fa4-9174-10f8b9494d9b
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TORMENTED_ANGEL,
    oracle_id = "176eeafd-0482-4fa4-9174-10f8b9494d9b",
    scryfall_id = "00d4d751-50df-4d8f-a6d9-4e76797c429a",
    color_identity = ColorSet::from_slice(&[Color::White]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tormented Angel",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ANGEL],
        power = Some(1),
        toughness = Some(5),
    ),],
);
