//! Trenching Steed — {3}{W} — Creature — Horse Rebel
//! Oracle: Sacrifice a land: This creature gets +0/+3 until end of turn.
//! Set: PCY #26 — Prophecy | Scryfall ID: 9a359837-2e41-4ddc-9299-89a783d62014 | Oracle ID: 31136103-535a-4d11-819a-1cbd57ad48a4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TRENCHING_STEED,
    oracle_id = "31136103-535a-4d11-819a-1cbd57ad48a4",
    scryfall_id = "9a359837-2e41-4ddc-9299-89a783d62014",
    color_identity = ColorSet::from_slice(&[Color::White]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Trenching Steed",
        mana_cost = mana!("{3}{W}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HORSE, subtypes::creature::REBEL],
        power = Some(2),
        toughness = Some(3),
    ),],
    abilities = &[activated!(
        cost!(Sacrifice(&Filter::YOUR_LAND)),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(3),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
