//! Tuknir Deathlock — {R}{R}{G}{G} — Legendary Creature — Human Wizard
//! Oracle: Flying
//! Oracle: {R}{G}, {T}: Target creature gets +2/+2 until end of turn.
//! Set: ME3 #184 — Masters Edition III | Scryfall ID: 5ab10b32-00b6-40b7-ad5e-ff2fd35951ef | Oracle ID: 0b6fa658-a344-4202-866b-e19997e32ff2
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::TUKNIR_DEATHLOCK,
    oracle_id = "0b6fa658-a344-4202-866b-e19997e32ff2",
    scryfall_id = "5ab10b32-00b6-40b7-ad5e-ff2fd35951ef",
    color_identity = ColorSet::from_slice(&[Color::Green, Color::Red]),
    commander = CommanderRule::Legendary,
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Tuknir Deathlock",
        mana_cost = mana!("{R}{R}{G}{G}"),
        types = TypeSet::CREATURE,
        supertypes = SupertypeSet::LEGENDARY,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::WIZARD],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{R}{G}", TapSelf),
        &[Effect::PumpTarget {
            power: Amount::Fixed(2),
            toughness: Amount::Fixed(2),
            keywords: KeywordSet::EMPTY,
            duration: Duration::UntilEndOfTurn
        }],
        target = Some(TargetSpec::Object(&Filter::CREATURE))
    ),],
);
