//! Volcano Imp — {3}{B} — Creature — Imp
//! Oracle: Flying
//! Oracle: {1}{R}: This creature gains first strike until end of turn.
//! Set: PLS #56 — Planeshift | Scryfall ID: a8281cc6-2132-4f76-841e-d1ade9cafb84 | Oracle ID: d2b1b4dd-e860-40d8-8e07-1dee5be65bc4
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VOLCANO_IMP,
    oracle_id = "d2b1b4dd-e860-40d8-8e07-1dee5be65bc4",
    scryfall_id = "a8281cc6-2132-4f76-841e-d1ade9cafb84",
    color_identity = ColorSet::from_slice(&[Color::Black, Color::Red]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Volcano Imp",
        mana_cost = mana!("{3}{B}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::IMP],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[activated!(
        cost!("{1}{R}"),
        &[Effect::PumpFilter {
            filter: &Filter::This,
            controlled_by: None,
            power: Amount::Fixed(0),
            toughness: Amount::Fixed(0),
            keywords: KeywordSet::FIRST_STRIKE,
            duration: Duration::UntilEndOfTurn
        }]
    ),],
);
