//! Vulshok Berserker — {3}{R} — Creature — Human Berserker
//! Oracle: Haste (This creature can attack and {T} as soon as it comes under your control.)
//! Set: DDI #53 — Duel Decks: Venser vs. Koth | Scryfall ID: 1dd6e25f-e58e-4ff8-83f3-b01d5f783632 | Oracle ID: 694f7e51-7b8b-4f00-bd77-a52eded4aaa1
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

card!(
    index = index::VULSHOK_BERSERKER,
    oracle_id = "694f7e51-7b8b-4f00-bd77-a52eded4aaa1",
    scryfall_id = "1dd6e25f-e58e-4ff8-83f3-b01d5f783632",
    color_identity = ColorSet::from_slice(&[Color::Red]),
    keywords = KeywordSet::HASTE,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Vulshok Berserker",
        mana_cost = mana!("{3}{R}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::HUMAN, subtypes::creature::BERSERKER],
        power = Some(3),
        toughness = Some(2),
    ),],
);
