//! Waterspout Djinn — {2}{U}{U} — Creature — Djinn
//! Oracle: Flying
//! Oracle: At the beginning of your upkeep, sacrifice this creature unless you return an untapped Island you control to its owner's hand.
//! Set: JVC #11 — Duel Decks Anthology: Jace vs. Chandra | Scryfall ID: 0c4d3ffe-3e4d-496f-98d7-60f3b1757b67 | Oracle ID: 050dac46-9ba0-4b8a-b61b-1c7ec6f3723a
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COST1: Filter = Filter::And(&[
    Filter::HasSubtype(subtypes::land::ISLAND),
    Filter::Untapped,
    Filter::ControlledByYou,
]);

card!(
    index = index::WATERSPOUT_DJINN,
    oracle_id = "050dac46-9ba0-4b8a-b61b-1c7ec6f3723a",
    scryfall_id = "0c4d3ffe-3e4d-496f-98d7-60f3b1757b67",
    color_identity = ColorSet::from_slice(&[Color::Blue]),
    keywords = KeywordSet::FLYING,
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Waterspout Djinn",
        mana_cost = mana!("{2}{U}{U}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::DJINN],
        power = Some(4),
        toughness = Some(4),
    ),],
    abilities = &[triggered!(
        Trigger::StepBegin {
            step: StepKind::Upkeep,
            whose: PlayerRel::You
        },
        &[Effect::PlayerMayPayCostOr {
            player: PlayerRel::You,
            cost: &CostPart::ReturnToHand(&COST1),
            effect: &Effect::SacrificeSelf
        }]
    ),],
);
