//! Wirewood Channeler — {3}{G} — Creature — Elf Druid
//! Oracle: {T}: Add X mana of any one color, where X is the number of Elves on the battlefield.
//! Set: KHC #79 — Kaldheim Commander | Scryfall ID: 5670ae47-befb-4aaf-a77a-d7dbd4d8dc08 | Oracle ID: 8badfd34-9b63-4ada-8012-b8cddaf5b492
// IMPLEMENTED — generated by `xtask codegen`: transcoded from the card's rules.

use baylee_cards_dsl::prelude::*;
use baylee_core::generated::subtypes;

static COUNT1: Filter = Filter::HasSubtype(subtypes::creature::ELF);

card!(
    index = index::WIREWOOD_CHANNELER,
    oracle_id = "8badfd34-9b63-4ada-8012-b8cddaf5b492",
    scryfall_id = "5670ae47-befb-4aaf-a77a-d7dbd4d8dc08",
    color_identity = ColorSet::from_slice(&[Color::Green]),
    coverage = Coverage::Implemented,
    faces = &[face!(
        name = "Wirewood Channeler",
        mana_cost = mana!("{3}{G}"),
        types = TypeSet::CREATURE,
        subtypes = &[subtypes::creature::ELF, subtypes::creature::DRUID],
        power = Some(2),
        toughness = Some(2),
    ),],
    abilities = &[mana_ability!(&[Effect::mana_choice_dynamic(
        ALL_MANA_COLORS,
        Amount::CountOf {
            filter: &COUNT1,
            zone: ZoneSel::Battlefield
        }
    )]),],
);
